# TODO: Translation updated at 2019-03-26 18:44

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:36
translate english ep24_dialogues3_fitness1_a36f6a0c:

    # m "Барди..."
    # m "Мы собираемся с Бетти ехать на фитнесс..."
    # m "Ты просил меня сообщить тебе..."
    # bardie "Отлично, Моника!"
    # bardie "Увидимся там!"
    # bardie "Сообщи мне, когда она останется наедине с ним!"
    m "Барди..."
    m "Мы собираемся с Бетти ехать на фитнесс..."
    m "Ты просил меня сообщить тебе..."
    bardie "Отлично, Моника!"
    bardie "Увидимся там!"
    bardie "Сообщи мне, когда она останется наедине с ним!"

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:48
translate english ep24_dialogues3_fitness2_fdb27c6f:

    # m "Бетти осталась наедине с тренером."
    # m "Делай что ты там задумал..."
    # bardie "..."
    m "Бетти осталась наедине с тренером."
    m "Делай что ты там задумал..."
    bardie "..."

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:67
translate english ep24_dialogues3_fitness3_7a85e4dc:

    # fitness_instructor "Бетти, расслабься."
    # "Здесь только мы одни..."
    # betty "Хорошо, я постараюсь..."
    # fitness_instructor "Делай вот так, выгибай ногу сильнее."
    # betty "Я стараюсь..."
    # fitness_instructor "Я помогу тебе, надо только немного поддержать..."
    # betty "Вот так?"
    # fitness_instructor "Да, тебе надо держать корпус ровнее..."
    # "Я помогу тебе..."
    # bardie "..."
    # betty "Хорошо..."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    # betty "Хорошо..."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "Тебе надо больше выгибать спинку, постарайся..."
    # betty "Я пытаюсь, у меня не получается выгнуться сильнее..."
    # fitness_instructor "У тебя очень обтягивающая форма."
    # fitness_instructor "Она сковывает твои движения."
    # fitness_instructor "Попробуй снять свой верх."
    # fitness_instructor "Увидишь, тебе сразу станет свободнее двигаться."
    # betty "Правда?"
    # "Я немного смущаюсь?"
    # fitness_instructor "Бетти, я всего-лишь фитнесс тренер."
    # fitness_instructor "Я желаю, чтобы ты добилась результатов."
    # fitness_instructor "Доверься мне!"
    # betty "Хорошо..."
    # bardie "..."
    # fitness_instructor "Вот так, Бетти!"
    # "Чувствуешь, как тебе стало свободнее двигаться?"
    # "У тебя сразу получилось прогнуть спинку, как следует!"
    # "Ты чувствуешь?"
    # betty "Да, я действительно выгнулась гораздо сильнее..."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    # betty "Хорошо..."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "Ты помнишь что без верха у тебя лучше результаты."
    # betty "Да, помню."
    # fitness_instructor "Пожалуйста, сними его."
    # betty "Хорошо."
    # fitness_instructor "Молодец."
    # fitness_instructor "Теперь тяни ножку, тяни сильнее..."
    # betty "Я не могу, мне дальше никак..."
    # fitness_instructor "Тебе больно, Бетти?"
    # betty "Нет, мне уже не больно..."
    # "Она... Она просто не гнется дальше и все..."
    # betty "У меня не получается!"
    # fitness_instructor "Бетти, я знаю что тебе мешает..."
    # fitness_instructor "Я знаю что тебе мешает добиться лучших результатов..."
    # betty "Что же?"
    # fitness_instructor "Твой низ, Бетти!"
    # fitness_instructor "Он слишком обтягивает тебя, сковывает твои движения!"
    # fitness_instructor "Твои связки могут позволить тебе сделать упражнение как надо."
    # fitness_instructor "Но твоя одежда не позволяет тебе сделать это."
    # betty "Что же делать с этим?"
    # fitness_instructor "Ты можешь снять с себя это, Бетти."
    # betty "Но я... Стесняюсь..."
    # fitness_instructor "Бетти, я твой инструктор!"
    # fitness_instructor "Я провожу персональные занятия с тобой."
    # fitness_instructor "Я делаю это бесплатно, потому что вижу в тебе потенциал!"
    # betty "Правда? У меня есть потенциал?"
    # fitness_instructor "Да, Бетти!"
    # fitness_instructor "Ты прекрасна!"
    # fitness_instructor "Доверься мне! Я лишь хочу чтобы у тебя получалось!"
    # fitness_instructor "Я хочу чтобы ты была успешной!"
    # betty "Хорошо, только..."
    # betty "Я ведь правда не толстая?"
    # fitness_instructor "Бетти, ты прекрасна! Тебе не стоит стесняться своего тела!"
    # betty "Хорошо..."
    # bardie "..."
    # fitness_instructor "Вот так, Бетти!"
    # fitness_instructor "У тебя получается, ты чувствуешь?"
    # betty "Да, я правда смогла поднять ногу выше..."
    # fitness_instructor "Отлично!"
    # fitness_instructor "Ты чувствуешь себя свободной?"
    # betty "Да..."
    # fitness_instructor "Тебе комортно, ты больше не стесняешь меня?"
    # betty "Да, мне очень комфортно..."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    # fitness_instructor "Хорошо, Бетти, молодец."
    # fitness_instructor "У тебя уже лучше получается."
    # fitness_instructor "Ты помнишь что одежда сковывает тебя?"
    # betty "Да, помню..."
    # fitness_instructor "Если ты хочешь, ты можешь снять ее."
    # fitness_instructor "Тогда мы сможем достичь большего прогресса."
    # betty "Хорошо..."
    # fitness_instructor "Теперь тянись, тянись как можешь..."
    # betty "..."
    # fitness_instructor "Вот так, хорошо..."
    # fitness_instructor "Давай, ты можешь еще, я знаю."
    # betty "Мне никак!"
    # betty "Я стараюсь!"
    # fitness_instructor "Бетти, ты слишком напряжена, ты чувствуешь это?"
    # betty "Да, я чувствую..."
    # fitness_instructor "Тебе надо расслабиться, Бетти."
    # betty "Но как это сделать?"
    # betty "Я волнуюсь, я хочу чтобы у меня получалось..."
    # fitness_instructor "Тебе нужно пройти сеанс медитации, Бетти."
    # fitness_instructor "Тогда ты сможешь расслабиться и у тебя все получится."
    # betty "Но как? Я не умею медитировать."
    # fitness_instructor "Хочешь чтобы я показал тебе как это надо делать?"
    # betty "Да, очень хочу..."
    # fitness_instructor "Я буду твоим проводником, Бетти."
    # fitness_instructor "Твоим проводником на пути к достижению душевного равновесия."
    # fitness_instructor "Я проведу тебя через весь путь."
    # fitness_instructor "Ты поймешь что такое настоящий Дзен..."
    # bardie "!!!"
    # fitness_instructor "Ты хочешь этого?"
    fitness_instructor "Бетти, расслабься."
    "Здесь только мы одни..."
    betty "Хорошо, я постараюсь..."
    fitness_instructor "Делай вот так, выгибай ногу сильнее."
    betty "Я стараюсь..."
    fitness_instructor "Я помогу тебе, надо только немного поддержать..."
    betty "Вот так?"
    fitness_instructor "Да, тебе надо держать корпус ровнее..."
    "Я помогу тебе..."
    bardie "..."
    betty "Хорошо..."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    betty "Хорошо..."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "Тебе надо больше выгибать спинку, постарайся..."
    betty "Я пытаюсь, у меня не получается выгнуться сильнее..."
    fitness_instructor "У тебя очень обтягивающая форма."
    fitness_instructor "Она сковывает твои движения."
    fitness_instructor "Попробуй снять свой верх."
    fitness_instructor "Увидишь, тебе сразу станет свободнее двигаться."
    betty "Правда?"
    "Я немного смущаюсь?"
    fitness_instructor "Бетти, я всего-лишь фитнесс тренер."
    fitness_instructor "Я желаю, чтобы ты добилась результатов."
    fitness_instructor "Доверься мне!"
    betty "Хорошо..."
    bardie "..."
    fitness_instructor "Вот так, Бетти!"
    "Чувствуешь, как тебе стало свободнее двигаться?"
    "У тебя сразу получилось прогнуть спинку, как следует!"
    "Ты чувствуешь?"
    betty "Да, я действительно выгнулась гораздо сильнее..."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    betty "Хорошо..."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "Ты помнишь что без верха у тебя лучше результаты."
    betty "Да, помню."
    fitness_instructor "Пожалуйста, сними его."
    betty "Хорошо."
    fitness_instructor "Молодец."
    fitness_instructor "Теперь тяни ножку, тяни сильнее..."
    betty "Я не могу, мне дальше никак..."
    fitness_instructor "Тебе больно, Бетти?"
    betty "Нет, мне уже не больно..."
    "Она... Она просто не гнется дальше и все..."
    betty "У меня не получается!"
    fitness_instructor "Бетти, я знаю что тебе мешает..."
    fitness_instructor "Я знаю что тебе мешает добиться лучших результатов..."
    betty "Что же?"
    fitness_instructor "Твой низ, Бетти!"
    fitness_instructor "Он слишком обтягивает тебя, сковывает твои движения!"
    fitness_instructor "Твои связки могут позволить тебе сделать упражнение как надо."
    fitness_instructor "Но твоя одежда не позволяет тебе сделать это."
    betty "Что же делать с этим?"
    fitness_instructor "Ты можешь снять с себя это, Бетти."
    betty "Но я... Стесняюсь..."
    fitness_instructor "Бетти, я твой инструктор!"
    fitness_instructor "Я провожу персональные занятия с тобой."
    fitness_instructor "Я делаю это бесплатно, потому что вижу в тебе потенциал!"
    betty "Правда? У меня есть потенциал?"
    fitness_instructor "Да, Бетти!"
    fitness_instructor "Ты прекрасна!"
    fitness_instructor "Доверься мне! Я лишь хочу чтобы у тебя получалось!"
    fitness_instructor "Я хочу чтобы ты была успешной!"
    betty "Хорошо, только..."
    betty "Я ведь правда не толстая?"
    fitness_instructor "Бетти, ты прекрасна! Тебе не стоит стесняться своего тела!"
    betty "Хорошо..."
    bardie "..."
    fitness_instructor "Вот так, Бетти!"
    fitness_instructor "У тебя получается, ты чувствуешь?"
    betty "Да, я правда смогла поднять ногу выше..."
    fitness_instructor "Отлично!"
    fitness_instructor "Ты чувствуешь себя свободной?"
    betty "Да..."
    fitness_instructor "Тебе комортно, ты больше не стесняешь меня?"
    betty "Да, мне очень комфортно..."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "В следующий раз мы выполним упражнения посложнее."
    fitness_instructor "Хорошо, Бетти, молодец."
    fitness_instructor "У тебя уже лучше получается."
    fitness_instructor "Ты помнишь что одежда сковывает тебя?"
    betty "Да, помню..."
    fitness_instructor "Если ты хочешь, ты можешь снять ее."
    fitness_instructor "Тогда мы сможем достичь большего прогресса."
    betty "Хорошо..."
    fitness_instructor "Теперь тянись, тянись как можешь..."
    betty "..."
    fitness_instructor "Вот так, хорошо..."
    fitness_instructor "Давай, ты можешь еще, я знаю."
    betty "Мне никак!"
    betty "Я стараюсь!"
    fitness_instructor "Бетти, ты слишком напряжена, ты чувствуешь это?"
    betty "Да, я чувствую..."
    fitness_instructor "Тебе надо расслабиться, Бетти."
    betty "Но как это сделать?"
    betty "Я волнуюсь, я хочу чтобы у меня получалось..."
    fitness_instructor "Тебе нужно пройти сеанс медитации, Бетти."
    fitness_instructor "Тогда ты сможешь расслабиться и у тебя все получится."
    betty "Но как? Я не умею медитировать."
    fitness_instructor "Хочешь чтобы я показал тебе как это надо делать?"
    betty "Да, очень хочу..."
    fitness_instructor "Я буду твоим проводником, Бетти."
    fitness_instructor "Твоим проводником на пути к достижению душевного равновесия."
    fitness_instructor "Я проведу тебя через весь путь."
    fitness_instructor "Ты поймешь что такое настоящий Дзен..."
    bardie "!!!"
    fitness_instructor "Ты хочешь этого?"

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:212
translate english ep24_dialogues3_fitness3_e5dad65c:

    # betty "Я хочу, но не таким путем. Я замужем!"
    # betty "А это выглядит как измена!"
    # fitness_instructor "..."
    # betty "Я оденусь и мы продолжим."
    # betty "Я уверена что смогу добиться успеха не прибегая к медитациям..."
    # fitness_instructor "Хорошо, Бетти..."
    betty "Я хочу, но не таким путем. Я замужем!"
    betty "А это выглядит как измена!"
    fitness_instructor "..."
    betty "Я оденусь и мы продолжим."
    betty "Я уверена, что смогу добиться успеха не прибегая к медитациям..."
    fitness_instructor "Хорошо, Бетти..."

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:220
translate english ep24_dialogues3_fitness3_cff771c4:

    # betty "Да, я очень хочу..."
    # fitness_instructor "Тогда начнем!"
    # fitness_instructor "Расслабься и чувствуй меня!"
    # fitness_instructor "Чувствуй меня, следуй за мной!"
    # betty "Да! Хорошо!"
    # fitness_instructor "Ты чувствуешь меня?"
    # betty "Да!"
    # fitness_instructor "Ты чувствуешь как тебя заполняет энергия равновесия?"
    # betty "Да!"
    # fitness_instructor "Ты чувствуешь прилив энергетических сил?"
    # betty "Да!"
    # fitness_instructor "Ты следуешь за мной по дороге к Дзен?"
    # betty "Да!"
    # fitness_instructor "Тебе нравится эта медитация?"
    # betty "Да!"
    # fitness_instructor "Очень нравится?"
    # betty "Да, очень!"
    betty "Да, я очень хочу..."
    fitness_instructor "Тогда начнем!"
    fitness_instructor "Расслабься и чувствуй меня!"
    fitness_instructor "Чувствуй меня, следуй за мной!"
    betty "Да! Хорошо!"
    fitness_instructor "Ты чувствуешь меня?"
    betty "Да!"
    fitness_instructor "Ты чувствуешь как тебя заполняет энергия равновесия?"
    betty "Да!"
    fitness_instructor "Ты чувствуешь прилив энергетических сил?"
    betty "Да!"
    fitness_instructor "Ты следуешь за мной по дороге к Дзен?"
    betty "Да!"
    fitness_instructor "Тебе нравится эта медитация?"
    betty "Да!"
    fitness_instructor "Очень нравится?"
    betty "Да, очень!"

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:248
translate english ep24_dialogues3_fitness4_3ea426cd:

    # bardie "Ну все, Бетти, ты попалась!"
    # bardie "Теперь ты узнаешь кто действительно хозяин в доме!"
    bardie "Ну все, Бетти, ты попалась!"
    bardie "Теперь ты узнаешь кто действительно хозяин в доме!"

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:256
translate english ep24_dialogues3_fitness5_7acb6319:

    # mt "Стоит узнать у Барди, видел-ли он что-нибудь с Бетти..."
    mt "Стоит узнать у Барди, видел-ли он что-нибудь с Бетти..."

# game/Quests/EP2_04/ep24_dialogues3_fitness.rpy:262
translate english ep24_dialogues3_fitness6_07ce043e:

    # mt "Я не понимаю..."
    # "Эта Бетти что, продолжает трахаться с тренером?!"
    # "После того что было?!"
    mt "Я не понимаю..."
    "Эта Бетти что, продолжает трахаться с тренером?!"
    "После того что было?!"

translate english strings:

    # Quests/EP2_04/ep24_dialogues3_fitness.rpy:31
    old "Сказать Барди, что Моника идет на фитнесс с Бетти."
    new ""

    # Quests/EP2_04/ep24_dialogues3_fitness.rpy:31
    old "Не говорить ему..."
    new ""

    # Quests/EP2_04/ep24_dialogues3_fitness.rpy:208
    old "Да, я очень хочу..."
    new ""

    # Quests/EP2_04/ep24_dialogues3_fitness.rpy:208
    old "Я хочу, но не таким путем. Я замужем!"
    new ""
