# TODO: Translation updated at 2019-11-05 23:52

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:63
translate english dialogue_5_dance_strip_2_976d7c69:

    # mt "Фи, это же просто подсобка, а не гримерка!"
    # mt "И все такое... старое!"
    # mt "Как здесь можно готовиться к выступлениям?!"
    # stripper "Это ты новая танцовщица что-ли?.." 
    # stripper "М, понятно..."
    # mt "???"
    # stripper "Увижу тебя рядом со своими вещами - скажу Джо, что ты у меня украла что-нибудь." 
    # stripper "Советую держаться подальше."
    # mt "..."
    # mt "И я рада познакомиться..."
    # mt "Как грубо!"
    # mt "Всего лишь какая-то стриптизерша из трущоб!"
    # mt "Ей, видимо, неизвестно, что такое воспитание и манеры..."
    # mt "Мне надо надеть сценический костюм. Которого у меня нет..."
    # mt "Что же делать?"
    # mt "Попросить у этой хамки что-нибудь из одежды?"
    # mt "..."
    # stripper "Чего уставилась?!" 
    # stripper "Тебе на сцену через пять минут, чего ты ждешь?"
    # stripper "Или ты пойдешь в этом наряде для бомжей?"
    # m "Мне не выдали сценический костюм. Я не знаю, в чем выходить на сцену."
    # stripper "Сценический костюм?!"
    # stripper "Аха-ха!!!"
    # stripper "Может, тебе еще личного ассистента и гримера предоставить?!"
    # stripper "Аха-ха-ха!"
    # mt "..." 
    # stripper "Ты же не думаешь, что я тебе дам свою одежду?!"
    # stripper "Иди танцуй голая!"
    # mt "Вот стерва!!!"
    # mt "!!!" 
    # mt "Что же мне теперь делать?" 
    # mt "Выйти на сцену в этой одежде?"
    # mt "Но я не могу идти на сцену в таком виде!"
    # mt "Кто-нибудь из этих неудачников узнает меня!"
    # mt "И не хватало еще, чтобы мое лицо узнал кто-то за пределами этих трущоб..."
    # mt "..."
    # mt "Где эта Эшли?!"
    # mt "В чем, по ее мнению, я должна танцевать?!"
    mt "Eww, it's just a utility room, not a dressing room!"
    mt "And everything is... so old!"
    mt "How can you prepare for performances here?!"
    stripper "Are you the new dancer?.." 
    stripper "Mm, okay..."
    mt "???"
    stripper "If I see you next to my stuff, I'll tell Joe you stole something from me." 
    stripper "I advise you to stay away."
    mt "..."
    mt "И я рада познакомиться..."
    mt "How rude!"
    mt "Just some stripper out of the slums!"
    mt "She doesn't seem to know what education and manners are..."
    mt "I have to put on a stage costume. Which I don't have..."
    mt "What to do?"
    mt "Should I ask this boorish woman for something to wear?"
    mt "..."
    stripper "What are you staring at?!" 
    stripper "You on stage in five minutes, what are you waiting for?"
    stripper "Or are you going in that bum outfit?"
    m "No one gave me a stage costume. I don't know what to wear on stage."
    stripper "Stage costume?!"
    stripper "Aha-ha!!!"
    stripper "Maybe you need a personal assistant and makeup artist as well?!"
    stripper "Ah-ha-ha!"
    mt "..." 
    stripper "You don't think I'll give you my clothes, do you?!"
    stripper "Go, dance naked!"
    mt "Bitch!!!"
    mt "!!!" 
    mt "What should I do now?" 
    mt "Go on stage in these clothes?"
    mt "But I can't go on stage like this!"
    mt "One of these losers can recognize me!"
    mt "I don't want my face to be recognized by anyone outside the slums..."
    mt "..."
    mt "Where's Ashley?!"
    mt "What does she think I should dance in?!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:132
translate english dialogue_5_dance_strip_3_6ccf7229:

    # m "Где Эшли?"
    # joe "[monica_pub_name], можешь спросить у меня. Что ты хотела?"
    # joe "Я тебе помогу решить любой вопрос!"
    # m "Мне не в чем выступать на сцене!"
    # m "В этой одежде я выходить туда не собираюсь!"
    # m "..."
    # joe "Не вижу здесь никакой проблемы."
    # joe "Иди голая! У тебя тогда будет больше чаевых."
    # m "Конечно, нет! Я ни за что не буду танцевать голая!"
    # m "!!!"
    # m "Мне нужна какая-нибудь одежда для сцены!"
    # joe "Ну, а я чем могу помочь?"
    # joe "Попроси одежду у другой стриптизерши."
    # m "Она сказала, что не даст мне ничего..."
    # m "..." 
    # joe "Ну хорошо. Сегодня на сцену можешь не выходить."
    # joe "Эшли я скажу, что ты будешь отрабатывать долг, начиная с завтрашнего дня."
    # joe "{c}Приходи завтра{/c}."
    # joe "Будет работать Клэр. Она тебе даст что-нибудь из одежды."
    # mt "{c}Завтра{/c} мне предстоит снова вернуться в эту ужасную гримерку, фи!"
    # mt "Да еще и придется знакомиться с еще одной хамкой!"
    # mt "!!!"
    m "Where's Ashley?"
    joe "[monica_pub_name], you can ask me. What do you want?"
    joe "I'll help you with any questions!"
    m "I have nothing to wear on stage!"
    m "I'm not going out there in these clothes!"
    m "..."
    joe "I don't see any problem here."
    joe "Go naked! You'll have more tips then."
    m "No way! I'm not going to dance naked!"
    m "!!!"
    m "I need some clothes for the stage!"
    joe "Well, what can I do for you?"
    joe "Ask another stripper to give you clothes."
    m "She said she wouldn't give me anything..."
    m "..." 
    joe "Well. You don't have to go on stage tonight."
    joe "I'll tell Ashley you're going to be working on your debt starting tomorrow."
    joe "{c}Come tomorrow{/c}."
    joe "Claire will work. She'll give you some clothes."
    mt "{c}Tomorrow{/c} I have to go back to that horrible dressing room again, ew!"
    mt "Да еще и придется знакомиться с еще одной хамкой!"
    mt "!!!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:336
translate english dialogue_5_dance_strip_8_9f365275:

    # mt "Это и есть вторая стриптизерша?"
    # mt "Надо приготовиться к знакомству со второй хамкой." 
    # mt "Она, наверное, тоже возомнила себя звездой, как та рыжая стерва..."
    # mt "Звездой в грязном пабе в трущобах!.." 
    # stripper "Привет." 
    # stripper "Молли мне говорила, что у нас новенькая. Это ты?"
    # m "..."
    # m "Д-да... Привет..."
    # stripper "Я Клэр. А ты?"
    # m "Я [monica_pub_name]. А Молли это та рыжая стриптизерша?"
    # clare "Да." 
    # clare "Она тут звезда и очень гордится этим."
    # clare "С ней лучше дружить и не вставать у нее на пути."
    # mt "Звезда! Ха-ха! Стриптизерша со звездной болезнью!"
    # mt "Похоже, эта Клэр единственная в этой дыре, кто может нормально общаться."
    # clare "Ты давно в стриптизе, [monica_pub_name]?"
    # m "Нет. Сегодня будет мое первое выступление..."
    # mt "Танцы у пилона на улицах трущоб - не в счет!" 
    # clare "Не волнуйся." 
    # clare "Я выступаю уже несколько лет и мне очень нравится."
    # m "Нравится?!" 
    # m "Я думала такое делают только из-за денег..."
    # clare "Для меня это искусство. Мне нравится делиться своей красотой и видеть восторженные взгляды мужчин."
    # clare "Это занятие не является источником денег для меня."
    # mt "Хм... Искусство?.."
    # mt "Возможно, если так к этому относиться, то намного проще выходить на сцену."
    # mt "Но я не представляю себе такого отношения к этому."
    # mt "Сами по себе танцы полуголой на публике отвратительны."
    # mt "И я не изменю своего отношения к этому никогда!"
    # mt "!!!"
    # clare "[monica_pub_name], почему ты не переодеваешься?"
    # clare "В чем ты будешь выступать?"
    # clare "Тебе уже пора выходить на сцену."
    # m "У меня нет одежды для сцены..."
    # m "Эшли сказала, что я могу спросить одежду у тебя."
    # clare "Без проблем. Ты можешь взять вот это." 
    # mt "А из этой Клэр получилась бы неплохая модель..."
    # mt "Конечно, до Мелани, а тем более до меня, ей далеко, но все же."
    # mt "И что она забыла в этой дыре, тем более, что она тут не из-за денег..."
    # clare "К вещам Молли лучше не приближайся."
    # clare "Наша звезда очень ревностно к этому относится." 
    # clare "У меня полно подобных шмоток."
    # clare "Можешь этот костюм оставить себе."
    # m "Серьезно?!" 
    # m "..." 
    # mt "Мне придется надевать на себя ЭТО?"
    # mt "Фи! Какой вульгарный костюм!"
    # mt "Да еще и после стриптизерши!"
    # mt "Какой ужас!"
    # mt "Я, Моника Бакфетт, буду танцевать полуголая! В дешевом пабе для толпы неудачников!!!"
    # mt "Я не могу поверить в это!"
    mt "Is this the second stripper?"
    mt "I better prepare to meet the second whore." 
    mt "She probably thought she was a star, too, like that redhead bitch..."
    mt "A star in a dirty pub in the slums!.." 
    stripper "Hey." 
    stripper "Molly told me we had a new girl. Is that you?"
    m "..."
    m "Y-Yes... Hey..."
    stripper "I'm Claire. What about you?"
    m "I'm [monica_pub_name]. Is Molly the redhead stripper?"
    clare "Yes." 
    clare "She's a star here, and she's very proud of it."
    clare "It is better to be friends with her and not get in her way."
    mt "Star! Ha ha! Stripper with star-struck!"
    mt "Looks like this Claire is the only one in this dump who can communicate properly."
    clare "Have you been a stripper for a long time, [monica_pub_name]?"
    m "No. Today will be my first performance..."
    mt "Dancing at the pole in the streets of the slums does not count!" 
    clare "Don't worry." 
    clare "I have been performing for several years, and I really like it."
    m "Do you like it?!" 
    m "I thought they only do it for money..."
    clare "For me, it's some kind of art. I like to share my beauty and see the enthusiastic looks of men."
    clare "Это занятие не является источником денег для меня."
    mt "Um... Art?.."
    mt "Perhaps if I had the same approach, it would be much easier for me to go on stage."
    mt "But I can't imagine that attitude."
    mt "Dancing half-naked in public is disgusting."
    mt "And I will not change my attitude to this ever!"
    mt "!!!"
    clare "[monica_pub_name], why don't you change your clothes?"
    clare "What are you going to wear for the performance?"
    clare "It's your turn to go on stage."
    m "I don't have clothes for the stage..."
    m "Ashley said I could ask you for clothes."
    clare "No problem. You can have this." 
    mt "This Claire could be a good model..."
    mt "Of course, she never could reach Melanie or even me, but still..."
    mt "And what is she doing here in this dump, especially since she's not here for the money..."
    clare "Don't stay close to Molly's things."
    clare "Our star is very jealous of this." 
    clare "I have a lot of clothes like that."
    clare "You can keep this suit."
    m "Seriously?!" 
    m "..." 
    mt "Do I have to wear THIS?"
    mt "Ew! What a vulgar costume!"
    mt "And after the strip!"
    mt "How horrible!"
    mt "I, Monica Buckfett, should dance half-naked! In a cheap pub for a bunch of losers!!!"
    mt "I can't believe it!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:428
translate english dialogue_5_dance_strip_8_1c00f72e:

    # clare "А у тебя отличная фигура, [monica_pub_name]."
    # mt "Она что, ко мне пытается пристать, как Эшли?!"
    # mt "Я не хочу связываться с еще одной лесбиянкой!"
    # clare "Мужчины в зале с ума сойдут, когда тебя увидят."
    # mt "Я к этому привыкла."
    # mt "Мужчины всегда сходили по мне с ума..."
    # clare "Ты сегодня будешь звездой, [monica_pub_name]."
    # mt "Конечно, буду! Мне нет здесь равных!"
    # mt "И не только здесь! Мне нет равных нигде!"
    # clare "Таким шикарным ногам и такой попе, как у тебя, позавидует любая модель."
    # clare "Ты просто создана для обложки какого-нибудь модного журнала."
    # mt "Хм... Хорошо, что она их не читает."
    # mt "Боюсь себе даже представить, если меня здесь кто-нибудь узнает."
    clare "You have a great shape, [monica_pub_name]."
    mt "Is she trying to molest me like Ashley?!"
    mt "I don't want to mess with another lesbian!"
    clare "The men in the audience will go crazy when they see you."
    mt "I got used to it."
    mt "Мужчины всегда сходили по мне с ума..."
    clare "You'll be a star tonight, [monica_pub_name]."
    mt "Of course, I will! I have no rival here!"
    mt "И не только здесь! Мне нет равных нигде!"
    clare "Such gorgeous legs and such an ass as you have, any model will envy."
    clare "You're just made for the cover of some fashion magazine."
    mt "Um... It's a good thing she doesn't read them."
    mt "I'm afraid to imagine if anyone recognizes me here."

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:655
translate english dialogue_5_dance_strip_17_4487aafe:

    # joe "[monica_pub_name], это костюм Клэр?"  
    # m "Да." 
    # joe "Я смотрю, ты с ней подружилась..."  
    # m "Тебе что с этого?" 
    # joe "Выяснишь для меня, как к ней подкатить?"
    # m "???" 
    # joe "Она тут ни с кем не общается..."
    # joe "И никого к себе не подпускает..."
    # joe "На приваты не соглашается, хотя предложений много..."
    # joe "А она тут работает уже не один год. И я все это время не знаю, как подойти к ней..."
    # clare "Что здесь происходит?!" 
    # clare "Тебе чего надо от [monica_pub_name]?!" 
    # joe "Я... Мне... Я просто..." 
    # clare "Я просто пойду сейчас к твоей жене!" 
    # clare "И расскажу, чем ТЫ тут занимаешься!"
    # joe "Ч-ч-чем???"
    # clare "Пристаешь к [monica_pub_name]!!!"
    # joe "Я... Я не пристаю!"
    # joe "Не надо ничего говорить Эшли!"
    # clare "Тогда пошел отсюда! Быстро!!!" 
    # joe "!!!"
    # clare "Вот кобель!"
    # clare "!!!"
    # clare "Если снова будет приставать, скажи мне. Он меня боится."
    # m "Спасибо, Клэр."
    # mt "Когда я выберусь из этого дна, заведу себе такой же хлыст от извращенцев!"
    joe "[monica_pub_name], is this Claire's costume?"  
    m "Yes." 
    joe "I see you've made friends with her..."  
    m "What do you care about?" 
    joe "Can you figure out for me how to get her?"
    m "???" 
    joe "She doesn't talk to anyone here..."
    joe "And she doesn't let anyone near her..."
    joe "She does not agree to the private shows, although there are many offers..."
    joe "And she's been working here for years. And all this time I didn't have a chance to approach her..."
    clare "What's going on here?!" 
    clare "What do you want from [monica_pub_name]?!" 
    joe "I am... Me... I just....." 
    clare "I'll just go to your wife now!" 
    clare "And I'll tell her what YOU're doing here!"
    joe "WH-WH-what???"
    clare "Do you pester [monica_pub_name]!!!"
    joe "I am... I'm not pestering!"
    joe "Don't say anything to Ashley!"
    clare "Then get out of here! Quick!!!" 
    joe "!!!"
    clare "What a dog!"
    clare "!!!"
    clare "If he tries again, tell me. He's afraid of me."
    m "Thank you, Claire."
    mt "Когда я выберусь из этого дна, заведу себе такой же хлыст от извращенцев!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:748
translate english dialogue_5_dance_strip_21_b71ff680:

    # ashley "[monica_pub_name], сколько ты заработала сегодня чаевых?"
    # m "Зачем тебе это нужно знать?" 
    # ashley "Ты забыла, что ты здесь работаешь за 30 процентов от чаевых?."
    # m "???"
    # m "Но ты же говорила, что я смогу забирать чаевые!"
    # m "МОИ чаевые! Которые я заработала, выступая на сцене!"
    # ashley "Ага. Ты забираешь 30 процентов чаевых, остальное - мне."
    # ashley "Тебя что-то не устраиваает?!"
    # m "..." 
    # mt "Если я сейчас ей откажу, она запретит мне работать здесь..."
    # mt "А мне нужна эта работа..."
    # mt "Как же меня достала эта Эшли!"
    # mt "!!!"
    # ashley "Чего ты ждешь?!"
    # ashley "Сейчас же давай сюда чаевые или можешь убираться отсюда навсегда!"
    ashley "[monica_pub_name], how much have you earned today?"
    m "Why do you need to know that?" 
    ashley "Did you forget you work here for 30 percent of the tip?."
    m "???"
    m "But you said I could take tips!"
    m "My tips! Which I earned by performing on stage!"
    ashley "Ага. Ты забираешь 30 процентов чаевых, остальное - мне."
    ashley "Is there something that doesn't suit you?!"
    m "..." 
    mt "If I refuse her now, she will forbid me to work here..."
    mt "And I need this job..."
    mt "I'm so sick of Ashley."
    mt "!!!"
    ashley "What are you waiting for?!"
    ashley "Give me a tip now, or you can get out of here forever!"

