# TODO: Translation updated at 2019-11-05 23:48

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:63
translate german dialogue_5_dance_strip_2_976d7c69:

    # mt "Фи, это же просто подсобка, а не гримерка!"
    # mt "И все такое... старое!"
    # mt "Как здесь можно готовиться к выступлениям?!"
    # stripper "Это ты новая танцовщица что-ли?.." 
    # stripper "М, понятно..."
    # mt "???"
    # stripper "Увижу тебя рядом со своими вещами - скажу Джо, что ты у меня украла что-нибудь." 
    # stripper "Советую держаться подальше."
    # mt "..."
    # mt "И я рада познакомиться..."
    # mt "Как грубо!"
    # mt "Всего лишь какая-то стриптизерша из трущоб!"
    # mt "Ей, видимо, неизвестно, что такое воспитание и манеры..."
    # mt "Мне надо надеть сценический костюм. Которого у меня нет..."
    # mt "Что же делать?"
    # mt "Попросить у этой хамки что-нибудь из одежды?"
    # mt "..."
    # stripper "Чего уставилась?!" 
    # stripper "Тебе на сцену через пять минут, чего ты ждешь?"
    # stripper "Или ты пойдешь в этом наряде для бомжей?"
    # m "Мне не выдали сценический костюм. Я не знаю, в чем выходить на сцену."
    # stripper "Сценический костюм?!"
    # stripper "Аха-ха!!!"
    # stripper "Может, тебе еще личного ассистента и гримера предоставить?!"
    # stripper "Аха-ха-ха!"
    # mt "..." 
    # stripper "Ты же не думаешь, что я тебе дам свою одежду?!"
    # stripper "Иди танцуй голая!"
    # mt "Вот стерва!!!"
    # mt "!!!" 
    # mt "Что же мне теперь делать?" 
    # mt "Выйти на сцену в этой одежде?"
    # mt "Но я не могу идти на сцену в таком виде!"
    # mt "Кто-нибудь из этих неудачников узнает меня!"
    # mt "И не хватало еще, чтобы мое лицо узнал кто-то за пределами этих трущоб..."
    # mt "..."
    # mt "Где эта Эшли?!"
    # mt "В чем, по ее мнению, я должна танцевать?!"
    mt "Wahhh, das ist ja nur eine Abstellkammer, keine Umkleide!"
    mt "Und alles ist so... alt!"
    mt "Wie soll ich mich hier auf den Tanz vorbereiten?!"
    stripper "Bist du eine neue Tänzerin?" 
    stripper "Mm, okay..."
    mt "???"
    stripper "Wenn ich dich in der Nähe von meinem Zeug sehe, sage ich Joe, du hast mich beklaut." 
    stripper "Ich rate dir, bleib weg von mir."
    mt "..."
    mt "И я рада познакомиться..."
    mt "Wie unhöflich!"
    mt "Nur eine Stripperin aus den Slums!"
    mt "Sie weiß anscheinend nicht, was Erziehung und gute Manieren sind..."
    mt "Ich muss ein Bühnenkostüm anziehen. Welches ich nicht besitze..."
    mt "Was soll ich tun?"
    mt "Soll ich diese proletenhafte Frau nach etwas fragen?"
    mt "..."
    stripper "Was starrst du so?!" 
    stripper "Du bist in fünf Minuten dran, beeil dich!"
    stripper "Oder willst du in diesen Lumpen da raus?"
    m "Niemand hat mir ein Bühnenkostüm gegeben. Ich weiß nicht, was ich auf der Bühne anziehen soll."
    stripper "Bühnenkostüm?"
    stripper "Hahaha!"
    stripper "Vielleicht brauchst du noch einen persönlichen Assistenten und einen Makeup Artist?"
    stripper "Hahaha!"
    mt "..." 
    stripper "Du denkst doch nicht, dass ich dir meine Kleider leihe, oder?"
    stripper "Dann tanze nackt!"
    mt "Schlampe!!"
    mt "!!!" 
    mt "Was soll ich jetzt tun?" 
    mt "Auf die Bühne in diesen Kleidern?"
    mt "Aber ich kann so nicht raus gehen!"
    mt "Einer dieser Loser könnte mich wiedererkennen!"
    mt "Ich will nicht, dass irgendwer außerhalb der Slums mein Gesicht wieder erkennt..."
    mt "..."
    mt "Wo ist Ashley?!"
    mt "Was denkt sie, in was ich tanzen soll?"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:132
translate german dialogue_5_dance_strip_3_6ccf7229:

    # m "Где Эшли?"
    # joe "[monica_pub_name], можешь спросить у меня. Что ты хотела?"
    # joe "Я тебе помогу решить любой вопрос!"
    # m "Мне не в чем выступать на сцене!"
    # m "В этой одежде я выходить туда не собираюсь!"
    # m "..."
    # joe "Не вижу здесь никакой проблемы."
    # joe "Иди голая! У тебя тогда будет больше чаевых."
    # m "Конечно, нет! Я ни за что не буду танцевать голая!"
    # m "!!!"
    # m "Мне нужна какая-нибудь одежда для сцены!"
    # joe "Ну, а я чем могу помочь?"
    # joe "Попроси одежду у другой стриптизерши."
    # m "Она сказала, что не даст мне ничего..."
    # m "..." 
    # joe "Ну хорошо. Сегодня на сцену можешь не выходить."
    # joe "Эшли я скажу, что ты будешь отрабатывать долг, начиная с завтрашнего дня."
    # joe "{c}Приходи завтра{/c}."
    # joe "Будет работать Клэр. Она тебе даст что-нибудь из одежды."
    # mt "{c}Завтра{/c} мне предстоит снова вернуться в эту ужасную гримерку, фи!"
    # mt "Да еще и придется знакомиться с еще одной хамкой!"
    # mt "!!!"
    m "Wo ist Ashley?!"
    joe "[monica_pub_name], du kannst mich fragen, was brauchst du?"
    joe "Ich kann dir jede Frage beantworten!"
    m "Ich habe nichts für die Bühne zum anziehen!"
    m "Ich werde nicht in diesen Kleidern raus gehen!"
    m "..."
    joe "Ich sehe da kein Problem."
    joe "Geh nackt! Dann bekommst du auch mehr Trinkgeld."
    m "Niemals! Ich werde nicht nackt tanzen!"
    m "!!!"
    m "Ich brauche Bühnenkleider!"
    joe "Hm, mal sehen, was ich da für dich tun kann."
    joe "Frage eine andere Stripperin nach Kleidern."
    m "Sie sagten, sie geben mir nichts..."
    m "..." 
    joe "Du musst heute nicht auf die Bühne."
    joe "Ich sage Ashley, dass du ab morgen deine Schulden begleichen wirst."
    joe "{c}Komme morgen wieder{/c}."
    joe "Claire arbeitet, sie wird dir was geben."
    mt "{cMorgen{/c} muss ich wieder in diese abartige Umkleide, wah!"
    mt "Да еще и придется знакомиться с еще одной хамкой!"
    mt "!!!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:336
translate german dialogue_5_dance_strip_8_9f365275:

    # mt "Это и есть вторая стриптизерша?"
    # mt "Надо приготовиться к знакомству со второй хамкой." 
    # mt "Она, наверное, тоже возомнила себя звездой, как та рыжая стерва..."
    # mt "Звездой в грязном пабе в трущобах!.." 
    # stripper "Привет." 
    # stripper "Молли мне говорила, что у нас новенькая. Это ты?"
    # m "..."
    # m "Д-да... Привет..."
    # stripper "Я Клэр. А ты?"
    # m "Я [monica_pub_name]. А Молли это та рыжая стриптизерша?"
    # clare "Да." 
    # clare "Она тут звезда и очень гордится этим."
    # clare "С ней лучше дружить и не вставать у нее на пути."
    # mt "Звезда! Ха-ха! Стриптизерша со звездной болезнью!"
    # mt "Похоже, эта Клэр единственная в этой дыре, кто может нормально общаться."
    # clare "Ты давно в стриптизе, [monica_pub_name]?"
    # m "Нет. Сегодня будет мое первое выступление..."
    # mt "Танцы у пилона на улицах трущоб - не в счет!" 
    # clare "Не волнуйся." 
    # clare "Я выступаю уже несколько лет и мне очень нравится."
    # m "Нравится?!" 
    # m "Я думала такое делают только из-за денег..."
    # clare "Для меня это искусство. Мне нравится делиться своей красотой и видеть восторженные взгляды мужчин."
    # clare "Это занятие не является источником денег для меня."
    # mt "Хм... Искусство?.."
    # mt "Возможно, если так к этому относиться, то намного проще выходить на сцену."
    # mt "Но я не представляю себе такого отношения к этому."
    # mt "Сами по себе танцы полуголой на публике отвратительны."
    # mt "И я не изменю своего отношения к этому никогда!"
    # mt "!!!"
    # clare "[monica_pub_name], почему ты не переодеваешься?"
    # clare "В чем ты будешь выступать?"
    # clare "Тебе уже пора выходить на сцену."
    # m "У меня нет одежды для сцены..."
    # m "Эшли сказала, что я могу спросить одежду у тебя."
    # clare "Без проблем. Ты можешь взять вот это." 
    # mt "А из этой Клэр получилась бы неплохая модель..."
    # mt "Конечно, до Мелани, а тем более до меня, ей далеко, но все же."
    # mt "И что она забыла в этой дыре, тем более, что она тут не из-за денег..."
    # clare "К вещам Молли лучше не приближайся."
    # clare "Наша звезда очень ревностно к этому относится." 
    # clare "У меня полно подобных шмоток."
    # clare "Можешь этот костюм оставить себе."
    # m "Серьезно?!" 
    # m "..." 
    # mt "Мне придется надевать на себя ЭТО?"
    # mt "Фи! Какой вульгарный костюм!"
    # mt "Да еще и после стриптизерши!"
    # mt "Какой ужас!"
    # mt "Я, Моника Бакфетт, буду танцевать полуголая! В дешевом пабе для толпы неудачников!!!"
    # mt "Я не могу поверить в это!"
    mt "Ist das die andere Stripperin?"
    mt "Ich bereite mich besser darauf vor, diese andere Hure zu treffen." 
    mt "Sie dachte vielleicht, dass sie der Star ist, wie der Rotschopf..."
    mt "Ein Star in einem dreckigen Pub in den Slums..." 
    stripper "Hey." 
    stripper "Molly sagte, wir haben eine Neue! Bist du das?"
    m "..."
    m "J-Ja... Hey..."
    stripper "Ich bin Claire. Und du?"
    m "Ich bin [monica_pub_name]. Ist Molly die Rothaarige?"
    clare "Ja." 
    clare "Sie ist der Star hier und darauf ist sie sehr stolz."
    clare "Ist wohl besser mit ihr befreundet zu sein und ihr nicht in den Weg zu kommen."
    mt "Ein Star! Haha! Eine Stripperin mit Starallüren!"
    mt "Scheint so, als wäre Claire die Einzige, mir der man hier normal reden."
    clare "Bist du schon lange Stripperin, [monica_pub_name]?"
    m "Nein. Heute ist mein erstes Mal..."
    mt "Tanzen an der Stange in den Slums zählt hier nicht!" 
    clare "Kein Sorge." 
    clare "Ich mache das schon seit einigen Jahren und mir gefällt es wirklich."
    m "Dir gefällt das?!" 
    m "Ich dachte, man macht das nur wegen dem Geld..."
    clare "Für mich ist das eine Art Kunst. Ich zeige gerne meine Schönheit und genieße die verzehrenden Blicke der Männer."
    clare "Это занятие не является источником денег для меня."
    mt "Ehm... Kunst?..."
    mt "Vielleicht wäre es mit dieser Einstellung viel leichter für mich auf der Bühne..."
    mt "Aber ich kann mir das so noch nicht vorstellen."
    mt "Halb nackt in der Öffentlichkeit zu tanzen ist abstoßend."
    mt "Und diese Haltung werde ich auch nicht mehr ändern!"
    mt "!!!"
    clare "[monica_pub_name], warum ziehst du dich nicht um?"
    clare "Was trägst du für die Show?"
    clare "Du bist dran."
    m "Ich habe nicht mal was zum anziehen..."
    m "Ashley sagte, ich könnte eventuell dich fragen nach einem Outfit."
    clare "Kein Thema, du kannst das haben." 
    mt "Diese Claire wäre ein gutes Model..."
    mt "Natürlich käme sie nie an Melanie oder gar mich heran, aber immerhin..."
    mt "Was macht sie nur hier in den Slums, besonders, da es ihr nicht um das Geld geht..."
    clare "Geh lieber weg von Mollys Sachen."
    clare "Unser Star hier ist da sehr eigen." 
    clare "Ich habe viele Outfits wie diese."
    clare "Das kannst du behalten."
    m "Im Ernst?!" 
    m "..." 
    mt "Ich soll DAS tragen?"
    mt "Ih! Was für ein vulgäres Teil!"
    mt "Und nach dem Striptease..."
    mt "Wie furchtbar!"
    mt "Soll ich, Monica Buckfett, halb nackt tanzen! In einem billigen Loch für Loser!!!"
    mt "Ich fasse es nicht!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:428
translate german dialogue_5_dance_strip_8_1c00f72e:

    # clare "А у тебя отличная фигура, [monica_pub_name]."
    # mt "Она что, ко мне пытается пристать, как Эшли?!"
    # mt "Я не хочу связываться с еще одной лесбиянкой!"
    # clare "Мужчины в зале с ума сойдут, когда тебя увидят."
    # mt "Я к этому привыкла."
    # mt "Мужчины всегда сходили по мне с ума..."
    # clare "Ты сегодня будешь звездой, [monica_pub_name]."
    # mt "Конечно, буду! Мне нет здесь равных!"
    # mt "И не только здесь! Мне нет равных нигде!"
    # clare "Таким шикарным ногам и такой попе, как у тебя, позавидует любая модель."
    # clare "Ты просто создана для обложки какого-нибудь модного журнала."
    # mt "Хм... Хорошо, что она их не читает."
    # mt "Боюсь себе даже представить, если меня здесь кто-нибудь узнает."
    clare "Du hast eine tolle Figur, [monica_pub_name]."
    mt "Versucht sie mich zu belästigen wie Ashley?"
    mt "Ich will nicht noch Ärger mit einer anderen Lesbe!"
    clare "Die Männer im Publikum werden durchdrehen, wenn sie dich sehen."
    mt "Ich bin daran gewöhnt."
    mt "Мужчины всегда сходили по мне с ума..."
    clare "Du wirst heute ein Star sein, [monica_pub_name]."
    mt "Natürlich werde ich das! Ich habe hier keine Rivalin."
    mt "И не только здесь! Мне нет равных нигде!"
    clare "So wunderbare Beine und mit so einem heißen Arsch den du hast, würde dich jedes Model beneinden."
    clare "Du bist ja geradezu gemacht als Covermodel eines Modemagazins."
    mt "Eh... Gut, dass sie die nicht liest."
    mt "Ich habe Angst was wäre, wenn mich jemand erkennen würde."

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:655
translate german dialogue_5_dance_strip_17_4487aafe:

    # joe "[monica_pub_name], это костюм Клэр?"  
    # m "Да." 
    # joe "Я смотрю, ты с ней подружилась..."  
    # m "Тебе что с этого?" 
    # joe "Выяснишь для меня, как к ней подкатить?"
    # m "???" 
    # joe "Она тут ни с кем не общается..."
    # joe "И никого к себе не подпускает..."
    # joe "На приваты не соглашается, хотя предложений много..."
    # joe "А она тут работает уже не один год. И я все это время не знаю, как подойти к ней..."
    # clare "Что здесь происходит?!" 
    # clare "Тебе чего надо от [monica_pub_name]?!" 
    # joe "Я... Мне... Я просто..." 
    # clare "Я просто пойду сейчас к твоей жене!" 
    # clare "И расскажу, чем ТЫ тут занимаешься!"
    # joe "Ч-ч-чем???"
    # clare "Пристаешь к [monica_pub_name]!!!"
    # joe "Я... Я не пристаю!"
    # joe "Не надо ничего говорить Эшли!"
    # clare "Тогда пошел отсюда! Быстро!!!" 
    # joe "!!!"
    # clare "Вот кобель!"
    # clare "!!!"
    # clare "Если снова будет приставать, скажи мне. Он меня боится."
    # m "Спасибо, Клэр."
    # mt "Когда я выберусь из этого дна, заведу себе такой же хлыст от извращенцев!"
    joe "[monica_pub_name], ist das Claires Outfit?"  
    m "Ja." 
    joe "Ich sehe, du hast dich mit ihr angefreundet..."  
    m "Was interessiert dich das?" 
    joe "Kannst du für mich rausfinden, wie ich mich ihr nähern kann?"
    m "???" 
    joe "Sie redet mit niemandem hier..."
    joe "Und sie lässt auch keinen an sich ran..."
    joe "Sie lehnt jede Privatvorstellung ab, obwohl es viele Anfragen gibt..."
    joe "Und das, obwohl sie seit Jahren hier arbeitet. Und während all der Zeit hatte ich keine Chance, mich ihr zu nähern."
    clare "Was ist hier los?!" 
    clare "Was willst du von [monica_pub_name]?!" 
    joe "Ich... Also... Ich wollte nur..." 
    clare "Ich gehe jetzt zu deiner Frau!" 
    clare "Und sage ihr, was DU hier machst!"
    joe "W-W-WA-WAS?!?"
    clare "Löcherst du etwa [monica_pub_name]!!!"
    joe "Ich... Nein, das mache ich nicht!"
    joe "Sag nichts Ashley!"
    clare "Dann verschwinde hier! Schnell!!!" 
    joe "!!!"
    clare "Was für ein Köter!"
    clare "!!!"
    clare "Wenn er das nochmal versucht, sag es mir. Er hat Angst vor mir."
    m "Dank dir, Claire."
    mt "Когда я выберусь из этого дна, заведу себе такой же хлыст от извращенцев!"

# game/Quests/EP2_09/ep29_dialogues2_dance_strip.rpy:748
translate german dialogue_5_dance_strip_21_b71ff680:

    # ashley "[monica_pub_name], сколько ты заработала сегодня чаевых?"
    # m "Зачем тебе это нужно знать?" 
    # ashley "Ты забыла, что ты здесь работаешь за 30 процентов от чаевых?."
    # m "???"
    # m "Но ты же говорила, что я смогу забирать чаевые!"
    # m "МОИ чаевые! Которые я заработала, выступая на сцене!"
    # ashley "Ага. Ты забираешь 30 процентов чаевых, остальное - мне."
    # ashley "Тебя что-то не устраиваает?!"
    # m "..." 
    # mt "Если я сейчас ей откажу, она запретит мне работать здесь..."
    # mt "А мне нужна эта работа..."
    # mt "Как же меня достала эта Эшли!"
    # mt "!!!"
    # ashley "Чего ты ждешь?!"
    # ashley "Сейчас же давай сюда чаевые или можешь убираться отсюда навсегда!"
    ashley "[monica_pub_name], wieviel hast du heute bekommen?"
    m "Warum willst du das wissen?" 
    ashley "Hast du vergessen, dass ich 30 Pozent des Trinkgeldes bekomme?"
    m "???"
    m "Aber du hast gesagt, ich darf alles behalten!"
    m "Mein Trinkgeld! Welches ich durch das Tanzen auf der Bühne verdient habe!"
    ashley "Ага. Ты забираешь 30 процентов чаевых, остальное - мне."
    ashley "Stört dich etwas daran?!"
    m "..." 
    mt "Wenn ich sie abweise, wird sie mir verbieten, hier zu arbeiten..."
    mt "Und ich brauche diesen Job..."
    mt "Ich habe Ashley so satt."
    mt "!!!"
    ashley "Worauf wartest du?!"
    ashley "Gib mit das Geld oder verschwinde hier für immer!"

