# TODO: Translation updated at 2019-08-15 14:57

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:7
translate english ep27_dialogues2_melanie1_10836444:

    # secretary "Мисс Мелани, со мной связалась Мисс Виктория, секретарь Мистера Дика." 
    # secretary "Она просила передать Вам, чтобы Вы посетили его офис."
    secretary "Мисс Мелани, со мной связалась Мисс Виктория, секретарь Мистера Дика." 
    secretary "Она просила передать Вам, чтобы Вы посетили его офис."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:10
translate english ep27_dialogues2_melanie1_5ba196c2:

    # melanie "Она сообщила причину необходимости визита?" 
    melanie "Она сообщила причину необходимости визита?" 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:12
translate english ep27_dialogues2_melanie1_9030ca43:

    # secretary "Мисс Мелани, она сказала что это в Ваших интересах." 
    secretary "Мисс Мелани, она сказала что это в Ваших интересах." 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:14
translate english ep27_dialogues2_melanie1_0ec2b741:

    # melanie "Эта девочка так и сказала, дословно?" 
    melanie "Эта девочка так и сказала, дословно?" 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:16
translate english ep27_dialogues2_melanie1_f40ecdb6:

    # secretary "Да, Мисс Мелани, она так и сказала."
    secretary "Да, Мисс Мелани, она так и сказала."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:23
translate english ep27_dialogues2_melanie1_7d1b2980:

    # melanie "Если эта девочка еще раз позвонит, то передайте ей, что мои интересы ее никак не касаются." 
    melanie "Если эта девочка еще раз позвонит, то передайте ей, что мои интересы ее никак не касаются." 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:25
translate english ep27_dialogues2_melanie1_53c0c8d0:

    # secretary "Хорошо, Мисс Мелани, я передам."
    secretary "Хорошо, Мисс Мелани, я передам."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:28
translate english ep27_dialogues2_melanie1_cb85cd88:

    # melanie "..." 
    # melanie "Хорошо, спасибо. Я подумаю насчет этого."
    melanie "..." 
    melanie "Хорошо, спасибо. Я подумаю насчет этого."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:36
translate english ep27_dialogues2_melanie1_31da08cf:

    # melanie "В моих интересах?" 
    # melanie "Очень странный подбор слов..."
    # melanie "Возможно, это перефразировала его секретарь."
    # melanie "Юная девочка, ревнующая своего Босса."
    melanie "В моих интересах?" 
    melanie "Очень странный подбор слов..."
    melanie "Возможно, это перефразировала его секретарь."
    melanie "Юная девочка, ревнующая своего Босса."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:41
translate english ep27_dialogues2_melanie1_cec5853f:

    # melanie "Странно что Дик не связался со мной напрямую..." 
    # melanie "Ладно, стоит навестить его."
    melanie "Странно что Дик не связался со мной напрямую..." 
    melanie "Ладно, стоит навестить его."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:58
translate english ep27_dialogues2_melanie2_f05f871b:

    # reception_secretary "Здравствуйте, Миссис Мелани!" 
    # reception_secretary "Рада снова видеть Вас!"
    # reception_secretary "Вы решили навестить Мистера Дика?"
    reception_secretary "Hello, Mrs. Melanie!" 
    reception_secretary "Рада снова видеть Вас!"
    reception_secretary "Вы решили навестить Мистера Дика?"

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:62
translate english ep27_dialogues2_melanie2_87be496e:

    # melanie "Да, верно." 
    # melanie "Его офис все там-же?"
    melanie "Да, верно." 
    melanie "Его офис все там-же?"

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:65
translate english ep27_dialogues2_melanie2_f1fe784b:

    # reception_secretary "Да, его офис там же." 
    # reception_secretary "Разрешите Вас проводить туда?"
    reception_secretary "Да, его офис там же." 
    reception_secretary "Разрешите Вас проводить туда?"

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:68
translate english ep27_dialogues2_melanie2_8950b6fa:

    # melanie "Нет необходимости в этот раз." 
    # melanie "Я помню как туда подняться."
    melanie "Нет необходимости в этот раз." 
    melanie "Я помню как туда подняться."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:71
translate english ep27_dialogues2_melanie2_69417e87:

    # reception_secretary "Если что-то понадобится, дайте мне знать!" 
    reception_secretary "Если что-то понадобится, дайте мне знать!" 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:73
translate english ep27_dialogues2_melanie2_7ad5efc3:

    # melanie "Спасибо." 
    melanie "Thank you." 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:78
translate english ep27_dialogues2_melanie2_5d97b613:

    # melanie "Странно, а где эта маленькая девочка, которая думает что знает что и в чьих интересах..." 
    # melanie "Надо высказать Дику свое неудовольствие ей."
    melanie "Странно, а где эта маленькая девочка, которая думает что знает что и в чьих интересах..." 
    melanie "Надо высказать Дику свое неудовольствие ей."

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:81
translate english ep27_dialogues2_melanie2_c2e1c51f:

    # melanie "..." 
    melanie "..." 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:83
translate english ep27_dialogues2_melanie2_bc88fb30:

    # melanie "И где сам Дик?" 
    # melanie "Наверное, в своем кабинете..."
    # img_13950
    # dick_secretary "О, Мисс Мелани..." 
    # dick_secretary "Проходите, я Вас как раз ждала..."
    # img_13951
    # melanie "Девочка, я не ошиблась кабинетом?" 
    # melanie "Или, может быть, это ты ошиблась стулом?"
    # img_13952
    # melanie "Я пришла к Мистеру Дику, твоему Боссу." 
    # melanie "Любишь посидеть на его месте, пока его нет?"
    # img_13953
    # dick_secretary "Вы не ошиблись кабинетом, Мисс Мелани." 
    # dick_secretary "И Вы пришли ко мне, а не к Мистеру Дику."
    # dick_secretary "Это я пригласила Вас..."
    # img_13954
    # melanie "Ты?!" 
    # melanie "Не слишком-ли смелая инициатива, юная девока?"
    # melanie "Это слишком много чести для маленькой секретарши, которая спит со своим Боссом."
    # melanie "Ты ведь знаешь кто я такая."
    # img_13955
    # dick_secretary "Я знаю кто Вы такая, Мисс Мелани..." 
    # img_13956
    # melanie "Ты ревнуешь и делаешь глупости, но помни." 
    # melanie "Я могу щелчком пальцев лишить тебя милости твоего Босса и этой работы."
    # melanie "Ты играешь с огнем, девочка."
    # img_13957
    # dick_secretary "Мисс Мелани." 
    # dick_secretary "Меня трогают Ваши слова, но я трачу сейчас свое время на разговор, который в Ваших же интересах."
    # img_13958
    # melanie "У нас с тобой разные интересы, девочка." 
    # melanie "И они никак не могут пересекаться."
    # melanie "Ты не можешь сказать ничего, что могло бы заинтересовать меня."
    # melanie "Ты очень предсказуемая и примитивная."
    # melanie "Я вижу тебя насквозь."
    # img_13959
    # dick_secretary "Мисс Мелани, Вы продолжаете делать все, чтобы более и более нравиться мне." 
    # img_13960
    # dick_secretary "Но перейдем к делу."  
    # img_13961
    # dick_secretary "В круг моих знакомых входит фотограф, папарацци." 
    # dick_secretary "Он следит за знаменитостями, вроде Вас."
    # img_13962
    # melanie "..." 
    # img_13963
    # dick_secretary "..." 
    # img_13964
    # melanie "Таких знаменитых моделей как Я окружает множество извращенцев." 
    # melanie "Я к этому привыкла."
    # melanie "Чем ты хочешь меня удивить, девочка?"
    # img_13965
    # dick_secretary "Дело в том, что Мистер Дик уже какое-то время занимается делом некой Моники Бакфетт." 
    # dick_secretary "Она чем-то неугодила некоему Мистеру Маркусу и теперь отчаянно нуждается в помощи."
    # dick_secretary "Вы знаете что-нибудь про это, Мисс Мелани?"
    # img_13966
    # melanie "Я знаю Миссис Бакфетт. Это мой бывший Босс." 
    # melanie "Она покинула место работы и теперь я не знаю что с ней."
    # img_13967
    # melanie "Меня это неинтересует." 
    # melanie "Это все?"
    # dick_secretary "Мисс Мелани." 
    # dick_secretary "Пожалуйста, взгляните на эти снимки."
    # melanie "..."
    # dick_secretary "Вот на этот."
    # dick_secretary "И вот на этот."
    # melanie "И что с того?" 
    # melanie "Эти снимки сделаны в разное время."
    # melanie "На первом - моя личная жизнь."
    # melanie "На втором - Миссис Бакфетт навестила меня для того, чтобы..."
    # dick_secretary "Для того, чтобы попросить Вас о помощи." 
    # melanie "Это не твое дело, девочка." 
    # melanie "Я понимаю твою ревность, но смирись с тем, что Я нравлюсь твоему Боссу больше чем ТЫ."
    # dick_secretary "..." 
    # dick_secretary "Если мы положим эти снимки в следующем порядке..." 
    # dick_secretary "То становится очевидно, что Миссис Бакфетт пришла к Вам за помощью." 
    # dick_secretary "Затем Вы помогли ей, соблазнив Мистера Дика, моего Босса."
    # melanie "..." 
    # dick_secretary "Мистер Маркус связывался со мной какое-то время назад." 
    # dick_secretary "И просил сообщить ему, если кто-либо еще будет пытаться помочь Миссис Бакфетт."
    # melanie "!!!" 
    # dick_secretary "Я решила пойти Вам навстречу и сообщила Вам об этом до того, как эти кадры попадут на публику." 
    # dick_secretary "И до того, как эти кадры попадут к Мистеру Маркусу."
    # dick_secretary "Я подумала что это может заинтересовать Вас, Мисс Мелани."
    # melanie "..." 
    # dick_secretary "Вам это интересно или мы можем закончить разговор?" 
    # melanie "Виктория, я бы..." 
    # melanie "Я бы предпочла, чтобы эти фото не попадали на публику и к Мистеру Маркусу вовсе..." 
    # dick_secretary "Это весьма сложно, Мисс Мелани." 
    # dick_secretary "Мой знакомый хочет заработать на этих фото."
    # dick_secretary "К тому же, мне показалось что Мистер Маркус влиятельный человек." 
    # dick_secretary "И может достойно отблагодарить меня за помощь."
    # dick_secretary "Вы знакомы с ним?"
    # melanie "!!!" 
    # melanie "Я..." 
    # melanie "Я немного знакома с ним..."
    # melanie "Мисс Виктория." 
    # melanie "Мы с Вами умные люди."
    # melanie "Я уверена, что мы можем найти компромисс."
    # melanie "Назовите сумму."
    # dick_secretary "Ах, деньги..." 
    # dick_secretary "Да, это разумное предложение."
    # dick_secretary "И я готова принять их, но..."
    # melanie "Что Но?.." 
    # dick_secretary "Я не принимаю подарков от незнакомых людей..." 
    # melanie "Что ты имеешь ввиду, девочка?" 
    # dick_secretary "Мисс Виктория." 
    # melanie "..." 
    # melanie "Что Вы имеете ввиду, Мисс Виктория?" 
    # dick_secretary "Видите-ли, Мисс Мелани." 
    # dick_secretary "У меня здесь ответственная работа."
    # dick_secretary "У меня строгий Босс, который учит меня не доверять незнакомым людям."
    # dick_secretary "Поэтому я не могу принять у Вас Ваши деньги."
    # melanie "..." 
    # dick_secretary "..." 
    # melanie "Что мне сделать, чтобы Вы стали доверять мне, Мисс Виктория." 
    # dick_secretary "Вы должны сделать так, чтобы я могла доверять Вам, Мисс Мелани." 
    # melanie "Что для этого надо сделать?" 
    # dick_secretary "Стать моей подружкой." 
    # melanie "Что мне надо сделать, чтобы стать Вашей подружкой, Мисс Виктория?" 
    # dick_secretary "Мисс Мелани, Вам надо попросить меня о том, чтобы стать ей." 
    # dick_secretary "Затем вести себя как хорошая подружка."
    # dick_secretary "С плохими подружками я не дружу."
    # dick_secretary "И для плохих подружек я не буду идти на жерты, чтобы не распространять их неосторожные фото..."
    # melanie "..." 
    # dick_secretary "..." 
    # melanie "!!!" 
    # dick_secretary "???" 
    melanie "И где сам Дик?" 
    melanie "Наверное, в своем кабинете..."
    img_13950
    dick_secretary "О, Мисс Мелани..." 
    dick_secretary "Проходите, я Вас как раз ждала..."
    img_13951
    melanie "Девочка, я не ошиблась кабинетом?" 
    melanie "Или, может быть, это ты ошиблась стулом?"
    img_13952
    melanie "Я пришла к Мистеру Дику, твоему Боссу." 
    melanie "Любишь посидеть на его месте, пока его нет?"
    img_13953
    dick_secretary "Вы не ошиблись кабинетом, Мисс Мелани." 
    dick_secretary "И Вы пришли ко мне, а не к Мистеру Дику."
    dick_secretary "Это я пригласила Вас..."
    img_13954
    melanie "Ты?!" 
    melanie "Не слишком-ли смелая инициатива, юная девока?"
    melanie "Это слишком много чести для маленькой секретарши, которая спит со своим Боссом."
    melanie "Ты ведь знаешь кто я такая."
    img_13955
    dick_secretary "Я знаю кто Вы такая, Мисс Мелани..." 
    img_13956
    melanie "Ты ревнуешь и делаешь глупости, но помни." 
    melanie "Я могу щелчком пальцев лишить тебя милости твоего Босса и этой работы."
    melanie "Ты играешь с огнем, девочка."
    img_13957
    dick_secretary "Мисс Мелани." 
    dick_secretary "Меня трогают Ваши слова, но я трачу сейчас свое время на разговор, который в Ваших же интересах."
    img_13958
    melanie "У нас с тобой разные интересы, девочка." 
    melanie "И они никак не могут пересекаться."
    melanie "Ты не можешь сказать ничего, что могло бы заинтересовать меня."
    melanie "Ты очень предсказуемая и примитивная."
    melanie "Я вижу тебя насквозь."
    img_13959
    dick_secretary "Мисс Мелани, Вы продолжаете делать все, чтобы более и более нравиться мне." 
    img_13960
    dick_secretary "Но перейдем к делу."  
    img_13961
    dick_secretary "В круг моих знакомых входит фотограф, папарацци." 
    dick_secretary "Он следит за знаменитостями, вроде Вас."
    img_13962
    melanie "..." 
    img_13963
    dick_secretary "..." 
    img_13964
    melanie "Таких знаменитых моделей как Я окружает множество извращенцев." 
    melanie "Я к этому привыкла."
    melanie "Чем ты хочешь меня удивить, девочка?"
    img_13965
    dick_secretary "Дело в том, что Мистер Дик уже какое-то время занимается делом некой Моники Бакфетт." 
    dick_secretary "Она чем-то неугодила некоему Мистеру Маркусу и теперь отчаянно нуждается в помощи."
    dick_secretary "Вы знаете что-нибудь про это, Мисс Мелани?"
    img_13966
    melanie "Я знаю Миссис Бакфетт. Это мой бывший Босс." 
    melanie "Она покинула место работы и теперь я не знаю что с ней."
    img_13967
    melanie "Меня это неинтересует." 
    melanie "Это все?"
    dick_secretary "Мисс Мелани." 
    dick_secretary "Пожалуйста, взгляните на эти снимки."
    melanie "..."
    dick_secretary "Вот на этот."
    dick_secretary "И вот на этот."
    melanie "И что с того?" 
    melanie "Эти снимки сделаны в разное время."
    melanie "На первом - моя личная жизнь."
    melanie "На втором - Миссис Бакфетт навестила меня для того, чтобы..."
    dick_secretary "Для того, чтобы попросить Вас о помощи." 
    melanie "Это не твое дело, девочка." 
    melanie "Я понимаю твою ревность, но смирись с тем, что Я нравлюсь твоему Боссу больше чем ТЫ."
    dick_secretary "..." 
    dick_secretary "Если мы положим эти снимки в следующем порядке..." 
    dick_secretary "То становится очевидно, что Миссис Бакфетт пришла к Вам за помощью." 
    dick_secretary "Затем Вы помогли ей, соблазнив Мистера Дика, моего Босса."
    melanie "..." 
    dick_secretary "Мистер Маркус связывался со мной какое-то время назад." 
    dick_secretary "И просил сообщить ему, если кто-либо еще будет пытаться помочь Миссис Бакфетт."
    melanie "!!!" 
    dick_secretary "Я решила пойти Вам навстречу и сообщила Вам об этом до того, как эти кадры попадут на публику." 
    dick_secretary "И до того, как эти кадры попадут к Мистеру Маркусу."
    dick_secretary "Я подумала что это может заинтересовать Вас, Мисс Мелани."
    melanie "..." 
    dick_secretary "Вам это интересно или мы можем закончить разговор?" 
    melanie "Виктория, я бы..." 
    melanie "Я бы предпочла, чтобы эти фото не попадали на публику и к Мистеру Маркусу вовсе..." 
    dick_secretary "Это весьма сложно, Мисс Мелани." 
    dick_secretary "Мой знакомый хочет заработать на этих фото."
    dick_secretary "К тому же, мне показалось что Мистер Маркус влиятельный человек." 
    dick_secretary "И может достойно отблагодарить меня за помощь."
    dick_secretary "Вы знакомы с ним?"
    melanie "!!!" 
    melanie "I..." 
    melanie "Я немного знакома с ним..."
    melanie "Мисс Виктория." 
    melanie "Мы с Вами умные люди."
    melanie "Я уверена, что мы можем найти компромисс."
    melanie "Назовите сумму."
    dick_secretary "Ах, деньги..." 
    dick_secretary "Да, это разумное предложение."
    dick_secretary "И я готова принять их, но..."
    melanie "Что Но?.." 
    dick_secretary "Я не принимаю подарков от незнакомых людей..." 
    melanie "Что ты имеешь ввиду, девочка?" 
    dick_secretary "Мисс Виктория." 
    melanie "..." 
    melanie "Что Вы имеете ввиду, Мисс Виктория?" 
    dick_secretary "Видите-ли, Мисс Мелани." 
    dick_secretary "У меня здесь ответственная работа."
    dick_secretary "У меня строгий Босс, который учит меня не доверять незнакомым людям."
    dick_secretary "Поэтому я не могу принять у Вас Ваши деньги."
    melanie "..." 
    dick_secretary "..." 
    melanie "Что мне сделать, чтобы Вы стали доверять мне, Мисс Виктория." 
    dick_secretary "Вы должны сделать так, чтобы я могла доверять Вам, Мисс Мелани." 
    melanie "Что для этого надо сделать?" 
    dick_secretary "Стать моей подружкой." 
    melanie "Что мне надо сделать, чтобы стать Вашей подружкой, Мисс Виктория?" 
    dick_secretary "Мисс Мелани, Вам надо попросить меня о том, чтобы стать ей." 
    dick_secretary "Затем вести себя как хорошая подружка."
    dick_secretary "С плохими подружками я не дружу."
    dick_secretary "И для плохих подружек я не буду идти на жерты, чтобы не распространять их неосторожные фото..."
    melanie "..." 
    dick_secretary "..." 
    melanie "!!!" 
    dick_secretary "???" 

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:286
translate english ep27_dialogues2_melanie2_36f012e8:

    # melanie "Мне надо подумать!" 
    # dick_secretary "Думайте быстрее, Мисс Мелани!"
    melanie "Мне надо подумать!" 
    dick_secretary "Думайте быстрее, Мисс Мелани!"

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:290
translate english ep27_dialogues2_melanie2_b90ce831:

    # melanie "Мисс Виктория..." 
    # melanie "Я хочу стать Вашей подружкой."
    # dick_secretary "Неубедительно." 
    # dick_secretary "Я не верю в искренность Ваших слов."
    # dick_secretary "Попробуйте еще раз."
    # melanie "!!!" 
    # melanie "Мисс Виктория..." 
    # melanie "Я - Мелани, самая популярная модель Модного Журнала."
    # melanie "Я очень известна и знаменита."
    # melanie "И Я бы очень хотела стать Вашей подружкой."
    # melanie "И была бы счастлива, если бы Вы приняли мою дружбу с Вами..."
    # dick_secretary "Хорошо, но ты обещаешь быть хорошей подружкой?" 
    # dick_secretary "Каждый четверг присылать мне сертификат на $ 10.000 и делать все что я скажу."
    # melanie "!!!" 
    # dick_secretary "..." 
    # melanie "!!!"
    # dick_secretary "???" 
    # melanie "Да, я согласна..." 
    # dick_secretary "Повтори все что я сказала!" 
    # melanie "!!!" 
    # dick_secretary "!!!" 
    # melanie "Я..." 
    # melanie "Я обещаю что буду хорошей подружкой."
    # melanie "И буду каждый четверг присылать Вам сертификат на $ 10.000."
    # dick_secretary "И?" 
    # melanie "..." 
    # dick_secretary "..." 
    # melanie "И буду делать что Вы скажете, Мисс Виктория." 
    # dick_secretary "Хорошо, подружка." 
    # dick_secretary "Пока ты будешь хорошей подружкой, эти фото останутся только у меня."
    # melanie "..." 
    # dick_secretary "Да, кстати." 
    # dick_secretary "У меня есть еще одна подружка, которую ты хорошо знаешь."
    # melanie "..."
    # dick_secretary "Она навещает меня регулярно." 
    # dick_secretary "Однако, она не всегда себя хорошо ведет."
    # dick_secretary "И, чтобы сновать стать хорошей подружкой, ей приходится просить прощения у меня."
    # melanie "..." 
    # dick_secretary "Это хорошо что ты одела ту же шубку, что и на фото."  
    # dick_secretary "Можно сделать хороший кадр."
    # melanie "..." 
    # dick_secretary "Могу поспорить, что под этой шубкой ничего нет." 
    # dick_secretary "Ты ведь пришла для того, чтобы трясти своими сиськами перед Диком, да?"
    # melanie "!!!" 
    # dick_secretary "Давай, показывай их, как это сделала первая подружка." 
    # dick_secretary "Я хочу сделать фото и сравнить Ваши сиськи."
    # melanie "!!!" 
    # melanie "Я не буду показывать свою грудь!" 
    # melanie "Я уважающая себя женщина и..."
    # dick_secretary "Ты плохая подружка! Можешь уходить!" 
    # dick_secretary "Хорошая подружка не пререкается со мной."
    # melanie "!!!" 
    # dick_secretary "Можешь идти, я не задерживаю тебя!" 
    # melanie "!!!" 
    # dick_secretary "..." 
    # melanie "..." 
    # melanie "Хорошо..."
    # melanie "Я сделаю это, но на этом все, договорились?"
    # dick_secretary "Это только начало, подружка!" 
    # dick_secretary "Да, и еще одно пререкание и я с тобой больше не дружу!"
    # melanie "!!!" 
    # dick_secretary "Давай, показывай!" 
    # dick_secretary "Мне нужно фото, дискредитирующее тебя перед Мистером Диком!"
    # melanie "..." 
    # dick_secretary "Отлично!" 
    # dick_secretary "Теперь Мистер Дик поймет, что ты такая же шлюха, как и Бакфетт!"
    # melanie "!!!" 
    # dick_secretary "У тебя красивая грудь, подружка!" 
    # melanie "Я знаю..." 
    # melanie "Мисс Виктория..."
    # melanie "Все мечтают о такой груди, как у меня..."
    # dick_secretary "Но скажи, чья грудь лучше?" 
    # dick_secretary "Твоя или моя?" 
    # melanie "..." 
    # dick_secretary "..." 
    # dick_secretary "Хорошенько подумай, прежде чем ответить, подружка..."
    # melanie "..." 
    # melanie "Ваша грудь лучше, Мисс Виктория..." 
    # dick_secretary "Правильный ответ." 
    # dick_secretary "Хорошая подружка!"
    # melanie "Мисс Виктория, мы закончили?" 
    # melanie "Я могу идти?"
    # dick_secretary "Нет, подружка." 
    # dick_secretary "Я хочу чтобы ты мне помогла..."
    # melanie "..." 
    # melanie "В чем Вы хотите чтобы я Вам помогла, Мисс Виктория?" 
    # dick_secretary "Подружка, я ждала тебя здесь целый день." 
    # dick_secretary "Я всегда ношу сапожки, чтобы выглядеть красиво." 
    # dick_secretary "И, пока я тебя ждала, у меня затекла ножка."
    # melanie "..."
    # dick_secretary "Пожалуйста, сними этот сапожок!" 
    # dick_secretary "Будь хорошей подружой!"
    # melanie "!!!" 
    # dick_secretary "..." 
    # dick_secretary "Хорошо, а теперь сделай моей ножке массаж своей грудью..." 
    # melanie "ЧТО?!" 
    # melanie "Моей грудью?! Трогать моей грудью твои ноги?!!" 
    # dick_secretary "Кажется я слышала пререкание?" 
    # dick_secretary "Или мне послышалось?"
    # melanie "!!!" 
    # dick_secretary "Мне послышалось?" 
    # dick_secretary "Или передо мной плохая подружка?!"
    # melanie "!!!"
    # dick_secretary "..." 
    # melanie "Вам послышалось, Мисс Виктория..." 
    # dick_secretary "Давай, подружка!" 
    # dick_secretary "Твои сиськи - это твой основной рабочий инструмент."
    # dick_secretary "С помощью этого инструмента ты сделала карьеру."
    # dick_secretary "Почему бы не использовать его, чтобы снять усталось у лучшей подружки?"
    # melanie "..."
    # dick_secretary "Я ведь твоя лучшая подружка, Мелани? Правда?"
    # melanie "!!!"
    # melanie "Вы..."
    # melanie "Вы моя лучшая подружка, Мисс Виктория..."
    # dick_secretary "Давай, подружка, Да!"
    # dick_secretary "Да, Давай!"
    # dick_secretary "Хорошенько работай своими сиськами, Да!"
    # dick_secretary "Меня так возбуждает!"
    # dick_secretary "Эти сиськи стоят миллоны долларов."
    # dick_secretary "Тебе пишут сотни тысяч поклонников, Да?"
    # melanie "Да, Мисс Виктория..."
    # dick_secretary "Но я думаю это лучшее применение твоим сиськам, нежели показ их Мистеру Дику!"
    # melanie "!!!"
    # dick_secretary "Скажи, ты рада сделать массаж своей лучшей подружке?"
    # melanie "!!!"
    # melanie "Да, я рада сделать Вам массаж, Мисс Виктория..."
    # dick_secretary "Хорошо..."
    # dick_secretary "Возьми мой большой пальчик себе в рот..."
    # melanie "!!!"
    # dick_secretary "Мне надо повторить?"
    melanie "Mrs. Victoria..." 
    melanie "Я хочу стать Вашей подружкой."
    dick_secretary "Неубедительно." 
    dick_secretary "Я не верю в искренность Ваших слов."
    dick_secretary "Попробуйте еще раз."
    melanie "!!!" 
    melanie "Mrs. Victoria..." 
    melanie "Я - Мелани, самая популярная модель Модного Журнала."
    melanie "Я очень известна и знаменита."
    melanie "И Я бы очень хотела стать Вашей подружкой."
    melanie "И была бы счастлива, если бы Вы приняли мою дружбу с Вами..."
    dick_secretary "Хорошо, но ты обещаешь быть хорошей подружкой?" 
    dick_secretary "Каждый четверг присылать мне сертификат на $ 10.000 и делать все что я скажу."
    melanie "!!!" 
    dick_secretary "..." 
    melanie "!!!"
    dick_secretary "???" 
    melanie "I agree..." 
    dick_secretary "Повтори все что я сказала!" 
    melanie "!!!" 
    dick_secretary "!!!" 
    melanie "I..." 
    melanie "Я обещаю что буду хорошей подружкой."
    melanie "И буду каждый четверг присылать Вам сертификат на $ 10.000."
    dick_secretary "И?" 
    melanie "..." 
    dick_secretary "..." 
    melanie "И буду делать что Вы скажете, Мисс Виктория." 
    dick_secretary "Хорошо, подружка." 
    dick_secretary "Пока ты будешь хорошей подружкой, эти фото останутся только у меня."
    melanie "..." 
    dick_secretary "Oh, by the way." 
    dick_secretary "У меня есть еще одна подружка, которую ты хорошо знаешь."
    melanie "..."
    dick_secretary "Она навещает меня регулярно." 
    dick_secretary "Однако, она не всегда себя хорошо ведет."
    dick_secretary "И, чтобы сновать стать хорошей подружкой, ей приходится просить прощения у меня."
    melanie "..." 
    dick_secretary "Это хорошо что ты одела ту же шубку, что и на фото."  
    dick_secretary "Можно сделать хороший кадр."
    melanie "..." 
    dick_secretary "Могу поспорить, что под этой шубкой ничего нет." 
    dick_secretary "Ты ведь пришла для того, чтобы трясти своими сиськами перед Диком, да?"
    melanie "!!!" 
    dick_secretary "Давай, показывай их, как это сделала первая подружка." 
    dick_secretary "Я хочу сделать фото и сравнить Ваши сиськи."
    melanie "!!!" 
    melanie "Я не буду показывать свою грудь!" 
    melanie "Я уважающая себя женщина и..."
    dick_secretary "Ты плохая подружка! Можешь уходить!" 
    dick_secretary "Хорошая подружка не пререкается со мной."
    melanie "!!!" 
    dick_secretary "Можешь идти, я не задерживаю тебя!" 
    melanie "!!!" 
    dick_secretary "..." 
    melanie "..." 
    melanie "Fine..."
    melanie "Я сделаю это, но на этом все, договорились?"
    dick_secretary "Это только начало, подружка!" 
    dick_secretary "Да, и еще одно пререкание и я с тобой больше не дружу!"
    melanie "!!!" 
    dick_secretary "Давай, показывай!" 
    dick_secretary "Мне нужно фото, дискредитирующее тебя перед Мистером Диком!"
    melanie "..." 
    dick_secretary "Excellent!" 
    dick_secretary "Теперь Мистер Дик поймет, что ты такая же шлюха, как и Бакфетт!"
    melanie "!!!" 
    dick_secretary "У тебя красивая грудь, подружка!" 
    melanie "I found out..." 
    melanie "Mrs. Victoria..."
    melanie "Все мечтают о такой груди, как у меня..."
    dick_secretary "Но скажи, чья грудь лучше?" 
    dick_secretary "Твоя или моя?" 
    melanie "..." 
    dick_secretary "..." 
    dick_secretary "Хорошенько подумай, прежде чем ответить, подружка..."
    melanie "..." 
    melanie "Ваша грудь лучше, Мисс Виктория..." 
    dick_secretary "Right." 
    dick_secretary "Good girlfriend!"
    melanie "Мисс Виктория, мы закончили?" 
    melanie "Can I go?"
    dick_secretary "Нет, подружка." 
    dick_secretary "Я хочу чтобы ты мне помогла..."
    melanie "..." 
    melanie "В чем Вы хотите чтобы я Вам помогла, Мисс Виктория?" 
    dick_secretary "Подружка, я ждала тебя здесь целый день." 
    dick_secretary "Я всегда ношу сапожки, чтобы выглядеть красиво." 
    dick_secretary "И, пока я тебя ждала, у меня затекла ножка."
    melanie "..."
    dick_secretary "Пожалуйста, сними этот сапожок!" 
    dick_secretary "Будь хорошей подружой!"
    melanie "!!!" 
    dick_secretary "..." 
    dick_secretary "Хорошо, а теперь сделай моей ножке массаж своей грудью..." 
    melanie "WHAT?!" 
    melanie "Моей грудью?! Трогать моей грудью твои ноги?!!" 
    dick_secretary "Кажется я слышала пререкание?" 
    dick_secretary "Или мне послышалось?"
    melanie "!!!" 
    dick_secretary "Мне послышалось?" 
    dick_secretary "Или передо мной плохая подружка?!"
    melanie "!!!"
    dick_secretary "..." 
    melanie "Вам послышалось, Мисс Виктория..." 
    dick_secretary "Давай, подружка!" 
    dick_secretary "Твои сиськи - это твой основной рабочий инструмент."
    dick_secretary "С помощью этого инструмента ты сделала карьеру."
    dick_secretary "Почему бы не использовать его, чтобы снять усталось у лучшей подружки?"
    melanie "..."
    dick_secretary "Я ведь твоя лучшая подружка, Мелани? Правда?"
    melanie "!!!"
    melanie "Вы..."
    melanie "Вы моя лучшая подружка, Мисс Виктория..."
    dick_secretary "Давай, подружка, Да!"
    dick_secretary "Да, Давай!"
    dick_secretary "Хорошенько работай своими сиськами, Да!"
    dick_secretary "Меня так возбуждает!"
    dick_secretary "Эти сиськи стоят миллоны долларов."
    dick_secretary "Тебе пишут сотни тысяч поклонников, Да?"
    melanie "Да, Мисс Виктория..."
    dick_secretary "Но я думаю это лучшее применение твоим сиськам, нежели показ их Мистеру Дику!"
    melanie "!!!"
    dick_secretary "Скажи, ты рада сделать массаж своей лучшей подружке?"
    melanie "!!!"
    melanie "Да, я рада сделать Вам массаж, Мисс Виктория..."
    dick_secretary "Fine..."
    dick_secretary "Возьми мой большой пальчик себе в рот..."
    melanie "!!!"
    dick_secretary "Мне надо повторить?"

# game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:554
translate english ep27_dialogues2_melanie2_f8875a1f:

    # dick_secretary "Ах! Как чудесно!"
    # dick_secretary "Ах! Ах!"
    # melanie "!!!"
    # dick_secretary "А теперь... теперь..."
    # dick_secretary "Теперь... АААаааааааххххх!!!"
    # dick_secretary "Ладно, подружка..." 
    # dick_secretary "На сегодня хватит..."
    # dick_secretary "Мы продолжим нашу дружбу позже..."
    # dick_secretary "Ты можешь идти, подружка, но помни про наш уговор..." 
    dick_secretary "Ах! Как чудесно!"
    dick_secretary "Ах! Ах!"
    melanie "!!!"
    dick_secretary "А теперь... теперь..."
    dick_secretary "Теперь... АААаааааааххххх!!!"
    dick_secretary "Ладно, подружка..." 
    dick_secretary "На сегодня хватит..."
    dick_secretary "Мы продолжим нашу дружбу позже..."
    dick_secretary "Ты можешь идти, подружка, но помни про наш уговор..." 

translate english strings:

    # game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:18
    old "Идти на встречу с Викторией."
    new "Идти на встречу с Викторией."

    # game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:18
    old "Отказаться от встречи (пропуск всех событий с Викторией)."
    new "Отказаться от встречи (пропуск всех событий с Викторией)."

    # game/Quests/EP2_07/ep27_dialogues2_melanie.rpy:282
    old "Попросить Викторию стать ее подружкой."
    new "Попросить Викторию стать ее подружкой."

