# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:27
translate german ep211_dialogues6_slum_apartment_1_0bd0bb16:

    # mt "Каждый раз, когда прихожу сюда..."
    # mt "Боюсь, что встречу ту кошмарную лесбиянку."
    # mt "Как вспомню этот ужас в хостеле..."
    # mt "Нет! Даже думать об этом не хочу!"
    # mt "Тоже мне, дешевый ночлег!"
    # mt "!!!"
    # mt "Хммм..."
    # mt "Кстати, о дешевом ночлеге..."
    # mt "И почему я раньше об этом не задумывалась?!"
    # mt "У меня сейчас есть работа. Заработок у меня стабильный."
    # mt "Возможно, мне удастся арендовать какую-нибудь небольшую квартиру?"
    # mt "По-моему, это хорошая идея!"
    # mt "Я, наконец-то, перестану работать на эту семейку идиотов!"
    # mt "И жить независимо ни от кого!!!"
    # mt "Только как мне подобрать подходящую по цене квартиру?"
    # mt "..."
    # mt "Юлия снимает квартиру в ужасном доме!"
    # mt "Но стоит признать, что квартира у нее довольно уютная."
    # mt "Конечно, там все старое и убогое..."
    # mt "Но все же я была бы не против жить в подобной квартире."
    # mt "Представь только, Моника!"
    # mt "Никто не будет тебе указывать, что делать и какую одежду носить..."
    # mt "Никто не будет ограничивать тебя в еде или в походах в душ..."
    # mt "..."
    # mt "Кто может знать, где найти дешевое жилье?"
    # mt "???"
    # mt "В прошлый раз продавец шавермы посоветовал мне хостел..."
    # mt "Возможно, стоит спросить у него?"
    mt "Immer wenn ich her komme..."
    mt "Habe ich Angst, diese schreckliche Lesbe zu treffen."
    mt "Ich erinnere mich noch an den Hostelhorror..."
    mt "Nein! Ich will nicht mehr daran denken!"
    mt "Das billige Bett!"
    mt "!!!"
    mt "Hmmm ..."
    mt "Apropos billig..."
    mt "Warum habe ich nicht vorher daran gedacht?!"
    mt "Ich habe jetzt einen Job. Mein Einkommen ist regelmäßig."
    mt "Vielleicht kann ich mir ein kleines Apartement mieten?"
    mt "Ich glaube, das ist eine gute Idee!"
    mt "Dann kann ich damit aufhören, für diese Idiotenfamilie zu arbeiten!"
    mt "Und endlich unabhängig leben!!!!!!"
    mt "Aber wie finde ich das richtige Apartement zu einem guten Preis?"
    mt "..."
    mt "Julia hat ein Apartement in einem schrecklichen Haus!"
    mt "Aber ich muss zugeben, dass es schon gemütlich sein kann."
    mt "Natürlich ist alles alt und unschön..."
    mt "Aber ich würde wirklich gern in so einer Wohnung leben."
    mt "Stell dir das doch mal vor, Monica!"
    mt "Niemand wird dir mehr sagen, was du tragen sollst..."
    mt "Niemand kann bestimmen, was du isst und wann du duscht..."
    mt "..."
    mt "Wer könnte wissen, wo man billige Wohnungen bekommt?"
    mt "???"
    mt "Letztes Mal hat mir der Kebabtyp das Hostel empfohlen..."
    mt "Vielleicht sollte ich ihn fragen?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:67
translate german ep211_dialogues6_slum_apartment_2_75f2b7ff:

    # mt "Уверена, он знает какое-нибудь дешевое жилье."
    # mt "Мне эта идея настолько понравилась..."
    # mt "И почему я раньше об этом не подумала?"
    mt "Er weiß sicher etwas passendes."
    mt "Mir gefällt diese Idee so sehr..."
    mt "Warum habe ich da nicht früher dran gedacht?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:76
translate german ep211_dialogues6_slum_apartment_3_02b8e298:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # m "Нет. Мне не нужен твой кебаб!"
    # m "..."
    shawarma "Oh Madame!"
    shawarma "Bist du für den besten Kebab der Gegend gekommen?"
    m "Nein. Ich brauche keinen!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:83
translate german ep211_dialogues6_slum_apartment_3_3e89a366:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # mt "Нет, я пока не готова тратить деньги на апартаменты."
    # mt "Мне это сейчас не по карману."
    # m "Сам ешь свой отвратительный кебаб!"
    shawarma "Oh Madame!"
    shawarma "Bist du für den besten Kebab der Gegend gekommen?"
    mt "Nein, ich will noch kein Geld für Apartements ausgeben."
    mt "Ich kann es mir noch nicht leisten."
    m "Friss deinen ekligen Kebab selber!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:92
translate german ep211_dialogues6_slum_apartment_3_4ccfab15:

    # mt "Животное!"
    # m "!!!"
    mt "So ein Tier!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:97
translate german ep211_dialogues6_slum_apartment_3_08c0c4af:

    # m "Я хотела кое-что у тебя спросить..."
    # shawarma "Все, что Мадаме захотеть, Джек все сделать!"
    # shawarma "Для прекрасной Мадаме Джеку ничего не жалко!"
    # m "Мне..."
    # m "..."
    # m "Одной моей знакомой нужны апартаменты."
    # m "Она хочет их арендовать..."
    # m "За небольшую плату."
    # m "Ты знаешь, где можно найти что-то подходящее?"
    # shawarma "О, Мадаме!"
    # shawarma "Вы правильно сделали, что пришли ко мне!"
    # shawarma "Джек все здесь знать!"
    # shawarma "Для восхитительной Мадаме у Джека есть апрартаменты!"
    # m "Это... Это не для меня квартира..."
    # shawarma "Мадаме может не волноваться."
    # shawarma "Джек никому не рассказывать!" 
    # m "!!!"
    # m "Так у тебя есть апартаменты под аренду?" 
    # shawarma "Конечно, Мадаме!!!"
    # shawarma "И как раз сейчас они свободны!"
    # shawarma "Это шикарный апрартамент! Мадаме будет очень доволен!"
    # shawarma "И всего за 50 долларов за один неделя!"
    # shawarma "Прекрасный Мадаме не найдет ничего дешевле!"
    # mt "Всего 50 долларов в неделю?!"
    # mt "Боже! Я не верю в эту удачу!"
    # mt "Наконец-то!"
    # mt "..."
    # mt "Хотя... Это не такие уж маленькие деньги для меня сейчас..."
    # mt "!!!"
    # mt "Интересно, что это за апартаменты?"
    # m "А где эти апартаменты находятся?"
    # shawarma "Недалеко отсюда, Мадаме!"
    # shawarma "Мадаме хочет посмотреть свой будущий шикарный апрартамент?"
    # m "..."
    m "Ich möchte dich was fragen..."
    shawarma "Alles was Sie wollen, Madame, Jack wird es machen!"
    shawarma "Für die wunderschöne Madame, wird Jack alles tun!"
    m "Ich bin..."
    m "..."
    m "Eine meiner Freundinnen braucht ein Apartement."
    m "Sie will es mieten..."
    m "Für eine geringe Miete."
    m "Weißt du, wo ich sowas finde?"
    shawarma "Oh Madame!"
    shawarma "Gut, dass Du damit zu mir gekommen bist!"
    shawarma "Jack weiß alles!"
    shawarma "Für eine schöne Madame hat Jack ein Apartement!"
    m "Das... Das ist nicht für mich..."
    shawarma "Die Madame muss sich nichts denken."
    shawarma "Jack wird es niemandem sagen!" 
    m "!!!"
    m "Also vermietest du Apartements?" 
    shawarma "Natürlich, Madame!!"
    shawarma "Derzeit sind sie günstig!"
    shawarma "Das ist ein wunderschönes Apartement! Es wird der Madame gefallen!"
    shawarma "Für nur 50 $ die Woche!"
    shawarma "Die liebliche Madame wird nichts günstigeres finden!"
    mt "Nur 50 $ die Woche?!"
    mt "Oh Gott, was für ein Glück!"
    mt "Endlich!"
    mt "..."
    mt "Obwohl... das ist nicht wenig Geld für mich..."
    mt "!!!"
    mt "Ich frage mich, was das für ein Apartement wohl ist..."
    m "Wo sind die Apartements?"
    shawarma "Nicht weit von hier!"
    shawarma "Will die Madame ihre luxuriöse, zukünftige Wohnung sehen?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:138
translate german ep211_dialogues6_slum_apartment_3_57df20b7:

    # mt "Я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Нет."
    # m "Мне нужно еще подумать."
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    mt "Ich bin noch nicht bereit, soviel Geld auszugeben."
    mt "Ich kann es mir noch nicht leisten."
    m "Nein."
    m "Ich muss nochmal darüber nachdenken."
    shawarma "Wenn Madame es will, kann sie immer zu Jack kommen!"
    shawarma "Jack wird glücklich sein, der Madame zu helfen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:146
translate german ep211_dialogues6_slum_apartment_3_35ce5548:

    # m "А там никто больше не будет жить, кроме меня?"
    # shawarma "Конечно, нет!"
    # shawarma "Мадаме будет хозяйкой в этот шикарный апрартамент!"
    # m "Отлично!"
    # m "Я хочу их посмотреть!"
    m "Und außer mir wird da niemand wohnen?"
    shawarma "Natürlich nicht!"
    shawarma "Die Madame wird alleine sein in dem wunderschönen Apartement!"
    m "Ausgezeichnet!"
    m "Ich will sie sehen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:157
translate german ep211_dialogues6_slum_apartment_4_0b452b14:

    # mt "Этот дом просто кошмарный!!!"
    mt "Das Haus ist widerlich!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:163
translate german ep211_dialogues6_slum_apartment_5_731c9362:

    # mt "Жуть!!!"
    # mt "Он что-то говорил про шикарные апартаменты?"
    # mt "Шикарные апартаменты в ТАКОМ доме?!"
    # mt "???"
    # m "Ты уверен, что апартаменты хорошие?"
    # shawarma "Конечно, Мадаме!"
    # shawarma "Там есть очень большой комнат!"
    # shawarma "Отдельный кухня!"
    # shawarma "И даже отдельный душ!"
    # shawarma "Мадаме идти за мной и сам все посмотреть!"
    # m "..."
    mt "Horror!!!"
    mt "Sagte er nicht was von luxuriösen Wohnungen?"
    mt "Luxuriöse Wohnungen in so einem Haus?"
    mt "???"
    m "Bist du sicher, dass diese Wohnungen gut sind?"
    shawarma "Natürlich!"
    shawarma "Sie haben große Zimmer!"
    shawarma "Eine eigene Küche!"
    shawarma "Und eine Dusche!"
    shawarma "Madame möge mir folgen und alles anschauen!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:179
translate german ep211_dialogues6_slum_apartment_6_3df513d4:

    # m "Куда ты меня привел?!"
    # m "Это что?! Квартира?!"
    # m "?!?!?!"
    # shawarma "Да, Мадаме!"
    # shawarma "Теперь это Ваш шикарный апрартамент!"
    # m "Шикарный?!"
    # m "Да ты охренел?!"
    # shawarma "В этот прекрасный апрартамент раньше жить рабочие."
    # m "Рабочие?!"
    # shawarma "Да! Они делать ремонт в очень богатых местах!"
    # shawarma "Может быть, Мадаме слышать про отель Ле Фгранд или офис Модный Журнал?"
    # m "!!!"
    # shawarma "Рабочий, который делать такую хорошую работу, всегда любить комфорт и чистота."
    # shawarma "Они бы не жить здесь, если бы это место не быть таким хорошим!"
    # m "..."
    # m "А что это за убогие обои?! Это тоже от рабочих?"
    # shawarma "Нет, Мадаме."
    # shawarma "Еще раньше здесь жить прекрасный женщин, чистый ангел!"
    # shawarma "Он оказывать здесь небольшие услуги уважаемым жителям нашей улица!"
    # mt "Боже! Какой кошмар!"
    # shawarma "Ну что? Мадаме будет жить в этот шикарный квартир?"
    # m "..."
    m "Wohin hat er mich gebracht?!"
    m "Was ist das?! Ein Apartement?!"
    m "?!?!?!"
    shawarma "Ja, Madame!"
    shawarma "Das ist ein wunderbares Apartement!"
    m "Wunderbar?!"
    m "Bist du total bescheuert?!"
    shawarma "Hier haben Arbeiter gewohnt."
    m "Arbeiter?!"
    shawarma "Ja! Sie reparieren Dinge bei den Reichen!"
    shawarma "Vielleicht hat die Madame schon mal was vom La Grande Hotel oder dem Fashion Magazin gehört?"
    m "!!!"
    shawarma "Arbeiter, die so tolle Arbeit haben, mögen einen gewissen Komfort und Sauberkeit."
    shawarma "Sie hätten hier nicht gewohnt, wenn es nicht so schön wäre!"
    m "..."
    m "Und was ist das für eine zerknitterte Tapete?! Ist die auch von den Arbeitern?"
    shawarma "Nein, Madame."
    shawarma "Früher wohnte hier eine wunderschöne Frau, ein wahrer Engel!"
    shawarma "Ich bin da um den armen Leuten ein zu Hause zu geben."
    mt "Oh Gott, was für ein Alptraum!"
    shawarma "Und? Will die Madame hier wohnen?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:206
translate german ep211_dialogues6_slum_apartment_6_4171ca65:

    # m "Я не буду жить в этой!"
    # m "В этой!"
    # m "В этом пристанище для бомжей!!!"
    # m "!!!"
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    m "Darin werde ich nicht wohnen...!"
    m "Darin...!"
    m "In diesem Hafen für Obdachlose!!!"
    m "!!!"
    shawarma "Wenn Madame es will, kann sie immer zu Jack kommen!"
    shawarma "Jack wird glücklich sein, der Madame zu helfen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:216
translate german ep211_dialogues6_slum_apartment_6_4ccfab15:

    # mt "Животное!"
    # m "!!!"
    mt "So ein Tier!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:221
translate german ep211_dialogues6_slum_apartment_6_f2a90234:

    # mt "Может быть, стоит арендовать эту грязную дыру?"
    # mt "Всего 50 долларов в неделю..."
    # mt "..."
    # mt "Это ведь на какое-то время."
    # mt "Потом я подберу себе жилье получше."
    # m "Я... Я согласна арендовать эти ужасные апра... апартаменты ненадолго."
    # shawarma "Отлично! Мадаме сделать правильный решение!"
    # shawarma "Джек очень счастлив, что такой восхитительный женщин будет жить в его апрартамент!"
    # m "Когда требуется оплата, прямо сейчас? Я сразу смогу здесь жить?"
    # shawarma "Конечно, Мадаме сразу может тут остаться и жить!"
    # shawarma "Только Джеку сначала нужен документ Мадаме..."
    # mt "Документы?!"
    # mt "Дъявол!!!"
    # mt "!!!"
    # mt "Что же делать?!"
    # m "Я... Я не хотела бы показывать свои документы..."
    # m "Тем более, у меня их нет с собой..."
    # m "Я их забыла дома..."
    # m "..."
    # m "Без документов никак нельзя?"
    # shawarma "Если Мадаме хочет снять этот квартир без документ..."
    # shawarma "То Джек легко помочь Мадаме с этим!"
    # shawarma "Этот прекрасный апартамент не входит в жилой фонд..."
    # shawarma "Поэтому здесь нет злой проверяющий миграционных бумаг!"
    # shawarma "И такой прекрасный леди мочь жить здесь без документ!"
    # m "В таком случае, мы договорились."
    # m "Я арендую эту ужасную квартиру!"
    # shawarma "Прекрасно! Джек счастлив помочь такой восхитительный женщин!"
    # shawarma "Этот шикарный квартир будет стоить всего 300 долларов в неделю для Мадаме!"
    # m "!!!"
    # m "ЧТО?!"
    # m "Ты же говорил, что она стоит $ 50 в неделю!"
    # m "Почему сейчас стало $ 300?!"
    # m "?!?!?!"
    # shawarma "Специально для Мадаме!"
    # shawarma "Документ есть - апартамент стоит $ 50 в неделю!"
    # shawarma "Документ нет - апартамент стоит $ 300 в неделю!"
    # shawarma "Джек все для Вас готов сделать, Мадаме!"
    # shawarma "Мадаме никакой квартир больше не найдет, если у нее нет документ!"
    # shawarma "Да еще и по специальный цена!"
    # m "Апартаменты в трущобах за 300 долларов в неделю?!"
    # m "?!?!?!"
    # mt "Вот сволочь!"
    # mt "!!!"
    # mt "300 долларов в неделю..."
    # mt "..."
    mt "Könnte es es wert sein, dieses Loch zu mieten?"
    mt "Nur 50 $ die Woche?!"
    mt "..."
    mt "Übergangsweise."
    mt "Danach werde ich einen besseren Ort finden."
    m "Ich... Ich stimme dem Mietvertrag zu... für eine Zeit lang."
    shawarma "Ausgezeichnet! Madame trifft die richtige Entscheidung!"
    shawarma "Jack ist sehr glücklich, dass so eine fröhliche Dame in seiner Wohnung leben wird!"
    m "Wann ist die Zahlung fällig? Kann ich gleich einziehen?"
    shawarma "Natürlich ist das möglich!"
    shawarma "Jack braucht nur zuerst Dokumente der Madame..."
    mt "Dokumente??!"
    mt "Dieser Teufel!"
    mt "!!!"
    mt "Was mache ich jetzt?"
    m "Ich... Ich will meine Dokumente nicht zeigen..."
    m "Außerdem habe ich sie nicht dabei..."
    m "Ich habe sie zu Hause vergessen..."
    m "..."
    m "Ist es ohne Dokumente unmöglich?"
    shawarma "Wenn Madame das Apartement ohne Dokumente will..."
    shawarma "Dann hilft Jack auch hier gerne aus!"
    shawarma "Dieses schöne Apartement ist als solches nicht offiziel gelistet..."
    shawarma "Daher gibt es auch keinen verärgerten Prüfer."
    shawarma "Und eine so schöne Frau kann hier sicherlich auch ohne Papiere leben!"
    m "Dann haben wir einen Deal."
    m "Ich nehme dieses furchtbare Apartement!"
    shawarma "Perfekt! Jack freut sich sehr, einer so schönen Frau zu helfen!"
    shawarma "Das wunderschöne Apartement kostet auch nur 300 $ die Woche!"
    m "!!!"
    m "WAS?!"
    m "Du hast gesagt, es kostet 50 $!"
    m "Warum jetzt 300?!"
    m "?!?!?!"
    shawarma "Nun ja..."
    shawarma "Mit Papieren kostet es 50 $ die Woche!"
    shawarma "Ohne Papiere kostet das Apartement 300 $ die Woche!"
    shawarma "Jack wird es dennoch ermöglichen für die Madame!"
    shawarma "Madame wird kein anderes Apartement ohne Papiere finden!"
    shawarma "Und das ist noch ein guter Preis!"
    m "Ein Apartement in den Slums für 300$ die Woche?!"
    m "?!?!?!"
    mt "So ein Arsch!"
    mt "!!!"
    mt "300 Dollar pro Woche..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:272
translate german ep211_dialogues6_slum_apartment_6_9cf469b3:

    # m "Я не буду жить в этом!"
    # m "В этом пристанище для бомжей!!!"
    # m "Да еще и за такие деньги!"
    # m "!!!"
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    m "Ich werde hier nicht leben!"
    m "In diesem Hafen für Obdachlose!!!"
    m "Das ist viel Geld!"
    m "!!!"
    shawarma "Wenn Madame es will, kann sie immer zu Jack kommen!"
    shawarma "Jack wird glücklich sein, der Madame zu helfen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:282
translate german ep211_dialogues6_slum_apartment_6_4ccfab15_1:

    # mt "Животное!"
    # m "!!!"
    mt "So ein Tier!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:287
translate german ep211_dialogues6_slum_apartment_6_ee1676d6:

    # mt "Вот дъявол!"
    # mt "Мне не удастся снять жилье без документов..."
    # mt "Получается, что это единственный вариант, который я могу найти..."
    # mt "..."
    # shawarma "Мадаме жить один и Джек ее не беспокоить совсем."
    # shawarma "Только один раз в неделю Джек приходить за деньгами."
    # mt "И что мне делать?"
    # mt "???"
    # mt "С другой стороны... Это будет МОЕ жилье... МОЕ!!!"
    # mt "О том, где я живу, никто не будет знать..."
    # mt "Я буду сама себе хозяйка..."
    # mt "И больше никакие никчемные деревенщины мною не будут командовать!"
    # shawarma "Мадаме согласен?"
    # m "Деньги платить сейчас?"
    # shawarma "Да. Сейчас."
    # shawarma "И Мадаме может сразу оставаться жить здесь."
    # m "Следующая оплата ровно через неделю?"
    # shawarma "Джек будет приходить {c}каждая суббота вечер{/c} за деньгами."
    # shawarma "Мадаме платить и оставаться здесь жить!"
    # m "..."
    mt "Das ist der Teufel!"
    mt "Ohne Papiere kann ich nichts mieten..."
    mt "Das ist die einzige Möglichkeit, die ich habe..."
    mt "..."
    shawarma "Madame lebt alleine und Jack will sie nicht belästigen."
    shawarma "Nur einmal pro Woche kommt Jack und will Geld."
    mt "Was soll ich tun?"
    mt "???"
    mt "Andererseits... wir es MEINE Wohnung sein... MEINE!!!"
    mt "Niemand wird wissen, dass ich sie habe..."
    mt "Ich bin meine eigene Herrin..."
    mt "Und keine nutzlosen Idioten werden mich herum kommandieren!"
    shawarma "Stimmt Madame zu?"
    m "Zahlt sie jetzt?"
    shawarma "Ja. Jetzt."
    shawarma "Madame kann sofort einziehen."
    m "Die nächste Zahlung erfolgt dann in genau einer Woche?"
    shawarma "Jack kommt {c}jeden Samstag Abend{/c} um die Miete zu holen."
    shawarma "Wenn Madame bezahlt, bleibt sie auch hier!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:313
translate german ep211_dialogues6_slum_apartment_6_decc33f8:

    # shawarma "Джек счастлив помочь прекрасной Мадаме!"
    # shawarma "Джек придти за деньгами в следующий суббота."
    # shawarma "Вот ключи от Ваш шикарный апартамент!"
    # shawarma "До суббота, прекрасный леди!"
    # m "..." 
    shawarma "Jack freut sich, der schönen Madame zu helfen!"
    shawarma "Jack kommt dann kommenden Samstag."
    shawarma "Hier sind die Schlüssel für das luxuriöse Apartement!"
    shawarma "Bis Samstag dann, schöne Frau!"
    m "..." 

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:327
translate german ep211_dialogues6_slum_apartment_7_617c7d7a:

    # mt "Это самое жуткое место, которое я видела в своей жизни!"
    # mt "Ни в коем случае нельзя, чтобы кто-нибудь узнал, что Моника Бакфетт живет здесь!"
    # mt "!!!"
    # mt "С другой стороны..."
    # mt "Теперь у меня есть МОЕ жилье!"
    # mt "Я могу послать к черту сопляка Барди и эту дуру Бетти!"
    # mt "Хотя... Наверное пока не стоит этого делать..."
    # mt "Вдруг у меня не окажется денег на продление аренды..."
    # mt "Но, все равно, Я теперь независима от них!"
    # mt "Это маленький шаг навстречу к моей цели."
    # mt "Тот день, когда Моника Бакфетт вернет себе все, что у нее отняли, становится все ближе!"
    mt "Das ist der gruseligste Ort, den ich je gesehen habe!"
    mt "Keinesfalls darf jemand wissen, dass Monica Buckfett hier lebt!"
    mt "!!!"
    mt "Andererseits..."
    mt "Jetzt habe ich MEINE eigene Wohnung!"
    mt "Ich kann endlich von dem Wichser Bardie und der dummen Betty fern bleiben!"
    mt "Obwohl... vielleicht ist es das noch nicht wert..."
    mt "Ich habe noch nicht das Geld, mit diese Wohnunh ewig leisten zu können."
    mt "Aber, für jetzt bin ich erstmal unabhängig!"
    mt "Ein weiterer, kleiner Schritt in die richtige Richtung."
    mt "Der Tag, an dem Monica Buckfett wieder alles erhält, was iht gestohlen wurde, kommt näher!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:346
translate german ep211_dialogues6_slum_apartment_8a_1ba992ec:

    # mt "Какое же кошмарное это место!"
    # mt "Может, стоит сделать тут небольшой ремонт?"
    mt "Dieser Ort ist ein Alptraum!"
    mt "Vielleicht muss man hier einiges reparieren?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:351
translate german ep211_dialogues6_slum_apartment_8b_9dc00cc2:

    # mt "Фи! Какая грязь!"
    # mt "Кто сюда притащил весь этот хлам?"
    mt "Wow! Was für eine Unordnung!"
    mt "Wer hat all das Zeug hier her gebracht?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:356
translate german ep211_dialogues6_slum_apartment_8c_702a51ac:

    # mt "Это, конечно, не сравнится с моей шикарной кроватью..."
    # mt "На которой спит теперь эта сучка Бетти."
    # mt "Но все же, на этом можно спать..."
    mt "Das kann natürlich mit meinem tollen Bett nicht mithalten..."
    mt "Auf dem jetzt Betty pennt."
    mt "Aber man kann darauf schlafen."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:362
translate german ep211_dialogues6_slum_apartment_8d_f554aef4:

    # mt "Что за кошмарная мебель здесь?!"
    # mt "Я не хочу даже прикасаться к ней!"
    mt "Was sind hier für schrecklich Möbel?!"
    mt "Я не хочу даже прикасаться к ней!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:367
translate german ep211_dialogues6_slum_apartment_8e_e893cc3d:

    # mt "Нужно будет принести сюда свои наряды..."
    mt "Du musst deine Outfits herbringen..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:372
translate german ep211_dialogues6_slum_apartment_8f_a9d90429:

    # mt "Ужасная кухня!"
    # mt "Надеюсь, здесь нет тараканов?"
    # mt "Все равно я не смогу готовить здесь еду!"
    mt "Widerliche Küche!"
    mt "Надеюсь, здесь нет тараканов?"
    mt "Все равно я не смогу готовить здесь еду!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:378
translate german ep211_dialogues6_slum_apartment_8g_247dc2c6:

    # mt "Эта посуда осталась от прежних жильцов?"
    # mt "Фи! Я не буду ее трогать!"
    mt "Wurde das von dem frührern Bewohner zurück gelassen?"
    mt "Woah! Das fasse ich nicht an!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:384
translate german ep211_dialogues6_slum_apartment_8h_6a5868f1:

    # mt "Эта ванная комната отвратительна!"
    # mt "Я не хочу сюда даже заходить!"
    mt "Dieses Bad ist ja eklig!"
    mt "Ich will da nicht mal rein gehen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:389
translate german ep211_dialogues6_slum_apartment_8i_0871f6f2:

    # mt "Фууу!"
    # mt "Как мне на этом писать?!"
    mt "Puh!"
    mt "Wie soll ich darauf schreiben?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:394
translate german ep211_dialogues6_slum_apartment_8j_926d56b0:

    # mt "Это что за непонятная куча старого хлама?"
    # mt "В этом можно как-то умываться и мыть руки?"
    mt "Was soll dieser Schmutzhaufen?"
    mt "Kann man da Hände waschen?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:399
translate german ep211_dialogues6_slum_apartment_8k_6128cdb6:

    # mt "Мне придется мыть свое великолепное тело водой из куска ржавой трубы..."
    # mt "..."
    mt "Ich muss meinen wunderbaren Körper mit Wasser aus rostigen Rohren waschen..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:412
translate german ep211_dialogues6_slum_apartment_9_ae61b4c8:

    # mt "А это еще что?"
    # mt "Хммм..."
    # mt "Это подделка на мою любимую модель этого бренда..."
    # mt "..."
    # mt "Почему бы мне не носить это дома?"
    # mt "Нужно померить этот наряд."
    # mt "..."
    # mt "Я, конечно, догадываюсь, кто носил это раньше..."
    # mt "Но это неважно... Это теперь МОЕ!!!"
    mt "А это еще что?"
    mt "Hmmm ..."
    mt "Это подделка на мою любимую модель этого бренда..."
    mt "..."
    mt "Warum trage ich das nicht zu Hause?"
    mt "Нужно померить этот наряд."
    mt "..."
    mt "Я, конечно, догадываюсь, кто носил это раньше..."
    mt "Но это неважно... Это теперь МОЕ!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:427
translate german ep211_dialogues6_slum_apartment_9a_8ee288fc:

    # mt "Хорошо, что никто не увидит меня в подделке этого бренда..."
    # mt "О том, что их до меня носил кто-то я предпочитаю не думать."
    # mt "Джек говорил, что раньше здесь жила какая-то проститутка..."
    # mt "..."
    # mt "Мне не важно! Эта одежда теперь моя!"
    mt "Хорошо, что никто не увидит меня в подделке этого бренда..."
    mt "О том, что их до меня носил кто-то я предпочитаю не думать."
    mt "Jack sagte, dass vorher eine Art Prostituierte hier gewohnt hat..."
    mt "..."
    mt "Ist mir egal! Dieses Kleider sind nun meine!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:437
translate german ep211_dialogues6_slum_apartment_10_5cc3ee7e:

    # shawarma "Прекрасный Мадаме!"
    # shawarma "Джек пришел взять с нее деньги за шикарный апартамент!"
    # mt "За эту квартиру и $ 50 жалко платить..."
    # m "..."
    # shawarma "Мадаме стал еще прекрасней в этот домашней костюм!"
    # shawarma "Джек не может отвести глаз от прелестной Мадаме!"
    # shawarma "Вы такой яркий сияющий женщин!"
    # shawarma "Я подходить к дом и видеть, как он светится, благодаря Ваша красота!"
    # mt "Когда он уже заткнется и уйдет отсюда!"
    # m "..."
    # shawarma "Я подумал, что Мадаме слишком прекрасен, чтобы давать Джеку целых $ 300!"
    # shawarma "Джек сделать благородный поступок и предложить скидку для Мадаме!"
    # m "Скидку?"
    # shawarma "Да!"
    # shawarma "Джек сделать скидка в 10 процент, если..."
    # shawarma "Мадаме позволит прикоснуться ему к ее красота и целовать Джека!"
    # mt "!!!"
    # shawarma "Но это еще не все!"
    # shawarma "Джек сделать очень-очень щедрый скидка для Мадаме. 20 процент!"
    # shawarma "Если нефритовый стержень Джека проникать внутрь прекрасный Мадаме!!!"
    # m "Что ты несешь?!"
    # m "Что это все значит?!"
    # shawarma "Это значит, Джек предлагать Вам выгодный сделка."
    # shawarma "Скидка в 10 или 20 процент."
    # m "..."
    shawarma "Liebliche Madame!"
    shawarma "Jack ist da um die Miete zu holen!"
    mt "Eine Schande, für dieses Apartement zu zahlen..."
    m "..."
    shawarma "Die Madame sieht in diesen Sachen sogar noch besser aus!"
    shawarma "Jack bekommt seinen Blick nicht mehr abgewendet!"
    shawarma "Du bist so eine tolle Frau!"
    shawarma "Ich nähere mich dem Haus, und alles leuchtet, dank dir!"
    mt "Когда он уже заткнется и уйдет отсюда!"
    m "..."
    shawarma "Ich denke, die Madame ist zu schön, um Jack 300 $ zu geben!"
    shawarma "Jack gewährt der Madame einen Rabatt!"
    m "Rabatt?"
    shawarma "Ja!"
    shawarma "Jack gibt dir einen Rabatt von 10 %%, wenn..."
    shawarma "Die Madame Jack erlaubt sie zu berühren und zu küssen!"
    mt "!!!"
    shawarma "Aber das ist nicht alles!"
    shawarma "Jack kann auch ein großzügigeres Angebot machen. 20%%!"
    shawarma "Wenn der Jadestift von Jack die Madame penetrieren darf!!!"
    m "Von was redest du bitte?!"
    m "Was soll das bedeuten!?"
    shawarma "Das heißt, Jack bietet dir einen Rabatt an."
    shawarma "Von 10 oder 20 Prozent."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:467
translate german ep211_dialogues6_slum_apartment_10_5a8eea34:

    # mt "Почему бы мне не воспользоваться его предложением?"
    # mt "Скидка мне не помешает."
    # m "И что мне сделать, чтобы получить эту скидку?"
    # shawarma "У прекрасной Мадаме рот как лепесток роз!"
    # shawarma "Такой же восхитительный и нежный!"
    # shawarma "Джек будет счастлив дать в этот рот свой нефритовый стержень!"
    # m "ЧТО?!"
    # m "Да как ты смеешь мне подобное предлагать?!"
    # m "!!!"
    # shawarma "Джек делать очень щедрый и благородный предложение Мадаме..."
    # shawarma "Но если Мадаме откажется, Джек на нее не обижаться."
    # shawarma "Тогда она может просто заплатить Джеку $ 300 за шикарный квартир."
    # mt "Черт!"
    # mt "И что же мне делать?"
    # mt "10 процентов от $ 300 - это немало."
    # mt "А у меня сейчас каждый цент на счету."
    # m "..."
    mt "Warum sollte ich das nicht wahrnehmen?"
    mt "Der Rabatt kümmert mich nicht."
    m "Und was muss ich dafür tun?"
    shawarma "Die schöne Madame hat einen Mund wie eine Rosenblüte!"
    shawarma "So schön und zart!"
    shawarma "Jack würde darin gerne seinen Stift versenken!"
    m "WAS?!"
    m "Wie kann er es wagen, mir sowas anzubieten?!"
    m "!!!"
    shawarma "Jack hat ein sehr gutes Angebot gemacht."
    shawarma "Aber wenn die Madame es ablehnt, wird Jack nicht sauer sein."
    shawarma "Dann kann sie gerne 300 Dollar für das schöne Apartement bezahlen."
    mt "Huch!"
    mt "Was soll ich also tun?"
    mt "10 Prozent von 300 sind viel."
    mt "Sonst habe ich die volle Summe zu bezahlen."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:490
translate german ep211_dialogues6_slum_apartment_10_5fa75320:

    # m "Ты что, ненормальный?!"
    # m "Конечно, я не буду этого делать!"
    # m "Как ты мог вообще до такого додуматься!!!"
    m "Bist du irre?!"
    m "Natürlich werde ich das nicht tun!"
    m "Wie kannst du nur an sowas denken?!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:497
translate german ep211_dialogues6_slum_apartment_10_aa0f5f5b:

    # mt "Животное!"
    # m "!!!"
    # shawarma "Тогда Мадаме платить Джеку $ 300."
    mt "So ein Tier!"
    m "!!!"
    shawarma "Dann muss die Madame 300 $ zahlen."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:506
translate german ep211_dialogues6_slum_apartment_10_885e44c4:

    # mt "Почему бы мне не воспользоваться его предложением?"
    # mt "Скидка мне не помешает."
    # m "И что мне сделать, чтобы получить эту скидку?"
    # shawarma "Красота Мадаме ослеплять Джека!"
    # shawarma "Мадаме прекрасна как древнегреческий богинь!"
    # shawarma "Джек будет счастлив, если она позволит..."
    # shawarma "Проникнуть нефритовый стержень Джека в ее сладкий дырочка!"
    # m "ЧТО-О-О-О?!"
    # m "?!?!?!"
    # m "Да как ты смеешь мне подобное предлагать?!"
    # m "!!!"
    # shawarma "Джек делать очень щедрый и благородный предложение Мадаме..."
    # shawarma "Но если Мадаме откажется, Джек на нее не обижаться."
    # shawarma "Тогда она может просто заплатить Джеку $ 300 за шикарный квартир."
    # mt "Черт!"
    # mt "И что же мне делать?"
    # mt "20 процентов от $ 300 - это немало."
    # mt "А у меня сейчас каждый цент на счету."
    # m "..."
    mt "Warum sollte ich das nicht wahrnehmen?"
    mt "Der Rabatt kümmert mich nicht."
    m "Und was muss ich dafür tun?"
    shawarma "Die Schönheit der Madame blendet Jack!"
    shawarma "Die Madame ist so schön, wie eine griechische Gottheit!"
    shawarma "Jack ist glücklich, wenn sie erlaubt, dass..."
    shawarma "Jacks Jadestift in ihr süßes Loch eintaucht!"
    m "WAAAAAAAS?!"
    m "?!?!?!"
    m "Wie kann er es wagen, mir sowas anzubieten?!"
    m "!!!"
    shawarma "Jack hat ein sehr gutes Angebot gemacht."
    shawarma "Aber wenn die Madame es ablehnt, wird Jack nicht sauer sein."
    shawarma "Dann kann sie gerne 300 Dollar für das schöne Apartement bezahlen."
    mt "Huch!"
    mt "Was soll ich also tun?"
    mt "20 Prozent von 300 ist wirklich viel."
    mt "Sonst habe ich die volle Summe zu bezahlen."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:531
translate german ep211_dialogues6_slum_apartment_10_5fa75320_1:

    # m "Ты что, ненормальный?!"
    # m "Конечно, я не буду этого делать!"
    # m "Как ты мог вообще до такого додуматься!!!"
    m "Bist du irre?!"
    m "Natürlich werde ich das nicht tun!"
    m "Wie kannst du nur an sowas denken?!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:538
translate german ep211_dialogues6_slum_apartment_10_aa0f5f5b_1:

    # mt "Животное!"
    # m "!!!"
    # shawarma "Тогда Мадаме платить Джеку $ 300."
    mt "So ein Tier!"
    m "!!!"
    shawarma "Dann muss die Madame 300 $ zahlen."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:548
translate german ep211_dialogues6_slum_apartment_10_9cb21b79:

    # m "Мне не нужны никакие скидки!"
    # m "Я готова заплатить сумму полностью."
    # m "Забирай деньги и иди!"
    # shawarma "Отлично, Мадаме! Джек очень рад!"
    # shawarma "Джек придет в {c}следующий суббота вечер{/c}!"
    # shawarma "И Мадаме может не сомневаться!"
    # shawarma "Джек очень благородный и щедрый!"
    # shawarma "Он снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    m "Ich brauche keinen Rabatt!"
    m "Ich bezahle die volle Summe."
    m "Nimm das Geld und geh!"
    shawarma "Super, Madame! Jack ist sehr glücklich!"
    shawarma "Jack kommt {c}nächsten Samstah Abend wieder{/c}!"
    shawarma "Da kannst du dir sicher sein!"
    shawarma "Jack ist großzügig und spendabel!"
    shawarma "Er wird der Madame auch nächste Woche einen Rabatt anbieten!"
    m "Das ist alles, geh jetzt!"
    mt "So ein Tier!"
    mt "Gut, dass ich ihn für eine ganze Woche nicht mehr sehe!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:564
translate german ep211_dialogues6_slum_apartment_10_996db04f:

    # mt "Что же мне делать?"
    # mt "У меня не хватает денег на оплату..."
    # mt "Может, он согласится подождать несколько дней?"
    # m "..."
    # m "Я тебе смогу заплатить за апартаменты через несколько дней."
    # m "Ты же не выселишь такую прекрасную леди, как я, на улицу?"
    # m "Всего лишь несколько дней и я все оплачу."
    # shawarma "Нет-нет, Мадаме!"
    # shawarma "Джек восхищается Вашей красотой."
    # shawarma "Но Джек с Мадаме договорился, что деньги будут каждый суббота."
    # shawarma "Нет денег в суббота - нет шикарный апрартамент у Мадаме!"
    # shawarma "Джеку, конечно, очень жаль..."
    # shawarma "Но он вынужден выселять прекрасный леди прямо сейчас!"
    mt "Was mache ich jetzt?"
    mt "Ich habe nicht genug Geld..."
    mt "Vielleicht gibt er mir ein paar Tage Aufschub?"
    m "..."
    m "Ich kann in ein paar Tagen bezahlen."
    m "Du wirst doch nicht eine so schöne Frau wie mich auf die Straße setzen, oder?"
    m "Nur noch ein paar Tage, und ich zahle alles."
    shawarma "Nein nein, Madame!"
    shawarma "Jack bewundert deine Schönheit."
    shawarma "Aber Jack und die Madame haben vereinbart, dass das Geld jeden Samstag zu zahlen ist."
    shawarma "Gibt es kein Geld am Samstag - gibt es kein luxuriöses Apartement für die Madame."
    shawarma "Jack tut das natürlich sehr leid..."
    shawarma "Aber er muss sich an die Regeln halten, wie die Madame auch!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:590
translate german ep211_dialogues6_slum_apartment_11_b942ba20:

    # m "10 процентов - это сколько?"
    # shawarma "Целых $ 30, Мадаме!"
    # shawarma "Джек делать очень щедрый предложение для Вас!"
    # mt "Черт!"
    # mt "Если я соглашусь, я сэкономлю целых $ 30!"
    # mt "..."
    # m "Если об этом узнает хоть одна живая душа!!!"
    # m "!!!"
    # shawarma "Что Вы, Мадаме?!"
    # shawarma "Джек честный и благородный!"
    # shawarma "Джек никому не рассказать о Мадаме!"
    # m "Если кто-то узнает, я тебя убью!"
    # shawarma "Прекрасный Мадаме может не переживать!"
    # shawarma "Джек дает слово мужчины!"
    # mt "Моника, до чего ты докатилась?"
    # mt "Ты собралась делать минет какому-то неудачнику за скидку..."
    # mt "..."
    # mt "Но об этом ведь никто не узнает..."
    # mt "Тем более он даже не догадывается кто я такая..."
    # mt "..."
    # mt "А я сэкономлю деньги."
    # mt "Фу! Не могу поверить, что я делаю это..."
    # mt "И, главное, кому?!"
    # mt "Фу!!!"
    # mt "!!!"
    # shawarma "О, прекрасный Мадаме!"
    # shawarma "Словно лепестки роз ласкают мой нефритовый стержень!"
    # shawarma "Такие нежный и сладкий губы и ротик у Мадаме."
    # shawarma "Джек готов наслаждаться этим вечно!"
    # shawarma "О, Мадаме! Поласкайте мой стержень своим нежным языком!"
    # shawarma "Да, восхитительно!"
    # shawarma "Мммммм!!!"
    # shawarma "Ещееее!"
    # shawarma "ОООООООО!!!" 
    # shawarma "Мадаме, мне никто не доставлял большего наслаждения, чем Вы!!!"
    # shawarma "Джек сдержать свое слово и сделать для Мадаме скидку в 10 процент!"
    # m "..."
    # shawarma "Джек снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    # mt "Не могу поверить, что я сделала это!!!"
    # mt "Какая мерзость!!!"
    # mt "В следующий раз никаких скидок, Моника!"
    # mt "Такой леди, как ты, не пристало заниматься подобными непотребствами!"
    # mt "!!!"
    m "10 Prozent sind wieviel?"
    shawarma "30 Dollar!"
    shawarma "Jack hat hier ein sehr gutes Angebot gemacht!"
    mt "Huch!"
    mt "Wenn ich zustimme, spare ich mir 30 $!"
    mt "..."
    m "Wenn das auch nur eine Menschenseele rausfindet!!!"
    m "!!!"
    shawarma "Was denken sie denn?"
    shawarma "Jack sit ehrlich und großzügig!"
    shawarma "Jack wird nichts erzählen!"
    m "Wenn das jemand rausfindet, töte ich dich!"
    shawarma "Madame muss sich keine Sorgen machen!"
    shawarma "Jack gibt sein Wort!"
    mt "Monica, wie bist du da nur hin gekommen?"
    mt "Du gibst einem Loser einen BJ, nur für einen Rabatt..."
    mt "..."
    mt "Aber niemand wird das erfahern..."
    mt "Und, er weiß nicht mal, wer ich bin..."
    mt "..."
    mt "Ich spare mir Geld."
    mt "Gut! Ich kann nicht glauben, was ich da mache..."
    mt "Und besonders, mit wem?!"
    mt "Fuck!!!"
    mt "!!!"
    shawarma "Oh, schöne Madame!"
    shawarma "Wie Rosenblüten, die meinen Schaft streicheln!"
    shawarma "Madame hat so zarte und weiche Lippen."
    shawarma "Jack wird das für immer genießen!"
    shawarma "Oh Madame! Liebkose meinen Schaft mit deiner Zunge!"
    shawarma "Ja, wunderbar!"
    shawarma "Mmmmmmmm!!!"
    shawarma "Mehr!"
    shawarma "ОООООООО!!!" 
    shawarma "Niemand hat mir je mehr Freude bereitet!!!"
    shawarma "Jack hält sein Wort und gestattet einen Rabatt von 10 Prozent!"
    m "..."
    shawarma "Jack bietet der Madame auch nächsten Samstag einen Rabatt an!"
    m "Das ist alles, geh jetzt!"
    mt "So ein Tier!"
    mt "Gut, dass ich ihn für eine ganze Woche nicht mehr sehe!"
    mt "Ich fasse es nicht, dass ich das getan habe!"
    mt "Was für ein widerliches Ding!!!"
    mt "Nächstes Mal, gibt es keinen Rabatt, Monica!"
    mt "Eine Lady wie du, sollte sich nicht auf sowas einlassen!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:651
translate german ep211_dialogues6_slum_apartment_12_df4357b8:

    # m "20 процентов - это сколько?"
    # shawarma "Целых $ 60, Мадаме!"
    # shawarma "Джек делать очень щедрый предложение для прекрасный леди!!!"
    # mt "Черт!"
    # mt "Если я соглашусь, я сэкономлю целых $ 60!"
    # mt "..."
    # mt "Моника, ты сейчас серьезно?!"
    # mt "Как ты можешь даже предполагать подобное?!"
    # mt "Ты действительно займешься с этим животным сексом за скидку в $ 60?!"
    # mt "?!?!?!"
    # mt "..."
    # mt "Но об этом ведь никто не узнает..."
    # mt "..."
    # mt "А я сэкономлю деньги."
    # m "Я тебя сразу предупрежаю!!!"
    # m "Если об этом узнает хоть одна живая душа!!!"
    # m "Если ты хотя бы намекнешь кому-то о том, что здесь сейчас будет!!!"
    # m "Я тебя убью!!!"
    # m "!!!"
    # m "Ты меня понял?!"
    # shawarma "Что Вы, Мадаме?!"
    # shawarma "Джек честный и благородный!"
    # shawarma "Джек никому не рассказать о Мадаме!"
    # shawarma "Прекрасный Мадаме может не переживать!"
    # shawarma "Джек дает слово мужичины!"
    # shawarma "У Мадаме великолепный попочка!!!"
    # shawarma "Сладкий и прекрасный попочка!!!"
    # shawarma "Джек очень любить такие!"
    # m "Не смей делать какие-нибудь извращенства!"
    # shawarma "Нет-нет, что Вы, Мадаме."
    # shawarma "Джек просто трогать сладкий попочка."
    # shawarma "Ммммм, гладкий и упругий... как персик!"
    # mt "Боже... Когда же он заткнется?!"
    # mt "Фу! Не могу поверить, что я делаю это..."
    # mt "!!!"
    # shawarma "О, какой сладкий дырочка у Мадаме!!!"
    # shawarma "Как тепло и хорошо мой нефритовый стержень!!!"
    # shawarma "Ооооо, как сладко!!!"
    # shawarma "Джек готов наслаждаться этим вечно!"
    # shawarma "Мммммм!!!"
    # shawarma "Джек делать прекрасный Мадаме скидка каждый суббот!!!"
    # shawarma "Оооо, Джек просто на седьмом небе!!!"
    # shawarma "Ааааа!!!"
    # shawarma "Мммммм!!!"
    # shawarma "ОООООООО!!!" 
    # shawarma "Мадаме, мне никто не доставлял больший наслаждений, чем Вы!!!"
    # shawarma "Джек сдержать свое слово и сделать для Мадаме скидку в 20 процент!"
    # m "..."
    # shawarma "Джек снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    # mt "Не могу поверить, что я сделала это!!!"
    # mt "Какая мерзость!!!"
    # mt "В следующий раз никаких скидок, Моника!"
    # mt "Такой леди, как ты, не пристало заниматься подобными непотребствами!"
    # mt "!!!"
    m "20 Prozent sind wieviel?"
    shawarma "Genau 60 Dollar, Madame!"
    shawarma "Jack bietet hier ein mehr als großzügiges Angebot an!!!"
    mt "Huch!"
    mt "Wenn ich zustimme, spare ich mir 60 Dollar!"
    mt "..."
    mt "Monica, im Ernst jetzt?!"
    mt "Wie kannst du das nur erwägen?"
    mt "Willst du wirklich für 60 $ mit diesem Tier Sex haben?"
    mt "?!?!?!"
    mt "..."
    mt "Aber niemand wird das erfahern..."
    mt "..."
    mt "Ich spare mir Geld."
    m "Ich warne dich!"
    m "Wenn das auch nur eine Menschenseele rausfindet!!!"
    m "Wenn du auch nur irgendjemand davon erzählst..."
    m "Dann töte ich dich!"
    m "!!!"
    m "Verstanden?"
    shawarma "Was denken sie denn?"
    shawarma "Jack sit ehrlich und großzügig!"
    shawarma "Jack wird nichts erzählen!"
    shawarma "Madame muss sich keine Sorgen machen!"
    shawarma "Jack gibt sein Wort!"
    shawarma "Madame hat einen traumhaften Arsch!!!"
    shawarma "Sexy und lieblich!!!"
    shawarma "Jack liebt diesen Arsch!"
    m "Wage es nicht, und mach was perverses!"
    shawarma "Nein, nein, nein, Madame!"
    shawarma "Jack berührt ihn nur."
    shawarma "Mmmmm, weich und doch fest... wie ein Pfirsich!"
    mt "Gott... Wann hält er endlich die Klappe?!"
    mt "Gut! Ich kann nicht glauben, was ich da mache..."
    mt "!!!"
    shawarma "Oh, was für ein süßes Loch die Madame hat!!!"
    shawarma "So warm und schön!!!"
    shawarma "Ohhhhhhh, so gut!"
    shawarma "Jack wird das für immer genießen!"
    shawarma "Mmmmmmmm!!!"
    shawarma "Jack macht der Madame jeden Samstag einen wunderbaren Rabatt!!!"
    shawarma "Ohhh, Jack ist im Himmel!!!"
    shawarma "Ahhhh!!!"
    shawarma "Mmmmmmmm!!!"
    shawarma "ОООООООО!!!" 
    shawarma "Madame, noch nie hat mir Eine mehr Freude bereitet!!!"
    shawarma "Jack hält sein Wort und gestattet einen Rabatt von 20 Prozent!"
    m "..."
    shawarma "Jack bietet der Madame auch nächsten Samstag einen Rabatt an!"
    m "Das ist alles, geh jetzt!"
    mt "So ein Tier!"
    mt "Gut, dass ich ihn für eine ganze Woche nicht mehr sehe!"
    mt "Ich fasse es nicht, dass ich das getan habe!"
    mt "Was für ein widerliches Ding!!!"
    mt "Nächstes Mal, gibt es keinen Rabatt, Monica!"
    mt "Eine Lady wie du, sollte sich nicht auf sowas einlassen!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:720
translate german ep211_dialogues6_slum_apartment_13_d850b685:

    # mt "Вот скотина!"
    # mt "Грязное инстинктивное животное!!!"
    # mt "Как он посмел меня выставить на улицу?!"
    # mt "?!?!?!"
    # mt "Я все равно зайду обратно в квартиру!"
    # mt "Ключи же остались у меня!"
    # mt "!!!"
    # mt "Только нужно дождаться, когда он уйдет из квартиры."
    mt "Du Bastard!"
    mt "Dreckiges Tier!!!"
    mt "Wie kann er es wagen, mich auf die Straße zu setzen?!"
    mt "?!?!?!"
    mt "Ich gehe sowieso wieder zurück!"
    mt "Die Schlüssel habe ich ja noch!"
    mt "!!!"
    mt "Ich muss nur warten, bis er endlich weg ist."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:734
translate german ep211_dialogues6_slum_apartment_14_8e4fef89:

    # mt "Мне нужно немного позже прийти сюда."
    # mt "Это животное еще в квартире..."
    mt "Ich komme einfach später wieder."
    mt "Dieses Tier ist immer noch in dem Apartement..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:742
translate german ep211_dialogues6_slum_apartment_15_efc3ce3b:

    # mt "Вот скотина!!!"
    # mt "Он поменял замки в моей квартире!!!"
    # mt "Сволочь!!!"
    # mt "!!!"
    # mt "И что мне теперь делать?!"
    # mt "Неужели мне придется идти к нему и уговаривать впустить меня обратно?!"
    # mt "?!?!?!"
    mt "Du Bastard!"
    mt "Er hat die Schlösser ausgetauscht!!!"
    mt "Schwein!!!"
    mt "!!!"
    mt "Was mache ich jetzt?"
    mt "Muss ich wirklich zu ihm und ihn überzeugen, dass er mich wieder rein lässt?!"
    mt "?!?!?!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:750
translate german ep211_dialogues6_slum_apartment_15_8fc1f114:

    # mt "Он все равно меня не впустит. У меня нет денег заплатить за неделю..."
    # mt "Мне нужно заработать $ 300."
    # mt "Потом я пойду и поговорю с ним."
    # mt "Он не сможет отказать мне."
    mt "Das wird er eh nicht machen. Ich muss das Geld für eine Woche bezahlen..."
    mt "Ich muss 300 $ verdienen."
    mt "Dann komme ich wieder und rede mit ihm."
    mt "Er kann mich nicht abweisen."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:761
translate german ep211_dialogues6_slum_apartment_16_c0b38246:

    # mt "Я не могу зайти в свою квартиру..."
    # mt "Эта сволочь поменяла замки!"
    # mt "Мне нужно пойти к нему."
    mt "Ich kann nicht in mein Apartement..."
    mt "Der Bastard hat die Schlösser ausgetauscht!"
    mt "Ich muss zu ihm."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:772
translate german ep211_dialogues6_slum_apartment_17_500edb17:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # shawarma "Или Мадаме хочет снова жить в шикарный апрартамент?"
    # m "Я хочу вернуться в свою квартиру!"
    # shawarma "Джек не может отказать такой прекрасный леди!"
    # shawarma "А у Мадаме есть деньги?"
    # m "Да!"
    # shawarma "Мадаме может заплатить деньги Джеку прямо сейчас."
    # shawarma "Джек даст Мадаме новый ключ."
    # shawarma "И она может снова жить в шикарный апрартамент Джека!"
    shawarma "Oh Madame!"
    shawarma "Bist du für den besten Kebab der Gegend gekommen?"
    shawarma "Will Madame wieder in einem wunderschönen Apartement leben?"
    m "Ja, ich will wieder zurück!"
    shawarma "Jack kann eine so schöne Lady nicht abweisen!"
    shawarma "Hat die Madame das Geld?"
    m "Ja!"
    shawarma "Du kannst mir das Geld gleich jetzt geben."
    shawarma "Jack gibt der Madame dann den Schlüssel."
    shawarma "Und dann kann sie wieder in Jacks wunderschönem Apartement wohnen!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:784
translate german ep211_dialogues6_slum_apartment_17_cf64e261:

    # shawarma "Отлично, Мадаме!"
    # shawarma "Джек счастлив, что прекрасный Мадаме снова будет жить в его апрартамент!"
    # shawarma "Вот Ваш ключ. С возвращенем, прекрасный леди!"
    # mt "Наконец-то я могу вернуться в свою квартиру!"
    # mt "!!!"
    shawarma "Toll!"
    shawarma "Jack ist glücklich, dass die schöne Madame wieder in dem Apartement wohnt!"
    shawarma "Hier ist dein Schlüssel. Willkommen zurück, schöne Lady!"
    mt "Endlich kann ich wieder zurück!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:792
translate german ep211_dialogues6_slum_apartment_17_58f6c4c1:

    # mt "Нет, я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Я пока не готова заплатить деньги..."
    # shawarma "Если Мадаме передумает, она знать, где найти Джека!"
    # m "..."
    mt "Nein, ich bin noch nicht bereit, soviel Geld auszugeben."
    mt "Ich kann es mir noch nicht leisten."
    m "Ich bin noch nicht bereit, soviel Geld auszugeben."
    shawarma "Wenn die Madame ihre Meinung ändert, weiß sie, wo sie Jack findet!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:800
translate german ep211_dialogues6_slum_apartment_17_8b2a483c:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # shawarma "Или Мадаме хочет снова жить в шикарный апрартамент?"
    # mt "Нет, я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Я пока не готова заплатить деньги..."
    # shawarma "Если Мадаме передумает, она знать, где найти Джека!"
    # m "..."
    shawarma "Oh Madame!"
    shawarma "Bist du für den besten Kebab der Gegend gekommen?"
    shawarma "Will Madame wieder in einem wunderschönen Apartement leben?"
    mt "Nein, ich bin noch nicht bereit, soviel Geld auszugeben."
    mt "Ich kann es mir noch nicht leisten."
    m "Ich bin noch nicht bereit, soviel Geld auszugeben."
    shawarma "Wenn die Madame ihre Meinung ändert, weiß sie, wo sie Jack findet!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:814
translate german ep211_dialogues6_slum_apartment_18_ec2a48e9:

    # mt "Наконец-то я дома!"
    # mt "Никогда бы не подумала, что буду рада вернуться сюда!"
    # mt "!!!"
    mt "Endlich zu Hause!"
    mt "Ich hätte nie gedacht, einmal froh zu sein, wenn ich hier bin!"
    mt "!!!"

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:62
    old "Спросить у продавца шавермы про аренду квартиры."
    new "Frage den Kebabverkäufer nach einem Apartement."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:74
    old "Спросить про апартаменты..."
    new "Frage nach Apartements..."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:74
    old "Уйти отсюда."
    new "Verschwinde von hier."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:90
    old "Моника называла продавца шавермы животным"
    new "Monica nannte den Kebabverkäufer ein Tier"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:133
    old "Нет. $ 50 в неделю - это слишком дорого."
    new "Nein. 50 Dollar die Woche ist zu teuer."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:308
    old "Заплатить $ 300 за апартаменты."
    new "Zahle 300 Dollar pro Apartement."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:320
    old "Заработать $ 300 за аренду апартаментов до субботы."
    new "Verdiene 300 Dollar Miete bis Samstag."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:321
    old "У меня теперь есть место, где я могу жить. Апартаменты в трущобах... Но это лучше, чем подвал в доме, где живет семейка идиотов."
    new "Ich habe einen Ort zum wohnen. Es ist ein Apartement in den Slums... Aber das ist immer noch besser, als der Keller in dem Haus voller Idioten."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "Заплатить со скидкой."
    new "Bezahle mit einem Rabatt."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "Заплатить $ 300"
    new "Zahle 300 $"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "У меня нет денег."
    new "Ich habe kein Geld."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:464
    old "Скидка 10 процентов."
    new "10 %% Rabatt."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:464
    old "Скидка 20 процентов."
    new "20 %% Rabatt."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:484
    old "Ни за что!!!"
    new "Niemals!!!"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:728
    old "Вернуться в квартиру позже."
    new "Gehe später zurück zum Apartement."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:764
    old "Поговорить с Джеком и снова заселиться в квартиру."
    new "Rede mit Jack und schaue später wieder in das Apartement."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:770
    old "Спросить про квартиру..."
    new "Frage wegen dem Apartement..."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:782
    old "Заплатить $ 300."
    new "Zahle 300 $."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:782
    old "Нет! Я не готова платить такую сумму!"
    new "Nein! Ich bin nicht bereit, so viel zu zahlen!"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:819
    old "Оплата за апартаменты в трущобах."
    new "Miete für die Apartements in den Slums."

