# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:7
translate german ep211_dialogues4_julia_1_2f3feef2:

    # mt "Пора уже заканчивать эту комедию с нежностями."
    # mt "Мне надоело строить из себя какую-то влюбленную дурочку."
    # mt "..."
    # mt "Мне нужно попасть к Юлии домой."
    # mt "Тогда я точно смогу залезть к ней под платье..."
    # mt "Или хотя бы посмотреть, какого цвета белье лежит у нее в шкафчиках."
    # mt "А вдруг она меня тогда обманула и она вообще не носит трусики?"
    # mt "Это бы объяснило то, что она так упорно отказывается дать заглянуть себе под юбку..."
    # mt "Нужно будет это выяснить."
    # mt "..."
    # mt "И как мне попасть к ней домой?"
    # mt "???"
    # mt "Хм... Придется пригласить ее на свидание еще раз..."
    # mt "И напроситься к ней в гости."
    # mt "Да, точно."
    # mt "Она уже доверяет мне намного больше, чем раньше."
    # mt "Думаю, в этот раз она мне не откажет."
    # m "Милая, я хотела бы провести с тобой вечер..."
    # m "Сменить обстановку..."
    # m "Мы с тобой видимся только на работе."
    # m "Что скажешь?"
    # julia "Миссис Бакфетт..."
    # julia "Вы... Вы приглашаете меня на свидание?!"
    # m "Да, милая. Я хочу пригласить тебя на ужин."
    # julia "О, Миссис Бакфетт, это замечательная идея!"
    # julia "Я с радостью проведу с Вами вечер!"
    # julia "А когда?"
    # m "Сегодня вечером, после работы."
    # m "В том же кафе рядом с твоим домом."
    # julia "Хорошо, Миссис Бакфетт. С нетерпением буду ждать вечера!"
    mt "Zeit, dieses Theater zu beenden."
    mt "Ich bin das langsam leid."
    mt "..."
    mt "Ich muss zu Julias Wohnung."
    mt "Dann kann ich bestimmt unter ihr Kleid schauen."
    mt "Oder zumindest einen Blick in ihren Wäscheschrank erhaschen."
    mt "Aber was, wenn sie gar keine trägt?"
    mt "Das würde erklären, warum sie sich so vehement wehrt..."
    mt "Ich muss es rausfinden."
    mt "..."
    mt "Aber wie komme ich in ihre Wohnung?"
    mt "???"
    mt "Hmm... Ich muss sie nochmal ausführen..."
    mt "Und sie um einen Besuch bitten."
    mt "Ja, so mache ich's."
    mt "Sie vertraut mir schon viel mehr."
    mt "Ich denke, dieses Mal wird sie mich nicht zurück weisen."
    m "Süße, ich würde gerne den Abend mit dir verbringen..."
    m "Mal rauskommen..."
    m "Wir sehen uns nur in der Arbeit."
    m "Was meinst du?"
    julia "Frau Buckfett..."
    julia "Du... willst mich auf ein Date einladen?!"
    m "Ja, Schätzchen. Ich möchte dich gerne zum Abendessen einladen."
    julia "Oh, Frau Buckfett, das ist eine tolle Idee."
    julia "Ich würde mich sehr freuen!"
    julia "Wann?"
    m "Heute, nach der Arbeit."
    m "Im Cafe neben deiner Wohnung."
    julia "Ok, Frau Buckfett. Ich freue mich auf heute Abend."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:50
translate german ep211_dialogues4_julia_2_34703247:

    # julia "Миссис Бакфетт! Я так рада нашей встрече!"
    # m "Привет, милая..."
    julia "Frau Buckfett! Schön, dich zu sehen!"
    m "Hallo Hübsche..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:57
translate german ep211_dialogues4_julia_2_0077a8a0:

    # mt "Нет, я не хочу этого делать!" 
    # mt "Не хочу и не буду!"
    # mt "Мне надоели эти глупости!"
    # mt "!!!"
    mt "Nein, das will ich bestimmt nicht!" 
    mt "Das will ich nicht, und das werde ich auch nicht tun!"
    mt "Das langweilt mich so!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:63
translate german ep211_dialogues4_julia_2_35713388:

    # cafe_barista "Добрый вечер. Пожалуйста наше меню."
    # julia "О, я так давно не ела чизкейк!"
    # m "Милая..."
    # m "Думаю, что тебе не нужно заказывать чизкейк."
    # julia "???"
    # m "..."
    # m "Это вредно для фигуры..."
    # julia "Тогда, может быть..."
    # julia "..."
    # mt "Долбанная официанта!"
    # mt "Зачем она притащила меню?!"
    # cafe_barista "Мэм, а Вы что желаете?"
    # m "Я ничего не буду!"
    # m "Я как раз недавно плотно поела и, боюсь, еще один прием пищи может сказаться на моей фигуре."
    # mt "Не хватало еще тратить здесь свои деньги!"
    # mt "Откуда вообще взялись такие цены в этой дыре?!"
    # julia "Я выбрала!"
    # julia "Мне, пожалуйста, этот салат. Греческий."
    # mt "Никчемная Юлия!"
    # mt "Можно было выбрать что-то и подешевле!"
    # julia "И еще латте, пожалуйста."
    # mt "!!!"
    # julia "Миссис Бакфетт, Вы точно ничего не хотите?"
    # m "Нет, милая. Я не голодна..."
    # cafe_barista "Может, воды?"
    # m "НЕТ!" 
    # cafe_barista "Хорошо. Скоро принесу Ваш заказ."
    # mt "Мне снова придется платить за ужин!"
    # mt "А самой сидеть и смотреть, как ест эта никчемная Юлия!"
    # mt "!!!"
    # julia "Миссис Бакфетт, Вы сегодня так хорошо выглядите..."
    # m "Спасибо... Милая..."
    # m "Ты тоже."
    # m "..."
    # mt "Мне даже не о чем с ней поговорить..."
    # mt "И неудивительно! О чем может разговаривать с какой-то служанкой такая леди как Я?!"
    # m "..."
    cafe_barista "Guten Abend. Bitten werfen Sie einen Blick in die Karte."
    julia "Oh, ich hatte schon so lange keinen Käsekuchen mehr!"
    m "Süß..."
    m "Ich denke, du brauchst keinen Käsekuchen."
    julia "???"
    m "..."
    m "Der ist schlecht für die Figur..."
    julia "Dann vielleicht..."
    julia "..."
    mt "Verdammte Bedienung!"
    mt "Warum hat sie die Karte gebracht?!"
    cafe_barista "Was wünschen Sie?"
    m "Nichts."
    m "Ich habe erst kürzlich gegessen und noch mehr würde meiner Figur schaden."
    mt "Ich will mein Geld hier nicht verschwenden!"
    mt "Wieso sind die Sachen in diesem Loch so teuer?!"
    julia "Ich weiß es!"
    julia "Ich hätte gerne den griechischen Salat, bitte."
    mt "Nutzlose Julia!"
    mt "Du hättest auch was günstigeres aussuchen können!"
    julia "И еще латте, пожалуйста."
    mt "!!!"
    julia "Frau Buckfett, willst du wirklich nichts?"
    m "Nein, Süße, Ich habe keinen Hunger..."
    cafe_barista "Vielleicht ein Wasser?"
    m "NEIN!" 
    cafe_barista "Gut. Ich bringe Ihre Bestellung bald."
    mt "Schon wieder muss ich für das Abendessen zahlen!"
    mt "Und neben der wertlosen Julia sitzen und ihr beim Essen zuschauen!"
    mt "!!!"
    julia "Frau Buckfett, du siehst heute so gut aus!"
    m "Danke... Schätzchen..."
    m "Du auch."
    m "..."
    mt "Ich weiß nicht mal, über was ich mit ihr reden soll..."
    mt "Kein Wunder. Was soll eine Lady wie ich mit einer Magd sprechen?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:115
translate german ep211_dialogues4_julia_2_4ec02e1e:

    # m "Юлия, милая, расскажи о себе..."
    # m "Я тут поняла, что совсем ничего о тебе не знаю..."
    # cafe_barista "Ваш заказ, пожалуйста."
    # julia "Спасибо."
    # julia "Мне приятно, что Вас это интересует, Миссис Бакфетт..."
    # m "..."
    # julia "Я родилась и выросла в другой стране."
    # julia "..."
    # julia "У моей семьи нет большого достатка."
    # julia "Родители живут от зарплаты до зарплаты."
    # julia "..."
    # julia "Я очень скучаю по своей родине, но..."
    # julia "Я не хочу возвращаться туда."
    # m "Почему?"
    # julia "У меня есть богатый и влиятельный родственник. Мой дядя."
    # julia "Он пытается влиять на нашу семью и мне это совсем не нравится."
    # julia "У меня с ним очень плохие отношения."
    # julia "В моей семье меня никто не понимал и не поддерживал."
    # julia "Поэтому я уехала и живу независимо от них."
    # julia "Должно произойти нечто экстраординарное, чтобы я вернулась к ним..."
    # julia "..."
    # mt "Странно... Дома у нее богатый родственник."
    # mt "Могла бы наладить с ним отношения и не знать никакой нужды."
    # mt "А она здесь работает за копейки."
    # mt "Никогда не понимала логику неудачников..."
    # m "..."
    # m "Сейчас ты живешь здесь, в трущобах?"
    # julia "Да, Миссис Бакфетт."
    # julia "Я арендую тут квартиру."
    # mt "Хммм.."
    # mt "Арендовать квартиру в трущобах - это, наверное, недорого?"
    # mt "..."
    # mt "Но жить в трущобах!!! Фи!"
    # mt "..."
    # mt "С другой стороны..."
    # mt "Не будет деревенщины Бетти и озабоченного сопляка Барди..."
    # mt "Сколько уже можно работать на эту семейку идиотов?!"
    # mt "Да еще и без оплаты!"
    # mt "Я смогу забыть эту семейку, как страшный сон."
    # mt "Начать жить независимо ни от кого."
    # mt "Почему бы мне не попробовать?"
    # mt "..."
    # mt "Только у кого мне узнать про аренду квартиры?"
    # mt "Мне нужно будет подумать об этом..."
    # cafe_barista "Мэм, с вас $ 20."
    # julia "Миссис Бакфетт, спасибо за ужин."
    # julia "Я... Я хотела бы... в знак благодарности за вечер..."
    # julia "Пригласить Вас к себе домой."
    # mt "!!!"
    # mt "Отлично!"
    # julia "Только я стесняюсь, что такая леди как Вы..."
    # julia "Придет в такую конуру, в которой я живу..."
    # m "Да. Это, конечно, будет шокирующе для меня и непривычно..."
    # m "Но ради моих чувств к тебе, милая, я готова потерпеть этот дискомфорт."
    # mt "Я почти у цели!"
    # mt "Какой замечательный сегодня вечер!"
    # julia "Спасибо, Миссис Бакфетт. Вы так добры."
    # m "Ну что? Пойдем?"
    # julia "Да, Миссис Бакфетт."
    m "Julia, Schätzchen, erzähl mir was über dich..."
    m "Ich merke, ich weiß überhaupt nichts über sie..."
    cafe_barista "Ihre Bestellung, bitte."
    julia "Danke."
    julia "Es freut mich, dass du da bist, Frau Buckfett."
    m "..."
    julia "Ich wurde in einem anderen Land geboren und bin da aufgewachsen."
    julia "..."
    julia "Meine Familie war nicht sehr reich."
    julia "Meine Eltern lebten von Lohnscheck zu Lohnscheck."
    julia "..."
    julia "Ich vermisse meine Heimat, aber..."
    julia "Ich will nicht zurück."
    m "Warum?"
    julia "Ich habe einen reichen und einflussreichen Verwandten, mein Onkel."
    julia "Er versucht meine Familie zu beeinflussen und das gefällt mir nicht."
    julia "Ich habe eine sehr schlechte Beziehung mit ihm."
    julia "Niemand in meiner Familie unterstützt mich."
    julia "Deswegen bin ich gegangen."
    julia "Es müsste schon etwas besonderes passieren, dass ich zurück gehe..."
    julia "..."
    mt "Seltsam... Sie hat einen reichen Verwandten zu Hause."
    mt "Sie hätte mit ihm ein gutes Verhältnis haben können."
    mt "Und jezzt arbeitet sie hier für Cents."
    mt "Ich werde die Logik dieser Loser nie verstehen..."
    m "..."
    m "Lebst du nun in den Slums?"
    julia "Ja, Frau Buckfett."
    julia "Ich miete eine Wohnung hier."
    mt "Hmmm..."
    mt "Ein Apartement in den Slums ist wahrscheinlich billig."
    mt "..."
    mt "Aber dann lebt man in den Slums!!!"
    mt "..."
    mt "Andererseits..."
    mt "Andererseits gibt es hier keinen Bardie und keine Betty."
    mt "Wie lange willst du noch für diese Idiotenfamilie arbeiten?!"
    mt "Und das ohne Bezahlung!"
    mt "Ich könnte diese Familie wie einen Alptraum vergessen."
    mt "Ich kann unabhängig leben."
    mt "Warum versuche ich es nicht mal?"
    mt "..."
    mt "Aber wer könnte mir ein Apartement vermieten?"
    mt "Ich muss darüber nachdenken..."
    cafe_barista "Das macht 20$."
    julia "Danke für das Dinner."
    julia "Ich... ich würde gerne... als Anerkennung des Abends..."
    julia "Dich zu mir nach Hause einladen."
    mt "!!!"
    mt "Ausgezeichnet!"
    julia "Ich schäme mich nur, dass eine Lady wie du..."
    julia "In so eine Bude kommt, in der ich lebe..."
    m "Ja. Natürlich wird mich das irritieren und unüblich sein..."
    m "Aber wegen meiner Gefühle für dich, Schätzchen, will ich das ertragen."
    mt "Bald hab ich's!"
    mt "Was für ein schöner Abend!"
    julia "Danke, Frau Buckfett. Du bist so nett."
    m "Und? Gehen wird?"
    julia "Ja, Frau Buckfett."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:189
translate german ep211_dialogues4_julia_3_28da916e:

    # mt "О Боже! Какой кошмарный дом!"
    # mt "Как здесь можно жить?!"
    # mt "Уверена, тут живут одни неудачники и... извращенцы!"
    # mt "И тут небезопасно вечером..."
    # mt "Нет. Вряд ли я смогу жить в таких условиях."
    # mt "Такая леди, как я, никогда не сможет привыкнуть к подобному."
    # mt "..."
    # mt "Хотя... Для меня и это место сейчас бы подошло..."
    mt "Oh mein Gott! Was für ein Alptraum!"
    mt "Wie kann man hier leben?"
    mt "Ich bin sicher, dass hier nur Loser leben... und Perverse!"
    mt "Und hier ist es auch Abends nicht sicher..."
    mt "Nein. Unwahrscheinlich, dass ich unter solchen Bedingungen leben könnte."
    mt "Eine Lady wie ich könnte sich niemals daran gewöhnen."
    mt "..."
    mt "Obwohl... Der Platz wäre auch gut für mich..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:202
translate german ep211_dialogues4_julia_4_58570ed2:

    # mt "Хммм... Я думала, будет намного хуже."
    # mt "Нет, здесь все, конечно, ужасно, но..."
    # mt "В моей ситуации это могло бы стать неплохим вариантом на время."
    # mt "Пожалуй, стоит обдумать вопрос аренды квартиры."
    # mt "Наверняка жилье здесь почти ничего не стоит..."
    # mt "И я смогу договориться с кем-нибудь о том, чтобы снимать его без лишних документов..."
    # mt "И потом... Все равно никто не узнает, что я живу в трущобах."
    # mt "Это ведь ненадолго."
    # julia "..."
    # m "Юлия, милая, ты напрасно переживала."
    # m "У тебя очень уютно."
    # julia "Правда?"
    # m "Да, милая..."
    # m "..."
    mt "Hmmm... Ich dachte, es wäre viel schlimmer."
    mt "Nein, alles ist da, zwar in schlechtem Zustand, aber da..."
    mt "Und in meiner Situation, könnte das zeitweise eine gute Option sein."
    mt "Vielleicht sollte ich das mal bedenken."
    mt "Sicherlich kostet das Wohnen hier quasi nichts."
    mt "Und ich kann mit dem Vermieter hier sicher eine Lösung wegen der fehlenden Dokumente finden..."
    mt "Und dann... wird niemand wissen, dass ich in den Slums lebe."
    mt "Es wird ja nicht lange sein."
    julia "..."
    m "Julia, Schätzchen."
    m "Schön hast du es hier."
    julia "Wirklich?"
    m "Ja wirklich..."
    m "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:222
translate german ep211_dialogues4_julia_4_283b99cb:

    # mt "Нет, я не буду этого делать!" 
    # mt "Мне надоело заниматься этими глупостями!"
    # mt "!!!"
    # m "Знаешь, Юлия, у меня сегодня еще много дел."
    # m "Так что, я пойду."
    # julia "Но... Миссис Бакфетт!"
    # julia "Это из-за того, что я..."
    # julia "Постоянно Вам отказываю?"
    # m "Это уже не имеет значения!"
    # m "Забудь все, что было!"
    # m "Увидимся на работе."
    # julia "..."
    mt "Nein, das mache ich nicht!" 
    mt "Das langweilt mich so!"
    mt "!!!"
    m "Weißt du, Julia, ich muss heute noch viel erledigen."
    m "Also, gehe ich jetzt."
    julia "Aber... Frau Buckfett!"
    julia "Ist es, weil ich..."
    julia "Dich dauernd ablehne?"
    m "Das hat damit nichts zu tun!"
    m "Vergiss alles, was war."
    m "Wir sehen uns nur in der Arbeit."
    julia "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:236
translate german ep211_dialogues4_julia_4_409e9ae0:

    # mt "Вот он момент!"
    # julia "!!!"
    # julia "Миссис Бакфетт, я... Я еще не готова..."
    mt "Nun kommt der Moment!"
    julia "!!!"
    julia "Frau Buckfett... Ich, ich bin noch nicht bereit. ..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:245
translate german ep211_dialogues4_julia_4_e66e4b42:

    # m "Милая, я тебя просто потрогаю и не более того."
    # m "У тебя ведь есть там трусики, правда?"
    # julia "Да, Миссис Бакфетт... Они есть..."
    # m "Можно я проверю это? Я только проведу там рукой, я не буду подглядывать..."
    # julia "Ну... Если только потрогать... Только совсем немного..."
    # mt "Ага! Она все-таки носит трусики!"
    # mt "Я почти у цели!"
    # mt "Осталось уговорить ее приподнять платье..."
    # julia "Миссис Бакфетт... На сегодня этого будет достаточно..."
    # mt "Твою мать!!!"
    # mt "!!!"
    # mt "!!!!!!"
    m "Schätzchen, ich berühre dich ja nur, mehr nicht."
    m "Da ist dein Höschen, stimmts?"
    julia "Ja, Frau Buckfett... sind sie..."
    m "Darf ich mal schauen? Ich fühle auch nur und schaue nicht..."
    julia "Gut... Wenn es nur ums berühren geht... Ein wenig vielleicht..."
    mt "Yeah! Sie hat noch ein Höschen an!"
    mt "Bald hab ich's!"
    mt "Ich muss sie nur noch überreden, das Kleid hoch zu heben..."
    julia "Frau Buckfett... Das reicht für heute..."
    mt "Fuck!!!"
    mt "!!!"
    mt "!!!!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:266
translate german ep211_dialogues4_julia_4_075ce702:

    # mt "Мне надоело заниматься этими глупостями!" 
    # mt "!!!"
    # m "Знаешь, Юлия, у меня сегодня еще много дел."
    # m "Так что, я пойду."
    # julia "Но... Миссис Бакфетт!"
    # julia "Это из-за того, что я Вам отказала?"
    # m "Это уже не имеет значения!"
    # m "Забудь все, что было!"
    # m "Увидимся на работе."
    # julia "..."
    mt "Das langweilt mich so!" 
    mt "!!!"
    m "Weißt du, Julia, ich muss heute noch viel erledigen."
    m "Also, gehe ich jetzt."
    julia "Aber... Frau Buckfett!"
    julia "Ist es, weil ich dich zurück gewiesen habe?"
    m "Das hat damit nichts zu tun!"
    m "Vergiss alles, was war."
    m "Wir sehen uns nur in der Arbeit."
    julia "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:278
translate german ep211_dialogues4_julia_4_f66090be:

    # mt "Так, Моника, спокойно."
    # mt "У тебя есть еще один вариант..."
    # m "Юлия, милая. Мне нужно в туалет. Подскажи, где он?"
    # julia "Конечно, Миссис Бакфетт. Вон та дверь, справа."
    mt "Okay, Monica. Beruhig dich."
    mt "Gibt's noch eine andere Option...?"
    m "Julia, Schätzchen. Ich muss schnell auf die Toilette. Wo ist sie?"
    julia "Natürlich, Frau Buckfett. Erste Tür rechts."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:287
translate german ep211_dialogues4_julia_5_1f927c50:

    # julia "Дверь в туалет справа от входной двери, Миссис Бакфетт."
    julia "Die erste Türe auf der rechten Seite, Frau Buckfett."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:293
translate german ep211_dialogues4_julia_6_91374fb0:

    # mt "Стиральная машинка... Корзина для белья... Шкафчики..."
    # mt "Наверняка, здесь что-то есть из ее белья!"
    # mt "Дьявол!"
    # mt "Почему здесь ничего нет?!"
    # mt "Где все белье?!"
    # mt "У нее что, только одни трусики, которые сейчас на ней?!"
    # mt "Какого только хлама нет, но только не трусиков!!!"
    # mt "Какого черта?!"
    # mt "!!!"
    # mt "Никчемная Юлия!!!"
    # mt "Бесит!!!"
    mt "Waschmaschine... Wäschekorb... Fächer..."
    mt "Hier muss doch Unterwäsche sein!"
    mt "Diese Teufelin!"
    mt "Warum ist hier nichts?!"
    mt "Wo ist die ganze Wäsche?!"
    mt "Hat sie nur ein Höschen, welches sie trägt?!"
    mt "Was für ein Dreck, nicht ein Paar Höschen!!!"
    mt "Was zur Hölle?"
    mt "!!!"
    mt "Nutzlose Julia!!!"
    mt "Das macht mich sauer!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:311
translate german ep211_dialogues4_julia_7_7871bfb2:

    # m "Милая, мне очень нравится твоя квартира."
    # m "Она небольшая, но уютная."
    # m "Я с удовольствием приду к тебе в гости еще раз..."
    # julia "Я буду очень рада, Миссис Бакфетт!"
    m "Schätzchen, ich mag dein Apartement total gerne."
    m "Klein, aber gemütlich."
    m "Ich freue mich, dich wieder zu besuchen..."
    julia "Das würde mich auch sehr freuen, Frau Buckfett!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:320
translate german ep211_dialogues4_julia_7_0077a8a0:

    # mt "Нет, я не хочу этого делать!" 
    # mt "Не хочу и не буду!"
    # mt "Мне надоели эти глупости!"
    # mt "!!!"
    mt "Nein, das will ich bestimmt nicht!" 
    mt "Das will ich nicht, und das werde ich auch nicht tun!"
    mt "Das langweilt mich so!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:325
translate german ep211_dialogues4_julia_7_eeec6f75:

    # m "Мне так не хочется уходить от тебя..."
    # m "Но у меня сегодня еще дела."
    # m "Скоро увидимя, милая."
    # julia "До свидания, Миссис Бакфетт."
    # julia "Буду очень скучать и ждать встречи с Вами."
    m "Ich möchte so nicht gehen..."
    m "Aber ich muss noch Dinge erledigen."
    m "Bis bald, Schätzchen."
    julia "Auf Wiedersehen, Frau Buckfett."
    julia "Ich freue mich schon darauf."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:334
translate german ep211_dialogues4_julia_8_dbd1814a:

    # mt "Снова ничего не получилось!!!"
    # mt "!!!"
    # mt "Сколько можно?!"
    # mt "?!?!?!"
    mt "Es hat wieder nicht geklappt!!!"
    mt "!!!"
    mt "Was soll ich noch alles machen?!"
    mt "?!?!?!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:342
translate german ep211_dialogues4_julia_9_023bd8b5:

    # mt "Все!"
    # mt "С меня хватит!"
    # mt "Пошло оно все к черту!"
    # mt "!!!"
    mt "Das war's."
    mt "Das reicht!"
    mt "Verdammt!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:350
translate german ep211_dialogues4_julia_10_54d68fff:

    # mt "Тут небезопасно вечером..."
    # mt "Наверняка, здесь полно извращенцев!"
    # mt "Нужно скорее уходить отсюда!"
    # mt "!!!"
    mt "Abends ist es hier nicht sicher..."
    mt "Hier sind bestimmt ein Haufen Perverse!"
    mt "Ich muss hier schnell weg!"
    mt "!!!"

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:40
    old "После работы пойти на свидание с Юлией в кафе."
    new "Gehe mit Julia zu einem Date in einem Cafe nach der Arbeit."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:112
    old "Попросить Юлию рассказать о себе."
    new "Frage Julia über sie selbst."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:217
    old "Попытаться задрать платье Юлии."
    new "Versuche, Julias Kleid hoch zu ziehen."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:242
    old "Я просто потрогаю..."
    new "Ich berühre es ja nur..."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:262
    old "Поискать трусики в ванной комнате."
    new "Suche nach Höschen im Badezimmer."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:262
    old "Уйти отсюда! (завершение сюжета с Юлией)"
    new "Verschwinde von hier! (Schließe den Plot mit Julia ab)"

