# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_escort_scene2.rpy:10
translate german ep211_escort_scene2_1_61f7f42d:

    # waitress "Здравствуйте, Мэм! Администратор Вас ждет на ресепшене."
    waitress "Hallo. Der Boss wartet schon auf dich."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:15
translate german ep211_escort_scene2_1_bc3b4878:

    # waitress "Вы? Вы здесь работаете?!" 
    # waitress "Я, даже не думала, что..."
    # m "Я..."
    # m "Я здесь не работаю... Я жду, когда мне принесут еду."
    # waitress "Мэм, но Вы же ничего не заказывали..."
    # mt "Вот черт!"
    # m "Да?"
    # m "..."
    # m "А, ну конечно. Не заказывала..." 
    # m "Я... Жду здесь человека."
    # m "..."
    # m "Кто там меня звал? Администратор?"
    # waitress "Да, Мэм."
    # m "Я сейчас подойду к ней."
    waitress "Du? Du arbeitest hier?!" 
    waitress "Das hätte ich nicht gedacht..."
    m "Ich..."
    m "Ich arbeite hier nicht... Ich warte auf Essen, was mit gebracht wird."
    waitress "Aber du hast doch gar nichts bestellt..."
    mt "Verdammt!"
    m "Ja?"
    m "..."
    m "Ah, natürlich. Das habe ich nicht..." 
    m "Ich... ich warte hier auf einen Mann."
    m "..."
    m "Der mich hier her bestellt hat."
    waitress "Ja."
    m "Ich bin schon früher gekommen."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:35
translate german ep211_escort_scene2_1_d93ce6c5:

    # waitress "Вы?!" 
    # m "Да, это Я!"
    # m "Удивительно, что ты все еще работаешь здесь!"
    # waitress "Мэм..."
    # waitress "А для меня удивительно, что Вы работаете здесь..."
    # m "!!!"
    # m "С чего ты взяла, что я здесь работаю?!" 
    # m "По-твоему, я похожа на работника ресторана?!"
    # waitress "Мэм... Вас администратор попросила позвать к себе..." 
    # waitress "Она сказала, что Вы одна из..."
    # m "Это неважно, что она сказала!"
    # m "Я не собираюсь выслушивать от тебя всякие глупости!"
    # m "Никчемная официантка!"
    waitress "Du?!" 
    m "Ja, ICH!"
    m "Überraschend, dass du immer noch hier arbeitest."
    waitress "Ehm..."
    waitress "Ich finde es toll, dass du hier arbeitest..."
    m "!!!"
    m "Wieso denkst du das?!" 
    m "Denkst du, ich sehe aus, wie ein Hotelmitarbeiterin?!"
    waitress "Ehm... Der Chef sagte, ich soll dich holen..." 
    waitress "Sie sagte, du bist eine der..."
    m "Es ist egal, was sie gesagt hat!"
    m "Ich höre mir nicht jeden Schwachsinn von dir an!"
    m "Nutzlose Bedienung!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:56
translate german ep211_escort_scene2_2_b8283038:

    # mt "Странно, что ее здесь нет."
    # mt "Возможно, она в служебном коридоре?"
    mt "Komisch, dass sie nicht da ist."
    mt "Vielleicht ist sie im Servicekorridor?"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:64
translate german ep211_escort_scene2_3_58eeafef:

    # client "Да, вот эта девушка. Я хочу ее."
    # reception "Это [monica_hotel_name]. Вы уверены?"
    # reception "У нас есть другие девушки для такого заказа."
    # client "Меня интересует именно эта."
    # client "Она больше подойдет для меня, чем остальные девушки."
    # reception "У тебя сегодня выезд к клиенту."
    # reception "Ты должна будешь сопровождать этого джентельмена на встрече."
    # reception "И вести себя, как его девушка."
    # reception "..."
    # reception "Правда, мне не понятно, почему клиент выбрал именно тебя..."
    # client "Не просто вести себя как моя девушка!"
    # client "Нужно сделать так, чтобы никто не догадался, что я плачу за это."
    # client "Это очень важно!"
    # reception "Будьте спокойны. Наши девушки - профессионалы."
    # reception "Если что-то будет не так..."
    # reception "То Вам будет компенсирована сумма вдвое больше той..."
    # reception "Которую Вы заплатите за заказ."
    # client "Очень надеюсь на это."
    # client "Для меня это принципиально важный момент."
    # m "Что мне нужно будет делать?"
    # client "Вам надо будет быть моей девушкой. Луизой."
    # m "Почему Луизой?"
    # reception "Помолчи!"
    # reception "Это желание клиента и у тебя нет права обсуждать его!"
    # mt "Никчемная администраторша!"
    # reception "Вы уверены, что Вам нужен только эскорт?"
    # reception "Не хотите ли воспользоваться опцией секса с этой девушкой?"
    # reception "Согласно нашего прейскуранта?"
    # client "Нет. Для меня важно, чтобы она вела себя как моя девушка."
    # client "Больше меня никакие услуги не интересуют."
    # client "Очень важно, чтобы она была похожа на мою девушку!"
    # reception "Вы можете воспользоваться любой услугой из прейскуранта..."
    # reception "Если передумаете."
    # reception "В наших интересах оказать как можно больше услуг для того..."
    # reception "Чтобы наш клиент остался максимально доволен."
    # mt "Она прямо навязывает ему услуги из прейскуранта."
    # mt "Ее, видимо, не устраивает, что мне попался нормальный клиент."
    # mt "А не какой-нибудь извращенец."
    # mt "Эти сучки теперь будут мне завидывать."
    # reception "Ну что, ты все поняла?"
    # reception "Будешь осуществлять эскорт, играя роль его девушки."
    # reception "Если будешь делать это плохо, то будешь оштрафована!"
    # reception "Тебе понятно, [monica_hotel_name]?!"
    # m "Да, мне все понятно."
    # reception "Иди переодевайся."
    # reception "Для этого заказа тебе надо кое-что поприличнее."
    client "Ja, dieses Mädchen. Die will ich."
    reception "Das ist [monica_hotel_name]. Bist du sicher??"
    reception "Dafür haben wir andere Mädchen."
    client "Diese interessiert mich aber."
    client "Sie gefält mir besser, als die Anderen."
    reception "Heute musst du dich mit einem Kunden treffen."
    reception "Du musst diesen Gentleman bei einem Meeting begleiten."
    reception "Und so tun, als wärst du seine Freundin."
    reception "..."
    reception "Um ehrlich zu sein, ich weiß nicht, warum der Kunde dich wollte..."
    client "Benimm dich einfach wie meine Freundin!"
    client "Es ist wichtig, dass niemand bemerkt, dass ich dafür bezahle."
    client "Das ist sehr wichtig!"
    reception "Ruhig. Unsere Mädels sind Profis."
    reception "Wenn was schief geht..."
    reception "Bekommst du das doppelte Geld..."
    reception "Was du vorher bezahlt hast."
    client "Das hoffe ich."
    client "Das ist ein monumental wichtiger Punkt für mich."
    m "Was muss ich machen?"
    client "Du musst meine Freundin sein. Louise."
    m "Warum Louise?"
    reception "Halt die Klappe!"
    reception "Das ist der Wunsch des Kunden, mehr musst du nicht wissen!"
    mt "Nutzlose Frau!"
    reception "Bist du sicher, dass du nur eine Escort willst?"
    reception "Möchtest du die Sex-Option mit diesem Mädchen?"
    reception "Basierend auf unserer Preisliste?"
    client "Nein. Es ist für mich nur wichtig, dass sie sich wie meine Freudin benimmt."
    client "Ein weiterer Service interessiert mich nicht."
    client "Es ist wichtig, dass sie auch wie meine Freudin aussieht!"
    reception "Du kannst dir alles aus der Preisliste aussuchen..."
    reception "Wenn du deine Meinung änderst."
    reception "Es ist in unserem Interesse, dass so viele Optionen wir möglich angeboten werden..."
    reception "Damit der Kunde so zufrieden wie möglich ist."
    mt "Sie will ihm unbedingt weitere Dienstleistungen andrehen."
    mt "Ihr gefällt es wohl nicht, dass mich ein normaler Kunde will."
    mt "Nicht ein Perverser."
    mt "Diese Bitches beneiden mich nun bestimmt."
    reception "Hast du alles verstanden?"
    reception "Du hast einen Auftrag und benimmst dich wie seine Freundin."
    reception "Wenn du es nicht gut machst, wirst du bestraft!"
    reception "Verstanden, [monica_hotel_name]?!"
    m "Ja, alles klar."
    reception "Zieh dich um."
    reception "Du brauchst etwas braveres zum anziehen dafür."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:124
translate german ep211_escort_scene2_3a_ab9c57ca:

    # mt "Это его друг? Больше похож на его босса..."
    # client "Эй, Дэниел! Привет!"
    # daniel "Привет, Нэд! Как всегда, опаздываешь!"
    # ned "Да, мы с моей девушкой немного задержались..."
    # ned "Кстати, занокомься. Это Луиза."
    # ned "Луиза, это мой друг и коллега Дэниел."
    # ned "Сегодня он устраивает небольшую вечеринку для друзей."
    # daniel "Ну наконец-то Нэд познакомил меня со своей девушкой!"
    # daniel "Проходите в дом. Там вас двано уже все ждут."
    mt "Ist das sein Freund? Sieht eher wie sein Chef aus..."
    client "Hey Daniel. Hallo!"
    daniel "Hi Ned! Du bist spät dran, wie immer!"
    ned "Ja, meine Freundin hat sich etwas verspätet..."
    ned "Кстати, занокомься. Это Луиза."
    ned "Louise, das ist mein Freund und Kollege Daniel."
    ned "Er gibt heute eine kleine Party."
    daniel "Ну наконец-то Нэд познакомил меня со своей девушкой!"
    daniel "Проходите в дом. Там вас двано уже все ждут."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:140
translate german ep211_escort_scene2_4_d0fa3872:

    # ned "Эй, ребята, привет!"
    # ned "Хочу представить вам мою девушку. Ее зовут Луиза."
    # ned "Луиза, это мои коллеги и друзья."
    # ned "Дэниел и его жена Эмма."
    # ned "Марти и его жена Натали."
    # daniel "Привет, Луиза!"
    # emma "Приятно познакомиться!"
    # marty "Привет!"
    # natalie "Присаживайтесь к нам."
    # natalie "Наконец-то, Нэд познакомил нас со своей девушкой."
    # natalie "Я очень рада познакомиться, Луиза."
    # m "Мне тоже приятно познакомиться."
    # mt "Моника, тебе сегодня повезло с клиентом..."
    # mt "Вкусный ужин, светские разговоры в компании приличных людей..."
    # mt "И никаких извращенцев."
    # mt "Все, к чему ты так привыкла... И чего так не хватает теперь."
    # ned "Луиза, дорогая, хочешь вина?"
    # m "Пожалуй, я не откажусь."
    # daniel "Нэд, так вот почему ты стал опаздывать на работу!" 
    # daniel "Очевидно, что с такой прекрасной девушкой ты не спишь целыми ночами!"
    # daniel "Аха-ха!"
    # emma "Дэниел, оставь свои пошлые шуточки."
    # emma "Ты смущаешь ими Луизу!"
    # daniel "Да ладно тебе, детка."
    # emma "И перестань называть меня деткой. Ты же знаешь, мне это не нравится!"
    # daniel "Хорошо, любимая, как скажешь."
    # daniel "Эй, Марти! Ты когда-нибудь расстаешься с телефоном?"
    # daniel "Натали, он в постель его тоже берет? Аха-ха!"
    # natalie "Марти очень много работает."
    # natalie "Даже сейчас он просматривает документы по работе."
    # natalie "Совсем не отдыхает. Да, дорогой?"
    # marty "Угу..."
    # emma "Луиза, расскажи нам, чем ты занимаешься?"
    # emma "Нэд ничего нам не рассказывал про тебя..."
    # m "Я являюсь руководителем в одной крупной компании."
    # natalie "Ого!"
    # m "Да. Помимо основной деятельности, связанной с индустрией моды..."
    # m "У меня еще бизнес в сфере недвижимости."
    # emma "О, серьезно?!" 
    # m "Да, у меня в подчинении много сотрудников."
    # daniel "Твоя деятельность связана с модной индустрией?"
    # emma "Расскажи нам. Это очень интересно!" 
    # m "По работе мне часто приходится посещать публичные мероприятия..."
    # m "Выступать перед публикой, давать интервью."
    # m "И, конечно же, я всегда в курсе всех событий в мире моды."
    # ned "Да, Луиза очень занятая девушка." 
    # ned "Редко такое бывает, что мы можем провести вечер вместе..."
    # ned "Я вас давно хотел с ней познакомить, но у нее не бывает свободного времени."
    # ned "По вечерам она обычно ведет какие-нибудь переговоры..."
    # ned "И важные бизнес-встречи."
    # ned "Ведь такие встречи очень важны для развития ее бизнеса."
    # ned "Да, дорогая?"
    # m "Все верно."
    # m "У меня широкий круг знакомых, которые имеют немалый вес в этом городе..."
    # m "И даже в стране."
    # daniel "И как у тебя хватает времени на что-то, кроме работы?" 
    # mt "Никчемные людишки..."
    # mt "Млеют при виде меня и от мысли том, кто я такая!!!"
    # m "Да, это довольно непросто..."
    # m "Грамотное планирование своего рабочего времени..."
    # m "А также помощь моих личных ассистентов..."
    # m "Позволяют мне иногда провести вечер не на работе, а в свое удовольствие."
    # m "Нэд, налей мне еще вина!" 
    # m "..."
    # m "Пожалуйста, дорогой." 
    # ned "Конечно, любимая."
    # emma "Луиза, как тебе наш с Дэниелем дом?"
    # emma "Мы его так долго выбирали..."
    # emma "Это наш гостевой дом. Мы любим устраивать здесь вечеринки с друзьями."
    # emma "У нас есть даже рояль!"
    # natalie "Но, к сожалению, никто из нас не умеет играть на нем..."
    # emma "Да..."
    # m "Эмма, у вас чудесный дом. Он очень изысканный."
    # mt "Конечно, не такой изысканный как мой дом..."
    # m "А что касается игры на пианино..."
    # m "Я из высшего общества, как вы уже поняли..."
    # m "Соответственно, у меня очень хорошее образование и воспитание."
    # m "В высшем обществе считается дурным тоном для девушки..."
    # m "Неумение владеть каким-либо музыкальным инструментом."
    # m "И я когда-то посещала занятия в музыкальной школе."
    # emma "Правда?! Это замечательно, Луиза!"
    # natalie "Сыграй нам что-нибудь, пожалуйста!!!"
    # m "Легко! Для меня это не составит никакого труда!"
    # emma "Мальчики, Луиза сейчас будет играть на пианино!"
    # natalie "Нэд, почему ты раньше не познакомил нас с такой замечательной девушкой?!"
    # ned "..."
    # mt "Похоже, что эта работа не так уж и плоха..."
    # mt "Нет, конечно это отвратительно, но..."
    # mt "Учитывая другие варианты заработать деньги, эскорт не так уж плох..."
    # mt "Я думала, что работа в эскорте будет моим кошмаром."
    # mt "Однако, в большинстве своем, это вполне безобидное общение."
    # mt "Я, пожалуй, поработаю здесь, пока не решу все свои проблемы."
    # mt "В любом случае, никто меня здесь не знает..."
    # mt "Даже если будут вопросы, я скажу, что это мой двойник."
    # mt "Если будет нужно, я найду где-нибудь в стране девушку, похожую на меня..."
    # mt "И предъявлю тем, кто будет что-то подозревать."
    # mt "Конечно, она будет всего-лишь похожа на меня..."
    # mt "У нее, конечно, не может быть такой красоты, которой обладаю Я!"
    # mt "Но, все-же..."
    # ned "Если у нас получится заключить с ними контракт..."
    # ned "Наши продажи взлетят в несколько раз."
    # daniel "Нэд, я не стал бы делать такие оптимистичные прогнозы."
    # daniel "С ними не так просто договориться, уж поверь мне..."
    # daniel "Но если у тебя это получится сделать..."
    # daniel "Я поговорю с директором о твоем повышении."
    # m "Нэд, подай мне салфетку."
    # ned "..."
    # ned "Конечно, дорогая."
    # m "И налей мне еще вина."
    # ned "..."
    # natalie "Луиза, наши мужья всегда так себя ведут..."
    # natalie "Постоянно только и разговоров, что о работе."
    # emma "Это точно."
    # emma "Но мы с Натали уже привыкли."
    # emma "Так что и ты привыкнешь."
    # natalie "Луиза, а какие у вас с Нэдом планы?"
    # natalie "Вы уже живете вместе или просто встречаетесь?"
    # emma "А может, вы собираетесь пожениться?"
    # natalie "Это было бы чудесно! Вы такая красивая пара!"
    # emma "Нэд не делал тебе предложение?"
    # m "Нэд только и думает, что о работе."
    # m "Уверена, ему мысль о женитьбе даже в голову не приходила."
    # m "Но когда Нэд все-таки решится..."
    # m "Ему придется постараться, чтобы я рассмотрела его предложение..."
    # emma "Хи-хи-хи..."
    # natalie "Девочки, мне нужно выйти на улицу, во двор."
    # natalie "Дэниел не разрешает курить в доме."
    # natalie "Никто не хочет составить мне компанию?"
    # emma "Я с тобой, Натали."
    # emma "Луиза, пойдем с нами?"
    # m "Да, пойдем."
    # ned "Луиза, дорогая, останься со мной, пожалуйста."
    # ned "Мы с тобой немного позже прогуляемся."
    ned "Hey Leute!"
    ned "Ich will euch meine Freundin vorstellen. Das ist Lousie."
    ned "Louise, das sind meine Freunde und Kollegen."
    ned "Daniel und seine Frau Emma."
    ned "Marty und seine Frau Natalie."
    daniel "Привет, Луиза!"
    emma "Schön dich zu treffen!"
    marty "Hallo!"
    natalie "Nimm Platz."
    natalie "Endlich lerne ich mal Neds Freundin kennen."
    natalie "Freut mich sehr, Louise."
    m "Ebenso."
    mt "Monica, heute hast du Glück mit dem Kunden ..."
    mt "Ein leckeres Abendessen, Smalltalk in Gesellschaft von anständigen Menschen ..."
    mt "Und nichts perverses."
    mt "Alles, wasich gewöhnt bin... und mir zur Zeit so fehlt..."
    ned "Louise, Schätzchen, willst du Wein?"
    m "Ja, das wäre schön."
    daniel "Ned, deswegen kommst du also in letzter Zeit oft zu spät in die Arbeit?" 
    daniel "Offenbar schläft man nicht viel nachts bei so einer Schönheit!"
    daniel "Hahaha!"
    emma "Daniel, hör mit den anstössigen Witzen auf!"
    emma "Du beschä,st Louise!"
    daniel "Komm schon Baby."
    emma "Und nenn mich nicht Baby. Du weißt, ich mag das nicht!"
    daniel "Wie du meinst, Schatz."
    daniel "Hey Marty! Trennst du dich auch mal von deinem Handy?"
    daniel "Nimmt er das auch ins Bett, Natalie? Hahaha!"
    natalie "Marty arbeitet sehr viel."
    natalie "Selbst jetzt schaut er Dokumente an."
    natalie "Er bekommt nicht genug Freizeit. Stimmt doch, Schatz."
    marty "Yeah ..."
    emma "Louise, was machst du?"
    emma "Ned hat uns überhaupt nichts über dich erzählt..."
    m "Ich bin Chefin in einem großen Unternehmen."
    natalie "Wow!"
    m "Ja. Zustätzlich zu meinen Hauptaufgaben, die mit der Modeinsudtrie zu tun haben..."
    m "Ich habe auch ein Immobiliengeschäft."
    emma "Oh wirklich ?!" 
    m "Ja, ich habe viele Angestellte."
    daniel "Du hast was mit der Modeindustrie zu tun?"
    emma "Erzähö schon. Das ist super interessant!" 
    m "Ich muss beruflich oft an öffentlichen Veranstaltungen teilnehmen."
    m "Reden in der Öffentlichkeit halten und Interviews geben."
    m "Und natürlich bin ich über alle Ereignisse in der Modewelt auf dem Laufenden."
    ned "Ja, Louise ist eine sehr beschäftigte Frau." 
    ned "Es kommt selten vor, dass wir einen Abend zusammen verbringen können ..."
    ned "Ich wollte sie euch schon lange vorstellen. Leider hat sie nicht viel Zeit."
    ned "Abends leitet sie oft Verhandlungen..."
    ned "Und wichtige Mettings."
    ned "Schließlich sind solche Treffen sehr wichtig für die Entwicklung ihrer Firma."
    ned "Ja, Darling?"
    m "Genau."
    m "Ich habe einen großen Freundeskreis, der in dieser Stadt viel Einfluss hat ..."
    m "Und sogar im ganzen Land."
    daniel "Und wie hast du mal Zeit für was Anderes außer der Arbeit?" 
    mt "Wertlose kleine Kreaturen ..."
    mt "Sie sind meiner nicht würdig!"
    m "Ja, es ist ziemlich schwierig ..."
    m "Ein gutes Zeitmanagment ist wichtig..."
    m "Und natürlich die Hilfe meiner persönlichen Assistenten ..."
    m "Sie ermöglichen mir gelegtlich, dass ich mir den Abend frei nehmen kann."
    m "Ned, bitte schenk mir nich etwas Wein nach!" 
    m "..."
    m "Bitte Schatz." 
    ned "Gerne, meine Liebe."
    emma "Louise, wie gefällt dir unser Haus?"
    emma "Wir haben lange gebraucht, bis wir es gefunden haben..."
    emma "Das ist unser Gästehaus. Hier haben wir Parties mit Freunden."
    emma "Wir haben sogar ein Klavier!"
    natalie "Aber leider kann keiner von uns spielen..."
    emma "Ja."
    m "Emma, du hast ein wunderbares Haus. Sehr exklusiv."
    mt "Natürlich nicht so exklusiv wie mein Haus..."
    m "Was das Klavierspielen betrifft..."
    m "Ich bin aus der gehobenen Gesellschaft, wie ihr ja nun wisst..."
    m "Daher habe ich eine gute Erziehung genossen."
    m "In dieser Gesellschaft ist es schlecht für eine Frau..."
    m "Wenn sie kein instrument beherrscht."
    m "Daher hatte ich Musikstunden."
    emma "Wirklich? Das ist ja toll, Louise!"
    natalie "Spiel uns bitte was vor!!!"
    m "Klar! Das ist nicht schwer!"
    emma "Leute, Louise spielt auf dem Klavier!"
    natalie "Ned, warum hast du uns denn nicht schon viel früher vorgestellt?!"
    ned "..."
    mt "Es scheint so, dass diese Arbeit gar nicht so schlecht ist ..."
    mt "Nein, natürlich ist es widerlich, aber ..."
    mt "Angesichts anderer Möglichkeiten, Geld zu verdienen, ist Eskortservice gar nicht so schlecht..."
    mt "Ich dachte, die Arbeit als Escort wäre ein Alptraum."
    mt "Aber bisher war eigentlich alles nur harmloser Smalltalk."
    mt "Vielleicht sollte ich so weiter arbeiten, bis all meine Probleme gelöst sind."
    mt "Am Wichtigsten aber ist, niemand kennt mich hier..."
    mt "Selbst wenn Fragen aufkämen, behaupte ich einfach, die Andere sieht mir sehr ähnlich."
    mt "Wenn nötig, finde ich eine Frau irgendwo, die mir ähnlich sieht."
    mt "Ich zeige sie denen, die was vermuten."
    mt "Natürlich wird sie mir nur ähnlich sehen..."
    mt "Sie kann natürlich nicht so schön sein, wie ich es bin!"
    mt "Aber immerhin..."
    ned "Wenn wir es schaffen, mit denen einen Deal zu machen..."
    ned "Werden unsere Verkäufe explodieren."
    daniel "Ned, ist das nicht zu optimistisch?"
    daniel "Die sind nicht gerade einfach zu handhaben, glaub mir..."
    daniel "Aber wenn du es schaffst..."
    daniel "Rede ich mit dem Boss über deine Beförderung."
    m "Ned, bitte gib mir eine Serviette."
    ned "..."
    ned "Klar, Schatz."
    m "Bitte schenk mir noch mehr Wein ein."
    ned "..."
    natalie "Louise, unsere Ehemänner benehmen sich immer so..."
    natalie "Reden immer nur über die Arbeit."
    emma "Das stimmt."
    emma "Aber Natalie und ich sind das schon gewohnt."
    emma "Ich hoffe, du auch bald."
    natalie "Louise, was sind deine Pläne mit Ned?"
    natalie "Lebt ihr schon zusammen oder dated ihr gerade noch?"
    emma "Oder werdet ihr heiraten?"
    natalie "Das wäre fantastisch! Ihr seid so ein schönes Pärchen!"
    emma "Ned hat dir noch keinen Antrag gemacht?"
    m "Ned denkt immer nur an die Arbeit."
    m "Ich bin sicher, dass der Gedanke an eine Hochzeit noch nicht mal in seinem Kopf war."
    m "Aber wenn Ned eine Entscheidung treffen muss..."
    m "Muss er sich schon viel Mühe geben, dass ich seinen Antrag in Erwägung ziehen würde..."
    emma "Hehehe..."
    natalie "Mädels, ich muss mal in den Garten."
    natalie "Daniel erlaubt es nicht, im Haus zu rauchen."
    natalie "Möchte mich wer begleiten?"
    emma "Ich komme mit, Natalie."
    emma "Louise, du auch?"
    m "Klar."
    ned "Louise, Schatz, bleib bitte bei mir."
    ned "Wir beide gehen später spazieren."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:307
translate german ep211_escort_scene2_5_6beae6f8:

    # ned "Ну что, Дэниел! Я выиграл наше пари! Аха-ха!!!"
    # ned "Гони мне мои деньги! Я сделал это!"
    # ned "У меня получилось! Наконец-то!"
    # daniel "Что?!"
    # marty "???"
    # daniel "Ты про что?" 
    # daniel "Ты про... про... Она что, проститутка?!" 
    # ned "Да!" 
    # m "Ч-что?" 
    # m "???"
    # mt "Мне это послышалось?"
    # daniel "Не могу поверить! Нет!"
    # daniel "Сколько раз ты пытался нас провести..."
    # daniel "Я всегда чую проституток за версту!"
    # daniel "Но как?! Нет! Я не верю!"
    # m "..."
    # marty "Пусть она сама нам скажет!"
    # ned "Ну? Скажи им, кто ты?"
    # mt "!!!"
    # mt "Я не могу поверить!!!"
    # mt "Он это все... Подстроил из-за спора?!"
    # mt "?!?!?!"
    # m "Я... Я его девушка..."
    # daniel "Аха-ха!"
    # daniel "Ну что я говорил тебе! Я не могу ошибиться!"
    # daniel "Ты не смог провести меня в те разы, не сможешь и теперь!"
    # ned "Нет! Она проститутка! Ее зовут [monica_hotel_name]."
    # ned "Мы заключили пари..."
    # ned "Если я приведу проститутку и ты не сможешь ее определить, то пари мое!"
    # daniel "Скажи, кто ты?"
    # daniel "Ты ведь Луиза, правда?"
    # m "Да. Я Луиза."
    # m "Я девушка Нэда..."
    # ned "Ну хватит уже!"
    # ned "Говори им, кто ты! Твоя игра закончена, [monica_hotel_name]!"
    # m "..."
    # ned "Если ты не скажешь, то я сообщу администратору сервиса эскорта..."
    # ned "Что ты не выполняешь условия заказа!!!"
    # mt "!!!"
    # mt "Сволочь! Мерзавец!"
    ned "Ok Daniel! Ich habe unsere Wette gewonnen! Hahaha!"
    ned "Gib mir mein Geld!"
    ned "Ich hab' gewonnen!"
    daniel "Was?!"
    marty "???"
    daniel "Von was redest du?" 
    daniel "Sagst du, sie ist... ist... eine Prostituierte?!" 
    ned "Ja!" 
    m "WAS?" 
    m "???"
    mt "Habe ich mich verhört?"
    daniel "Nein! Das kann ich nicht glauben!!"
    daniel "Wie oft hast du schon versucht, uns zu verarschen?..."
    daniel "Ich merke es sofort, wenn Prostituierte in der Nähe sind!"
    daniel "Aber wie? Nein! Ich glaube es nicht!"
    m "..."
    marty "Sie soll es selbst sagen!"
    ned "Gut? Sag ihnen, wer du bist!"
    mt "!!!"
    mt "Ich kann es nicht glauben!!!"
    mt "Er hat das alles gemacht... wegen einer Wette?!"
    mt "?!?!?!"
    m "Ich...ich bin seine Freundin..."
    daniel "Hahaha!"
    daniel "Was habe ich gesagt? Ich irre mich nie!"
    daniel "Du wirst mich nie schlagen können, niemals!"
    ned "Nein! Sie ist eine Prostituierte. Ihr Name ist [monica_hotel_name]."
    ned "Wir haben gewettet..."
    ned "Wenn ich eine Escort mitbringe, und du checkst es nicht, gewinne ich!"
    daniel "Und, wie geht es dir?"
    daniel "Du bist Louise, oder?"
    m "Ja, ich bin Louise."
    m "Ich bin Ned's Freundin..."
    ned "Genug ist genug!"
    ned "Sag ihnen jetzt, wer du bist! Das Spiel ist vorbei, [monica_hotel_name]!"
    m "..."
    ned "Wenn du nicht ehrlich bist, informiere ich deinen Boss..."
    ned "Dass du nicht die Anforderungen erfüllt hast!!!"
    mt "!!!"
    mt "Dieser Bastard! Bastard!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:360
translate german ep211_escort_scene2_5_05939e32:

    # m "Я БЫЛА твоей девушкой!"
    # m "Но, после того как ты посмел устроить такое при своих друзьях!"
    # m "Я больше не хочу тебя видеть!"
    # ned "!!!"
    # daniel "Ну что, Нэд? Ты снова облажался!" 
    # marty "Аха-ха!!!"
    # ned "..." 
    # daniel "Я тебе говорил, что за версту вижу шлюх!"
    m "Ich WAR deine Freundin!"
    m "Aber nachdem du mich mit deinen Freunden verarscht hast..."
    m "Will ich dich nie wieder sehen!"
    ned "!!!"
    daniel "Also, Ned? Du hast wieder verloren!" 
    marty "Hahaha!"
    ned "..." 
    daniel "Ich sagte doch, ich erkenne Huren sofort!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:374
translate german ep211_escort_scene2_5_78f69e7f:

    # m "В условиях заказа было то, что я говорю, что я твоя девушка!"
    # m "А не доказываю обратное!!!"
    # m "Я соблюдаю условия!"
    # ned "Ага!"
    # ned "Она заговорила про условия!"
    # ned "Она призналась! Видишь, Дэниел?!"
    # daniel "Что?!"
    # daniel "Так ты действительно работаешь в эскорте?!"
    # m "Я... Я действительно здесь не совсем из чувственных побуждений..."
    # marty "А из каких?"
    # ned "Говори!"
    # m "..."
    # m "Из... Из несколько... Меркантильных..."
    # ned "Да она обычная проститутка из ВИП Эскорта!"
    # ned "Из отеля Ле Гранд! Я там нашел ее!"
    # mt "!!!"
    # marty "Я знаю всех, кто там работает..."
    # marty "Я не видел ее там!"
    # ned "Она там работает совсем недавно, потому я ее и заприметил."
    # ned "Я знал, что вы не могли ее там видеть."
    # ned "И она держится так статно, что сложно поверить в то..."
    # ned "Что она обычная проститутка."
    # mt "!!!"
    # mt "Мерзавец! Никчемный неудачник!"
    # mt "НЕНАВИЖУ!!!"
    # daniel "То есть... Погоди... Если она все же проститутка..."
    # daniel "То зачем ты притащил ее на эту встречу?!"
    # daniel "Ведь здесь же наши жены, Нэд!!!" 
    # daniel "Ты что, совсем сдурел?! Ты за кого нас держишь, а?!"
    # ned "Я знал, что ты не сможешь раскусить ее здесь, при Эмме. Аха-ха!"
    # ned "Если бы я привел ее в нашу сауну, как обычно приводил других..."
    # ned "То не смог бы выиграть наше пари!"
    # daniel "Ладно, твоя взяла."
    # daniel "Хотя..." 
    # daniel "Ты утверждаешь, что она проститутка..."
    # daniel "И, если она проститутка, то, получается, я могу ее трахнуть?"
    # ned "Конечно, можешь!"
    # m "ЧТО?!"
    # m "Нет!"
    # m "Мы так не договаривались!"
    # m "Ты меня нанял только сопровождать тебя!!!"
    # ned "Твоя администраторша навязывала мне ваш прейскурант."
    # ned "Она сказала, что я могу передумать в любой момент!"
    # m "Нет!"
    # m "!!!"
    # ned "Твое агентство гарантировало мне, что с тобой не будет проблем!"
    # ned "Мне позвонить твоему начальству?!"
    # mt "Сволочь!!!"
    # mt "Компания придурков!"
    # mt "Жалкие неудачники!"
    # mt "!!!"
    # daniel "Нэд, скажи, ты уже далал это?"
    # daniel "Пробовал ее? Ну и как она?"
    # ned "Если честно, то нет."
    # ned "Я договорился только сопровождать меня."
    # ned "Доплачивать за секс $ 500 - для меня дороговато."
    # ned "А вдруг бы ты раскусил ее? Тогда наше пари не покрыло бы мои расходы."
    # ned "Так что с нашим пари? Ты признаешь, что я выиграл?"
    # daniel "Да, черт возьми!"
    # daniel "И если ты ее еще не пробовал, то я буду первым!"
    # daniel "Я хочу трахнуть ее прямо сейчас!"
    # marty "А как же Эмма?"
    # marty "Она и Натали придут с минуты на минуту!"
    # daniel "К черту! Ребята, соврите что-нибудь!"
    # daniel "Скажите, что у меня важный звонок, а у Луизы..."
    # daniel "У Луизы закружилась голова и она ушла в уборную!"
    # daniel "И попросила ее не беспокоить!"
    # daniel "Как там тебя зовут?"
    # m "..."
    # ned "[monica_hotel_name]."
    # daniel "[monica_hotel_name], пойдем за мной!"
    # m "Но..."
    # m "Нет... Я не пойду... Я..."
    # ned "Все! Я звоню в ВИП Эскорт!"
    # ned "Скажу, что девушка отказывается работать по прейскуранту!"
    # mt "Черт! Что же мне делать?!"
    # mt "Я просто хотела заработать немного денег..."
    # mt "Я не предполагала, что это зайдет так далеко!"
    # mt "!!!"
    # ned "Добрый вечер. Да, я передумал..."
    # ned "Я хочу взять некоторые пункты из вашего прейскуранта."
    # reception "Да, сэр. Мы рады оказать Вам любые перечисленные в прейскуранте услуги!"
    # ned "Видите ли... Эта девушка... Она..." 
    # reception "Она что, отказывается что-то делать?!"
    # reception "Передайте ей, что она будет оштрафована или уволена!"
    # ned "Она..."
    # ned "Так ты согласна?"
    # m "!!!"
    m "Es war abgemacht, dass ich mich als deine Freundin ausgebe!"
    m "Auch wenn ich das Gegenteil nicht beweisen kann!!!"
    m "Stimme ich den Richtlinien zu!"
    ned "Ja!"
    ned "Sie redet von Richtlinien!"
    ned "Sie hat es zugegeben, siehst du, Daniel?!"
    daniel "Was?!"
    daniel "Also bist du wirklich eine Escort?!"
    m "Ich... ich bin aus einem gewissen Grund hier..."
    marty "Und welcher Grund wäre das?"
    ned "Sprich!"
    m "..."
    m "Wegen... wegen geschäftlicher Gründe..."
    ned "Ja, sie ist eine normale Prostituierte vom VIP Service!"
    ned "Aus dem La Grande Hotel! Da habe ich sie her!"
    mt "!!!"
    marty "Ich weiß, dass jeder, der da arbeitet..."
    marty "Ich habe sie noch nie gesehen!"
    ned "Sie hat da erst neulich angefangen, deswegen ist sie mir sofort in's Auge gestochen."
    ned "Ich wusste, dass du sie nicht kennen kannst."
    ned "Und sie wirkt so überzeugend, dass man kaum glauben kann, dass sie..."
    ned "Dass sie eine gewöhnliche Nutte ist."
    mt "!!!"
    mt "Bastard! Nutzloser Loser!"
    mt "ICH HASSE SIE!!!"
    daniel "Ich meine... Warte... Wenn sie eine Prostituierte ist..."
    daniel "Warum hast du sie dann heute mitgenommen?!"
    daniel "Unsere Frauen sind hier, Ned!!!" 
    daniel "Bist du total bescheuert?! Für wen hältst du uns, hä?!"
    ned "Ich wusste, dass du es noch schwerer hast, wenn Emma anwesend ist. Hahaha!"
    ned "Wenn ich sie in die Sauna mitgenommen hätte, so wie die Anderen..."
    ned "Hätte ich die Wette nicht gewonnen!"
    daniel "Ok, du hast es!"
    daniel "Warte..." 
    daniel "Du sagst, sie ist eine Nutte..."
    daniel "Und, wenn dem so ist, dann kann ich sie auch ficken, stimmts?"
    ned "Na klar."
    m "WAS?!"
    m "Nein! Das ist das teuerste Kleid im ganzen Laden."
    m "Das war nicht der Deal!"
    m "Du hast mich nur angeheuert, um dir Gesellschaft zu leisten!!!"
    ned "Dein Chef hat mir deine Preiliste gegeben."
    ned "Sie sagte, ich kann es mir jederzeit anders überlegen"
    m "Nein! Das ist das teuerste Kleid im ganzen Laden."
    m "!!!"
    ned "Deine Agentur sagte, es gäbe keine Probleme mit dir!"
    ned "Oder soll ich deine Vorgesetzte anrufen?!"
    mt "Schwein!!!"
    mt "Eine Idiotenfirma!"
    mt "Erbärmliche Verlierer!"
    mt "!!!"
    daniel "Ned, hast du es schon probiert?"
    daniel "Wie ist sie?"
    ned "Um ehrlich zu sein, nein, habe ich noch nicht."
    ned "Ich habe sie nur gebucht um mich zu begleiten."
    ned "500 $ für Sex zahlen ist recht viel für mich."
    ned "Was, wenn du es rausgefunden hättest? Dann hätte unsere Wette meine Kosten nicht mal gedeckt."
    ned "Also, was ist mit unserer Wette? Gibst du zu, dass ich gewonnen habe?"
    daniel "Zur Hölle, ja!"
    daniel "Und wenn du sie noch nicht probiert hast, dann bin ich der Erste!"
    daniel "Ich will sie gleich jetzt ficken!"
    marty "Aber was ist mit Emma?"
    marty "Sie und Natalie können jede Minute zurück sein!"
    daniel "Zur Hölle damit! Erfindet einfach was, Leute!"
    daniel "Sagt, dass ich einen wichtigen Anruf habe, und Louise..."
    daniel "Louise wurde schwindelig und sie ist in's Bad!"
    daniel "Keine Panik jetzt!"
    daniel "Wie war nochmal dein Name?"
    m "..."
    ned "[monica_hotel_name]."
    daniel "[monica_hotel_name], folge mir!"
    m "Aber..."
    m "Nein... Ich werde nicht... ich..."
    ned "Ok, ich rufe sofort den VIP Service an!"
    ned "Ich werde sagen, dass das Mädchen nicht arbeiten will!"
    mt "Mist! Was soll ich nur tun?!"
    mt "Ich wollte doch nur etwas Geld verdienen..."
    mt "Ich dachte nicht, dass es so weit geht!"
    mt "!!!"
    ned "Guten Abend. Ja, ich habe es mir anders überlegt..."
    ned "Ich hätte gerne ein paar Dinge von der Preisliste gebucht."
    reception "Ja. Wir freuen uns, ihnen alles auf der Liste anbieten zu können!"
    ned "Ehm... dieses Mädchen... sie..." 
    reception "Lehnt sie etwas ab?!"
    reception "Sag ihr, dass sie gefeurt oder bestraft wird!"
    ned "Sie ist..."
    ned "Also?"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:487
translate german ep211_escort_scene2_5_2ddeab0a:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # ned "Эй... Полегче!"
    # ned "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fick dich!"
    m "Zusammen mit deinen Freunden!"
    m "Ein Haufen erbärmlicher Verlierer !!!"
    ned "Hey... locker..."
    ned "Dann wirst du ohne Geld dastehen!"
    m "Steck es in dein Arsch!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:499
translate german ep211_escort_scene2_5_e746d83c:

    # mt "!!!"
    # mt "Мерзавец!!!"
    # mt "Если я сейчас откажусь, меня выгонят из эскорта!"
    # mt "Что же делать?!"
    # mt "Я не могу потерять эту работу..."
    # mt "Я Моника Бакфетт и никогда не соглашусь на что-то подобное!"
    # mt "..."
    # mt "Мне нужно представить, что я не Моника Бакфетт, а [monica_hotel_name]."
    # mt "Для [monica_hotel_name] обслужить клиента - несложное дело."
    # mt "Для [monica_hotel_name] важна только сумма заработка за вечер."
    # mt "Поэтому [monica_hotel_name] сейчас согласится пойти с Дэниелем..."
    # m "Я все слышала и нет необходимости никого увольнять."
    # m "Я согласна."
    # ned "Ну вот. Другое дело."
    # daniel "[monica_hotel_name], пошли за мной."
    # daniel "Давай, быстрее. У меня не так много времени."
    mt "!!!"
    mt "Dieser Bastard!!!"
    mt "Wenn ich jetzt ablehne, fliege ich raus!"
    mt "Was mache ich jetzt?"
    mt "Ich kann diesen Job aber nicht verlieren..."
    mt "Ich bin Monica Buckfett und ich würde niemals sowas zustimmen!"
    mt "..."
    mt "Ich muss mir vorstellen, dass ich nicht Monica Buckfett bin, sondern [monica_hotel_name]."
    mt "Für [monica_hotel_name] ist es kein großes Ding, einen Kunden zu bedienen."
    mt "Für [monica_hotel_name] ist nur wichtig, wieviel Geld sie pro Nacht macht."
    mt "Also wird [monica_hotel_name] zustimmen, mit Daniel zu gehen..."
    m "Ich habe alles gehört, es gibt keinen Grund, irgendwen zu feuern."
    m "Ich stimme zu."
    ned "Na also, schon besser."
    daniel "[monica_hotel_name], folge mir!"
    daniel "Los geht's. Ich habe nicht viel Zeit!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:524
translate german ep211_escort_scene2_6_fa529d44:

    # daniel "Я с самого начала вечера захотел трахнуть тебя, [monica_hotel_name]."
    # mt "Эмма, видимо, и не подозревает, какой он козел на самом деле."
    # mt "Может, рассказать ей?"
    # daniel "Даже если ты была бы женой Нэда..."
    # daniel "Я непременно сделал бы это в один из дней!"
    # daniel "Я весь вечер раздумывал над тем, как осуществить это..."
    # daniel "И вовсе не ожидал, что трахнуть такую как Луиза будет так просто!"
    # mt "!!!"
    # mt "Мерзавец!"
    # daniel "Скорее раздевайся!"
    # m "Дэниел, я... Могу я тебя попросить?"
    # daniel "Что такое, [monica_hotel_name]?"
    # m "Я не хочу, чтобы о том, что здесь произойдет, кто-то узнал..."
    # daniel "Конечно, [monica_hotel_name]!"
    # daniel "Я не собираюсь никому рассказывать про такую сладкую детку."
    # daniel "Я не хочу делиться тобой с кем-то!"
    # daniel "Я буду заказывать тебя и трахать тебя сам!"
    # daniel "Снимай с себя это скорее! Мне не терпится!"
    # mt "[monica_hotel_name] сейчас снимет с себя платье."
    # mt "И будет зарабатывать деньги."
    # mt "Это просто работа."
    # daniel "Ложись на диван и раздвинь ноги."
    # daniel "Ммммм, какая же ты охренительная, детка..."
    # daniel "Я никому тебя не отдам."
    # daniel "Я буду твоим постоянным клиентом."
    # daniel "Ты будешь трахаться только со мной."
    # mt "У тебя, неудачник, денег на меня не хватит..."
    # daniel "О, ты просто супер, [monica_hotel_name]!"
    # daniel "Такая горячая! Такая охренительная!"
    # daniel "Дааа! Хочу трахать тебя каждый день!"
    # daniel "Мммммм..."
    # daniel "О, просто чертовски охренительно!!!"
    # daniel "Даааа!"
    # daniel "Ааааа!!!"
    daniel "Ich wollte dich schon von Anfang an ficken, [monica_hotel_name]."
    mt "Emma weiß offenabr nicht, was für ein Arschloch er ist."
    mt "Vielleicht sollte ich es ihr sagen?"
    daniel "Selbst wenn du Ned's Frau wärst..."
    daniel "Hätte ich es wohl gemacht eines Tages!"
    daniel "Ich habe den ganzen Abend darüber nachgedacht, wie ich es anstellen könnte..."
    daniel "Und ich dachte nicht, dass es so einfach werden wird!"
    mt "!!!"
    mt "Bastard!"
    daniel "Zieh dich aus!"
    m "Daniel, ich... darf ich was fragen?"
    daniel "Was denn?"
    m "Ich will nicht, dass irgendwer rausfindet, was hier los ist..."
    daniel "Klar, [monica_hotel_name]!"
    daniel "ich werde es keinem sagen."
    daniel "Ich will dich mit keinem teilen!"
    daniel "Ich werde dich selbst bestellen und ficken!"
    daniel "Ausziehen! Ich kann nicht mehr warten!"
    mt "[monica_hotel_name] wird sich gleich ausziehen."
    mt "Und Geld verdienen."
    mt "Es ist nur ein Job."
    daniel "Leg dich auf das Sofa und spreiz die Beine."
    daniel "Mmmmm, du bist so fickbar, Baby..."
    daniel "Ich gebe dich keinem Anderen."
    daniel "Ich werde ein regelmäßiger Kunde werden."
    daniel "Du wirst nur mit mir ficken."
    mt "Du Loser hast doch nicht mal genug Geld für mich..."
    daniel "DU bist total klasse, [monica_hotel_name]!"
    daniel "So heiß! So verdammt heiß!"
    daniel "Yeah! Ich will dich jeden Tag ficken!"
    daniel "Mmmmmmm..."
    daniel "Oh, das ist so Wahnsinn!!!"
    daniel "Yeah!!"
    daniel "Ahhhh!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:571
translate german ep211_escort_scene2_7_8d30eb74:

    # emma "Нэд, Марти, а где Дэниел?"
    # marty "Ему позвонили с работы. Какой-то срочный звонок."
    # marty "Он пошел в свой кабинет на второй этаж, чтобы поговорить без посторонних."
    # marty "Он не хочет, чтобы ему мешали разговаривать по телефону."
    # natalie "А где Луиза?"
    # ned "У нее началось небольшое недомогание и она ушла в туалет."
    # ned "Попросила нас пока веселиться и не беспокоить ее."
    # ned "Она скоро придет."
    # ​natalie "Странно..."
    # marty "Что странного?"
    # natalie "Что парень и девушка одновременно отсутствуют..."
    # emma "Натали, уж не думаешь ли ты, что такая как Луиза..."
    # emma "Станет общаться с моим оболтусом и хамом?"
    # marty "..."
    # ned "..."
    # emma "Да и я его знаю..."
    # emma "Дэниел никогда бы не стал поступать так по отношению к Нэду."
    # emma "Так что, не говори ерунды. Они скоро придут."
    # emma "А пока давайте веселиться!"
    # natalie "Да, ты права. Я слишком подозрительна..."
    # natalie "Марти, дорогой, налей мне еще вина."
    emma "Ned, Marty, wo ist Daniel?"
    marty "Er hat einen Anruf von der Arbeit erhalten. Klang irgendwie wichtig."
    marty "Er ist in sein Büro rauf um ungestört reden zu können."
    marty "Er möchte nicht gestört werden."
    natalie "Und wo ist Louise?"
    ned "Ihr war etwas schwindelig und sie ist ins Bad."
    ned "Sie sagte, wir sollen einfach weiter machen und Spaß haben."
    ned "Sie kommt sicher bald wieder."
    ​natalie "Seltsam..."
    marty "Ist was komisch?"
    natalie "Ja, dass ein Typ und eine Frau gleichzeitig weg sin..."
    emma "Natalie, denkst du wirklich, dass jemand wie Louise..."
    emma "Sich mit so einem Rüpel unterhält?"
    marty "..."
    ned "..."
    emma "Ja, ich kenne ihn..."
    emma "Daniel würde Ned das niemals antun..."
    emma "Also sei nicht dumm. Sie kommen bald wieder."
    emma "In der zwischenzeit, haben wir Spaß!"
    natalie "Ja, du hast recht. Ich bin zu misstrauisch..."
    natalie "Marty, Schatz, schenk mir bitte ein bisschen Wein ein."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:599
translate german ep211_escort_scene2_8_29925f14:

    # daniel "Мммммм..."
    # daniel "Какие же у тебя сиськи!"
    # daniel "Даааа!"
    # daniel "В следующий раз я куплю тебя на всю ночь!"
    # daniel "И буду трахать тебя до утра!"
    # daniel "Ааааа!!!"
    # daniel "Эй! Что ты делаешь здесь?!"
    # daniel "Что-то случилось?!"
    # daniel "Эмма что-то заподозрила?!"
    # marty "Нет, все в порядке!"
    # daniel "Тогда зачем ты приперся сюда?"
    # marty "Я сказал, что пойду проверю, все ли у тебя хорошо."
    # daniel "Ааааа..."
    # daniel "Твою мать! ДА!!!"
    # daniel "АААААА!!!"
    # daniel "У меня все хорошо, как видишь."
    # marty "Вижу..."
    # marty "Вообще-то, я спросил у Нэда..."
    # marty "И он разрешил мне тоже воспользоваться Луизой или как там ее зовут."
    # m "!!!"
    # daniel "Аха-ха!"
    # daniel "Я уже закончил, так что можешь делать с ней все, что хочешь!"
    # m "Нет!!!"
    # m "Я занималась этим с одним человеком!"
    # m "Не было условия, чтобы делать это с кем-то еще!!!"
    # marty "Нэд сказал, что дополнительный клиент стоит сверху $ 400."
    # marty "Это входит в твой прейскурант."
    # m "А почему $ 400?! Разве не должно быть дороже, если клиентов больше?!"
    # marty "Администратор сказала Нэду, что у тебя индивидуальный прейскурант."
    # marty "Чем больше мужчин, тем дешевле!"
    # marty "Аха-ха!"
    # daniel "Аха-ха!"
    # mt "Сволочь!"
    # mt "Сучка!!!"
    # mt "Ненавижу эту тварь!!!"
    # mt "Она специально сделала это!"
    # mt "Она мстит мне за то, что я обозвала ее никчемной и обещала уволить!"
    # mt "Между прочим, вполне заслуженно!"
    # mt "Это несправедливо!!!"
    # mt "Дьявол!!!"
    # marty "Ну так что? Я могу сделать это?"
    # m "!!!"
    daniel "Mmmmmmm..."
    daniel "Die hast wunderbare Titten!"
    daniel "Yeah!!"
    daniel "Nächstes Mal zahle ich für die ganze Nacht!"
    daniel "Und dann ficke ich dich bis in den Morgen!"
    daniel "Ahhhh!!!"
    daniel "Hey! Was machst du hier?!"
    daniel "Ist was passiert?!"
    daniel "Ist Emma misstrauisch?"
    marty "Nein, alles ok!"
    daniel "Warum bist du dann da?"
    marty "Ich sagte, ich schaue, wie es bei dir läuft."
    daniel "Ahhhh ..."
    daniel "Fuck! JAAAA!!!"
    daniel "AAAAA!!!"
    daniel "Mir geht’s gut, wie du siehst."
    marty "Sehe ich..."
    marty "Also eigentlich habe ich Ned gefragt, ob..."
    marty "Er hat mir jedenfalls erlaubt, Louise auch zu benutzen, oder wie sie heißt."
    m "!!!"
    daniel "Hahaha!"
    daniel "Ich bin fertig, mach mir ihr was du willst!"
    m "Nein!!!"
    m "Der Deal war nur eine Person!"
    m "Es hieß nie, dass noch jemand darf!!"
    marty "Ned sagte, ein weiterer Kunde kostet 400$ extra."
    marty "Steht alles in der Preisliste."
    m "Warum 400$? Sollte ich nicht mehr wert sein für die Kunden?"
    marty "Dein Boss sagte Ned, du hast eine eigene Preisliste."
    marty "Je mehr Männer, desto günstiger wird es!"
    marty "Hahaha!"
    daniel "Hahaha!"
    mt "Du Bastard!"
    mt "Schlampe!"
    mt "Ich hasse diese Bitch!"
    mt "Das hat sie mit Absicht gemacht!"
    mt "Sie rächt sich dafür, dass ich sie nutzlose nannte!"
    mt "Aus gutem Grund, übrigens!"
    mt "Das ist unfair!"
    mt "Zefix!!!"
    marty "Also, kann ich?"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:654
translate german ep211_escort_scene2_8_a254eba4:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # marty "Эй... Полегче!"
    # marty "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fick dich!"
    m "Zusammen mit deinen Freunden!"
    m "Ein Haufen erbärmlicher Verlierer !!!"
    marty "Hey... locker..."
    marty "Dann wirst du ohne Geld dastehen!"
    m "Steck es in dein Arsch!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:666
translate german ep211_escort_scene2_8_dee3b8bf:

    # mt "!!!"
    # mt "Ненавижу их всех!"
    # mt "Поотрывала бы им яйца!!!"
    # mt "Мерзкие неудачники!"
    # marty "Ну? Чего молчишь? Ты согласна?"
    # mt "С другой стороны..."
    # mt "[monica_hotel_name] за этот вечер неплохо заработает."
    # mt "И, так получается, что деньги у меня с ней общие..."
    # m "Да... Согласна..."
    # marty "Вставай раком!"
    mt "!!!"
    mt "Ich hasse sie alle!!!"
    mt "Ich reiße ihnen allen die Eier ab!"
    mt "Dumme Loser!"
    marty "Gut? Was sagst du? Stimmst du zu?"
    mt "Andererseits..."
    mt "[monica_hotel_name] wird heute Abend viel verdienen."
    mt "Und ich teile mir das Geld mit ihr..."
    m "Ja, ich stimme zu..."
    marty "Zeit für Doggy!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:684
translate german ep211_escort_scene2_9_c3979c5f:

    # natalie "Дэниел, куда Марти ушел?"
    # daniel "Марти нашел меня и спросил, все ли у меня в порядке."
    # daniel "Я как раз закончил разговор и собирался возвращаться."
    # daniel "Тогда Марти решил зайти в туалет и я проводил его."
    # daniel "Нам пришлось идти в другой туалет, потому что основной был занят."
    # daniel "Там, видимо, сейчас Луиза."
    # daniel "Мы даже слышали какие-то звуки. Похоже, что ее тошнит."
    # natalie "Бедняжка!"
    # natalie "Она, должно быть, выбрала какое-то не то сочетание продуктов."
    # natalie "Эмма, может быть, нам стоит сходить к ней?" 
    # natalie "Проверим, все ли с ней хорошо?"
    natalie "Daniel, wo ist nun Marty hin?"
    daniel "Marty kam zu mir und wollte wissen, ob alles ok ist."
    daniel "Ich habe gerade fertig telefoniert und wollte gerade zurück."
    daniel "Dann wollte Marty ins Bad."
    daniel "Er musste aber zu einer anderen Toilette, die Eine ist ja besetzt."
    daniel "Louise ist da wohl drin."
    daniel "Wir haben was gehört, klang so, als wäre sie krank."
    natalie "Armes Ding!"
    natalie "Sie hat vielleicht nur was Falsches getrunken."
    natalie "Emma, vielleicht sollten wir nach ihr sehen?" 
    natalie "Schauen wir, ob es ihr gut geht."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:703
translate german ep211_escort_scene2_10_43c2afda:

    # marty "Мммм, какая у тебя клевая попка!"
    # marty "Такая упругая..."
    # mt "Когда же он уже кончит и отстанет от меня?"
    # marty "О, дааа!"
    # marty "Мммммм..."
    # marty "ААААААХ!!!"
    # mt "Ну наконец-то!!!"
    # mt "Надо одеваться и скорее уходить из этого чертового дома!!!"
    marty "Mmmm, was für ein geiler Arsch!"
    marty "So knackig..."
    mt "Wann ist er endlich fertig und geht?"
    marty "Oh ja!"
    marty "Mmmmmmm..."
    marty "AAAAAAH !!!"
    mt "Endlich!!!"
    mt "Ich muss mich anziehen und aus diesem verdammten Haus raus!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:720
translate german ep211_escort_scene2_11_9eec7ddd:

    # ned "Не стоит. Я сейчас сам пойду к Луизе и проверю, как она себя чувствует."
    # emma "Да, конечно. Пусть Нэд идет." 
    # emma "Нэд, тебе стоит заботиться о такой хорошей девушке, как Луиза."
    # emma "Иначе ты рискуешь ее потерять."
    # emma "Должно быть, у нее действительно к тебе чувства..."
    # emma "Раз такая как она согласилась встречаться с тобой."
    # ned "Да, Эмма. Луиза моя девушка и я очень горжусь этим!"
    ned "Nein, nein. Ich gehe zu Louise und schaue, ob alles ok ist."
    emma "Klar, lass Ned gehen." 
    emma "Ned, du solltest auf so eine tolle Frau wie Louise aufpassen."
    emma "Sonst riskierst du, sie zu verlieren."
    emma "Sie muss wirklich Gefühle für dich haben..."
    emma "Nachdem sie einem Date zugestimmt hat."
    ned "Ja, Emma. Louise ist meine Freundin und ich bin sehr stolz auf sie!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:735
translate german ep211_escort_scene2_12_7739303b:

    # ned "Черт! Пустите меня!"
    # ned "Теперь моя очередь! Дайте сюда!"
    # ned "Я должен ее трахнуть тоже! Все-таки, это моя девушка!!!"
    # m "!!!"
    # m "Ты..."
    # ned "$ 200! Следующий клиент стоит $ 200!!!"
    # ned "Я специально подождал, чтобы получить скидку!!!"
    # ned "Жаль, мы не взяли с собой Джима!"
    # ned "Тогда мне бы это обошлось всего в $ 100!"
    # mt "Жалкий жадный неудачник!!!"
    # mt "Подонок!!!"
    # m "!!!"
    ned "Scheiße! Lass mich auch mal!"
    ned "Ich bin dran! Gib sie rüber."
    ned "Ich muss sie auch ficken! Immerhin ist sie meine Freundin!!!"
    m "!!!"
    m "Du..."
    ned "200$! Der Nächste kostet 200$!!!"
    ned "Ich habe so lange gewartet, bis ich einen Rabatt bekomme!!!"
    ned "Wenn nur Jim auch da wäre!"
    ned "Dann würde es mich nur 100$ kosten!"
    mt "Widerliche, dumme Loser!"
    mt "Bastarde!!!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:752
translate german ep211_escort_scene2_12_2ddeab0a:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # ned "Эй... Полегче!"
    # ned "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fick dich!"
    m "Zusammen mit deinen Freunden!"
    m "Ein Haufen erbärmlicher Verlierer !!!"
    ned "Hey... locker..."
    ned "Dann wirst du ohne Geld dastehen!"
    m "Steck es in dein Arsch!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:764
translate german ep211_escort_scene2_12_c01ef09b:

    # mt "!!!"
    # mt "Это просто работа..."
    # ned "Даааа!!!"
    # marty "Эй, Нэд! Натали ничего не спрашивала про меня?"
    # ned "Нет, но беги скорее, а то тебя начнут искать!"
    # ned "Аааа..."
    # ned "Аааааа..."
    # ned "Аааааааа..."
    # ned "АААААА!!!" 
    mt "!!!"
    mt "Nur ein Job..."
    ned "Ja!!!"
    marty "Hey Ned, hat Natalie wegen mir gefragt?"
    ned "Nein, aber du gehst besser zu ihr, sonst sucht sie dich noch!"
    ned "Ahhh..."
    ned "Ahhhh ..."
    ned "Aaaaaaaa ..."
    ned "AAAAA!!!" 

# game/Quests/EP2_11/ep211_escort_scene2.rpy:783
translate german ep211_escort_scene2_13_527969cf:

    # mt "Я не могу смотреть на этих похотливых козлов!"
    # mt "Они только что изменили своим женам!"
    # mt "Изменили, сделав... сделав... Даже не хочу об этом думать!"
    # mt "А теперь сидят и лгут им! Как ни в чем не бывало!"
    # mt "Как же это мерзко!"
    # mt "А более мерзко то, что мне после всего..."
    # mt "После всей этй грязи..."
    # mt "Мне нужно тоже притворяться перед Эммой и Натали!"
    # mt "Это какой-то кошмар!"
    # ned "Луиза, любимая, ты себя уже лучше чувствуешь?"
    # m "Да..."
    # m "Спасибо за твою заботу, дорогой..."
    # mt "Подонок!!!"
    # natalie "Луиза, мы с Эммой так переживали за тебя."
    # emma "Тебе точно стало лучше? Может, тебе дать какие-нибудь лекарства?"
    # mt "Дайте мне яду. Я налью его в бокалы ваших козлов!"
    # m "Мне уже лучше, спасибо."
    # natalie "Ну и хорошо. Луиза, у меня на завтра запланирован шоппинг."
    # natalie "Эмма тоже ко мне присоединиться. Не хочешь составить нам компанию?"
    # emma "Да, это отличная идея!"
    # emma "Луиза, ты же хорошо разбираешься в моде..."
    # emma "Пойдем завтра с нами!"
    # emma "Погуляем по магазинам, зайдем в ресторан."
    # natalie "Потом можно будет сходить в СПА. Мы отлично проведем время!"
    # m "Спасибо за предложение, девочки, но..."
    # m "У меня завтра много работы."
    # m "У меня каждый день расписан буквально поминутно."
    # m "К сожалению, у меня не будет времени."
    # mt "Не хватало еще тратить на всякую ерунду деньги, которые я заработала с таким трудом..."
    # mt "Тем более, их даже не хватит на новую сумочку..."
    # emma "Жаль..."
    # natalie "Луиза, у тебя такой плотный рабочий график."
    # natalie "Когда вы успеваете встречаться с Нэдом?"
    # m "..."
    # m "По вечерам... Мы уделяем друг другу время."
    # ned "Да, любимая. Мы стараемся встречаться каждый вечер."
    # emma "Наверное, это так волнительно - ждать вечера, чтобы встретиться с любимым..."
    # m "..."
    # natalie "Луиза, а Нэд часто дарит тебе подарки?"
    # natalie "Мне вот Марти дарит цветы только по праздникам..."
    # marty "Дорогая, ну ты же итак знаешь, что я тебя люблю..."
    # natalie "Знаю. Но мне все равно хочется внимания."
    # natalie "А ты только и знаешь, что сидишь целыми вечерами в телефоне и работаешь!"
    # marty "Ну не обижайся. Я стараюсь ради нас с тобой." 
    # emma "А мой Дэниел часто балует меня цветами и всякими приятными сюрпризами."
    # daniel "Конечно, любимая. Мне нравится делать тебя счастливой." 
    # mt "Боже... Меня сейчас стошнит от этого всего..."
    # ned "Луиза, дорогая. Мне кажется, тебе снова нехорошо."
    # ned "Может быть, я отвезу тебя домой?"
    # m "Да, дорогой. Я буду тебе очень благодарна."
    # m "Спасибо за приятный вечер." 
    # m "Я была рада с вами познакомиться."
    # emma "Я надеюсь, вы с Нэдом к нам еще приедете."
    # emma "Я буду очень рада тебя видеть, Луиза!"
    # natalie "И мы обязательно еще сходим с тобой на шоппинг!"
    # m "Хорошо. Обязательно."
    # marty "Пока, Луиза. Приятно было познакомиться."
    # daniel "И мне тоже было приятно. Пока."
    mt "Ich kann diese lüsternen Arschlöcher nicht mehr sehen!"
    mt "Alle haben ihre Frauen betrogen!"
    mt "Ich will nicht mal dran denken!"
    mt "Und jetzt lügen sie sie alle an! Als wenn nichts gewesen wäre!"
    mt "Widerlich!"
    mt "Besonders nach alldem..."
    mt "Nach diesem Bullshit..."
    mt "Ich muss vor Natalie und Emma auch so tun, als wäre nichts gewesen!"
    mt "Ein Alptraum!"
    ned "Louise, Schatz, geht’s dir besser?"
    m "Ja."
    m "Danke für deine Sorge, Schatz..."
    mt "Bastarde!!!"
    natalie "Louise, Emma und ich haben uns gesorgt."
    emma "Sicher, dass es dir besser geht? Brauchst du eine Tablette?"
    mt "Gib mir Gift! Ich schütte es in eure Gläser, Arschlöcher!"
    m "Mir geht’s besser, danke."
    natalie "Das ist gut. Louise, ich habe für morgen was geplant."
    natalie "Emma ist auch dabei, leistest du uns Gesellschaft?"
    emma "Ja, eine tolle Idee!"
    emma "Louise, du weißt viel über Mode..."
    emma "Komm morgen mit uns mit!"
    emma "Gehen wir shoppen, danach in ein Restaurant."
    natalie "Danach gehen wir in einen SPA, wir werden eine tolle Zeit haben."
    m "Danke für das Angebot, Mädels, aber..."
    m "Ich habe morgen viel zu tun."
    m "Ich habe sprichwörtlich jeden Tag bis auf die Minute verplant."
    m "Leider habe ich keine Zeit."
    mt "Ich will nicht das ganze Geld ausgeben, das ich verdiene..."
    mt "Ich habe nicht mal genug dafür..."
    emma "Tut mir leid..."
    natalie "Louise, du bist so beschäftigt."
    natalie "Wann hast du Zeit, Ned zu treffen?"
    m "..."
    m "Abends... Wir finden dann schon was für uns."
    ned "Ja, Liebling. Wir versuchen, uns jeden Abend zu sehen."
    emma "Es ist spannend, sich nur am Abend zu sehen..."
    m "..."
    natalie "Louise, schenkt dir Ned oft was?"
    natalie "Marty schenkt mir nur zu Feiertagen Blumen..."
    marty "Schatz, du weißt doch, dass ich dich liebe..."
    natalie "Ich weiß, aber ich will auch Aufmerksamkeit."
    natalie "Alles was ich weiß, ist, dass du immer am Handy bist und arbeitest!"
    marty "Keine Anschuldigung. Ich mache das für uns." 
    emma "Mein Daniel schenkt mir oft Blumen und andere, schöne Dinge."
    daniel "Klar, Schatz. Ich mag es, wenn du glücklich bist." 
    mt "Oh Gott... Ich kotze gleich..."
    ned "Louise, Schatz. Geht es dir wieder schlecht?"
    ned "Vielleicht sollten wir nach Hause?"
    m "Ja, Schatz. Das wäre gut."
    m "Danke für den schönen Abend." 
    m "War toll, euch kennen zu lernen."
    emma "Ich hoffe, Du und Ned kommen bald wieder."
    emma "Das würde mich sehr freuen!"
    natalie "Dann gehen wir shoppen!"
    m "Na klar."
    marty "Tschüss, Louise. War schön mit dir!"
    daniel "Jup, tschüss."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:850
translate german ep211_escort_scene2_14_7046459d:

    # mt "Ненавижу эту никчемную администраторшу!"
    # mt "!!!"
    # reception "[monica_hotel_name]!!!"
    # reception "Мне звонил клент!"
    # reception "Он крайне недоволен твоим поведением!"
    # reception "Какого черта ты решила, что можешь диктовать свои условия клиенту?!"
    # m "Он изменил первоначальные условия..."
    # reception "Да!!! И он имел на это право!!!"
    # reception "Я тебя прощаю на первый раз и ограничусь только штрафом!"
    # reception "В следующий раз ты за подобное поведение вылетишь отсюда!!!"
    # reception "У нас ВИП Эскорт! Такое отношение к клиентам недопустимо!"
    # reception "Ты поняла меня?!?!"
    # m "Да..."
    # mt "Сучка!"
    # mt "Ненавижу!"
    # reception "Клиент за сопровождение заплатил $500."
    # reception "Ты оштрафована за невыполнение услуг согласно прейскуранту."
    # reception "И с этих денег ты не получаешь ни цента!"
    # mt "!!!"
    # m "Как?"
    # reception "Да, ни цента! И это ты еще легко отделалась!"
    # reception "Еще хоть одно малейшее нарушение и тебя ждет увольнение!!!"
    # reception "Тебе все понятно, [monica_hotel_name]?!"
    # m "Да..."
    # mt "Гори в аду, мразь!"
    # reception "Ты хорошо справилась с сегодняшним заказом..."
    # reception "Но клиент сказал, что ты вела себя нерешительно."
    # reception "[monica_hotel_name] должна сама предлагать услуги из прейскуранта!"
    # reception "И не заставлять клиентов уговаривать себя!"
    # reception "Если подобное поведение будет встречено еще раз..."
    # reception "То ты будешь оштрафована, понятно?!"
    # m "Да..."
    # mt "!!!"
    # reception "Клиент заплатил $500 за сопровождение на вечере..."
    # reception "И $1100 за три дополнительные услуги из прейскуранта."
    # reception "Твой заработок составляет 50 процентов от суммы."
    # reception "То есть $800."
    # reception "Вот твои деньги."
    # reception "Завтра можешь приходить снова."
    # reception "На сегодня все. Клиенты не любят использованный товар."
    # mt "Вот сучка!"
    # mt "!!!"
    mt "Ich hasse diese dumme Bitch im Hotel!"
    mt "!!!"
    reception "[monica_hotel_name]!!!"
    reception "Der Kunde hat mich angerufen!"
    reception "Er ist nicht zufrieden mit deinem Verhalten!"
    reception "Wie konntest du denken, du kannst dem Kunden sagen, was er darf oder nicht?!"
    m "Er hat die Vereinbarung einfach verändert!..."
    reception "Ja!!! Und das war auch ok!!!"
    reception "Ich vergebe dir das erste Mal und reduziere deine Strafe auf weniger Geld!"
    reception "Aber nächstes Mal fliegst du raus!!!"
    reception "Du bist eine VIP Escort! So ein Verhalten gegenüber Kunden ist inakzeptabel!"
    reception "Verstanden?!?!"
    m "Ja."
    mt "Schlampe!"
    mt "ICH HASSE IHN!"
    reception "Der Kunde hat 500$ bezahlt."
    reception "Du wirst gemessen an der Preisliste für dein Fehlverhalten bestraft."
    reception "Also, bekommst du heute keinen Cent!"
    mt "!!!"
    m "Wie?"
    reception "Genau, keinen Cent! Und das war noch gnädig!"
    reception "Noch einmal auch nur dir kleinste Verfehlung, und du fliegst raus!!!"
    reception "Hast du mich verstanden, [monica_hotel_name]?!"
    m "Ja."
    mt "Brenne in der Hölle, Abschaum!"
    reception "Du hast das heute gut gemacht..."
    reception "Aber der Kunde sagte, du hast gezögert."
    reception "[monica_hotel_name] muss den Service gemäß der Preisliste anbieten!"
    reception "Und versuche nicht, Kunden zu überreden, ihre Meinung zu ändern!"
    reception "Wenn das nochmal vorkommen sollte..."
    reception "Dann erhältst du eine Strafe, klar?"
    m "Ja."
    mt "!!!"
    reception "Der Kunde hat 500$ bezahlt."
    reception "Und 1.100$ für drei weitere Serviceleistungen."
    reception "Dein Verdienst sind 50%%."
    reception "Das macht 800$."
    reception "Hier ist dein Geld."
    reception "Du kannst morgen wiederkommen."
    reception "Das ist alles für heute. Die Kunden mögen keine gebrauchten Waren."
    mt "Was für eine Schlampe!"
    mt "!!!"

translate german strings:

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:357
    old "Сказать, что я его девушка и уйти!"
    new "Sage, dass du seine Freundin bist und gehe!"

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:357
    old "Сказать, что я работаю в эскорте."
    new "Sage, dass du als Escort arbeitest."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:484
    old "Согласиться пойти с Дэниелем."
    new "Stimme zu, mit Daniel zu gehen."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:651
    old "Смириться с прейскурантом."
    new "Stimme der Preisliste zu."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:749
    old "Смириться, иначе меня ждет штраф или увольнение."
    new "Mach mit, sonst gibt es Sanktionen."

