# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_escort_scene1.rpy:13
translate german ep211_escort_scene1_1a_5139b4d8:

    # mt "Что мне делать дальше?"
    # mt "..."
    mt "Was soll ich als nächstes tun?"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:31
translate german ep211_escort_scene1_1a_98200677:

    # mt "Что ж... Надеюсь, [monica_hotel_name] повезет сегодня с клиентом..."
    mt "Hm... Ich hoffe, dass [monica_hotel_name] heute Glück mit einem Kunden hat..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:35
translate german ep211_escort_scene1_1a_25ff8835:

    # mt "Нет! Я не буду заниматься этим!!!"
    # mt "Я Моника Бакфетт! Я никогда не опущусь до подобной грязи!"
    # mt "!!!"
    mt "Nein! Das werde ich nicht machen!!!"
    mt "Ich bin Monica Buckfett! Ich werde nicht so tief fallen!"
    mt "!!!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:46
translate german ep211_escort_scene1_1_9213bb70:

    # mt "Так, Моника. Соберись!"
    # mt "Не надо так нервничать."
    # mt "Ты в любой момент можешь послать всех к черту и уйти."
    # client "Добрый вечер, Мисс."
    # client "Я Вас раньше здесь не видел. Как вас зовут?"
    # m "Добрый вечер, Мистер."
    # m "Меня зовут [monica_hotel_name]."
    # client "[monica_hotel_name]. Какое прекрасное имя. Как и его обладательница."
    # client "Я очень рад, что сегодня проведу вечер с Вами, [monica_hotel_name]."
    # mt "Хмм... Разговаривает вежливо, выглядит вполне прилично."
    # mt "Думаю, от него не стоит ожидать никаких извращений..."
    # client "Позволите мне сразу пригласить Вас в номер, [monica_hotel_name]?"
    # mt "..."
    mt "Reiß dich zusammen Monica!"
    mt "Sein nicht so nervös."
    mt "Ich kann Jeden zur Hölle schicken, wann ich will und einfach gehen."
    client "Guten Abend."
    client "Ich habe dich hier noch nie gesehen. Wie heißen Sie?"
    m "Guten Abend."
    m "Ich bin [monica_hotel_name]."
    client "[monica_hotel_name]. Der Name ist so wuderschön, wie die Besitzerin"
    client "[monica_hotel_name,] ich freue mich sehr, den Abend mit Ihnen zu verbringen."
    mt "Hmm ... Er redet höflich, sieht ziemlich anständig aus."
    mt "Ich denke, er sollte keine Schwierigkeiten machen..."
    client "[monica_hotel_name] können wir jetzt auf dein Zimmer gehen?"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:64
translate german ep211_escort_scene1_1_3d014ec3:

    # mt "Нет! Я не могу это сделать!"
    # m "Я..."
    # m "Я не смогу с Вами пойти..."
    # m "Я... Я не работаю здесь!"
    # m "Я просто зашла поесть в ресторан..."
    # client "О, извините, Мисс."
    # client "Наверное, я перепутал столик."
    mt "Nein. Das kann ich nicht."
    m "Ich..."
    m "Ich kann mit dir nicht gehen..."
    m "Ich... Ich arbeite hier nicht!"
    m "Ich bin gerade nur zum Essen hier...."
    client "Oh Entschuldigung"
    client "Ich habe wohl den Tisch verwechselt."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:76
translate german ep211_escort_scene1_1_5c853789:

    # mt "Это же совсем нестрашно."
    # mt "Это просто обычный неудачник."
    # mt "Наверное, приходит сюда раз в месяц в день зарплаты. Фи!"
    # mt "Что-то пойдет не так - я просто уйду отсюда."
    # mt "Хммм..."
    # mt "Они мне тогда сказали, что будут давать мне заказы..."
    # mt "Только с проблемными клиентами."
    # mt "..."
    # mt "Мне нужно сказать этой никчемной администраторше, что у меня клиент."
    # mt "Может, она скажет, что с ним не так."
    # m "Да, мы можем пойти в номер."
    # m "Только мне нужно отойти на пару минут."
    # client "Конечно, [monica_hotel_name]."
    # client "Я буду ждать тебя у лифта."
    mt "Er ist völlig harmlos"
    mt "Er ist nur ein gewöhnlicher Verlierer."
    mt "Kommt wahrscheinlich nur an seinem Zahltag einmal im Monat hierher."
    mt "Es wird etwas schief gehen - ich gehe einfach hier weg."
    mt "Hmmm ..."
    mt "Sie sagten, sie geben mit Anweisungen..."
    mt "Ich muss mich um Problemkunden kümmern."
    mt "..."
    mt "Ich muss diesem nutzlosen Chef sagen, dass ich einen Kunden habe."
    mt "Vielleicht sagt sie mir, was mit ihm nicht stimmt."
    m "Ja, wir können aufs Zimmer gehen."
    m "Ich muss nur für ein paar Minuten weg."
    client "Natürlich, [monica_hotel_name]."
    client "Я буду ждать тебя у лифта."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:96
translate german ep211_escort_scene1_2_72e84a43:

    # m "У меня клиент. Он зовет пойти с ним в номер..."
    # reception "Я уже в курсе..."
    # reception "Это один из наших постоянных клиентов."
    # reception "Девочки не любят работать с ним."
    # m "Почему?"
    # mt "Вроде он не похож на извращенца."
    # reception "У него не встает, но он никак не хочет смириться с этим..."
    # reception "Он всегда заказывает девочек и мурыжит их до утра."
    # reception "Очень хочет кончить..."
    # reception "Но, как правило, безрезультатно."
    # reception "Потом скандалит и обвиняет девочек в том, что они плохо работают."
    # mt "!!!"
    # m "То есть... Если он скажет, что я плохо работаю, то..."
    # reception "Штраф."
    # mt "Вот сучка!"
    # m "Ты же сама говоришь, что дело в клиенте, а не в девочках!"
    # m "Какой еще штраф?!"
    # reception "Это правило нашего ВИП Эскорта."
    # mt "Что за бред!!!"
    # reception "И я переоделась бы на твоем месте..."
    # reception "Иди в служебный коридор."
    # reception "Там можно найти что-нибудь, что возбудит этого клиента."
    # m "Но..."
    # reception "Все! Иди. Не заставляй клиента ждать тебя!"
    # m "..."
    # reception "Быстро!"
    m "Ich habe einen Kunden. Er wartet darauf, mit Dir zu einem Zimmer zu gehen..."
    reception "Ich weiß schon..."
    reception "Das ist einer unserer normalen Kunden."
    reception "Die Mädchen arbeiten nicht gerne mit ihm."
    m "Warum?"
    mt "Er sieht nicht wie ein Perverser aus."
    reception "Er kriegt ihn nicht so gut hoch, aber will das nicht zugeben..."
    reception "Er kommandiert die Mädchen rum bügelt sie bis in den Morgen."
    reception "Er will kommen..."
    reception "Aber das ist gegen die Regeln."
    reception "Dann beschuldigt er die Mädchen, dass sie ihren Job nicht gut machen."
    mt "!!!"
    m "Das ist... Wenn er also sagt, ich arbeite nicht gut, ist das..."
    reception "Ok."
    mt "Was für eine Schlampe!"
    m "Du sagst, es liegt an dem Kunden, nicht den Mädchen?"
    m "Was ist ok?"
    reception "Die Regel bei dem VIP Escort Service."
    mt "Was für ein Unsinn!!!"
    reception "Wenn ich du wäre, würde ich mich umziehen..."
    reception "Иди в служебный коридор."
    reception "Там можно найти что-нибудь, что возбудит этого клиента."
    m "Aber..."
    reception "Все! Иди. Не заставляй клиента ждать тебя!"
    m "..."
    reception "Los!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:130
translate german ep211_escort_scene1_3_a8f99376:

    # client "[monica_hotel_name], я Вас уже заждался."
    # client "Пройдемте в номер!"
    # client "Мне уже не терпится посмотреть, что у Вас под платьем..."
    # mt "..."
    # mt "Так, Моника, соберись!"
    # mt "Тебе надо представить, что ты [monica_hotel_name]."
    # mt "А не Моника Бакфетт."
    # mt "А это просто обычный неудачник."
    # mt "Наверное, приходит сюда раз в месяц в день зарплаты. Фи!"
    # mt "Что-то пойдет не так - я просто уйду отсюда."
    client "[monica_hotel_name], я Вас уже заждался."
    client "Пройдемте в номер!"
    client "Мне уже не терпится посмотреть, что у Вас под платьем..."
    mt "..."
    mt "Also, Monica, denk nach!"
    mt "Du musst dir vorstellen, dass du [monica_hotel_name] bist."
    mt "Nicht Monica Buckfett."
    mt "Das ist nur ein normaler Loser."
    mt "Kommt wahrscheinlich nur an seinem Zahltag einmal im Monat hierher."
    mt "Es wird etwas schief gehen - ich gehe einfach hier weg."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:145
translate german ep211_escort_scene1_4_1399e723:

    # m "Что мне нужно сделать?"
    # mt "Дал бы денег просто так и отпустил бы..."
    # mt "У меня нет никакого желания делать для него что-то."
    # client "Для начала [monica_hotel_name] должна снять платье..."
    # mt "Моника, не переживай."
    # mt "Тебе нечего стесняться. У тебя великолепное тело."
    # mt "..."
    # mt "Он, наверняка, никогда не видел такой красивой женщины, как я."
    # mt "Сейчас он разденется и начнет лапать мое прекрасное тело. Фу!"
    # client "[monica_hotel_name], присаживайтесь рядом со мной."
    # client "Если [monica_hotel_name] позволит мне целовать ее ножку..."
    # client "Я буду щедр с Мисс."
    # mt "Он хочет целовать мне ноги?"
    # mt "Да еще и платить за это?!"
    # mt "?!?!?!"
    # mt "Он это серьезно?!"
    # mt "???"
    # mt "Может, я ослышалась?"
    # m "Мистер, Вы хотите целовать мою ногу?"
    # client "Да, Мисс. Позвольте Вашу ножку."
    # m "..."
    # m "Ммммм..."
    # mt "Это приятно..."
    # mt "Черт!"
    # mt "Он за это еще и денег заплатит?"
    # mt "Я готова работать так каждый вечер."
    # mt "О, как же приятно..."
    # client "А теперь [monica_hotel_name] возьмет мой палец в свой ротик..."
    # client "И пососет его..."
    # mt "???"
    m "Was muss ich tun?"
    mt "Ich würde gern nur das Geld nehmen und einfach gehen..."
    mt "Ich habe keine Lust, etwas für ihn zu tun."
    client "Zu Beginn muss [monica_hotel_name] ihr Kleid ausziehen ..."
    mt "Monica, hab keine Angst."
    mt "Du musst sich für nichts schämen. Du hast einen großartigen Körper."
    mt "..."
    mt "Er hat wahrscheinlich noch nie so schöne Frau wie mich gesehen."
    mt "Jetzt wird er sich ausziehen und anfangen, meinen schönen Körper zu begrapschen. Puh!"
    client "Setz dich neben mich [monica_hotel_name]."
    client "Wenn du mir erlaubst deine Beine zu küssen [monica_hotel_name]...."
    client "Werde ich zu dir großzügig sein."
    mt "Er will meine Beine küssen?"
    mt "Und dafür auch noch bezahlen?"
    mt "?!?!?!"
    mt "Ist das sein Ernst?"
    mt "???"
    mt "Vielleicht habe ich mich verhört?"
    m "Du möchtest meine Beine küssen?"
    client "Ja, deine Beine"
    m "..."
    m "Mmmm..."
    mt "Es ist schön..."
    mt "Huch!"
    mt "Dafür zahlt er Geld?"
    mt "Ich bin bereit, jeden Abend so zu arbeiten."
    mt "Oh, wie schön..."
    client "Und jetzt wird [monica_hotel_name] meinen Finger in Ihren Mund nehmen ..."
    client "Und ihn ablecken...."
    mt "???"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:187
translate german ep211_escort_scene1_4_0d5ba6cc:

    # mt "Фу! Нет! Я не могу это сделать!"
    # mt "Я не хочу облизывать грязные руки этого неудачника!"
    # m "Я..."
    # m "Я не смогу..."
    # m "Я... Я не предоставляю такую услугу!"
    # client "Но, Мисс... Мне сказали, что..."
    # m "Нет. Я не буду этого делать!"
    mt "Puh! Nein! Ich kann das nicht tuen!"
    mt "Ich will nicht die Hände von dem Loser lecken!"
    m "Ich..."
    m "Ich kann das nicht..."
    m "Ich... Ich biete diesen Service nicht an!"
    client "Aber Frau....Mir wurde gesagt, dass ..."
    m "Nicht. Ich werde es nicht tun!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:200
translate german ep211_escort_scene1_4_d6c1ab97:

    # mt "Это унизительно и..."
    # mt "Противно!"
    # mt "Но брать в рот его грязный палец!!!"
    # mt "!!!"
    # mt "Но он сказал, что будет щедр..."
    # mt "Все же это не какое-то там гадкое извращенство..."
    # mt "..."
    # mt "Это просто работа, Моника."
    # mt "..."
    # mt "Главное, чтобы меня не стошнило прямо на него."
    # client "Соси его!"
    # client "Оооооо!!!"
    # client "Как же приятно! Ещееее!!!"
    # client "А теперь, [monica_hotel_name], раздвинь ноги!"
    # client "Я хочу посмотреть на твою киску!"
    # client "!!!"
    # mt "Черт!"
    # mt "Какой-то мерзкий неудачник сейчас будет пялиться на мою..."
    # mt "..."
    # mt "Но если я откажу ему, он не заплатит денег."
    # mt "И будут проблемы с этой никчемной администраторшей..."
    # mt "Она говорила, что будет штраф."
    # mt "А мне нужны деньги."
    # mt "..."
    mt "Es ist so demütigend und ..."
    mt "Und ekelhaft!"
    mt "Oder seine dreckigen Finger in den Mund nehmen!!!"
    mt "!!!"
    mt "Aber er sagte, er wäre großzügig ..."
    mt "Es ist jedoch keine böse Perversion ..."
    mt "..."
    mt "Es ist nur ein Job, Monica."
    mt "..."
    mt "Hauptsache, ich kotze ihn nicht direkt an."
    client "Leck sie ab!"
    client "Ooooh!!!"
    client "Wie schön! Mehr!!!"
    client "Und jetzt, [monica_hotel_name], spreiz die Beine!"
    client "Ich will deine Pussy anschauen!"
    client "!!!"
    mt "Huch!"
    mt "Ein dummer Loser wird gleich meine... anstarren..."
    mt "..."
    mt "Aber wenn ich ablehne, wird er nicht bezahlen."
    mt "Und dann bekomme ich Probleme mit der Tussi an der Rezeption..."
    mt "Sie sagte, es ist ok."
    mt "Und ich brauche das Geld."
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:230
translate german ep211_escort_scene1_4_24fd42b5:

    # client "О, дааааа!"
    # client "Дрочи!"
    # m "???"
    # client "Я хочу смотреть, как ты дрочешь себе!"
    # client "Ну! Давай же! Дрочи!"
    client "Oh ja!"
    client "Machs dir!"
    m "???"
    client "Я хочу смотреть, как ты дрочешь себе!"
    client "Ну! Давай же! Дрочи!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:239
translate german ep211_escort_scene1_4_49d82231:

    # mt "Фу! Нет! Я не хочу!"
    # mt "Мне надоело возиться с этим неудачником!"
    # mt "!!!"
    # m "Нет. Я не буду этого делать!"
    mt "Oh! Nein! Das will ich nicht!"
    mt "Ich bin es schon leid, mich mit dem Loser abzugeben!"
    mt "!!!"
    m "Nicht. Ich werde es nicht tun!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:248
translate german ep211_escort_scene1_4_f57aafd8:

    # mt "Надеюсь, ему достаточно будет того, что он посмотрит как я себя трогаю..."
    # mt "Лучше так, чем он будет лезть к моей..."
    # mt "Ко мне своими грязными пальцами!"
    # client "Оооо!!! Я сейчас!!!"
    # client "Еще чуть-чуть!!!"
    # client "Ааааа!!!"
    # client "Засунь себе свой палец в дырочку!!!"
    # client "Давай же!!!"
    # client "ААААААА!!!"
    # mt "?!"
    # mt "Кончил?"
    # mt "Этот никчемный неудачник в жизни не видел такой красивой женщины как Я."
    # mt "Неудивительно, что с теми сучками из эскорта у него не получалось!"
    # mt "!!!"
    # mt "Боже. Моника, ты серьезно сейчас?!"
    # mt "Ты гордишься тем, что какой-то мерзкий тип обкончался, глядя на тебя?!"
    # mt "Ты что, совсем с ума сошла?!"
    # mt "Фу!"
    # mt "..."
    # client "Ты самая лучшая девочка здесь, [monica_hotel_name]."
    # client "Мне очень понравилось."
    # m "..."
    # client "Здесь 700 долларов. Я обязательно приду к тебе еще раз, [monica_hotel_name]." 
    # mt "700 долларов?!"
    # mt "Я заработала 700 долларов, облизывая палец незнакомому мужчине!"
    # mt "..."
    # mt "Меньше всего хочется отдавать половину этой сучке на ресепшене..."
    # mt "Может, уйти и больше просто не приходить сюда?"
    # mt "Что она мне сделает?"
    # mt "С другой стороны, здесь я за вечер могу заработать такие большие деньги."
    # mt "А она меня больше не пустит в ресторан."
    # mt "Нет, мне не стоит пока терять эту возможность заработка."
    mt "Ich hoffe, es reicht ihm zu sehen, wenn ich mich selbst berühre..."
    mt "Besser wenn ich es mache, als er..."
    mt "Mit seinen dreckigen Fingern!"
    client "Oh!!! Ich komme!!!"
    client "Noch ein bisschen mehr!!!"
    client "Ahhhh!!!"
    client "Засунь себе свой палец в дырочку!!!"
    client "Komm schon!!!"
    client "AAAAA!!!"
    mt "?!"
    mt "Fertig?"
    mt "Dieser wertlose Loser hat noch nie eine so schöne Frau gesehen."
    mt "Es überrascht nicht, dass er bei den Escort Bitches keinen Erfolg hatte!"
    mt "!!!"
    mt "Oh Gott Monica, wirklich jetzt?!"
    mt "Bist du stolz, dass ein Irrer wegen dir gekommen ist?!"
    mt "Bist du jetzt total bescheuert?!"
    mt "Pah!"
    mt "..."
    client "Du bist das beste Mädchen hier, [monica_hotel_name]."
    client "Es hat mir wirklich gefallen."
    m "..."
    client "Hier sind 700 Dollar. Ich werde dich definitiv wieder besuchen, [monica_hotel_name]." 
    mt "700 Dollar ?!"
    mt "Ich habe 700 Dollar verdient, indem ich die Finger eines Fremden abgeleckt habe!"
    mt "..."
    mt "Am allerwenigsten möchte ich dieser Schlampe an der Rezeption die Hälfte davon gehen ..."
    mt "Vielleicht sollte ich gehen und nie wieder hier her kommen?"
    mt "Was wird sie mit mir machen?"
    mt "Andererseits kann ich hier am Abend sehr viel Geld verdienen."
    mt "Und sie wird mich nicht mehr ins Restaurant lassen."
    mt "Nein, ich sollte mir diese Verdienstmöglichkeit nicht entgehen lassen."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:294
translate german ep211_escort_scene1_5_4026cc9e:

    # m "Клиент заплатил 700 долларов."
    # reception "И остался доволен."
    # reception "Ты хорошо поработала ртом."
    # mt "!!!"
    # m "Откуда ты?.."
    # reception "Я все знаю..."
    # reception "Это моя работа!"
    # reception "Вот твои деньги."
    # reception "Завтра можешь приходить снова."
    # reception "На сегодня все."
    # reception "Клиенты не любят использованный товар."
    # mt "Вот сучка!"
    # mt "Откуда она знает, что я... Работала ртом?!"
    # mt "Она подглядывала?!"
    # mt "!!!"
    m "Der Kunde hat mir 700 Dollar bezahlt."
    reception "Und war erfreut."
    reception "Du hast gute Arbeit mit deinem Mund geleistet."
    mt "!!!"
    m "Wo kommst du her?.."
    reception "Ich weiß schon Bescheid..."
    reception "Das ist mein Job!"
    reception "Hier ist dein Geld."
    reception "Du kannst morgen wiederkommen."
    reception "Das ist alles für heute."
    reception "Die Kunden mögen keine benutzte Ware."
    mt "Was für eine Schlampe!"
    mt "Woher weiß sie, dass ich ... mit dem Mund gearbeitet habe ?!"
    mt "Hat sie uns beobachtet?"
    mt "!!!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:315
translate german ep211_escort_scene1_6_424a662d:

    # mt "Я пока не могу так рисковать!"
    # mt "Эта сучка меня не пустит больше в ресторан, если я не отдам ей 50 процентов."
    # mt "А мне не выгодно терять такой заработок."
    # mt "Но я обязательно потом что-нибудь придумаю: чтобы не делиться с ней!"
    # mt "..."
    mt "Ich kann nicht mehr so ein Risiko eingehen!"
    mt "Diese Schlampe wird mich nicht mehr ins Restaurant lassen, es sei denn, ich gebe ihr 50 Prozent."
    mt "Und ich kanne es mir nicht leisten, diese Art von Einkommen zu verlieren."
    mt "Ich lasse mir später definitiv was einfallen, aber das wird ich ihr nicht sagen!"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:328
translate german ep211_escort_scene1_7_1c313cdf:

    # mt "Я сегодня за вечер заработала 350 долларов."
    # mt "Неплохой заработок, учитывая мою временную ситуацию."
    # mt "Возможно, мне стоит пересилить себя и поработать здесь еще какое-то время."
    # mt "Быть может, у меня получится зарабатывать еще больше."
    # mt "Мне нужно будет прийти сюда завтра."
    # mt "..."
    # mt "Я ведь в любой момент смогу отказаться и уйти."
    mt "Ich habe heute Abend 350 Dollar gemacht."
    mt "Das ist viel Geld in meiner derzeitigen Situation."
    mt "Vielleicht sollte ich mich überwinden und noch einige Zeit hier arbeiten."
    mt "Vielleicht schaffe ich es noch mehr zu verdienen."
    mt "Ich muss morgen erstmal her kommen."
    mt "..."
    mt "Ich kann jederzeit ablehen und gehen."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:340
translate german ep211_escort_scene1_8_4ad016fe:

    # mt "Я никогда не смогу решиться на такое!"
    # mt "Я Моника Бакфетт, а не какая-то проститутка!"
    mt "Das kann mich nie dafür entscheiden!"
    mt "Ich bin Monica Buckfett und nicht irgendeine Prostituierte!"

translate german strings:

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:15
    old "Встреча с клиентом (сцена)."
    new "Treffen mit dem Klienten (Szene)."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:15
    old "Ждать клиента за столиком."
    new "Warte am Tisch auf einen Kunden."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:17
    old "Клиент в номере отеля."
    new "Kunde im Hotelzimmer."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:17
    old "Выезд к клиенту."
    new "Gehe zum Kunden."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:91
    old "Пойти на ресепшн к администратору."
    new "Gehe zum Empfangsbüro."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:124
    old "Пойти к клиенту. Он ждет у лифта."
    new "Gehe zum Kunden. Er wartet am Aufzug."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:236
    old "Нет, я не хочу этого делать!"
    new "Nein, das will ich bestimmt nicht!"

