# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:4
translate german e211_dialogues_revenge_quest1_826aeb2b:

    # m "Ну что, корнишон..."
    # m "Пришло время поговорить по душам."
    # fred "..."
    # m "Итак, что ты знаешь про то, что случилось со мной?"
    # m "Говори!"
    # fred "ММффхпп... Мэм... мфхппп"
    # fred "Я... Я ничего не знаю, Мэм... мфхппп..."
    # m "О, Фред, фред..."
    # m "Как жаль... Я знала, что ты не очень далекого ума и повторяла это в свое время..."
    # m "Но, все-таки я была уверена, что капля рассудка у тебя есть, потому я и держала тебя..."
    # m "Ведь ты знаешь, что я деловой человек..."
    # m "А деловые люди не задают лишних вопросов."
    # m "Я не собираюсь много раз повторять одно и то же."
    # m "И, очень жаль, что лимит отведенного тебе времени для ответов ты тратишь на всякие глупости."
    # fred "..."
    # m "Я назвала тебя корнишоном, помнишь за что?"
    # fred "..."
    # m "За твой маленький член, Фред."
    # fred "..."
    # m "Да, я вижу что твой отросток достаточно выделяется среди общей массы двуногих животных..."
    # m "Однако, я оценивала тебя как мужчину, Фред..."
    # m "Ты ведь понимаешь, что размер члена у мужчины измеряется не отсюда..." 
    # m "А отсюда..." 
    # fred "..."
    # m "Поэтому, несмотря ни на что, ты корнишон, Фред..."
    # m "И никогда не изменишься..."
    # m "Маленькая собачка до старости щенок..."
    # m "Но я не виню тебя..."
    # fred "..."
    # m "Однако, корнишоны бывают полезные... и никчемные..."
    # fred "..."
    # m "Ты оказался никчемным корнишоном, Фред..."
    # m "Я найду нужную информацию и без тебя."
    # m "Но, ты знаешь, несмотря на то что я сказала, твой член, все-таки, портит картину корнишона."
    # m "А ты знаешь, я люблю порядок."
    # m "Поэтому не обижайся... Ничего личного, просто порядок."
    # fred "НЕЕЕТ!!!"
    # fred "ММПППХХХФФФФ!!! Я ХПФМММ!"
    # fred "Я СКАЖУ! МХХХПФМММ!"
    # m "О, ты хочешь быть полезным корнишоном, Фред?"
    # m "Тогда я потерплю небольшой беспорядок и не стану отстреливать тебе член..."
    # fred "Миссис Бакфетт! Прошу!"
    # fred "Не делайте глупостей! Я все скажу!"
    # m "Хорошо, Фред! Но это зависит от того что ты скажешь мне!"
    # m "Итак! Откуда ты узнал про то что случилось со мной?!"
    # fred "От Стива, Вашего младшего партнера!"
    # fred "Я узнал про Вас от него!"
    # m "От Стива?"
    # fred "Да, Миссис Бакфетт! В тот день я заезжал к нему и он сообщил мне все."
    # m "Зачем ты заезжал к нему?!"
    # fred "..."
    # m "Говори, Фред!"
    # m "ИЛИ, КЛЯНУСЬ! Я ОТСТРЕЛЮ ТВОИ ЯЙЦА К ЧЕРТОВОЙ МАТЕРИ!!!"
    # fred "Я заезжал к нему, чтобы отчитаться..."
    # m "Отчитаться о чем?!"
    # fred "О Ваших делах, Мэм... О Ваших передвижениях и связях..."
    # m "ЧТО?! ТЫ ШПИОНИЛ ЗА МНОЙ?!"
    # m "ШПИОНИЛ ДЛЯ ЭТОГО СЛИЗНЯКА СТИВА?!"
    # fred "Да, Мэм... Но я не знал что с Вами случится такое..."
    # fred "Поверьте, я не имею никакого отношения к этому!"
    # m "Ладно, Фред. Я знала что ты мерзавец..."
    # m "И ничуть не удивлена тому что ты, ко всему прочему, еще и шпионил за мной..."
    # m "Итак, какая у Стива была цель?"
    # m "С какой целью он собирал информацию про меня?"
    # m "Он хотел лишить меня компании, чтобы завладеть ей?!"
    # fred "Мэм... Нет..."
    # m "А что тогда, Фред?!"
    # fred "Мэм... Он собирал информацию про Вас, чтобы..."
    # fred "Чтобы переспать с Вами, Мэм..."
    # m "Вот мерзкий слизняк!"
    # m "Этот мешок с дерьмом думает своим членом, вместо мозгов!"
    # m "Впрочем как и ты, Фред!"
    # m "Интересно, сколько еще подобных мерзавцев вынашивало такие планы в отношении меня..."
    # fred "Мэм... Если честно... То, по-моему, ВСЕ..."
    # fred "Все мужчины вокруг ищут способы переспать с Вами, Мэм..."
    # m "Заткнись, Фред!"
    # m "Итак, что Стив сказал тебе?!"
    # fred "Мистер Стив сказал мне что некие люди взяли управление компанией в свои руки..."
    # fred "Сказал что Вы лишились всего имущества что у Вас есть..."
    # fred "И своих счетов..."
    # m "Не удивлена, что ты использовал эти знания для таких же похотливых целей, как и тот мешок с дерьмом!"
    # m "Откуда он это узнал?! У каких людей?!"
    # m "С кем он связан?!"
    # fred "Мэм... Я не знаю про тех людей, с которыми связан Мистер Стив..."
    # m "Значит ты, Фред, все-таки, бесполезный корнишон..."
    # fred "НЕТ!! Миссис Бакфетт!!!"
    # fred "Я знаю про причину того, что случилось с Вами!"
    # fred "Мистер Стив сказал мне!"
    # m "Да?"
    # m "И, в чем-же причина?"
    # fred "Мистер Стив не сказал мне точно, но это что-то связанное со днем до того, как Вы приехали в полицию!"
    # m "И что же это было?!"
    # fred "Я не знаю, Миссис Бакфетт!"
    # fred "Это какое-то событие или Ваш поступок!"
    # fred "Миссис Бакфетт! Я Вам нужен!"
    # fred "Приведите сюда Мистера Стива и я помогу Вам узнать у него все что Вам нужно!"
    # fred "Устройте нам очную ставку и он не сможет отвертеться!"
    # m "Хм... А ты очень любишь свой член, Фред..."
    # m "Итак, откуда ты получал информацию обо мне, впоследствии?!"
    # m "Откуда ты знал, что Дик хотел меня видеть?"
    # m "КТО передавал тебя это?!"
    # fred "Виктория..."
    # m "КТО?!"
    # fred "Виктория, Миссис Бакфетт..."
    # m "Ты... ты знаешь эту сучку?!"
    # fred "Да, Миссис Бакфетт..."
    # m "Я еще расспрошу тебя про нее..."
    # m "Но сейчас у меня большое желание увидеть этот мешок с дерьмом, по имени Стив!"
    # m "Корнишончик, я скоро вернусь!"
    # m "Веди себя хорошо, обещаешь?!"
    # fred "Да, Миссис Бакфетт..."
    m "Nun, du Essiggürkchen..."
    m "Wir sollten mal ein ernstes Gespräch führen."
    fred "..."
    m "Also, was weißt du, was mir passiert ist?"
    m "Sprich!"
    fred "Mmmmmhh... Frau... Mmmpgh..."
    fred "Ich... ich weiß nichts... mmmphhg..."
    m "О, Фред, фред..."
    m "Was für eine Schande... Ich wusste schon immer, dass du nicht der Hellste bist, das habe ich dir sogar gesagt, damals."
    m "Aber ich dachte, rudimentäre Ansätze von Logik wären dann doch da, deshalb habe ich dich nicht gefeuert..."
    m "Wie du weißt, bin ich eine Geschäftsfrau..."
    m "Und ich mag Leute, die nur wichtige Fragen stellen."
    m "Ich frage dich also das Gleiche nicht immer wieder und wieder."
    m "Du solltest deine Antworten nicht mit so einem Schwachsinn verschwenden."
    fred "..."
    m "Weißt du, warum ich dich Essiggurke nenne?"
    fred "..."
    m "Wegen deinem kleinen Schwanz, Fred."
    fred "..."
    m "Ja, ein gewisser Teil deines Körpers ist recht eindrucksvoll, verglichen mit den meisten Tieren auf zwei Beinen..."
    m "Aber ich vewerte dich als Mann..."
    m "Und für einen Mann fängt der Schwanz nicht da an..." 
    m "Sondern da..." 
    fred "..."
    m "Und deswegen bist du ein Gürkchen, Fred..."
    m "Und du wirst dich auch nie ändern..."
    m "Ein kleiner Wurm. Bis du stirbst..."
    m "Aber ich verachte dich nicht..."
    fred "..."
    m "Gürkchen können immer noch nützlich sein... oder auch nicht."
    fred "..."
    m "DU hast dich als nutzlos erwiesen, Fred..."
    m "Ich finde das auch ohne dich raus."
    m "Aber weißt du, dein Schwanz passt noch nicht zu deinem Spitznamen."
    m "Und du weißt, wie sehr ich Ordnung liebe!"
    m "Also, das ist nicht persönlich... aber kommen wir zur Sache."
    fred "NEEEEEIIINN!!!"
    fred "MHHHMPHHPH!!! ICH WERDE... MMMHPMM!"
    fred "ES SAGEN! MHHHPMMH!"
    m "Oh, du willst ein nützliches Gürkchen sein, Fred?"
    m "Dann ertrage ich diese Unordnung und schieße dir nicht den Schwanz weg..."
    fred "Frau Buckfett, bitte!"
    fred "Nichts überstürzen! Ich sage alles!"
    m "Gut, Fred! Aber es hängt alles davon ab, was du mir sagst!"
    m "Also! Was weißt du darüber, was mir passiert ist?!"
    fred "Ich weiß etwas von Steve, ihrem Partner!"
    fred "Ich habe von ihm über ihr Schicksal erfahren!"
    m "Von Steve?"
    fred "Ja, Frau Buckfett! Ich habe ihn besucht und er hat mir alles erzählt."
    m "Warum hast du ihn besucht?"
    fred "..."
    m "Rede, Fred!"
    m "ODER ICH SCHWÖRE, ICH SCHIESSE DIR DIE EIER AB!!!"
    fred "Ich habe ihn wegen einem Bericht besucht..."
    m "Welcher Bericht?!"
    fred "Über ihr Geschäft... Wohin sie gegangen sind und welche Beziehungen sie haben."
    m "WAS?! DU HAST MICH AUSSPIONIERT?"
    m "FÜR DIESEN SACK, STEVE?!"
    fred "Ja... aber ich hatte keine Ahnung, dass sowas wie das, was war, ihnen hätte passieren können..."
    fred "Glauben Sie mir, ich hatte damit nichts am Hut!"
    m "Gut, Fred. Ich wusste immer, du bist ein Bastard..."
    m "Also überrascht mich die Spionage nicht wirklich..."
    m "Also, was war Steves Ziel?"
    m "Warum wollte er Infos über mich?"
    m "Wollte er meine Firma bestehlen?!"
    fred "Nein..."
    m "Dann was, Fred?"
    fred "... Er wollte Infos über..."
    fred "Wie man Sie ins Bett bekommt..."
    m "Was für ein schmieriger Wurm!"
    m "Dieses Stück Scheiße denkt auch nur mit seinem Schwanz!"
    m "Wie du, Fred!"
    m "Ich frage mich, wieviel Bastarde sowas noch geplant haben..."
    fred "Wenn ich... ehrlich sein ... darf, dann... Jeder..."
    fred "Jeder Mann in ihrem Dunstkreis hätte gerne Sex mit Ihnen..."
    m "Halt's Maul, Fred!"
    m "Also, was hat Steve gesagt?!"
    fred "Steve sagte, dass gewisse Leute ihre Firma übernommen haben..."
    fred "Dass alles, was Sie hatten, genommen wurde..."
    fred "Inklusive dem Bankkonto..."
    m "Es überrascht mich nicht, dass du die Info für perverse Zwecke ausgenutzt hast, so ein Scheißhaufen wie du bist!"
    m "Woher wusste er das? Von wem?!"
    m "Mit wem arbeitet er zusammen!?"
    fred "Ich weiß nicht, wie Steves Verbindungen sind..."
    m "Dann bist du doch ein nutzloses Gürkchen, Fred..."
    fred "NEIN!! Frau Buckfett!!!"
    fred "Ich kenne den Grund hinter ihrem Schicksal!"
    fred "Steve sagte es mir!"
    m "Ja?"
    m "Und was ist er?!"
    fred "Steve war nicht gaz klar, aber es war irgendwas wegen dem Tag vor ihrem Besuch bei der Polizei!"
    m "Und was war das?!"
    fred "Ich weiß es nicht, Frau Buckfett!"
    fred "Ein Ereignis oder eine bestimmte Handlung!"
    fred "Frau Buckfett, Sie brauchen mich noch!"
    fred "Bring Steve her und ich helfe Ihnen, rauszufinden, was wir brauchen!"
    fred "Befrage uns beide, dann kann er keine Ausflüchte machen!"
    m "Ich sehe, du magst deinen Schwanz noch immer, Fred..."
    m "Also, wo noch hast du Infos über mich erhalten?!"
    m "Woher wusstest du, dass Dick mich sehen will?"
    m "WER gab dir die Info?!"
    fred "Victoria..."
    m "WER?!?!"
    fred "Victoria, Frau Buckfett..."
    m "Du... Du kennst diese Bitch!?"
    fred "Ja, Frau Buckfett..."
    m "Ich frage dich später zu ihr..."
    m "Jetzt will ich unbedingt erstmal dieses Arschloch Steve treffen!"
    m "Ich bin bald wieder da, mein liebliches Gürkchen!"
    m "Du bist ein braver Junge, ja?"
    fred "Ja, Frau Buckfett..."

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:125
translate german e211_dialogues_revenge_quest1a_a1218199:

    # mt "Мне надо идти к этому мешку с дерьмом Стиву!"
    mt "Ich muss diesen Scheißkerl Steve sehen!"

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:131
translate german e211_dialogues_revenge_quest2_c361969d:

    # jane "Здравствуйте, Миссис Бакфетт!"
    # m "Здравствуй, Джейн!"
    # m "Стив у себя?"
    # jane "Да, Миссис Бакфетт, Мистер Стив у себя в кабинете..."
    # jane "Я предупрежу его, что..."
    # m "Не стоит, Джейн..."
    # m "Я сама сообщу ему о своем визите."
    # m "Пожалуйста, не беспокой нас..."
    # jane "Хорошо, Миссис Бакфетт..."
    jane "Hallo, Frau Buckfett!"
    m "Hallo Jane!"
    m "Ist Steve da?"
    jane "Ja, Frau Buckfett, Steve ist in seinem Büro."
    jane "Lassen Sie ihn mich vorwarnen..."
    m "Nicht nötig, Jane..."
    m "Ich kündige mich selbst an."
    m "Bitte störe uns nicht."
    jane "Na gut, Frau Buckfett..."

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:143
translate german e211_dialogues_revenge_quest3_87c0fb13:

    # steve "Моника!"
    # steve "Рад тебя видеть!"
    # steve "Ты пришла заключить новый контракт?"
    # m "Да, Стив... Я пришла заключить новый контракт..."
    # steve "Моника, извини..."
    # steve "Я уже потратил средства на кое-кого другую..."
    # steve "Приходи через неделю..."
    # steve "Мы заключим очень выгодный контракт!"
    # m "Стив... Я бы хотела заключить контракт сейчас, если ты не против..."
    # m "Более того, я не буду брать с тебя деньги..."
    # steve "Не будешь брать деньги?"
    # steve "Хмммм..."
    # steve "Знаешь, Моника..."
    # steve "Ко мне недавно заходила Джейн и..."
    # steve "И она высосала все что было в моем члене, Моника..."
    # steve "Он совсем сухой и я боюсь что..."
    # m "Не переживай, Стив..."
    # m "Если у тебя не получится, ты ведь не рискуешь деньгами..."
    # steve "Ты права, Моника! Это отличная сделка!"
    # steve "Залезай под стол... Ты знаешь что Джейн может зайти..."
    # steve "А у меня с ней скоро свадьба и, в общем, ты понимаешь..."
    # m "Я все понимаю, Стив..."
    # m "Никаких проблем, усаживайся поудобнее..."
    # steve "Моника, надо-же! Своим присутствием ты вливаешь в меня мужскую силу!"
    # steve "Можешь приступать!"
    # steve "Но помнишь, что по условиям контракте ты не берешь у меня денег за это?!"
    # m "Да, Стив..."
    # m "Я не стану брать у тебя деньги в этот раз..."
    # m "..."
    # m "Вместо этого, я возьму твои яйца..." 
    # steve "!!!"
    steve "Monica!"
    steve "Schön dich zu sehen!"
    steve "Bist du da, um einen neuen Vertrag zu unterzeichnen?"
    m "Ja, Steve, genau deswegen bin ich da..."
    steve "Sorry, Monica"
    steve "Ich habe schon alle Ressourcen an wen Anders ausgegeben..."
    steve "Komm in einer Woche wieder..."
    steve "Dann machen wir einen neuen, wunderbaren Deal!"
    m "Steve... Ich möchte den Deal jetzt gleich machen..."
    m "Ich nehme nicht mal dein Geld, wenn es dir nichts ausmacht..."
    steve "DU willst kein Geld dafür?"
    steve "Hmmmm ..."
    steve "Weißt du, Monica..."
    steve "Jane war bei mir, und..."
    steve "Hat alles aus meinem Schwanz rausgelutscht..."
    steve "Er ist total leer, also..."
    m "Keine Sorge, Steve..."
    m "Du verlierst kein Geld und auch sonst nichts..."
    steve "Ok, Monica. Was willst du dann?"
    steve "Geh unter den Tisch, Jane kann jeden Moment rein kommen..."
    steve "Und wir haben doch bald unsere Hochzeit, weißt du..."
    m "Verstanden, Steve, keine Sorge..."
    m "Ist ok, fühl dich ganz wohl..."
    steve "Wow, Monica! Deine Anwesenheit erregt mich!"
    steve "Fang an!"
    steve "Но помнишь, что по условиям контракте ты не берешь у меня денег за это?!"
    m "Ja, Steve..."
    m "Diesmal nehme ich kein Geld..."
    m "..."
    m "Ich nehme dafür deine Eier!" 
    steve "!!!"

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:121
    old "Идти к Стиву"
    new "Gehe zu Steve"

