# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:13
translate german ep211_dialogues5_shiny_hole_1_0c40f660:

    # ashley "[monica_pub_name], танцы на сегодня еще не закончились."
    # m "???"
    # ashley "Тебе еще нужно будет поработать..."
    # ashley "Для одного клиента."
    # m "В смысле? Что значит поработать для одного клиента?!"
    # ashley "У моего заведения возникли финансовые трудности, по оплате кредита..."
    # ashley "Знаешь-ли, не так-то просто содержать такое яркое место..."
    # ashley "Да еще и обеспечивать тебя работой!"
    # m "..."
    # ashley "Один из посетителей паба, Мистер Беркельбаух, работает в кредитном отделе банка."
    # ashley "Он готов помочь."
    # m "Я тут вообще причем?"
    # ashley "Этот банкир готов оказать помощь не просто так..."
    # ashley "Он требует приват танец для него."
    # m "Ваша рыжая королева трущоб легко с этим справится."
    # ashley "Перестань цепляться к Молли!"
    # ashley "Она тут самая лучшая из моих девочек!"
    # m "!!!"
    # ashley "Клиент требует приват с тобой."
    # m "Я не собираюсь в этом участвовать!"
    # m "Кому надо, тот пусть и танцует в привате для этого неудачника!"
    # ashley "В таком случае, [monica_pub_name], ты уволена!"
    # ashley "Мало того, что ты постоянно крадешь чаевые..."
    # ashley "Так еще и споришь со мной!"
    # ashley "Да, и передай Клэр, что она тоже уволена."
    # ashley "И виновата в этом будешь только ты!"
    # m "!!!"
    # m "Что?! Клэр здесь ни при чем!"
    # m "И вообще! Почему сразу увольнение?!"
    # m "Только из-за того, что я отказалась идти в приват с каким-то..."
    # m "Никчемным банкиром!"
    # ashley "Да!"
    # ashley "Я вынуждена буду уволить всех, если он откажется помогать!"
    # ashley "Поэтому или ты сейчас же сделаешь так, как я сказала..."
    # ashley "Или убирайся отсюда ко всем чертям!!!"
    # m "!!!"
    # ashley "[monica_pub_name], иных вариантов нет."
    # ashley "Я даже готова простить тебе то, что ты в очередной раз украла чаевые..."
    # ashley "И отменить штраф..."
    # ashley "Если ты сейчас пойдешь в приват с этим банкиром."
    # m "..."
    # ashley "Тебе нечего бояться."
    # ashley "Ты с ним будешь только вдвоем."
    # ashley "Я тоже буду присутствовать..."
    # ashley "Я должна убедиться, что все пройдет, как надо."
    # mt "Вот черт! И что мне теперь делать?"
    # mt "Она сказала, что уволит не только меня, но и Клэр..."
    # mt "..."
    # mt "С другой стороны..."
    # mt "Это же просто танец. Только не на сцене, а для одного клиента."
    # mt "Тем более, что Эшли готова меня не штрафовать, если я соглашусь..."
    # m "..."
    # m "Я станцую для него, но только в одежде!"
    # ashley "Нет, [monica_pub_name], так дело не пойдет."
    # ashley "Ты покажешь ему не только свою грудь..."
    # ashley "Но и свою голенькую попку." 
    # ashley "А я проконтролирую, чтобы твою попку было хорошо видно..."
    # m "Я не буду танцевать перед ним голая!!!"
    # m "За кого ты меня принимаешь?!"
    # ashley "Тогда выметайся отсюда, [monica_pub_name]!"
    # ashley "Мне надоело с тобой спорить!!!"
    # m "!!!"
    ashley "[monica_pub_name], du musst noch mehr tanzen."
    m "???"
    ashley "Du musst noch etwas mehr arbeiten."
    ashley "Noch ein Kunde."
    m "Was meinst du, noch ein Kunde?!"
    ashley "Mein Etablisement hat kleine, finanzielle Schwierigkeiten wegen einem Kredit..."
    ashley "Es ist nicht leicht, den Laden zu schmeißen."
    ashley "Und dich mit arbeit zu versorgen!"
    m "..."
    ashley "Einer der Geldgeber, Herr Berckelbauch, arbeitet in der Kreditabteilung der Bank."
    ashley "Er ist bereit uns zu helfen."
    m "Und was hat das mit mir zu tun?"
    ashley "Seine Hilfe ist nicht gratis..."
    ashley "Er will einen Privattanz."
    m "Deine rothaarige Slumqueen kann sich doch darum kümmern."
    ashley "Hör auf, Molly zu beleidigen."
    ashley "Sie ist meine Beste hier!"
    m "!!!"
    ashley "Der Kunde will einen Tanz von dir."
    m "Da mache ich nicht mit!"
    m "Ich muss nicht für einen Loser nur wegen dir tanzen!"
    ashley "In diesem Fall, [monica_pub_name], bist du gefeuert!"
    ashley "Es reicht ja nicht, dass du Trinkgelder klaust..."
    ashley "Jetzt diskutierst du auch noch mit mir!"
    ashley "Ja, und sag Claire, sie ist auch gefeuert."
    ashley "Das ist deine Schuld!"
    m "!!!"
    m "Was?! Was hat Claire damit zu tun?"
    m "Und warum solltest du uns beide feuern?"
    m "Nur weil ich für den Typ nicht tanzen will..."
    m "Nutzloser Banker!"
    ashley "Ja!"
    ashley "Ich bin gezwungen, jeden zu feuern, der nicht helfen will!"
    ashley "Also, mach, was ich sage, oder..."
    ashley "Verschwinde von hier!!!"
    m "!!!"
    ashley "[monica_pub_name], Du hast keine andere Wahl!"
    ashley "Ich bin sogar so gnädig und vergesse, dass du Trinkgelder gestohlen hast..."
    ashley "Und ebenso deine Strafe..."
    ashley "Wenn du einen Privattanz für den Banker machst."
    m "..."
    ashley "Keine Angst."
    ashley "Es sind nur ihr beide."
    ashley "Gut, ich werde in der Nähe sein."
    ashley "Ich muss mich versichern, dass alles nach Plan läuft."
    mt "Verdammt! Was soll ich machen?"
    mt "Sie sagte, sie würde auch Claire feuern..."
    mt "..."
    mt "Andererseits..."
    mt "Es ist ja nur ein Tanz. Nur für einen Kunden und keine Gruppe."
    mt "Ashley sagte auch, ich bin meine Strafe los, wenn ich es tue..."
    m "..."
    m "Ich mache es, aber nur bekleidet!"
    ashley "Nein, [monica_pub_name], das geht nicht."
    ashley "Du wirst ihm nicht nur deine Titten zeigen..."
    ashley "Sondern auch den nackten Arsch." 
    ashley "Und ich werde dafür sorgen, dass man ihn gut sehen kann."
    m "Ich werde nicht nackt vor ihm tanzen!!!"
    m "Wer denkst du, bin ich?"
    ashley "Dann verschwinde von hier, [monica_pub_name]!"
    ashley "Ich bin es leid, zu diskutieren!!!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:88
translate german ep211_dialogues5_shiny_hole_1_3bc438d3:

    # mt "Я не собираюсь раздеваться перед каким-то..."
    # mt "Никчемным неудачником!"
    # mt "Пусть Эшли сама вертит перед ним своим голым задом!"
    # m "!!!"
    # m "За кого ты меня принимаешь?!"
    # m "Я не пойду ни в какой приват!"
    # ashley "Тогда выметайся отсюда, [monica_pub_name]!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "Ich werde mich nicht vor irgendwem ausziehen..."
    mt "Wertlose Loser!"
    mt "Ashley kann ja ihren Arsch vor ihm wackeln!"
    m "!!!"
    m "Wer denkst du, bin ich?"
    m "Ich werde keinen Privattanz machen!"
    ashley "Dann verschwinde von hier, [monica_pub_name]!!!"
    m "Mit Vergnügen!"
    mt "Endlich muss ich nicht mehr in dieses Loch zurück!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:100
translate german ep211_dialogues5_shiny_hole_1_cb2a5eb3:

    # m "А сколько клиент мне за это заплатит?"
    # ashley "Нисколько!"
    # ashley "Ты будешь подарком от заведения."
    # m "!!!"
    # ashley "Но я готова простить тебе штраф за это."
    # mt "Дьявол!"
    # m "Я пойду в приват. Где он?"
    # ashley "Приходи в подсобку после танца."
    # ashley "Я с клиентом буду ждать тебя там."
    # mt "!!!"
    # mt "Как я это сделаю?!"
    # mt "..."
    # mt "Так... Соберись!"
    # mt "Ты [monica_pub_name], а не Моника Бакфетт."
    # mt "А [monica_pub_name] не леди, а обычная стриптизерша."
    # mt "Она не боится танцевать голой перед всякими неудачниками."
    m "Wieviel bekomme ich dafür?"
    ashley "Nichts!"
    ashley "Das ist ein Geschenk von unserem Lokal."
    m "!!!"
    ashley "Aber ich werde dieses Mal deine Strafe vergessen."
    mt "Diese Teufelin!"
    m "Ich mache es. Wo ist er?"
    ashley "Komm nach dem Tanz ins Hinterzimmer."
    ashley "Der Kunde und ich werden da warten."
    mt "!!!"
    mt "Wie soll ich das machen?!"
    mt "..."
    mt "Pah... Ruhig!"
    mt "Du bist [monica_pub_name],nicht Monica Buckfett."
    mt "Und [monica_pub_name] ist keine Lady, sondern eine einfach Stripperin..."
    mt "Sie hat keine Angst, vor Anderen nackt zu tanzen..."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:125
translate german ep211_dialogues5_shiny_hole_2_28bba5f9:

    # mt "Эта извращенка Эшли не упустит своего шанса..."
    # mt "Чтобы пялиться на меня!"
    # mt "Делая вид, что она контролирует меня."
    # banker "О, детка..."
    # banker "Наконец-то ты пришла, [monica_pub_name]."
    # mt "Очередной никчемный неудачник."
    # banker "Давай, крошка, лезь на стол."
    # banker "Не заставляй меня ждать... Время - деньги."
    # mt "Мерзкий тип!"
    # mt "Если он притронется ко мне - врежу ему по яйцам!"
    # ashley "Ну? Чего ты ждешь?!"
    # ashley "Ты слышала, что тебе нужно сделать?"
    # mt "!!!"
    mt "Diese Perverse, Ashley, lässt auch keine Gelegenheit aus..."
    mt "Mich zu nerven!"
    mt "Während sie versucht, mich zu kontrollieren."
    banker "Oh Baby..."
    banker "Endlich bist du da, [monica_pub_name]."
    mt "Noch so ein wertloser Loser."
    banker "Komm schon, Süße, auf den Tisch!"
    banker "Lass mich nicht warten. Zeit ist Geld."
    mt "Blödmann!"
    mt "Wenn er mich berührt, trete ich ihn in die Eier!"
    ashley "Und? Worauf wartest du?!"
    ashley "DU hast mich gehört."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:147
translate german ep211_dialogues5_shiny_hole_2_7392d7af:

    # banker "Детка, снимай с себя трусики."
    # banker "Хочу посмотреть, что ты там прячешь."
    # mt "Черт!"
    # ashley "Выполняй!"
    # mt "!!!"
    banker "Hey Baby, zieh das Höschen aus."
    banker "Ich will sehen, was du da versteckst."
    mt "Huch!"
    ashley "Komm schon, mach es!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:158
translate german ep211_dialogues5_shiny_hole_2_670931df:

    # mt "Я не собираюсь танцевать голой перед..."
    # mt "Перед каким-то никчемным неудачником!"
    # mt "Пусть Эшли сама вертит перед ним своим голым задом!"
    # m "!!!"
    # m "Нет!"
    # m "Я не буду этого делать!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "Ich werde nicht nackt vor ihm tanzen!!!"
    mt "Nutzloser Loser!"
    mt "Ashley kann ja ihren Arsch vor ihm wackeln!"
    m "!!!"
    m "Nein! Das ist das teuerste Kleid im ganzen Laden."
    m "Das werde ich nicht tun!"
    ashley "Dann verpiss dich!!!"
    m "Mit Vergnügen!"
    mt "Endlich muss ich nicht mehr in dieses Loch zurück!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:169
translate german ep211_dialogues5_shiny_hole_2_ddd6a857:

    # mt "Это делает [monica_pub_name], а не я."
    # mt "[monica_pub_name] просто потанцует и уйдет отсюда."
    # banker "Эй, крошка."
    # banker "Смотри, что у меня для тебя есть!"
    # banker "Пойдем ко мне!" 
    # mt "?!?!?!"
    # m "Эшли?!"
    # m "Мы так не договаривались!!!"
    # ashley "Тебе просто нужно спуститься вниз и посидеть у клиента на коленях."
    # ashley "Чего здесь такого?!"
    # ashley "Делай, что тебе говорят!"
    # mt "Какого черта тут происходит?!"
    # mt "Она решила подложить меня под этого мерзкого типа?!"
    # mt "Знала бы она с кем вообще имеет дело!!!"
    # mt "!!!"
    mt "[monica_pub_name] macht es, nicht ich."
    mt "[monica_pub_name] tanzt und geht dann einfach."
    banker "Hey Baby."
    banker "Schau mal, was ich für dich habe!"
    banker "Komm her!" 
    mt "?!?!?!"
    m "Ashley?!"
    m "Das haben wir nicht vereinbart!!!"
    ashley "Du musst nur auf dem Schoß des Kunden sitzen."
    ashley "Es gibt nichts zu fürchten!"
    ashley "Mach, was man dir sagt!"
    mt "Was zur Hölle geht hier vor sich?!"
    mt "Will sie mich unter diesen ekligen Typen legen?!"
    mt "Wenn sie nur wüsste, mit wem sie sich anlegt!!!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:191
translate german ep211_dialogues5_shiny_hole_2_6b54e0c8:

    # mt "Я не собираюсь этого делать!"
    # mt "Пусть он лапает Эшли своими грязными руками!"
    # m "!!!"
    # m "Нет!"
    # m "Я не буду этого делать!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "Das werde ich nicht tun!"
    mt "Besser, er berührt mich nicht mit seinen schmutzigen Händen!"
    m "!!!"
    m "Nein! Das ist das teuerste Kleid im ganzen Laden."
    m "Das werde ich nicht tun!"
    ashley "Dann verpiss dich!!!"
    m "Mit Vergnügen!"
    mt "Endlich muss ich nicht mehr in dieses Loch zurück!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:202
translate german ep211_dialogues5_shiny_hole_2_c186442e:

    # mt "Грязная извращенка!"
    # mt "Ненавижу ее!!!"
    # mt "!!!"
    # banker "Мммм, какая ты аппетитная, крошка..."
    # ashley "Ну что, Мистер Беркельбаух, Вы довольны?"
    # ashley "Вы помните номер кредитного договора, по которому надо дать отсрочку?"
    # banker "Эшли, знаешь что больше всего в мире мне не нравится?"
    # ashley "Что, Мистер Беркельбаух?"
    # banker "Больше всего в мире мне не нравится, когда меня обманывают."
    # ashley "Что это значит? На что Вы намекаете? В чем обман?"
    # banker "Эшли, помнишь какое было условие?"
    # ashley "Вы хотели увидеть самую красивую попку Shiny Hole..."
    # ashley "И за это..."
    # banker "Я не уверен что это самая красивая попка Shiny Hole."
    # banker "Возможно, ты обманываешь меня."
    # ashley "ЧТО?! Я???"
    # ashley "Я с самого начала говорила тебе... Вам..."
    # ashley "С самого начала говорила что у Молли задница лучше, чем у [monica_pub_name]!"
    # ashley "Но ты... то есть Вы..."
    # banker "Эшли, прекрати! Задница Молли мне уже надоела."
    # banker "Эта ваша королева Shiny Hole готова на все ради пары баксов на чай!"
    # ashley "В чем тогда дело?! Почему Вы обвиняете меня в нечестности?!"
    # banker "Я не уверен что у [monica_pub_name] лучшая задница, потому что я не могу сравнить их все."
    # banker "Я еще не все увидел."
    # banker "А, потому, я имею право сомневаться в том, что ты даешь мне то, что декларируешь."
    # ashley "Что я де... декл... Что это за слово?"
    # ashley "Послушайте, Мистер Беркельбаух, Вы наш постоянный клиент и Вы знаете, что Клэр не танцует приват."
    # ashley "Ее задницу не получится оценить. Она танцует не ради денег."
    # ashley "Я никак не могу надавить на нее. Если я буду настаивать, она просто уйдет отсюда!"
    # banker "Я вижу задницу Клэр через день! Пусть она в тоненьких трусиках, но я могу оценить ее из зала."
    # ashley "Но в чем тогда проблема? Это все что у нас есть!"
    # ashley "У нас больше нет никаких попок, чтобы сравнить между ними!"
    # ashley "Я честно выполнила то о чем мы договорились!"
    # banker "Нет, Эшли! Здесь, в Shiny Hole, есть еще одна попка, которую никто не видел!"
    # banker "И ее не оценить из зала, потому что она пока не танцует, а зря!"
    # ashley "Какая? Кто это? Почему я не знаю про нее?!"
    # ashley "Это Джо снова притащил какую-то шлюху?!"
    # ashley "Также как сделал это с [monica_pub_name]?"
    # mt "!!!"
    # banker "Нет, Эшли! Я говорю про твою попку!"
    # ashley "ЧТО?! Причем здесь моя задница, Мистер Беркельбаух?!"
    # banker "При том, Эшли, что я подозреваю что твоя попка самая лучшая в Shiny Hole!"
    # banker "И ты скрыла это от меня, тем самым обманув."
    # banker "А ты уже знаешь что я больше всего не люблю..."
    # ashley "Но... Но как можно сравнивать меня с..."
    # ashley "С [monica_pub_name]?"
    # banker "Почему нельзя? Я не видел всех попок Shiny Hole и я имею право сомневаться!"
    # ashley "И что же ты хочешь?!"
    # banker "Залезай на стол и покажи свою попку, а я сравню ее с этой!"
    # ashley "Вообще-то я замужем!"
    # ashley "Моя попка, она... Она только для Джо, моего мужа!"
    # banker "Я не собираюсь сейчас трахать тебя, Эшли!"
    # banker "Но учти, отказ от проверки значит что ты что-то скрываешь от меня!"
    # banker "Если ты не предоставишь доказательство того, что твоя попка хуже, чем у [monica_pub_name]..."
    # banker "Или, если вдруг эта твоя попка не окажется хуже, чем у нее, то..."
    # banker "То банк завтра же выставит требование о досрочном погашении всей вашей кредитной линии, Эшли!!!"
    # banker "Я не терплю, когда меня пытаются выставить дураком, подсунув второсортный материал!"
    # mt "ЧТО?!!"
    # ashley "!!!"
    # banker "Давай! Залезай сейчас же! Я жду!"
    # ashley "Ты мне что, не оставляешь выбора?! Ты знаешь что я вкладываю душу в этом место!"
    # ashley "Я не могу потерять его!"
    # banker "Это ты не оставляешь мне выбора, Эшли! Ты отказываешься предъявить доказательство!"
    # banker "Вертишься, юлишь..."
    # banker "Ведь, если твоя попка и правда хуже, то тебе нечего бояться, правда?"
    # ashley "!!!"
    # banker "Да, и смотри на меня! Личико влияет на оценку любой попки!"
    # banker "Исходя из специфики своей работы, я люблю все оценивать комплексно!"
    # ashley "!!!"
    # banker "Да, и скажи [monica_pub_name], чтобы она сняла свою маску."
    # banker "Я вижу ее личико каждый день, когда она обслуживает клиентов."
    # banker "Незачем скрывать его сейчас. Это помешает комплексной оценке!"
    # m "ЧТО?!"
    # ashley "Давай, снимай свою дурацкую маску, делай что он говорит!"
    # m "Но!.."
    # ashley "Давай, он и так знает кто ты на самом деле!"
    # m "Он знает кто Я???"
    # ashley "Да, он знает, что ты новенькая официантка! Давай снимай!"
    mt "Sondern lieber Ashley, diese Perverse!"
    mt "Ich hasse sie!"
    mt "!!!"
    banker "Hmmm... Du bist so heiß, Baby..."
    ashley "Also, Herr Berckelbauch, zufrieden?"
    ashley "Erinnern Sie sich an die Kreditvertragsnummer, die Sie verlängern sollen?"
    banker "Ashley, weißt du, was ich am Meisten hasse?"
    ashley "Was, Herr Berckelbauch?"
    banker "Ich hasse es am Meisten, wenn ich verarscht werde."
    ashley "Was meinen Sie? Wer verarscht Sie denn?"
    banker "Weißt du noch, was wir ausgemacht haben, Ashley?"
    ashley "Sie wollten den geilsten Arsch im Shiny Hole sehen."
    ashley "Und deshalb..."
    banker "Ich bin mir nicht sicher, ob das der geilste Arsch hier ist."
    banker "Vielleicht verarscht du mich."
    ashley "WAS?! ICH???"
    ashley "Ich sagte von Anfang an..."
    ashley "Dass Mollys Arsch besser ist als der von [monica_pub_name]!"
    ashley "Aber Sie..."
    banker "Stopp! Mollys Arsch langweilt mich."
    banker "Deine Queen hier macht für ein paar Mäuse alles!"
    ashley "Was stimmt dann nicht?! Warum beschuldigen Sie dann mich?!"
    banker "Ich bin nicht sicher, ob [monica_pub_name] den besten Arsch hat, weil ich sie nicht vergleichen konnte."
    banker "Ich habe sie nicht alle gesehen."
    banker "Weswegen ich das Recht habe, die Richtigkeit deiner Behauptung anzuzweifeln."
    ashley "Richtigkeit... Was soll damit sein?"
    ashley "Hören Sie, Herr Berckelbauch, Sie sind unser Geldgeber und wissen, dass Claire keinen Privattanz macht."
    ashley "Sie können ihren Arsch hier nicht sehen. Sie tanzt nicht für Geld."
    ashley "Ich kann sie nicht überzeugen. Sie ist weg, wenn ich sie zu sehr bedränge!"
    banker "Ich sehe ihren Arsch jeden Tag. Sie hat zwar knappe Höschen an, aber man kann ihn deutlich sehen."
    ashley "Wo ist dann das Problem?"
    ashley "Wir haben nicht noch mehr Ärsche!"
    ashley "Ich habe meinen Teil des Deals definitiv erfüllt!"
    banker "Nein, Ashley! Hier im Shiny Hole gibt es noch einen Arsch, den niemand gesehen hat."
    banker "Man sieht ihn sonst nie auf der Bühne."
    ashley "Wo? Wer? Warum kenne ich sie nicht?"
    ashley "Hat Joe eine andere Hure gebracht?"
    ashley "So wie er [monica_pub_name] brachte?"
    mt "!!!"
    banker "Nein Ashley! Ich rede von deinem Arsch!"
    ashley "WAS?! Was hat mein Arsch damit zu tun, Herr Berckelbauch?!"
    banker "Und ich denke, dein Arsch ist der Beste hier, Ashley!"
    banker "Du hast ihn vor mir versteckt und wolltest mich verarschen!"
    banker "Und das hasse ich am Meisten..."
    ashley "Aber... Wie soll man denn meinen vergleichen mit..."
    ashley "Mit dem von [monica_pub_name]?"
    banker "Warum nicht? Ich habe nicht alle Ärsche im Shiny Hole gesehen, also habe ich meine Zweifel!"
    ashley "Was willst du?!"
    banker "Steig auf den Tisch und zeig mir deinen Arsch, dann kann ich ihn mit ihrem vergleichen!"
    ashley "Ich bin vereiratet!"
    ashley "Mein Arsch ist... Nur für meinen Ehemann, Joe!"
    banker "Ich werde dich ja nicht ficken, Ashley!"
    banker "Aber denk dran, wenn du ablehnst, heißt das, du verbirgst was vor mir!"
    banker "Wenn du nicht beweisen kann, dass dein Arsch besser ist, als von[monica_pub_name]..."
    banker "Und wenn es sich zeigt, dass dein Arsch nicht schlechter ist..."
    banker "Dann wirst du umgehend eine Bescheinigung der Bank erhalten, bzgl. Der Auszahlung."
    banker "Ich mag es nicht, wenn wer versucht mich zu verarschen, indem er mir zweitklassige Ware unterjubelt."
    mt "WAS??!"
    ashley "!!!"
    banker "Komm schon! Auf den Tisch, ich warte!"
    ashley "Du lässt mir keine Wahl, hm? Du weißt, dass ich mit Herzblut an dem Pub hänge!"
    ashley "Ich darf es nicht verlieren!!"
    banker "Du bist die, die mir keine Wahl lässt, Ashley. Du verweigerst mir den Beweis!"
    banker "Jammerst rum..."
    banker "Denn wenn dein Arsch nicht schlechter ist, hast du ja nichts zu befürchten, oder?"
    ashley "!!!"
    banker "Schau mich an! Dein Gesicht zählt auch mit!"
    banker "In Anbetracht des Deals, will ich alle Optionen kennen!"
    ashley "!!!"
    banker "Und sage [monica_pub_name], ihre Maske abzunehmen."
    banker "Ich sehe ihr Gesicht jeden Tag, wenn sie im Service arbeitet."
    banker "Es gibt keinen Grund, es jetzt zu verbergen. Das lenkt mich nur ab!"
    m "WAS?!"
    ashley "Nimm deine dumme Maske ab, mach, was er will!"
    m "Aber...!"
    ashley "Komm schon, er weiß doch, wer du bist!"
    m "Wer weiß, wer ich bin?!"
    ashley "Ja, er weiß, dass du unsere Bedienung bist! Komm, zieh sie aus!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:323
translate german ep211_dialogues5_shiny_hole_2_68566620:

    # m "Я не собираюсь делать подобное! Это уже слишком!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    m "Das mache ich nicht! Das ist zuviel!"
    ashley "Dann verpiss dich!!!"
    m "Mit Vergnügen!"
    mt "Endlich muss ich nicht mehr in dieses Loch zurück!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:330
translate german ep211_dialogues5_shiny_hole_2_7801caeb:

    # ashley "Только попробуй сделать что-то, чтобы твоя задница понравилась ему меньше моей!"
    # ashley "Тогда ты не просто вылетишь отсюда..."
    # ashley "Но я снова повешу на тебя все украденные чаевые, которые до этого простила тебе!"
    # m "!!!"
    # ashley "Встань в лучшую позу, какую только можешь! Соблазни его!"
    # mt "Что я делаю... О БОЖЕ..."
    # mt "Я стоя голая... АБСОЛЮТНО ГОЛАЯ!!!"
    # mt "Без маски..."
    # mt "Стою так, чтобы моя попа понравилась больше, чем задница хозяйки дыры в трущобах!"
    # mt "И понравилась кому?!?!"
    # mt "Какому-то никчемному клерку из кредитного отдела занюханного банка!"
    # mt "Ведь он даже не представляет, на какую леди он сейчас смотрит!"
    # mt "Ему недостижим мой уровень, даже в его снах!"
    # ashley "Ну, убедился?!"
    # banker "Я пока размышляю..."
    # banker "Какое твое мнение, Эшли?"
    # ashley "В смысле какое мое мнение?"
    # banker "Как ты думаешь, чья задница хуже? Твоя или [monica_pub_name]?"
    # ashley "Мне обязательно это говорить?"
    # banker "Да, Эшли. Я хочу услышать это от тебя."
    # banker "Я хочу услышать твою уверенность... в своей правоте..."
    # ashley "!!!"
    # ashley "Я... Я считаю..."
    # ashley "Я считаю что моя задница хуже, чем у [monica_pub_name]."
    # banker "Хорошо, Эшли! Твоя уверенность убедила меня."
    # banker "Да и, по правде говоря, твоя задница действительно ни к черту в сравнению с попкой [monica_pub_name]!"
    # ashley "!!!"
    # banker "Я подпишу бумаги."
    # banker "Но, впрочем, она не настолько уж плоха для сцены."
    # banker "Я бы, как зритель, одобрил, если бы ты вышла на сцену в одном лишь фартуке."
    # banker "Хе-хе!"
    # ashley "Мистер Беркельбаух!"
    # ashley "Я уже говорила Вам, что для танцев у нас есть такие шлюхи, как [monica_pub_name]."
    # ashley "Я занимаюсь здесь управлением и ведением бизнеса!"
    # banker "Да, Эшли. Конечно!"
    # banker "Хе-хе!"
    # banker "Сообщи мне, если у тебя снова возникнут финансовые трудности!"
    # m "Мы закончили? Я могу идти?!"
    # banker "Не так быстро! Я все еще не кончил."
    # banker "Эшли, ты ведь знаешь, приватный танец должен длиться, пока клиент не будет удовлетворен..."
    # ashley "Да, Мистер Беркельбаух..."
    # ashley "[monica_pub_name], ты должна удовлетворить клиента!"
    # m "Что?! Я не знала о подобном правиле!"
    # m "С какой стати Я..."
    # ashley "Знание правил не помогает тебе придерживаться их!"
    # ashley "Не забывай почему ты оказалась здесь!"
    # ashley "Быстро иди и удовлетвори клиента!"
    # m "Но как... Как я удовлетворю его?!"
    # banker "Я бы хотел чтобы эта прекрасная попка потерлась о мой банковский член."
    # ashley "Ты слышала?! Быстро иди к нему!"
    # m "!!!"
    ashley "Du willst doch nur, dass du aus der Situation raus kommst!"
    ashley "Aber dann wirst du rausgeworfen..."
    ashley "Und musst alle Trinkgelder nachzahlen, die du unterschlagen hast!"
    m "!!!"
    ashley "Mach die beste Pose, verführe ihn!"
    mt "Was mache ich da... OH GOTT!..."
    mt "Ich stehe hier nackt... ABSOLUT NACKT!!!"
    mt "Ohne meine Maske..."
    mt "Und versuche, dass mein Arsch besser aussieht als der von Ashley!"
    mt "Aber für wen?!?!"
    mt "Für ein nutzloses Bankerlein von der Kreditabteilung!"
    mt "Er hat keine Ahnung, welche wirkliche Lady er gerade anschaut!"
    mt "Er ist nicht mal in der Nähe von meinem Niveau!"
    ashley "Und, zufrieden?"
    banker "Ich beurteile noch..."
    banker "Was denkst du, Ashley?"
    ashley "Was meinst du?"
    banker "Wessen Arsch ist besser? Deiner oder der von [monica_pub_name]?"
    ashley "Muss ich das wirklich sagen?"
    banker "Ja, Ashley. Ich will es von dir hören."
    banker "Ich will deine Einschätzung hören..."
    ashley "!!!"
    ashley "Ich... denke..."
    ashley "Ich denke, mein Arsch ist nicht so schön wie der von [monica_pub_name]."
    banker "Gut, Ashley. Du hast mich überzeugt."
    banker "Und, um ehrlich zu sein, dein Arsch ist wirklich viel schlechter als der von [monica_pub_name]!"
    ashley "!!!"
    banker "Ich werde die Papiere unterzeichnen."
    banker "Aber sie taugt wirklich für die Bühne."
    banker "Es wäre schön, sie nackt tanzen zu sehen."
    banker "Hehe!"
    ashley "Her Berckelbauch!"
    ashley "Ich sagte doch schon, dass wir für das Tanzen Huren wie [monica_pub_name] haben."
    ashley "Ich manage hier alles."
    banker "Ja, Ashley, klar!"
    banker "Hehe!"
    banker "Sag mir, wenn du wieder finanzielle Probleme hast."
    m "Sind wir dann fertig? Kann ich gehen?"
    banker "Nicht so schnell, ich bin noch nicht fertig!"
    banker "Ashley, du weißt, dass ein Privattanz so lange geht, bis der Kunde zufrieden ist."
    ashley "Ja, Herr Berckelbauch..."
    ashley "[monica_pub_name], du musst den Kunden befriedigen!"
    m "Was?! Die Regel habe ich ja noch nie nicht gehört!"
    m "Warum sollte ich..."
    ashley "Das Unwissen von Regeln schützt nicht vor Strafe!"
    ashley "Vergiss nicht, warum du hier bist!"
    ashley "Geh und befriedige den Kunden!"
    m "Aber wie... Was soll ich tun?!"
    banker "Ich will, dass dieser wunderschöne Arsch sich an meinem Bankerarsch reibt."
    ashley "Gehört? Geh schnell zu ihm!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:398
translate german ep211_dialogues5_shiny_hole_2_68566620_1:

    # m "Я не собираюсь делать подобное! Это уже слишком!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    m "Das mache ich nicht! Das ist zuviel!"
    ashley "Dann verpiss dich!!!"
    m "Mit Vergnügen!"
    mt "Endlich muss ich nicht mehr in dieses Loch zurück!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:404
translate german ep211_dialogues5_shiny_hole_2_efb8e9bd:

    # banker "Вот так... Да."
    # banker "Хорошая девочка."
    # mt "Фу!"
    # mt "Вот он извращенец!"
    # banker "Девочки, вы хорошо поработали."
    # banker "Эшли, жду тебя завтра у себя в банке."
    # banker "Обсудим детали кредитного договора."
    # banker "Пока, крошка." 
    # ashley "[monica_pub_name], только попробуй рассказать об этом кому-нибудь!"
    # ashley "Если хоть кто-то узнает!"
    # ashley "Я тебя придушу!!!"
    # mt "Жаль. Думаю, Джо было бы интересно услышать подробности."
    # ashley "Поняла меня, [monica_pub_name]?!"
    # m "Я не расскажу никому."
    # ashley "Все! Иди! Ты на сегодня свободна."
    banker "Ja... So."
    banker "Gutes Mädchen."
    mt "Pah!"
    mt "Er ist so ein Perverser!"
    banker "Du hast einen guten Job gemacht."
    banker "Ashley, ich warte morgen in der Bank auf dich."
    banker "Wir besprechen dann den Vertrag."
    banker "Tschüssikofski, Babes." 
    ashley "[monica_pub_name], Wage es nicht, das jemandem zu erzählen!"
    ashley "Wenn auch nur Einer davon erfährt!"
    ashley "Erwürge ich dich!!!"
    mt "Was für einen Schande. Joe hätte das sicher gerne erfahren."
    ashley "Verstanden, [monica_pub_name]?!"
    m "Я не расскажу никому."
    ashley "Das reicht! Geh! Du hast heute frei."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:521
translate german ep211_dialogues5_shiny_hole_3_d349bd92:

    # ashley "Кстати, [monica_pub_name]!"
    # ashley "Нашим клиентам очень понравился твой танец с Клэр."
    # ashley "Они теперь просят, чтобы ты станцевала с Молли!"
    # ashley "А как ты знаешь, желание наших клиентов - закон!"
    # m "!!!"
    # m "Танцевать с этой рыжей сучкой?!"
    # m "Да ни за что!!!"
    # ashley "Тебе придется."
    # ashley "И я уже говорила, чтобы вы прекратили эту свою битву сучек!"
    # ashley "Она здесь королева и ее попка для меня важнее, чем твоя!"
    # m "!!!"
    # ashley "Ты так и не помирилась с ней?!"
    # m "Еще чего!"
    # m "Я еще должна сама к ней подходить и мириться?!"
    # m "После того, как она меня подставила?"
    # ashley "Да!"
    # ashley "Тебе надо попросить у Молли прощения!"
    # ashley "Вам придется в следующий раз вместе танцевать на сцене!"
    # ashley "И мне не надо, чтобы вы поубивали друг друга там!"
    # ashley "Наши клиенты должны остаться довольны."
    # ashley "Они щедро платят за танцы..."
    # ashley "И выручка паба в эти дни значительно увеличивается."
    # ashley "Так что никаких отговорок я слышать не буду!!!"
    # mt "Черт!"
    # mt "Долбанная Молли!"
    # mt "!!!"
    ashley "Anbei, [monica_pub_name]!"
    ashley "Unsere Gäste mochten den Tanz mit Claire sehr."
    ashley "Sie wollen dich nun mit Molly sehen!"
    ashley "Und was unsere Gäste sagen, ist Gesetz."
    m "!!!"
    m "Mit dieser Rotschopfschlampe tanzen?"
    m "Niemals!!!"
    ashley "Du musst!"
    ashley "Und hör endlich mit diesem Zickenkrieg auf."
    ashley "Sie ist hier die Königin und ihr Arsch ist wichtiger als deiner!"
    m "!!!"
    ashley "Du verträgst dich immer noch nicht mit ihr?"
    m "Was denn noch!"
    m "Muss ich mich darum kümmern?"
    m "Nachdem es eingerichtet ist?"
    ashley "Ja!"
    ashley "Du musst dich bei ihr entschuldigen!"
    ashley "Du musst nächstes Mal mit ihr tanzen!"
    ashley "Und hört auf zu streiten!"
    ashley "Unsere Kunden sollen zufrieden sein."
    ashley "Sie zahlen hunderte Dollar..."
    ashley "Der Umsatz des Pubs wird sich erhöhen."
    ashley "Also will ich nichts hören!"
    mt "Huch!"
    mt "Verdammte Molly!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:553
translate german ep211_dialogues5_shiny_hole_4_f4c080a6:

    # mt "Ненавижу эту сучку!!!"
    # mt "Теперь я еще должна и просить у нее прощения!"
    # mt "!!!"
    # mt "Я не буду этого делать!"
    # mt "Возможно, я просто попробую заговорить с ней."
    # mt "..."
    mt "Ich hasse sie!"
    mt "Jetzt muss ich mich bei ihr entschuldigen!"
    mt "!!!"
    mt "Das werde ich nicht tun!"
    mt "Vielleicht rede ich mal mit ihr."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:565
translate german ep211_dialogues5_shiny_hole_4_56ccee50:

    # mt "Нет!!!"
    # mt "Я не буду разговаривать с этой сучкой!"
    # mt "Мне плевать, что там Эшли говорит!"
    # mt "Ей надо, пусть сама с ней и танцует!"
    mt "Nein!!!"
    mt "Ich will aber nicht mit dieser Bitch reden!"
    mt "Mir egal, was Ashley sagt!"
    mt "Sie kann mit sich selbst tanzen!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:571
translate german ep211_dialogues5_shiny_hole_4_9f0a0a5c:

    # molly "!!!"
    molly "!!!"

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:83
    old "Пойти в приват с клиентом."
    new "Mach einen Privattanz für einen Kunden."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:83
    old "Не делать этого! (увольнение с паба)"
    new "Mache es nicht! (Du fliegst aus dem Pub raus)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:117
    old "Идти в подсобку барменов и станцевать приват."
    new "Gehe in das Separée und mach einen Privattanz."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:140
    old "Залезть на стол и танцевать."
    new "Geh auf den Tisch und tanze."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:153
    old "Снять трусики."
    new "Zieh dein Höschen aus."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:186
    old "Сесть на колени к банкиру."
    new "Setz dich auf den Schoß des Bankers."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:186
    old "Не делать этого! (увольнение из паба)"
    new "Mache es nicht! (Du fliegst aus dem Pub raus)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:319
    old "Снять маску"
    new "Nimm deine Maske ab."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:394
    old "Тереться о член Мистера Беркельбауха..."
    new "Reibe dich an Herrn Berckelbauchs Schwanz..."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:560
    old "Заговорить с Молли (в следующем обновлении)"
    new "Rede mit Molly (in kommenden Updates)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:560
    old "Ни за что!"
    new "Auf keinen Fall!"

