# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:17
translate german ep211_dialogues2_public_event_1_2b67fa28:

    # m "Биф..."
    # m "Я хотела узнать у тебя..."
    # m "Есть-ли еще работа?"
    # m "Мне нужны деньги..."
    # biff "Папочка доволен тем, как цыпочка провела презентацию."
    # biff "У тебя неплохо получается притворятся Моникой Бакфетт."
    # biff "Совсем скоро тебе придется сделать это еще раз..."
    # m "Я больше не собираюсь проводить никакие глупые презентации!"
    # biff "Во-первых, кукла, здесь я решаю, чем ты будешь заниматься!"
    # biff "Я здесь Босс!"
    # mt "Ненавижу эту сволочь!!!"
    # biff "Во-вторых, если не будешь меня слушаться..."
    # biff "Будешь ходить в той юбке с презентации и собирать отчеты у сотрудников!"
    # biff "Я и так собираюсь скоро заставить тебя делать это."
    # mt "!!!"
    # mt "Ни за что!"
    # biff "Но ты склоняешь меня к тому, чтобы сделать это прямо сейчас!"
    # biff "Понятно тебе, кукла?!"
    # m "..." 
    # biff "А теперь к делу..."
    # biff "Да, работа есть. Завтра ты поедешь со мной..."
    # m "???"
    # m "Куда?"
    # biff "У одного из наших будущих инвесторов завтра торжественный фуршет..."
    # biff "В честь дня рождения его компании."
    # biff "Мы приглашены на это торжественное мероприятие."
    # biff "На вечере будет много влиятельных людей из индустрии моды."
    # biff "А также будет присутствовать пресса."
    # m "..."
    # biff "Все, что от тебя требуется..."
    # biff "Пообщаться с репортерами от лица Моники Бакфетт."
    # biff "Тебе же не в первый раз придется притворяться ею."
    # biff "Так что думаю, ты справишься..."
    # biff "И не наговоришь никаких глупостей."
    # biff "Иначе я тебя вышвырну с работы обратно на улицу."
    # biff "Будешь обслуживать прохожих за 20 баксов."
    # biff "Ты же понимаешь, что мне ничего не стоит сделать это?"
    # biff "Ты мне итак слишком дорого обходишься, кукла двадцатидолларовая..."
    # m "!!!" 
    # biff "Чего ты так смотришь? Не согласна со мной?"
    # biff "Ты, смотрю, уже забыла, что я тебя с улицы сюда взял?"
    # biff "Сколько ты там зарабатывала за день, отсасывая у местных бомжей?"
    # biff "50 баксов? Или 100?"
    # biff "Пять бомжей в день и сотка баксов в кармане?"
    # biff "Аха-ха-ха!!!"
    # m "!!!"
    # biff "Я тебе плачу 5000 баксов за одну фотосессию!!!"
    # biff "Это немыслимые деньги для такой как ты!"
    # biff "А ты, шлюха неблагодарная, при этом еще пытаешься со мной спорить!"
    # biff "И не выполняешь свою работу!"
    m "Biff..."
    m "Ich wollte von dir wissen, ob..."
    m "Gibt es noch mehr Arbeit?"
    m "Ich brauche Geld!"
    biff "Daddy ist mit der Art, wie das Mädchen die Präsentation gemacht hat, zufrieden."
    biff "Du bist gut darin, vorzugeben, Monica Buckfett zu sein."
    biff "Das musst du bald wieder tun..."
    m "Ich werde nicht weiterhin dumme Präsentationen machen!"
    biff "Also Puppe, hier entscheide immer noch ich, was gemacht wird!"
    biff "Hier bin ich der Chef!"
    mt "Ich hasse diesen Bastard!!!"
    biff "Weiter, wenn du mir nicht gehorchst..."
    biff "Dann trägst du den Rock der Präsentation, wenn du die Berichte einsammelst!"
    biff "Ich werde dich schon bald dazu bringen."
    mt "!!!"
    mt "Auf keinen Fall!"
    biff "Aber jetzt zwingst du mich, es bereits zu tun!"
    biff "Verstanden, Puppe?!"
    m "..." 
    biff "Zum Punkt..."
    biff "Ja, es gibt einen Job. Morgen kommst du mit mir..."
    m "???"
    m "Wohin?"
    biff "Einer unserer zukünftigen Investoren hat morgen einen förmlichen Empfang..."
    biff "Zur Geburtstagfeier seines Unternehmens."
    biff "Wir sind zu diesem Galaevent eingeladen."
    biff "Am Abend sind viele einflussreiche Leute aus der Modebranche da."
    biff "Ebenso wie die Presse."
    m "..."
    biff "Alles, was du tun musst, ist..."
    biff "Sprich mit den Reportern und tu so, als wärst du Monica Buckfett."
    biff "Es ist ja nicht das erste Mal, dass du das vorgeben musst."
    biff "Also denke ich, das schaffst du schon..."
    biff "Und erzähle keinen Unsinn."
    biff "Sonst werfe ich dich morgen raus."
    biff "Du wirst dann Passanten für 20 $ beglücken."
    biff "Verstehst du, dass mir das nichts ausmacht?"
    biff "Du bist zu teuer für mich, eine 20 Dollar Puppe..."
    m "!!!" 
    biff "Warum schaust du so? Stimmst du mir nicht zu?"
    biff "Du hast wohl vergessen, dass ich dich von der Straße geholt habe."
    biff "Wieviel hast du da am Tag verdient, als du die obdachlosen Leute gelutscht hast?"
    biff "50 Mäuse? Oder 100?"
    biff "Fünf Obdachlose am Tag und 100 Kröten in der Tasche?"
    biff "Ah-ha-ha!!!"
    m "!!!"
    biff "Ich zahle dir 5.000 Mäuse für ein Fotoshooting!!!"
    biff "Das ist unvorstellbar viel, für jemanden wie dich!"
    biff "Und du, du unfankbare Hure, versuchst immer noch mit mir zu verhandeln?"
    biff "Und deinen Job nicht zu machen?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:73
translate german ep211_dialogues2_public_event_1_0138fb27:

    # m "Неправда, Биф!"
    # m "Я хорошо выполняю свою работу!"
    # biff "Да ты что?!"
    # biff "Почему же тогда еще ни один из инвесторов не дал свой ответ?!"
    # m "!!!"
    # biff "Ты думала, я пошутил тогда?!"
    # biff "Я жду результатов! Ты вообще что-нибудь для этого сделала?"
    # m "..."
    # biff "Это твоя забота, цыпочка. Иначе..."
    # biff "..."
    # biff "Ты сама должна понимать, что это в твоих интересах."
    # m "..."
    m "Das ist nicht wahr, Biff!"
    m "Ich mache meinen Job gut!"
    biff "Was machst du denn?!"
    biff "Warum hat dann noch kein einziger Investor geantwortet?!"
    m "!!!"
    biff "Denkst du, das war ein Witz?!"
    biff "Ich will Ergebnisse sehen! Hast du überhaupt schon was getan?"
    m "..."
    biff "Das ist deine einzige Aufgabe, Mädchen. Sonst..."
    biff "..."
    biff "Du musst verstehen, dass das in deinem Interesse ist..."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:89
translate german ep211_dialogues2_public_event_1_caaaed87:

    # m "Биф, но..."
    # m "Как я это сделаю?"
    # biff "Мне все равно, как цыпочка будет с ними договариваться."
    # biff "Это проблемы цыпочки. Папочке нужен результат!"
    # mt "Вот мразь!"
    # mt "!!!"
    # biff "И нечего так смотреть на меня!"
    # biff "Ты здесь никто! Какая-то грязная шлюха с улицы..."
    # biff "Еще пытаешься свои условия мне диктовать!"
    # m "..."
    # biff "В общем, кукла, ты испортила мне настроение."
    # biff "Теперь ты должна это исправить. Что ты можешь мне предложить?"
    # m "После всего, что ты мне тут наговорил!.."
    # m "Я еще должна поднимать тебе настроение?!"
    # biff "Да. Хорошие цыпочки именно так и поступают..."
    # m "!!!"
    # biff "Скажи мне, ты хорошая цыпочка?"
    # m "..."
    m "Aber Biff..."
    m "Wie soll ich das machen?"
    biff "Mir ist egal, wie du mit ihnen verhandelst."
    biff "Das ist dein Problem. Daddy will Ergebnisse!"
    mt "Was für ein Penner."
    mt "!!!"
    biff "Es gibt keinen Grund, mich so anzuschauen!"
    biff "Du bist ein Niemand hier! Eine dreckige Straßenhure..."
    biff "Die immer noch verucht, mir ihre Bedingungen aufzuschwatzen!"
    m "..."
    biff "Wie auch immer Puppe, du hast meine Laune ruiniert."
    biff "Jetzt musst du sie wieder aufbessern. Was kannst du mir anbieten?"
    m "Nach allem, was du mir gesagt hast!..."
    m "Was muss ich machen, dass du dich besser fühlst?!"
    biff "Ja. Gute Mädchen machen das..."
    m "!!!"
    biff "Sag mir, bist du ein gutes Mädchen?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:114
translate german ep211_dialogues2_public_event_1_e8e86b30:

    # m "Я не тебе не кукла и не шлюха!"
    # m "И не цыпочка!!!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не сделаешь то, что Я тебе говорю!"
    # mt "Да пошел ты!"
    # mt "Я найду другой способ зарабатывать деньги!"
    m "Ich bin nicht dein Idiot oder deine Hure!"
    m "Und ich kein CHICK!!!"
    biff "Du wirst nie wieder einen Job bekommen..."
    biff "Bis du machst, was ich sage!"
    mt "Aha."
    mt "Ich finde einen anderen Weg, Geld zu verdienen!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:123
translate german ep211_dialogues2_public_event_1_15601f85:

    # mt "Безмоглый кретин!"
    # mt "!!!"
    # m "Я хорошая цыпочка."
    # biff "Чем хорошая цыпочка будет поднимать настроение папочке?"
    # mt "Ненавижу его!"
    # biff "Я жду тебя завтра, цыпочка."
    # m "..."
    mt "Ein hilfloses Arschloch!"
    mt "!!!"
    m "Ich bin ein gutes Chick."
    biff "Was wird das gute Mädchen machen, um Daddy zu erfreuen?"
    mt "Ich hasse ihn!"
    biff "Ich warte morgen auf dich, Mädchen."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:136
translate german ep211_dialogues2_public_event_2_5cea6789:

    # m "Биф..."
    # m "А что насчет работы?"
    # biff "Я же сказал, что завтра будешь работать."
    # m "..."
    # biff "Приходи завтра вечером, кукла."
    # mt "Я тебе не кукла, придурок!"
    m "Biff..."
    m "Was ist mir der Arbeit?"
    biff "Ich sagte, dass du morgen arbeiten wirst."
    m "..."
    biff "Komm morgen Abend, Puppe."
    mt "Ich bin nicht dein Idiot, Trottel!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:147
translate german ep211_dialogues2_public_event_3_531eeb4a:

    # m "Биф..."
    # biff "А, цыпочка пришла!"
    # biff "Иди переодевайся."
    # biff "И поторопись! Нам уже пора выезжать."
    m "Biff..."
    biff "Ah, das Chick ist da."
    biff "Zieh dich um."
    biff "Und beeil dich! Wir müssen los."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:157
translate german ep211_dialogues2_public_event_4_0b3944e8:

    # mt "Мне нужно пойти в фотостудию."
    # mt "Биф сказал, что мне надо поторопиться."
    mt "Ich muss in's Fotostudio."
    mt "Biff sagte, ich muss mich beeilen."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:163
translate german ep211_dialogues2_public_event_5_9f059684:

    # mt "Этот фотограф-извращенец наверняка знает, какое платье мне подготовили."
    # alex_photograph "Миссис Бакфетт! Великолепно выглядите!"
    # m "Как и всегда."
    # m "Алекс, мне нужно платье для мероприятия..."
    # alex_photograph "Да, Миссис Бакфетт. Оно в гримерной комнате."
    mt "Dieser perverse Fotograf weiß vielleicht, welches Kleid ich tragen soll."
    alex_photograph "Frau Buckfett! Sie sehen toll aus!"
    m "Wie immer."
    m "Alex, ich brauche ein Kleid für das Event..."
    alex_photograph "Ja, Frau Buckfett. Es ist in der Umkleide."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:172
translate german ep211_dialogues2_public_event_5_b7852eba:

    # alex_photograph "О! Миссис Бакфетт!"
    # alex_photograph "!!!"
    # m "Алекс, как я выгляжу?"
    # alex_photograph "Вы восхитительны!!!"
    # alex_photograph "У меня просто нет слов!"
    # alex_photograph "!!!"
    # m "Тебе это платье не кажется слишком откровенным?"
    # m "Особенно в зоне декольте?"
    # alex_photograph "Нет, конечно! Оно идеально подчеркивает всю Вашу красоту."
    # mt "Хм..."
    # mt "Действительно."
    # mt "У меня великолепная фигура. Пусть все смотрят и завидуют."
    # mt "Далеко не каждая женщина сможет надеть такое платье."
    # mt "А я могу. Ведь я самая красивая женщина в этом городе."
    # mt "Вернее, в стране!"
    # mt "Наконец-то, у меня новое платье."
    # mt "Оно, конечно, не такое дорогое, как мне хотелось бы..."
    # mt "И достаточно откровенное."
    # mt "Но оно мне нравится..."
    # mt "Оставлю его себе."
    alex_photograph "Oh! Frau Buckfett!"
    alex_photograph "!!!"
    m "Alex, wie sehe ich aus?"
    alex_photograph "Großartig!!!"
    alex_photograph "Mir fehlen dir Worte!"
    alex_photograph "!!!"
    m "Denkst du nicht, dass dieses Kleid zu freizügig ist?"
    m "Besonders in diesem Bereich?"
    alex_photograph "Nein, natürlich nicht! Es betont wunderbar ihre Schönheit."
    mt "Hmm..."
    mt "Wirklich."
    mt "Ich habe eine tolle Figur. Jeder soll schauen und staunen."
    mt "Nicht jede Frau kann so ein Kleid tragen."
    mt "Ich schon. Ich bin die schönste Frau der Stadt."
    mt "Oder eher, des Landes!"
    mt "Endlich habe ich ein neues Kleid."
    mt "Es ist zwar nicht so teuer, wie mir das gefallen würde, aber..."
    mt "Eher ziemlich billig."
    mt "Aber ich mag es..."
    mt "Ich werde es behalten."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:198
translate german ep211_dialogues2_public_event_6_cf5f4df7:

    # biff "Цыпочка, выглядишь, как настоящая Моника Бакфетт!"
    # biff "Хорошо, что у тебя совсем нет мозгов..."
    # biff "И ты не можешь этим воспользоваться. Аха-ха!"
    # m "..." 
    # biff "Так. Я не понял, а почему ты надела трусики?"
    # biff "Папочка тебе запретил носить трусики!"
    # m "..."
    # m "Биф, это платье слишком откровенное."
    # m "Миссис Бакфетт никогда не пошла бы в таком платье на публичное мероприятие..."
    # biff "Можно подумать, ты знаешь о том, что сделала бы сучка Бакфетт. Аха-ха!"
    # mt "Идиот!!!"
    # mt "!!!"
    # m "Биф, там будет много людей и пресса."
    # m "..."
    # biff "Ну и что?"
    # m "В этом платье видно, если я буду без трусиков..."
    # m "Всем будет видно мою... Мою... Ну ты понял."
    # biff "И что ты предлагаешь?"
    # m "Можно я не буду снимать эти трусики?"
    # biff "Папочка разрешит оставить трусики только хорошей цыпочке."
    # m "..."
    biff "Mädchen, du siehst wirklich wie Monica Buckfett aus!"
    biff "Gut, dass du kein Hirn hast..."
    biff "Das du benutzen könntest. Haha!"
    m "..." 
    biff "OK, aber ich weiß nicht, warum du Höschen an hast."
    biff "Daddy hat es dir verboten!"
    m "..."
    m "Biff, das Kleid ist sonst zu freizügig."
    m "Frau Buckfett würde so ein Kleid niemals zu einem öffentlichen Event tragen..."
    biff "Du denkst, dass du weißt, was die Schlampe Buckfett machen würde? Haha!"
    mt "Idiot!!!"
    mt "!!!"
    m "Biff, da sind viele Leute und die Presse."
    m "..."
    biff "Und?"
    m "Man sieht in diesem Kleid, ob ich Höschen trage oder nicht..."
    m "Jeder wird meine... meine... Du weißt schon was, sehen."
    biff "Und was schlägst du vor?"
    m "Kann ich das Höschen nicht ausziehen?"
    biff "Daddy gibt Höschen nur seinen guten Mädchen."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:223
translate german ep211_dialogues2_public_event_6_45e8f8c6:

    # mt "Ненавижу этого придурка!"
    # mt "!!!"
    # m "Я хорошая цыпочка."
    # biff "Ну ладно. Можешь не снимать трусики..."
    # biff "Но если ты будешь плохой цыпочкой..."
    # biff "Например, не будешь слушаться папочку."
    # biff "Или недостаточно будешь стараться быть Моникой Бакфетт."
    # biff "Или... Или поставишь пятно на этом безумно дорогом платье."
    # biff "Тогда я сразу же заставлю тебя снять эти трусики!"
    # mt "!!!"
    # biff "Будешь хорошей цыпочкой - папочка будет доволен."
    # m "..."
    mt "Ich hasse diesen Pimmel!"
    mt "!!!"
    m "Ich bin ein gutes Chick."
    biff "Ok. Du musst dein Höschen nicht ausziehen..."
    biff "Aber wenn du ein böses Mädchen bist..."
    biff "Wenn du zum Beispiel Daddy nicht gehorchst."
    biff "Oder nicht hart genug versuchst, Monica Buckfett zu sein."
    biff "Oder... Oder dieses unfassbar teure Kleid versaust."
    biff "Dann zwinge ich dich sofort dazu, das Höschen auszuzuiehen!"
    mt "!!!"
    biff "Wenn du ein braves Mädchen bist - dann wird Daddy zufrieden sein."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:242
translate german ep211_dialogues2_public_event_7_1706963f:

    # mt "В этот вечер я буду наслаждаться своей настоящей жизнью."
    # mt "Наконец-то вкусно поем приличной еды и выпью дорогого вина..."
    # mt "А вокруг меня будут крутиться журналисты и мои поклонники..."
    # mt "Черт! Я заслужила возможность побыть собой настоящей!"
    # biff "Цыпочка, ты помнишь о том, что ты должна быть хорошей..."
    # biff "И не расстраивать папочку?"
    # biff "Сейчас цыпочка пойдет и пообщается с гостями."
    # biff "Тебе нужно открывать свой рот и говорить только правильные вещи."
    # biff "Для этого цыпочке не обязательно уметь разговаривать."
    # m "???"
    # biff "Что ты на меня так смотришь?"
    # biff "Я знаю, что у тебя нет мозгов."
    # biff "Поэтому когда не знаешь, что сказать - молчи."
    # biff "Когда ты молчишь, ты больше похожа на Монику Бакфетт."
    # m "..."
    # biff "Все, иди. Папочка будет за тобой присматривать."
    # biff "Представь, что ты не двадцатидолларовая шлюха..."
    # biff "Какой и являешься на самом деле. Ты - Моника Бакфетт."
    # mt "Пусть этот болван говорит, что хочет."
    # mt "Я буду наслаждаться и ничего не сможет испортить мне настроение."
    mt "Ich werde diesen Abend genießen."
    mt "Endlich kann ich gutes Essen essen und teuren Wein trinken..."
    mt "Ich werde von Journalisten und meinen Fans umgeben sein..."
    mt "Scheiße! Ich muss so tun als wäre ich ich!"
    biff "Mädchen, denk dran, dass du gut sein musst..."
    biff "Und ärgere Daddy nicht."
    biff "Jetzt geh', und rede mit den Gästen."
    biff "Sag nur die richtigen Sachen, wenn du sprichst."
    biff "Sonst sag einfach nichts."
    m "???"
    biff "Warum schaust du mich so an?"
    biff "Ich weiß, dass du kei Hirn hast."
    biff "Daher, sei still, wenn du nicht weißt, was du sagen sollst."
    biff "Du siehst eher nach Monica Buckfett aus, wenn du nichts sagst."
    m "..."
    biff "Gut, geh jetzt. Daddy beobachtet dich."
    biff "Stell dir einfach vor, dass du keine 20 $ Hure bist..."
    biff "Welche du ja bist. Und Monica Buckfett."
    mt "Lass den Idioten doch sagen, was er will."
    mt "Ich werde das genießen und nichts kann meine Laune ruinieren."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:275
translate german ep211_dialogues2_public_event_8_110646cd:

    # mt "Миссис Уайт."
    # mt "Ее журнал всегда был прямым конкурентом моего журнала."
    # mt "Терпеть ее не могу!"
    # mt "Та еще старая грымза!"
    mt "Frau White."
    mt "Ihr Magazin stand immer in direkter Konkurrenz zu meinem."
    mt "Ich kann sie nicht leiden!"
    mt "Die alte Schachtel!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:283
translate german ep211_dialogues2_public_event_9_d1149033:

    # mt "Миссис Уайт?"
    # mt "Кого я меньше всего ожидала увидеть на этом приеме, так это ее..."
    # guest1 "Миссис Бакфетт... Добрый вечер."
    # m "Миссис Уайт, рада встрече." 
    # guest1 "Не ожидала увидеть Вас здесь..."
    # guest1 "Вас совсем не видно в последнее время, Миссис Бакфетт."
    # guest1 "Вы пропустили несколько модных показов..."
    # guest1 "Я уже не говорю о неделе моды, где Вас тоже не было."
    # mt "Черт!"
    mt "Frau White?"
    mt "Ich habe sie hier nicht erwartet..."
    guest1 "Frau Buckfett... Guten Abend."
    m "Frau White, schön Sie zu sehen." 
    guest1 "Ich habe sie hier nicht erwartet..."
    guest1 "Sie waren in letzter Zeit recht spärlich zu sehen, Frau Buckfett."
    guest1 "Sie haben einige Modenschauen verpasst..."
    guest1 "Ich rede gar nicht von der Fashion Week, obwohl Sie da auch nicht waren."
    mt "Huch!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:296
translate german ep211_dialogues2_public_event_9_886ed0ce:

    # m "..."
    # m "У меня были другие, более важные дела, Миссис Уайт."
    # guest1 "Важнее, чем показы знаменитых модельеров в мировой столице моды?"
    # guest1 "Что может быть важнее в нашем бизнесе, Миссис Бакфетт?"
    # guest1 "Хотя..."
    # guest1 "Я совсем забыла, что Ваш журнал теперь не совсем про моду..."
    # guest1 "Ваш журнал, Миссис Бакфетт, и раньше не дотягивал до уровня моего журнала."
    # mt "!!!"
    m "..."
    m "Ich hatte andere, wichtigere Dinge zu tun, Frau White."
    guest1 "Wichtigeres als die Show von den berühmtesten Designern in der Modehauptstadt?"
    guest1 "Was könnte in unserem Geschäft denn wichtiger sein, Frau Buckfett?"
    guest1 "Warte..."
    guest1 "Ich habe doch ganz vergessen, dass es in Ihrem Magazin nicht nur um Mode geht..."
    guest1 "Ihr Magazin, Frau Buckfett, hat nie das Niveau des Meinen erreicht."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:307
translate german ep211_dialogues2_public_event_9_d166f866:

    # mt "Сучка!"
    # m "Я так не считаю, Миссис Уайт."
    # guest1 "Да, Миссис Бакфетт. Ваш журнал был намного хуже!"
    # guest1 "А сейчас Вы не знаете уже, что придумать..."
    # guest1 "Идете на какие-то откровенные шаги, называя это сменой курса журнала..."
    # guest1 "Выглядит это все очень сомнительно."
    # guest1 "Не удивлюсь, если скоро Вы лично будете раздеваться перед камерой."
    # mt "Почему эта грымза говорит об этом?"
    # mt "Она что-то знает о моих откровенных фотосессиях?!"
    # mt "!!!"
    # guest1 "Думаете, это сделает Ваш журнал успешным, Миссис Бакфетт?"
    mt "Schlampe!"
    m "Nein, hat es nicht, Frau White."
    guest1 "Ja, Frau Buckfett. Ihr Magazin ist deutlich schlechter!"
    guest1 "Und jetzt wissen Sie nicht, was Sie noch bringen sollen..."
    guest1 "Machen drastische Änderungen und nennen es Kurswechsel..."
    guest1 "Das sieht alles sehr fragwürdig aus."
    guest1 "Ich wäre nicht überrascht, wenn Sie sich bald vor der Kamera ausziehen."
    mt "Warum redet die Schachtel so mit mir?"
    mt "Weiß sie was von den dubiosen Fotoshootings?"
    mt "!!!"
    guest1 "Denken Sie, das wird Ihr Magazin erfolgreich machen, Frau Buckfett?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:321
translate german ep211_dialogues2_public_event_9_5301aed9:

    # m "..."
    # m "Мой журнал был всегда успешнее Вашего бульварного чтива."
    # m "И сейчас, благодаря смене курса, он стал еще популярнее."
    # m "Чего не скажешь о Вас и Вашем журнале."
    # m "Кстати, что касается фотосессий..."
    # m "Я могу позволить себе участвовать в фотосессиях для моего журнала."
    # m "Моей красоте завидуют многие топ-модели страны."
    # m "А Вам, Миссис Уайт, остается только завидовать этому факту."
    # guest1 "Ни в коем случае, Миссис Бакфетт."
    # guest1 "Я никогда не стала бы сниматься в сомнительных фотосессиях."
    # guest1 "Надеюсь, и Вы до этого не опуститесь." 
    # mt "!!!"
    # guest1 "Вынуждена прервать нашу милую беседу, Миссис Бакфетт."
    # guest1 "Приятно было с Вами встретиться."
    # mt "Ненавижу эту грымзу!"
    # mt "Злобная стерва!"
    # mt "!!!"
    # biff "Цыпочка должна притворяться лучше."
    # biff "Будешь и дальше себя так вести и спорить с уважаемыми людьми..."
    # biff "Не зная всех ньюансов предмета разговора..."
    # biff "Все поймут, что ты не Моника Бакфетт, а ее дешевая подделка."
    # mt "!!!"
    m "..."
    m "Mein Magazin war schon immer erfolgreicher als dein Schundblatt."
    m "Und jetzt, wegen dem Kurswechsel, wurde meins noch beliebter."
    m "Du kannst mir alles über dich und das Magazin erzählen."
    m "Anbei, wegen den Fotoshootings..."
    m "Ich könnte durchaus in einem Shooting mitmachen."
    m "Viele Models quer durch das Land bewundern meine Schönheit."
    m "Und Sie, Frau White, können diese Tatsache nur beneiden."
    guest1 "Keinesfalls, Frau Buckfett."
    guest1 "Ich würde nie ein fragwürdiges Fotoshooting machen."
    guest1 "Ich hoffe, ich falle nie so tief." 
    mt "!!!"
    guest1 "Leider muss ich unsere nette Konversation unterbrechen, Frau Buckfett."
    guest1 "War schön, Sie zu sehen."
    mt "Ich hasse diese Schachtel!"
    mt "Böse Bitch!"
    mt "!!!"
    biff "Du solltest dich besser benehmen."
    biff "Willst du weiter machen, dich so zu verhalten und mit anständigen Leuten zu streiten?"
    biff "Ohne jetzt das genaue Thema des Gespräches zu kennen..."
    biff "Jeder wird merken, dass du nicht Monica Buckfett bist, sondern nur eine billige Kopie."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:352
translate german ep211_dialogues2_public_event_10_c4f90472:

    # mt "Мне не о чем больше разговаривать с этой грымзой!"
    # mt "Терпеть ее не могу!"
    mt "Ich habe mit dieser Schachtel nichts mehr zu besprechen!"
    mt "Ich kann sie nicht leiden!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:360
translate german ep211_dialogues2_public_event_11_72f9ddbd:

    # mt "Я знаю ее."
    # mt "Грейс..."
    # mt "Была моделью в нескольких журналах о моде."
    # mt "Мечтает стать топ-моделью."
    # mt "Красивая, но очень глупая..."
    mt "Ich kenne sie."
    mt "Grace..."
    mt "Sie war Model in einigen Modemagazinen."
    mt "Sie träumt davon, Topmodel zu werden."
    mt "Schön, aber sehr dumm..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:370
translate german ep211_dialogues2_public_event_12_acfd0cb3:

    # guest2 "Миссис Бакфетт, здравствуйте."
    # guest2 "Вы превосходно выглядите!"
    # m "Спасибо, Грейс."
    # guest2 "Ваше платье просто великолепно!"
    # m "Чего не скажешь о твоем вульгарном наряде..."
    # guest2 "Миссис Бакфетт, я хотела поблагодарить Вас за приглашение на пробы."
    guest2 "Frau Buckfett, hallo!"
    guest2 "Sie sehen toll aus!"
    m "Danke, Grace."
    guest2 "Ihr Kleid ist umwerfend!"
    m "Was man von deinem vulgären Outfit jetzt nicht sagen kann..."
    guest2 "Frau Buckfett, vielen Dank für die Einladung."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:379
translate german ep211_dialogues2_public_event_12_60ae35ba:

    # mt "???"
    # m "Грейс, что ты имеешь ввиду? Какие пробы?"
    # guest2 "Мне на днях позвонил Ваш менеджер Биф."
    # guest2 "Он сказал, что Вам требуется топ-модель."
    # guest2 "И пригласил меня на пробы."
    # mt "Мой менеджер Биф? Как интересно..."
    # guest2 "Я хотела спросить, Мелани у Вас больше не работает?"
    mt "???"
    m "Grace, was meinst du? Um was geht's?"
    guest2 "Ihr Manager Biff hat mich kürzlich angerufen."
    guest2 "Er sagte, dass Sie ein Topmodel brauchen."
    guest2 "Und er hat mich zu einer Audition eingeladen."
    mt "Mein Manager Biff? Interessant..."
    guest2 "Arbeitet Melanie nicht mehr für Sie?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:389
translate german ep211_dialogues2_public_event_12_bbff8ebf:

    # m "Мелани сейчас в небольшом отпуске."
    # mt "Мелани..."
    # mt "Ее давно уже не видно на работе."
    # mt "Она должна была раздобыть компромат на Викторию и пропала куда-то."
    # mt "..."
    # mt "Нужно спросить у этого придурка Бифа."
    # mt "Может, он знает, когда вернется Мелани..."
    # guest2 "Меня немного смущает новый курс Вашего журнала."
    # guest2 "Но на пробы в топ-модель Вашего журнала я приду."
    # guest2 "Я сказала Вашему менеджеру, что приму участие в пробах."
    # guest2 "При условии, что не будет никаких откровенных кадров."
    m "Melanie ist zur Zeit auf Urlaub."
    mt "Melanie..."
    mt "Sie wurde öffentlich schon eine ganze Weile nicht mehr gesehen."
    mt "Sie hatte etwas mit Victiora zu klären und ist dann verschwunden."
    mt "..."
    mt "Frage den Trottel Biff."
    mt "Vielleicht weiß er, wann Melanie zurück kommt..."
    guest2 "Ich bin vom Kurswechsel Ihres Magazines etwas irritiert."
    guest2 "Aber ich komme gerne, um als Topmodel zu arbeiten."
    guest2 "Ich habe Ihrem Manager zugesagt, in einem Casting teilzunehmen."
    guest2 "Unter der Voraussetzung, dass es keine schmuddeligen Fotos gibt."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:403
translate german ep211_dialogues2_public_event_12_15069d19:

    # m "И что тебе на это пообещал мой менеджер Биф?"
    # guest2 "Он заверил меня, что мне не нужно беспокоится об этом."
    # guest2 "И что он все сделает, как я хочу."
    # mt "Ха-ха!!!"
    # m "Удачи тебе на пробах, Грейс."
    # guest2 "Спасибо, Миссис Бакфетт."
    # mt "Интересно, как Биф собирается заставить ее раздеваться перед камерой?"
    # biff "Цыпочка не должна забывать, что она Моника Бакфетт."
    # biff "А не шлюха, которая совсем недавно отсасывала у бомжей..."
    # biff "Дешевая шлюха не в курсе, что происходит в журнале."
    # biff "А Моника Бакфетт в курсе всех дел."
    # biff "И не задает глупых вопросов будущим моделям журнала."
    # mt "!!!"
    m "Und was hat dir mein Manager Biff zugesagt?"
    guest2 "Er sagte, ich müsse mir keine Sorgen machen."
    guest2 "Und dass er alles macht, was ich will."
    mt "Haha!!!"
    m "Viel Glück dabei, Grace."
    guest2 "Vielen Dank, Frau Buckfett."
    mt "Ich frage mich, wie Biff sie dazu bringen will, sich vor der Kamera auszuziehen?"
    biff "Das Mädchen sollte nicht vergessen, dass sie Monica Buckfett ist."
    biff "Und nicht die Hure, die neulich noch Obdachlose gelutscht hat..."
    biff "Die billige Hure, die nicht wusste, wie das Magazin arbeitet."
    biff "Und Monica Buckfett, allgemein."
    biff "Und zukünftige Models des Magazines keine dummen Fragen stellt."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:425
translate german ep211_dialogues2_public_event_13_78d6e5a8:

    # mt "Мне не о чем больше разговаривать с ней..."
    # mt "Поверила обещаниям Бифа, что станет топ-моделью журнала."
    # mt "Глупая девочка!"
    mt "Ich habe mit ihr nichts mehr zu besprechen..."
    mt "Sie hat Biff's Versprechen geglaubt, dass sie Topmodel des Magazines wird."
    mt "Dummes Mädchen!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:434
translate german ep211_dialogues2_public_event_14_7f74311d:

    # mt "Топ-модель. Весьма востребован в мире моды."
    # mt "..."
    # mt "Сразу видно, что он самовлюбленный никчемный придурок."
    mt "Topmodel. Sehr bekannt in der Modewelt."
    mt "..."
    mt "Es ist eindeutig, dass er ein Narzisst ist, der dumme Depp."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:442
translate german ep211_dialogues2_public_event_15_0693abea:

    # guest3 "Миссис Бакфетт, Вы прекрасно выглядите."
    # m "Спасибо."
    # m "Я тебя где-то видела... Мы знакомы?"
    # guest3 "Меня зовут Исаак. Я модель."
    # guest3 "Работаю на модных показах."
    # guest3 "Иногда участвую в фотосессиях."
    # m "..."
    # mt "Надеюсь, что Бифу не придет в его пустую голову идея..."
    # mt "Пригласить какого-нибудь придурка на съемку."
    # guest3 "Я Ваш давний поклонник, Миссис Бакфетт."
    # guest3 "И хочу сказать, что в последнее время Ваш журнал стал намного лучше."
    # guest3 "Я буду рад принять участие в фотосессии ню с Вами..."
    guest3 "Frau Buckfett, sie sehen toll aus."
    m "Danke."
    m "Ich habe Sie irgendwo schon mal gesehen... kennen wir uns?"
    guest3 "Mein Name ist Isaac. Ich bin Model."
    guest3 "Ich arbeite in Fashionshows."
    guest3 "Manchmal mache ich auch bei Shootings mit."
    m "..."
    mt "Ich hoffe, dass Biff nicht mit dummen Gedanken kommt..."
    mt "Und einen Idioten zu einem Shooting einlädt."
    guest3 "Ich bin schon lange Zeit ein Fan von Ihnen, Frau Buckfett."
    guest3 "Und ich wollte sagen, dass ihr Magazin seit kurzem deutlich besser wurde."
    guest3 "Ich würde mich freuen, in einem Nacktshooting mit Ihnen teil zu nehmen..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:457
translate german ep211_dialogues2_public_event_15_97774775:

    # m "Спасибо, Исаак..."
    # mt "Стоп!"
    # mt "Что?!"
    # m "Фотосессия ню?!"
    # m "?!?!?!"
    # guest3 "Ваш менеджер Биф сказал, что в скором будущем планируется эротическая фотосессия, в паре."
    # guest3 "И пригласил меня поучаствовать в ней."
    # guest3 "Конечно же, я не отказался." 
    # mt "!!!"
    # mt "Я этому Бифу яйца оторву!"
    # mt "Что он задумал?!"
    m "Danke, Isaac..."
    mt "Stopp!"
    mt "Was?!"
    m "Ein Nacktshooting?!"
    m "?!?!?!"
    guest3 "Ihr Manager Biff sagte, dass in naher Zukunft ein Nacktshooting als Paar geplant ist."
    guest3 "Und dazu hat er mich eingeladen."
    guest3 "Natürlich habe ich nicht abgelehnt." 
    mt "!!!"
    mt "Ich werde Biffs Eier abreißen!"
    mt "Was hat er vor?!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:471
translate german ep211_dialogues2_public_event_15_05fdf059:

    # m "..."
    # m "Возможно, Исаак, ты неверно понял моего менеджера."
    # m "Мы... Мы планируем серию фотосессий с участием мужчин моделей."
    # m "Но о моем присутствии в кадре и речи быть не может."
    # m "Мой менеджер имел ввиду не меня, а другую модель..."
    # guest3 "Нет, Миссис Бакфетт. Он говорил именно о Вас."
    # guest3 "В любом случае, я с удовольствием поработаю в Вашем журнале."
    # guest3 "Приятного вечера, Миссис Бакфетт."
    # mt "Биф сволочь!!!"
    # biff "Кукла!"
    # biff "Ты на грани провала!"
    # biff "Еще немного и все поймут, что ты дешевая подделка Моники Бакфетт!"
    # m "Биф, что за эротические фотосессии с участием этого парня?!"
    # m "?!?!?!"
    # biff "Это тебя не касается, кукла безмозглая!"
    # biff "Такое решение принял папочка!"
    # biff "Как папочка скажет, так и будешь делать!"
    # biff "Это твоя работа. Ты за это получаешь большие деньги!"
    # m "!!!"
    # biff "Быстро взяла себя в руки!"
    # biff "Еще раз услышу, что задаешь глупые вопросы гостям..."
    # biff "Немедленно вылетишь с этой модной вечеринки прямо на улицу, дальше сосать члены за $ 20!"
    # biff "Поняла!?"
    # mt "НЕНАВИЖУ!"
    # mt "!!!"
    m "..."
    m "Vielleicht hast du ihn nur falsch verstanden, Isaac."
    m "Wir... wir planen eine Reihe von Shootings mit männlichen Models."
    m "Aber ich werde nicht mitmachen."
    m "Mein Manager meinte nicht mich, sondern ein anderes Model...."
    guest3 "Nein, Frau Buckfett. Er hat ganz klar von Ihnen gesprochen."
    guest3 "Wie auch immer, ich würde gerne in Ihrem Magazin arbeiten."
    guest3 "Einen schönen Abend noch, Frau Buckfett."
    mt "Biff, der Bastard!"
    biff "Depp!"
    biff "Du bist knapp am Scheitern!"
    biff "Noch ein bisschen mehr, und man wird merken, dass du nur eine billige Fälschung bist!"
    m "Biff, was sollen die erotischen Shootings mit dem Typen?!"
    m "?!?!?!"
    biff "Das muss dich nicht interessieren, hirnlose Frau!"
    biff "Diese Entscheidung hat Daddy getroffen!"
    biff "Und was ich sage, machst du!"
    biff "Es ist dein Job und dafür bekommst du viel Geld!"
    m "!!!"
    biff "Jetzt reiß dich zusammen!"
    biff "Und schon wieder höre ich, dass du dumme Fragen stellst..."
    biff "Du fliegst von der Party auf die Straße und lutscht da die Penner für 20$!"
    biff "Verstanden?!"
    mt "ICH HASSE IHN!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:505
translate german ep211_dialogues2_public_event_16_a9dce1bf:

    # mt "Я не хочу больше с ним разговаривать!"
    # mt "Я ни за что не соглашусь на эротическую фотосессию!"
    # mt "Ни с ним, ни с кем-либо еще!!!"
    mt "Ich will mit ihm nicht mehr sprechen!"
    mt "Ich würde einem erotischen Shooting niemals zustimmen!"
    mt "Nicht mit ihm oder sonst wem!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:514
translate german ep211_dialogues2_public_event_17_98edc287:

    # mt "Райен. Один из самых востребованных и знаменитых фотографов города, вроде Алекса."
    # mt "Как по мне, ничего особенного я в его работах не видела."
    mt "Ryan. Einer der besten und bekanntesten Fotografen der Stadt. Wie Alex."
    mt "Ich selbst allerdings sehe nichts besonderes in seiner Arbeit."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:521
translate german ep211_dialogues2_public_event_18_2b1c78c8:

    # guest4 "Миссис Бакфетт, добрый вечер."
    # m "Здравствуй, Райен."
    # guest4 "Мы с Вами давно не встречались..."
    # guest4 "В последнее время, Вы почти не посещаете публичные мероприятия."
    # guest4 "Даже пропустили несколько модных показов."
    # mt "И? Я что, должна оправдываться?!"
    guest4 "Frau Buckfett, Guten Abend."
    m "Hallo, Ryan."
    guest4 "Ich wollte Sie schon so lange treffen..."
    guest4 "In letzter Zeit waren Sie kaum bei öffentlichen Events."
    guest4 "Haben sogar einige Modeshows verpasst."
    mt "Und? Muss ich mich dafür entschuldigen?!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:530
translate german ep211_dialogues2_public_event_18_a2905a2b:

    # m "У меня были другие, более важные дела, Райен."
    # guest4 "Понимаю, Миссис Бакфетт."
    # guest4 "Кстати о Ваших, так сказать, важных делах..."
    # guest4 "..."
    # mt "???"
    # guest4 "Я видел Ваши фотографии с закрытой фотосессии..."
    # mt "ЧТОООО?!"
    # mt "?!?!?!"
    # guest4 "Работа хорошая, но чувствуется Ваша скованность..."
    # guest4 "Я знаю, как сделать подобные кадры более чувственными."
    # mt "..."
    # mt "Как?"
    # mt "Откуда?"
    # mt "Кто?"
    # mt "?!?!?!"
    # mt "Алекс?!"
    # mt "!!!"
    # mt "Алекс сволочь!!!"
    m "Ich hatte andere, wichtigere Dinge zu tun, Ryan."
    guest4 "Verstehe, Frau Buckfett."
    guest4 "Weil wir gerade von wichtigen Dingen sprechen..."
    guest4 "..."
    mt "???"
    guest4 "Ich habe ihre Fotos von einem inoffiziellen Shooting gesehen..."
    mt "WAAAS?!"
    mt "?!?!?!"
    guest4 "Die Arbeit ist gut, aber ihre Hemmung stört..."
    guest4 "Ich weiß, wie Sie solche Bilder erotischer machen könnten."
    mt "..."
    mt "Wie?"
    mt "Wo?"
    mt "Wer!"
    mt "?!?!?!"
    mt "Alex?!"
    mt "!!!"
    mt "Alex, der Bastard!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:551
translate german ep211_dialogues2_public_event_18_17add987:

    # m "Вы обсуждали эту работу с Вашим коллегой Алексом?"
    # guest4 "Нет, Миссис Бакфетт."
    # guest4 "Алекс считает, что он лучший в своем деле."
    # guest4 "И не любит, когда ему дают профессиональные советы относительно его работ."
    # mt "..."
    # mt "Кто тогда?"
    # mt "Биф?!"
    # mt "!!!"
    # guest4 "Миссис Бакфетт, с большим сожалением вынужден оставить Вас."
    # guest4 "И помните, что всегда можете обратиться ко мне."
    # guest4 "Вы убедитесь, что мои снимки шедевральны."
    # guest4 "Приятно провести вечер."
    # mt "Я уверена, это сделал Биф!!!"
    # mt "АААААА!!!!"
    # mt "НЕНАВИЖУ!!!!!!"
    # biff "Нужно быть вежливее с такими уважаемыми людьми!"
    # biff "Ничего не понимаешь в том, что они говорят - улыбайся и молчи!"
    # biff "У тебя и правда совсем нет мозгов."
    # biff "Ты даже просто пообщаться с гостями не можешь!"
    # biff "Мне приходится все контролировать!"
    # m "Биф, ты показывал мои фотографии этому фотографу?!"
    # m "?!?!?!"
    # biff "..."
    # biff "Конечно, цыпочка!"
    # biff "И я планирую показать их также нашим инвесторам, как наглядное подтверждение нашего нового курса!"
    # biff "Я планирую это сделать до того, как эти снимки станут достоянием всей публики."
    # biff "Я считаю, что наши инвесторы заслуживают того, чтобы увидеть это первыми!"
    # biff "Цыпочка, ты согласна со мной?"
    # m "!!!"
    # m "Биф... Может быть, та фотосессия останется закрытой?"
    # biff "Нет, цыпочка! Это исключено!"
    # biff "И хватит со мной спорить!"
    # biff "Иди и дальше притворяйся Моникой Бакфетт, пока я не потерял терпение!"
    # mt "!!!"
    # mt "Я не могу допустить, чтобы кто-то увидел те кадры!"
    m "Hast du diese Arbeit mit deinem Kollegen Alex besprochen?"
    guest4 "Nein, Frau Buckfett..."
    guest4 "Alex glaubt, dass er der Beste seiner Zunft ist."
    guest4 "Und er mag es nicht, wenn man ihm Ratschläge zu seiner Arbeit gibt."
    mt "..."
    mt "Wer dann?"
    mt "Biff?!"
    mt "!!!"
    guest4 "Frau Buckfett, leider muss ich Sie schon verlassen."
    guest4 "Aber denken Sie dran, Sie können mich jederzeit anrufen."
    guest4 "Sie werden sehen, dass meine Bilder Meisterwerke sind."
    guest4 "Haben Sie noch einen schönen Abend."
    mt "Ich bin sicher, es war Biff!!!"
    mt "АААААА!!!!"
    mt "ICH HASSE IHN!!!!!!"
    biff "Du musst mich solchen Leuten höflicher sein!"
    biff "Du verstehst nicht, wovon sie reden - lächle und halt die Klappe!"
    biff "Du hast überhaupt kein Hirn."
    biff "Du kannst mit den Gästen nicht mal sprechen!"
    biff "Ich muss alles kontrollieren!"
    m "Biff, hast du diesem Fotografen meine Bilder gezeigt?!"
    m "?!?!?!"
    biff "..."
    biff "Geht klar, Baby!"
    biff "Ja, und ich will sie auch den Investoren zeigen, als bildliche Darstellung unseres Kurses quasi!"
    biff "Ich will das machen, bevor die Bilder veröffentlicht werden."
    biff "Ich denke, unsere Investoren sollten die Ersten sein, die sie sehen!"
    biff "Mädchen, stimmst du mir zu?"
    m "!!!"
    m "Biff... vielleicht sollte das Verschlusssache bleiben?"
    biff "Nein! Das steht nicht zur Debatte!"
    biff "Hör auf mit mir zu diskutieren!"
    biff "Geh und gib vor, Monica Buckfett zu sein, sonst verliere ich meine Geduld!"
    mt "!!!"
    mt "Ich kann es nicht zusallen, dass irgendwer diese Bilder sieht!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:595
translate german ep211_dialogues2_public_event_19_b9e7b732:

    # mt "Мне не о чем больше разговаривать с ним..."
    # mt "Ведет себя, как-будто он какая-то звезда."
    # mt "На деле, обычный фотограф-извращенец."
    mt "Ich habe mit ihm nichts mehr zu besprechen..."
    mt "Er benimmt sich, als wäre er eine Art Star."
    mt "Aber er ist nur ein gewöhnlicher, perverser Fotograf."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:604
translate german ep211_dialogues2_public_event_20_b60f0ce2:

    # mt "Мия и Шарлотт. Светские львицы."
    # mt "Не пропускают ни одного мероприятия."
    # mt "Их мужья возглавляют совет директоров одной крупной корпорации."
    # mt "А эти две особы только и успевают, что тратить их деньги."
    mt "Mia und Charlotte."
    mt "Verpassen kein einziges Event."
    mt "Ihre Ehemänner sind hochrangige Direktoren in einer großen Firma."
    mt "Und die Zwei können nur deren Geld ausgeben."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:613
translate german ep211_dialogues2_public_event_21_5e6651b7:

    # guest5 "Добрый вечер."
    # guest6 "Здравствуйте."
    # guest5 "Мия, я весьма удивлена тому факту, что Мистер Кэмпбелл..."
    # guest5 "Пригласил на этот праздничный фуршет владелицу журнала..."
    # guest5 "С сомнительной репутацией."
    # guest6 "Я тоже удивлена." 
    # guest6 "Странно, что Вы посещаете подобные мероприятия..."
    # guest6 "Я думала на праздничном фуршете Мистера Кэмпбелла..."
    # guest6 "Будут присутствовать исключительно представители высшего света."
    # mt "Я и есть леди из высшего общества!"
    # mt "Две змеи!"
    # mt "Никчемные дуры!"
    guest5 "Guten Abend."
    guest6 "Hallo."
    guest5 "Mia, ich bin überrascht, dass Herr Campell..."
    guest5 "Ich habe den Besitzer eines Magazines zu diesem großzügigen Buffett eingeladen..."
    guest5 "Mit einem fragwürdigen Ruf."
    guest6 "Das überrascht mich auch." 
    guest6 "Seltsam, dass du an solchen Events teil nimmst..."
    guest6 "Ich dachte mir bei Herrn Campbells Banket, dass..."
    guest6 "Nur Mitglieder der High Society da sind."
    mt "Ich bin von der High Society!"
    mt "Zwei Schlangen!"
    mt "Nutzlose Kreaturen!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:630
translate german ep211_dialogues2_public_event_21_ec1cfbd9:

    # m "Мистер Кэмпбелл пригласил сегодня всю элиту мира моды."
    # m "И мне весьма странно видеть на этом вечере вас."
    # m "Вы имеете какое-то отношение к индустрии моды?"
    # m "Уверена, что нет."
    # m "Человек, разбирающийся в моде и искусстве..."
    # m "Никогда не назвал бы мой журнал сомнительным."
    # guest6 "Как странно... Миссис Уайт, владелица другого модного журнала..."
    # guest6 "Она одной из первых употребила слово 'сомнительный' касательно Вашего журнала."
    # guest6 "Получается, она ничего не понимает в моде и искусстве?"
    # mt "!!!"
    m "Herr Campbell hat die Elite der ganzen Modewelt eingeladen."
    m "Und es ist seltsam, dich hier heute zu sehen."
    m "Hast du irgendwas mit der Modeindustrie zu tun?"
    m "Ich weiß nicht so genau."
    m "Mein Mann mag Mode und Kunst..."
    m "Ich würde meine Magazine niemals fragwürdig nennen."
    guest6 "Seltsam... Frau White, die Besitzerin eines anderen Modemagazins..."
    guest6 "Sie war die erste, die mein Magazin 'fragwürdig' nannte."
    guest6 "Wie sich zeigt, hat sie weder von Fashion noch von Kunst Ahnung."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:643
translate german ep211_dialogues2_public_event_21_a66427c9:

    # m "У нас с Миссис Уайт несколько напряженные отношения."
    # m "Мы конкуренты."
    # m "А Миссис Уайт никогда не отличалась тактичностью."
    # m "Впрочем, как и некоторые здесь присутствующие..."
    # guest5 "..."
    # guest6 "..."
    # m "Я считаю, что вообще вести диалог о подобных вещах, не соответствует моему высокому уровню."
    # m "До свидания. Возможно, увидимся на одном из будущих модных показов."
    # biff "Ты пятно на платье не поставила, глупая кукла?"
    # m "Нет!"
    # biff "Смотри, аккуратнее. Хоть одно маленькое пятно..."
    # biff "И я высчитаю стоимость платья из твоей зарплаты!"
    # biff "Тебе придется целый месяц сниматься с членом во рту за бесплатно!"
    # mt "Да пошел ты!"
    # mt "Козел!"
    m "Frau White und ich haben eine enge Beziehung."
    m "Wir sind Konkurrenten."
    m "Und Frau White war noch nie taktvoll."
    m "Wie auch einige Andere hier..."
    guest5 "..."
    guest6 "..."
    m "Ich denke, dass Gespräche über dieses Thema meine Stellung unterstreichen."
    m "Tschüss. Vielleicht sehe ich dich ja bei einer Modenschau."
    biff "Du hast doch keinen Fleck auf das Klei gemacht, dumme Frau, oder?"
    m "Nein! Das ist das teuerste Kleid im ganzen Laden."
    biff "Pass auf. Nur ein kleiner Fleck..."
    biff "Und ich ziehe dir das Kleid vom Gehalt ab!"
    biff "Du wirst monatelang Schwänze umsonst in den Mund nehmen müssen!"
    mt "Aha."
    mt "Arschloch!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:667
translate german ep211_dialogues2_public_event_22_55274d88:

    # mt "Фи! Не хочу больше разговаривать с этими дурами!"
    mt "Pah! Ich will mit diesen dummen Leuten nicht mehr sprechen!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:672
translate german ep211_dialogues2_public_event_23_f334f1d9:

    # reporter1 "Миссис Бакфетт, можно взять у Вас интервью."
    # m "Можно..."
    # reporter1 "Скажите, это правда, что Ваш журнал теперь больше про эротику?"
    # reporter1 "Чем про моду..."
    # m "Мой журнал, в первую очередь, про женскую красоту."
    # reporter2 "Миссис Бакфетт, ходят слухи, что проводятся достаточно..."
    # reporter2 "Откровенные фотосессии для Вашего журнала..."
    # m "Мы проводим фотосессии, на которых в полной мере раскрываем..."
    # m "Всю женственность и красоту наших моделей."
    # reporter3 "Когда мы сможем увидеть эти долгожданные снимки?"
    # m "Совсем скоро вы сможете насладиться эстетикой этих снимков."
    # reporter2 "Миссис Бакфетт, говорят Вы лично позируете перед камерой."
    # reporter2 "Это правда?"
    # m "Я самая лучшая модель. Со мной никто не сравниться."
    # m "Поэтому иногда я лично учавствую в фотосессиях..."
    # reporter1 "Миссис Бакфетт, а еще говорят, что у Вас была фотосессия..."
    # reporter1 "Где Ваша грудь практически полностью видна из-под платья."
    # reporter1 "Собираетесь ли Вы сделать фотосессия топлесс?"
    # m "Интересно, кто мог такое рассказать вам?"
    # m "Это не так. Я никогда не позволила бы себе обнажить грудь перед камерой."
    # m "Мир не достоин того, чтобы созерцать совершенную красоту моего тела."
    # reporter2 "Миссис Бакфетт, а кто этот мужчина, с которым Вы пришли?"
    # m "Это мой менеджер."
    # m "У меня нет времени заниматься некоторыми рутинными делами..."
    # m "Я управляю большой компанией, а всей остальной рутиной занимается он."
    # reporter3 "В одном из своих интервью Вы достаточно неприязенно отзывались..."
    # reporter3 "О Мистере Кэмпбелле. А сегодня вы присутствуете на его мероприятии..."
    # reporter3 "С чем связано..."
    # m "Интервью окончено. Вы можете сделать еще несколько снимков."
    # mt "Никчемные журналисты!"
    # mt "Про какие слухи они говорили? Откуда они их узнают?"
    # mt "Кто может рассказывать такие подробности? Алекс? Бифф?"
    # mt "Узнаю - уволю всех к черту!"
    # mt "Когда снова стану Боссом..."
    # mt "Мне во что бы то ни стало нужно скорее возвращать мой журнал МНЕ!"
    # mt "И прекращать эти глупости со сменой курса журнала!"
    reporter1 "Frau Buckfett, können wir ein Interview haben?"
    m "Kann ich..."
    reporter1 "Sagen Sie, stimmt es, dass ihr Magazin nun mehr erotische Inhalte publiziert?"
    reporter1 "Was ist mit der Mode?..."
    m "Mein Magazin dreht sich primär um die Schönheit der Frau."
    reporter2 "Frau Buckfett, es gibt Gerüchte, dass einiges passiert ist..."
    reporter2 "Anrüchige Fotoshession in ihrem Magazin..."
    m "Wir machen saubere Shootings bei denen wir vollständig..."
    m "Die Schönheit der Frauen zeigen."
    reporter3 "Wann können wir diese lange erwarteten Bilder sehen?"
    m "Bald könnt ihr diese ästhetischen Bilder bewundern."
    reporter2 "Frau Buckfett, es heißt, Sie persönlich stünden vor der Kamera."
    reporter2 "Stimmt das?"
    m "Ich bin das beste Model. Niemand kann sich mit mir messen."
    m "Daher mache ich manchmal selber mit."
    reporter1 "Frau Buckfett, es heißt auch, dass es ein Shooting gab, in dem Sie..."
    reporter1 "In dem man Ihre Brust nahezu vollständig sehen kann."
    reporter1 "Werden Sie auch oben ohne Fotos machen?"
    m "Ich frage mich, wer Ihnen sowas erzählt."
    m "Das stimmt nicht. Ich würde niemals meine Brüste vor der Kamera zeigen."
    m "Die Welt ist es nicht wert, meine unfassbare Schönheit zu sehen."
    reporter2 "Frau Buckfett, wer ist der Mann, mit dem Sie hier sind?"
    m "Das ist mein Manager."
    m "Ich habe jetzt keine Zeit mehr für Smalltalk..."
    m "Ich betreibe ein großes Unternehmen, er kümmert sich um den Rest."
    reporter3 "In einem Ihrer Interviews haben Sie sich über Herrn Campbell geäußert..."
    reporter3 "Und nun besuchen Sie selbst eines seiner Events..."
    reporter3 "Was ist der Grund?"
    m "Das Interview ist vorbei. Sie können noch Bilder machen."
    mt "Wertlose Journalisten!"
    mt "Von welchen Gerüchten sprechen die? Woher wissen sie das?"
    mt "Wer könnte solche Details erzählen? Alex? Biff?"
    mt "Ich werde es rausfinden - und ihn feuern!"
    mt "Wenn ich wieder der Boss bin..."
    mt "Bei den Göttern, ich muss das Magazin bald wieder an MICH reißen!"
    mt "Und diesen Unsinn mit dem Kurswechsel stoppen!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:721
translate german ep211_dialogues2_public_event_24_8271d075:

    # mt "Стефани и Ребекка?!"
    # mt "А они то что здесь делают?!"
    # mt "Дьявол!"
    # mt "..."
    # mt "С другой стороны, это шанс восстановить мою репутацию перед ними..."
    mt "Stephanie und Rebecca?!"
    mt "Was wollen die denn hier?!"
    mt "Diese Teufelin!"
    mt "..."
    mt "Andererseits ist das eine gute Gelegenheit, meinen Ruf bei ihnen wieder in's rechte Licht zu rücken..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:731
translate german ep211_dialogues2_public_event_25_2da32c61:

    # stephanie "Моника!"
    # rebecca "Какая неожиданная встреча!"
    # m "Привет, подружки!"
    # rebecca "У тебя такое шикарное платье!"
    # stephanie "Да, оно прекрасно подчеркивает твою фигуру!"
    # m "Спасибо, девочки."
    stephanie "Monica!"
    rebecca "Was für ein unerwartetes Treffen!"
    m "Hallo Freundinnen!"
    rebecca "So ein tolles Kleid!"
    stephanie "Ja, es passt perfekt zu deiner Figur!"
    m "Danke, Mädels."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:739
translate german ep211_dialogues2_public_event_25_abbd17de:

    # rebecca "Немного непривычно видеть тебя вновь в таком раскошном образе."
    # rebecca "Мы уже привыкли, что ты носишь вещи какой-то провинциальной дуры, которая покрикивает на тебя."
    rebecca "Es ist etwas ungewohnt, dich wieder in sowas zu sehen."
    rebecca "Wir waren es schon gewohnt, dich in Sachen zu sehen, die eher ländlich waren."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:745
translate german ep211_dialogues2_public_event_25_2c33916e:

    # m "Я же вам говорила, что у меня приключения..."
    # m "Но сегодня я решила принять прглашение Мистера Кэмпбелла."
    # rebecca "Все равно странно, что ты позволяешь этой провинциалке командовать тобой..."
    # rebecca "Это выглядит очень смешно."
    # rebecca "То, что ты носишь за ней ее вещи - это тоже приключения, да?"
    # rebecca "А сюда ты ее не стала брать? Хи-хи..."
    # mt "Черт! Вот пристали со своими глупыми вопросами!"
    # mt "Как хорошо, что здесь нет Бетти..."
    # m "Ничего странного. Просто такая игра."
    # stephanie "И как долго она еще будет продолжаться?"
    # stephanie "Ведь ты пропускаешь все наши девичники."
    # m "Я же сказала, что недолго! Скоро я закончу это дело и займусь своими обычными заботами."
    # stephanie "Да? Ты говорила что тебе больше неинтересны обычные развлечения."
    # stephanie "Что ты тогда делаешь здесь?"
    # rebecca "Да, Моника. Я помню, что ты говорила, что это скучно."
    # rebecca "И что твои развлечения сейчас гораздо интереснее!"
    # mt "!!!"
    # m "Подружки... Да, мне сейчас это не очень интересно."
    # m "Но не забывайте кто Я!"
    # m "Я - владелица крупнейшего журнала моды!"
    # m "И мне необходимо бывать на подобных вечерах, чтобы решать серьезные дела и вести переговоры!"
    # rebecca "Хорошо, Моника."
    # rebecca "Мы рады видеть тебя здесь!"
    # stephanie "Да, Моника. Мы рады."
    # stephanie "А то, если честно, мы начали сомневаться, говоришь ли ты нам правду."
    # stephanie "Вдруг ты действительно работаешь гувернанткой у той провинциальной дуры."
    # m "Что вы, подружки!"
    # m "Как вы могли такое подумать?!"
    # m "Это ведь было бы так нелепо! Фи!"
    # m "Моника Бакфетт и какая-то гувернантка..."
    # stephanie "Да, Моника. Это было бы совершенно нелепо."
    # stephanie "И я очень рада, что это не так."
    # m "А как у вас дела, подружки?"
    # m "Я не ожидала вас увидеть на этом вечере."
    # stephanie "Все отлично."
    # stephanie "Ты ведь знаешь, мы не можем пропустить подобной вечеринки."
    # stephanie "Здесь можно найти много интересных людей, с которыми можно познакомиться."
    # mt "И, судя по наряду Ребекки, найти, с кем бы переспать..."
    # mt "Стефани пришла сюда развлекаться."
    # mt "А Ребекка явно хочет найти очередной мешок с деньгами."
    # mt "..."
    m "Ich habe doch gesagt, dass ich Abenteuer machen..."
    m "Aber heute wollte ich Herrn Campbells Einladung annehmen."
    rebecca "Komisch, dass du dich so rumkommandieren lässt..."
    rebecca "Das sieht lustig aus."
    rebecca "Die Tatsache, dass du ihr die Sachen nachträgst gehört auch zum Abenteuer?"
    rebecca "Und du machst das immer noch? Hehe..."
    mt "Fix. Immer diese dummen Fragen."
    mt "Gut, dass Betty nicht hier ist."
    m "Nichts ist seltsam, es ist nur ein Spiel."
    stephanie "Und wie lange geht das noch?"
    stephanie "Denn du vermisst uns bestimmt schon."
    m "Ich hab doch schon gesagt, nicht mehr lange. Bald ist das vorbei uns alles wie immer."
    stephanie "Ja? Du sagtest, gewöhnliche Unterhaltung interessiert dich nicht mehr."
    stephanie "Was machst du dann hier?"
    rebecca "Ja, Monica. Ich erinnere mich auch, dass du gesagt hast, sowas ist langweilig."
    rebecca "Und dass deine Unterhaltung deutlich spannender ist."
    mt "!!!"
    m "Freundinnen... Ja, das interessiert mich momentan nicht so sehr."
    m "Aber vergesst nicht, wer ich bin!"
    m "Ich bin die Besitzerin des größten Modemagazins!"
    m "Und ich muss an solchen Abenden hin und wieder teilnehmen und Dinge zu klären und zu verhandeln!"
    rebecca "Na gut, Monica."
    rebecca "Wir freuen uns, dich hier zu sehen!"
    stephanie "Ja, Monica. Wir freuen uns."
    stephanie "Aber, um ehrlich zu sein, wir haben bezweifelt, ob du uns die Wahrheit erzählst."
    stephanie "Am Schluß arbeitest du wirklich noch als Dienstmädchen für einen Dorfdepp."
    m "Freundinnen, was redet ihr da?"
    m "Wie könnt ihr sowas denken?!"
    m "Das wäre lächerlich! Pah!"
    m "Monica Buckfett als Dienstmädchen..."
    stephanie "Ja, Monica. Das wäre total lächerlich."
    stephanie "Ich bin froh, dass es nicht stimmt."
    m "Wie geht's euch, Freundinnen?"
    m "Ich habe nicht erwartet, euch heute hier zu sehen."
    stephanie "Alles ist gut."
    stephanie "Weißt du, so eine Party können wir doch nicht verpassen."
    stephanie "Es gibt so viele interessante Leute zu treffen."
    mt "Und, Rebeccas Outfit zu urteilen, jemanden, mit dem sie schlafen kann."
    mt "Stephanie ist gekommen, um Spaß zu haben."
    mt "Und Rebecca will eindeutig einen anderen Sugardaddy finden."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:790
translate german ep211_dialogues2_public_event_25_bf0138c8:

    # m "Ребекка, у тебя такой интересный наряд сегодня!"
    # m "Тебе очень идет!"
    # mt "Похожа на новогоднюю елку..."
    # rebecca "Спасибо, подружка!"
    # m "С кем-нибудь познакомилась здесь?"
    # rebecca "Нет, но я очень хочу познакомиться вон с тем парнем."
    # rebecca "Ты же знаешь, кто он?"
    # m "Джеймс Тернер? Ну да, знаю..."
    # m "Обычный исполнитель... Ничего особенного."
    # rebecca "Моника, о нем сейчас пишут все СМИ!"
    # rebecca "Он мега популярен!"
    # rebecca "Я просто в восторге от него!"
    # m "И что тебе мешает познакомиться с ним?"
    # rebecca "Да он ни на кого внимания не обращает!"
    # rebecca "Я уже пыталась подойти к нему..."
    # stephanie "Да. Она пыталась. Это бесполезно."
    # stephanie "Моника, ты же здесь всех знаешь..."
    # stephanie "Может, познакомишь Ребекку с Тернером?"
    # stephanie "Я могла бы это сделать, но мой отец сенатор будет против."
    # stephanie "Я не могу это делать на публике, ты знаешь."
    # mt "???"
    # rebecca "Точно! Стефани, отличная идея!"
    # rebecca "Моника, пожалуйста!"
    # rebecca "Он очень знаменит и богат."
    # rebecca "Если я с ним начну встречаться, обо мне тоже будут писать все газеты!"
    # rebecca "Потом меня заметит какой-нибудь продюсер..."
    # rebecca "И я, наконец, тоже стану богатой и знаменитой!"
    # rebecca "Моника, ну что тебе стоит подойти к нему?"
    # rebecca "Ну пожалуйста!"
    # mt "Хммм..."
    # mt "А почему бы и мне не попробовать найти себе мужчину..."
    # mt "Который решит все мои небольшие временные недоразумения..."
    # mt "Которые у меня возникли?"
    # mt "Стоит попробовать."
    # mt "Я самая красивая женщина на этом вечере."
    # mt "Мне не составит никакого труда найти себе богатого мужчину."
    # mt "Но только не этого никчемного певца с фиолетовыми волосами! Фи!"
    # mt "Этот самовлюбленный кретин не потратит ни на какую девушку и цента!"
    # mt "Я найду себе мужчину лучше!"
    # mt "А этого, так уж и быть, оставлю Ребекке..."
    # mt "..."
    m "Rebecca, dein Outfit ist so toll heute!"
    m "Es steht dir so gut!"
    mt "Sieht aus wie ein Weihnachtsbaum..."
    rebecca "Danke, Freundin!"
    m "Hast du schon wen hier getroffen?"
    rebecca "Nein, aber ich will wirklich den Typ da drüben kennen lernen."
    rebecca "Weißt du, wer er ist?"
    m "James Turner? Ehm ja, den kenne ich..."
    m "Ein gewöhnlicher Darsteller... Nichts besonderes."
    rebecca "Monica, die Presse schreibt über ihn!"
    rebecca "Er ist total bekannt!"
    rebecca "Das macht mich voll an!"
    m "Und was hält dich davon ab, ihn kennen zu lernen?"
    rebecca "Er nimmt niemanden um sich wahr!"
    rebecca "Ich habe schon versucht, mich ihm zu nähern..."
    stephanie "Ja. Sie hat es versucht. Ergebnislos."
    stephanie "Monica, du kennst jeden hier..."
    stephanie "Kannst du Rebecca nicht mit James Turner bekannt machen?"
    stephanie "Ich könnte es auch, aber mein Vater, der Senator, wäre dagegen."
    stephanie "Also kann ich es nicht öffentlich machen, weißt du."
    mt "???"
    rebecca "Ja, Stephanie, tolle Idee."
    rebecca "Monica, bitte!"
    rebecca "Er ist sehr berühmt und reich."
    rebecca "Wenn ich ihn date, schreiben alle Zeitungen auch über mich!"
    rebecca "Dann wird ein Produzent auf mich aufmerksam..."
    rebecca "Und dann, werde ich endlich auch reich und berühmt!"
    rebecca "Monica, also, redest du mit ihm?"
    rebecca "Oh bitte!"
    mt "Hmmm ..."
    mt "Warum versuche ich eigentlich nicht, einen Mann zu finden..."
    mt "Welcher all meine zeitweisen, kleinen Probleme löst..."
    mt "Die ich habe."
    mt "Es wäre einen Versuch wert."
    mt "Ich bin die schönste Frau dieses Abends."
    mt "Es wäre ein Leichtes für mich, einen reichen Mann zu finden."
    mt "Aber nicht diesen nutzlosen Sänger mit pinken Haaren. Pah!"
    mt "Dieser narzistische Schnösel gibt für kein Mädchen auch nur einen Cent aus!"
    mt "Ich werde einen besseren Mann finden!"
    mt "Und da kommt Rebecca in's Spiel..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:835
translate german ep211_dialogues2_public_event_25_8ec961d7:

    # m "Ребекка, не вижу никакой проблемы, чтобы познакомиться с ним."
    # m "Ждите меня здесь, девочки."
    # m "Я сейчас вернусь."
    m "Rebecca, ich sehe kein Problem darin, euch bekannt zu machen."
    m "Wartet auch mich hier, Mädels."
    m "Ich bin gleich wieder da."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:846
translate german ep211_dialogues2_public_event_26_655a17af:

    # mt "Сначала мне нужно подойти к этому никчемному Тернеру."
    mt "Erst muss ich diesen nutzlosen Turner ansprechen."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:853
translate german ep211_dialogues2_public_event_27_6487a28e:

    # mt "Джеймс Тернер."
    # mt "Никчемный исполнитель никчемных песен."
    # mt "И что Ребекка в нем нашла?"
    mt "James Turner"
    mt "Nutzloser Darsteller von nutzlosen Songs."
    mt "Was sieht Rebecca nur in ihm?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:861
translate german ep211_dialogues2_public_event_28_1588810d:

    # guest8 "Добрый вечер..."
    # guest8 "Моника Бакфетт, если не ошибаюсь?"
    # m "Все верно, Мистер Тернер. Добрый вечер."
    # guest8 "Рад знакомству."
    # guest8 "Вы уже пробовали вино, которое здесь подают?"
    # guest8 "Вполне неплохое..."
    # m "Да, пробовала. Очень вкусное."
    # mt "Какое вино?!"
    # mt "Не хватало еще испачкать платье!"
    # mt "Биф сказал что мне придется его отрабатывать... Даже боюсь вспоминать как..."
    guest8 "Guten Abend..."
    guest8 "Monica Buckfett, wenn ich Recht habe?"
    m "Das stimmt, Herr Turner. Guten Abend."
    guest8 "Freut mich, Sie zu treffen."
    guest8 "Haben Sie den Wein hier probiert?"
    guest8 "Gar nicht mal so schlecht..."
    m "Ja, habe ich. Sehr vorzüglich."
    mt "Welchen Wein?!"
    mt "Keine Lust, jetzt schon einen Fleck auf das Kleid zu bringen!"
    mt "Biff sagte, ich müsste das abarbeiten... Ich will gar nicht daran denken, wie..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:874
translate german ep211_dialogues2_public_event_28_5c765e14:

    # m "Мистер Тернер, я хотела бы Вас познакомить со своей подругой..."
    # guest8 "С подругой?"
    # m "Да. Вон та девушка в ярком платье."
    # guest8 "Ага. Видел ее."
    # guest8 "Она весь вечер пытается подкатить ко мне..."
    # guest8 "Так она Ваша подруга?"
    # m "Моя подруга и очень хорошая девушка."
    # mt "Я стала слишком много врать в последнее время..."
    # mt "Главное, чтобы это не вошло в привычку."
    # guest8 "..." 
    # guest8 "Вообще-то, я не против..." 
    # guest8 "И я прекрасно понимаю цель знакомства..."
    # m "..."
    # guest8 "Я познакомлюсь с ней при одном условии."
    # m "Каком условии, Мистер Тернер?"
    # guest8 "У меня планируется съемка нового клипа."
    # guest8 "Но я никак не могу подобрать подходящую локацию."
    # guest8 "Я слышал, что над интерьером Вашего дома работал какой-то известный дизайнер..."
    # guest8 "Я ранее видел его работы. И хочу сказать, что мне очень понравилось."
    # guest8 "Думаю, что Ваш дом вполне подойдет для съемки моего клипа."
    # m "???"
    # m "Это и есть Ваше условие, Мистер Тернер?"
    # guest8 "Да."
    # guest8 "Вы разрешаете мне снять клип в Вашем доме."
    # guest8 "А я соглашаюсь познакомиться с Вашей подругой."
    # mt "Вот дъявол!"
    m "Herr Turner, ich würde Sie gerne meiner Freundin vorstellen..."
    guest8 "Eine Freundin?"
    m "Ja. Die Frau in dem hellen Kleid."
    guest8 "Yeah, ich habe sie gesehen."
    guest8 "Sie versucht schon den ganzen Abend, mit mir zu sprechen..."
    guest8 "Sie ist also ihre Freundin?"
    m "Meine Freundin und eine sehr nette Person."
    mt "In letzter Zeit lüge ich echt zu viel..."
    mt "Hauptsache, das wird nicht zur Gewohnheit."
    guest8 "..." 
    guest8 "Ist mir eigentlich... egal..." 
    guest8 "Ich weiß durchaus, wie man dated."
    m "..."
    guest8 "Ich treffe mich mit ihr unter einer Bedingung."
    m "Welche, Herr Turner?"
    guest8 "Ich will ein neues Video drehen."
    guest8 "Aber ich finde einfach icht die richtige Location."
    guest8 "Ich habe gehört, dass einige berühmte Designer in Ihrem Haus gearbeitet haben..."
    guest8 "Ich habe die Arbeit schon früher mal gesehen. Ich mag es wirklich."
    guest8 "Ich denke, Ihr Haus wäre perfekt für mein Video."
    m "???"
    m "Das ist ihre Bedingung, Herr Turner?"
    guest8 "Ja."
    guest8 "Sie erlauben mit, ein Video in Ihrem Haus zu drehen."
    guest8 "Und ich treffe mich mit Ihrer Freundin."
    mt "Das ist der Teufel!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:903
translate german ep211_dialogues2_public_event_28_6a2909fc:

    # m "Мне приятно, что Вы хотите снять клип в стенах моего дома."
    # m "Я подумаю и дам Вам ответ немного позже..."
    # guest8 "Без проблем."
    # guest8 "Буду ждать."
    m "Ich fühle mich geehrt, dass Sie ein Video in meinem Haus machen wollen."
    m "Ich denke drüber nach und gebe Ihnen dann bescheid..."
    guest8 "Kein Problem."
    guest8 "Ich werde auf dich warten."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:915
translate german ep211_dialogues2_public_event_29_fe330b46:

    # mt "Я не хочу подходить к нему!"
    # mt "Сейчас будет опять просить снять свой никчемный клип в моем доме..."
    mt "Ich will nicht zu ihm hin!"
    mt "Jetzt fragt er mich dann gleich wieder, sein verdammtes Video in meinem Haus zu drehen..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:922
translate german ep211_dialogues2_public_event_30_7926b18d:

    # stephanie "Ну что?!"
    # rebecca "Он согласился?"
    stephanie "Und?!"
    rebecca "Hat er zugestimmt?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:926
translate german ep211_dialogues2_public_event_30_f5455032:

    # m "Он согласился при одном условии..."
    # rebecca "Каком условии?"
    # m "Он сказал, что хочет снять клип в моем доме."
    # m "Если я соглашусь, то он с тобой познакомиться, Ребекка."
    # rebecca "У тебя такой роскошный дом! Неудивительно что он попросил тебя об этом."
    # rebecca "И? Ты же согласилась, Моника?!"
    # m "Я сказала, что мне нужно подумать..."
    # rebecca "Что?!"
    # rebecca "Моника!!!"
    # rebecca "Ну пожалуйста скажи ему, что ты согласна!"
    # mt "Надо же, как она меня уговаривает..."
    # mt "Ее звездная карьера, практически в моих руках."
    # mt "Ха-ха!"
    # m "Я не хочу, чтобы кто-то топтался по моему дому своими грязными ногами..."
    # m "Ты ведь знаешь, что я не терплю чужаков на своей территории."
    # stephanie "Моника, зато в твоем доме снимут клип!"
    # stephanie "Это же круто!"
    # stephanie "Подумаешь, потопчутся немного."
    # stephanie "У тебя же есть гувернантка. Ей это все убирать, а не тебе."
    # mt "!!!"
    # m "Я подумаю, девочки..."
    m "Unter einer Bedingung..."
    rebecca "Welche?"
    m "Er sagte, er will ein Video in meinem Haus drehen."
    m "Wenn ich zustimme, dann will er sich mit Rebecca treffen."
    rebecca "Du hast so ein luxuriöses Zuhause! Kein Wunder, dass er dich gefragt hat."
    rebecca "UND? Du hast ja gesagt, oder, Monica?!"
    m "Ich sagte, ich muss darüber nachdenken..."
    rebecca "Was?!"
    rebecca "Monica!!!"
    rebecca "Bitte sag ihm, dass du zustimmst!"
    mt "Sie versucht mich zu überzeugen..."
    mt "Ihre Karriere ist sozusagen in meinen Händen."
    mt "Haha!"
    m "Ich will nicht, dass irgendwer mit dreckigen Füßen in meinem Haus rumtrampelt..."
    m "Ihr wisst, dass ich Außenstehende nicht auf meinem Grund toleriere."
    stephanie "Monica, aber sie wollen nur ein Video in deinem Haus drehen!"
    stephanie "Das ist so cool!"
    stephanie "Denk drüber nach."
    stephanie "Du hast ein Deinstmädchen, sie wird alles sauber machen, nicht du."
    mt "!!!"
    m "Ich denke drüber nach, Mädels..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:949
translate german ep211_dialogues2_public_event_30_c64d3953:

    # m "Он отказался."
    # rebecca "Отказался?"
    # m "Да. Сказал, что у него уже есть девушка."
    # m "И он ни с кем знакомиться не хочет."
    # rebecca "Жаль..."
    # rebecca "Это был отличный план."
    m "Er hat abgelehnt."
    rebecca "Hat er?"
    m "Ja. Er sagte, er hat schon eine Freundin."
    m "Und er will sich mit keiner Anderen treffen."
    rebecca "Tut mir leid..."
    rebecca "Das war ein so guter Plan."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:957
translate german ep211_dialogues2_public_event_30_ad4ffb94:

    # stephanie "Ребекка, не расстраивайся."
    # stephanie "У меня появилась отличная идея!"
    # stephanie "Почему бы тебе не сняться в журнале Моники?"
    # stephanie "Она легко сделает тебя известной."
    # mt "Твою мать!"
    # m "..."
    # rebecca "Да, но..."
    # rebecca "У Моники немного сменился курс журнала..."
    # m "..."
    # stephanie "Кстати, Моника, а почему ты приняла такое решение?"
    # stephanie "Ты ведь всегда так гордилась, что у тебя журнал о моде..."
    # stephanie "А теперь неожиданно изменила свое мнение..."
    # m "..."
    # m "Мне просто стало скучно, девочки."
    # m "Поэтому я приняла такое решение."
    # rebecca "Это правда, что ты участвуешь в откровенных фотосессиях?"
    # rebecca "Все об этом говорят."
    # m "Я не назвала бы их откровенными."
    # m "Я не раздеваюсь перед объективом камеры."
    # m "Просто провожу обычные фотосессии в красивых нарядах."
    # m "Я никогда не позволила бы себе показать на камеру..."
    # m "Какую-нибудь интимную часть своего прекрасного тела!"
    # stephanie "Ребекка, тогда тебе ничего не мешает сняться для журнала Моники!"
    # rebecca "Да, я тоже так думаю."
    # rebecca "Моника, ты же не будешь против?"
    # mt "Все! Они мне надоели!"
    # mt "Ведут себя, как две попрошайки."
    # mt "Моника дай то, Моника дай это..."
    # mt "!!!"
    stephanie "Rebecca, sei nicht sauer."
    stephanie "Ich habe eine tolle Idee!"
    stephanie "Warum modelst du nicht in Monicas Magazin?"
    stephanie "Sie macht dich problemlos berühmt."
    mt "Fuck!"
    m "..."
    rebecca "Ja, aber..."
    rebecca "Monica hat die Richtung des Magazines etwas verändert..."
    m "..."
    stephanie "Anbei, Monica, warum eigentlich?"
    stephanie "Du warst immer so stolz, dass du ein Modemagazin hast..."
    stephanie "Und jetzt hast du plötzlich deine Meinung geändert..."
    m "..."
    m "Es hat mich gelangweilt, Mädels."
    m "Daher diese Entscheidung."
    rebecca "Stimmt es, dass du in schmuddeligen Fotoshootings mitmachst?"
    rebecca "Jeder spricht davon."
    m "Ich würde sie anständig nennen."
    m "Ich ziehe mich nicht vor der Kamera aus."
    m "Ich mache nur normale Shootings in normalen Kleidern."
    m "Ich würde mich niemals nackt vor der Kamera zeigen..."
    m "Keine intimen Stellen meines Körpers!"
    stephanie "Rebecca, dann hält dich ja nichts davon ab, bei Monica zu modeln!"
    rebecca "Das denke ich auch."
    rebecca "Monica, macht es dir was aus?"
    mt "Ahhhh! Sie langweilen mich so!"
    mt "Benehmen sich wie zwei Bettler."
    mt "Monica, ich will dies und das..."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:990
translate german ep211_dialogues2_public_event_30_e13076e6:

    # m "Я подумаю, девочки..."
    # m "А теперь, извините, мне нужно идти."
    # m "Мне нужно поговорить по работе еще с несколькими знаменитыми гостями."
    # m "Пока, пожружки!"
    # stephanie "До встречи, дорогая!"
    # rebecca "Я буду ждать ответа, Моника!"
    # m "Конечно, Ребекка!"
    m "Ich denke drüber nach, Mädels..."
    m "Entschuldigt mich bitte, ich muss kurz weg."
    m "Ich muss mit ein paar anderen, berühmten Gästen sprechen."
    m "Tschö mit Ö!"
    stephanie "Bis dann!"
    rebecca "Ich warte auf deine Antwort, Monica!"
    m "Klar, Rebecca!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1003
translate german ep211_dialogues2_public_event_31_6d403a60:

    # mt "Не хочу больше к ним подходить!"
    # mt "Сейчас снова начнут у меня что-нибудь выпрашивать!"
    mt "Ich will mich ihnen nicht nochmal annnähren!"
    mt "Sonst fragen sie wieder nach was Anderem!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1011
translate german ep211_dialogues2_public_event_32_2e3a0d8b:

    # mt "Адриано!"
    # mt "Он без ума от меня."
    # mt "Он сделал великолепный дизайн интерьера моего дома."
    # mt "Он делает все, что я захочу, стоит мне только об этом сказать."
    mt "Adriano!"
    mt "Er ist verrückt nach mir."
    mt "Er hat ein tolles Innendesign für mein Haus gemacht."
    mt "Er macht alles, was ich will. Ich muss nur darüber sprechen."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1020
translate german ep211_dialogues2_public_event_33_b8185386:

    # guest7 "Моника!"
    # guest7 "Как я рад снова встретиться с тобой, дорогая!"
    # guest7 "Я так скучал по тебе!"
    # guest7 "Ты ослепительно прекрасна в этом платье!"
    # m "Здравствуй, Адриано..."
    # m "Признаться, я тоже соскучилась по тебе."
    # guest7 "Как я рад это слышать, дорогая!"
    # guest7 "Расскажи, как твои дела?"
    # guest7 "Все ли у тебя хорошо на работе?"
    # guest7 "Может быть, я могу чем-то быть полезным?"
    # guest7 "Ты же знаешь, я для тебя все готов сделать!"
    guest7 "Monica!"
    guest7 "Wie sehr ich mich freue, dich hier zu sehen!"
    guest7 "Ich habe dich so sehr vermisst!"
    guest7 "Du siehst so unfassbar gut in diesem Kleid aus!"
    m "Hallo Adriano..."
    m "Ich muss zugeben, du hast mir auch gefehlt."
    guest7 "Wie schön, dass du da bist, Schätzchen!"
    guest7 "Wie geht es dir?"
    guest7 "Wie läuft's in der Arbeit?"
    guest7 "Vielleicht kann ich hilfreich sein?"
    guest7 "Ich mache alles für dich!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1034
translate german ep211_dialogues2_public_event_33_a977d0cc:

    # m "Адриано, ты и правда на все готов ради меня?"
    # guest7 "Да, Моника!"
    # guest7 "Мое сердце всегда будет принадлежать только тебе!"
    # guest7 "В тот день, когда ты мне ответишь взаимностью..."
    # guest7 "Я стану самым счастливым мужчиной на свете!"
    # mt "Хм, мило..."
    # mt "Мне он, конечно, совсем не нравится..."
    # mt "Но..."
    # mt "Адриано тот человек, который сможет мне помочь с деньгами."
    # mt "На него я смогу положиться."
    # mt "И, наконец, решить свои временные трудности."
    # mt "Только... Что ему сказать?"
    # mt "Не рассказывать же ему всю правду..."
    m "Adriano, bist du wirklich bereit für mich?"
    guest7 "Ja..."
    guest7 "Mein Herz wird immer dir gehören!"
    guest7 "Der Tag, an dem du das auch so siehst..."
    guest7 "Wird der schönste Tag meines Lebens!"
    mt "Uh, wie nett..."
    mt "Ich mag ihn eigentlich nicht..."
    mt "Aber..."
    mt "Adriano aber ist der Mann, der mir finanziell aushelfen kann."
    mt "Ich kann mich auf ihn verlassen."
    mt "Endlich kann ich meine zeitweiligen Probleme lösen."
    mt "Aber... Was soll ich ihm sagen?"
    mt "Ich kann ihm nicht die ganze Wahrheit sagen..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1050
translate german ep211_dialogues2_public_event_33_ba7a0965:

    # m "Адриано, может мы поужинаем?.."
    # biff "Ты хочешь пригласить к нам на ужин Адриано?"
    # biff "Отличная идея, дорогая!"
    # biff "Адриано, вы придете к нам с Моникой вместе со своей женой?"
    # guest7 "..."
    # biff "Мы устроим замечательный вечер и познакомимся семьями."
    # biff "Да, дорогая?"
    # guest7 "Моника, это... Это твой муж?"
    # biff "Да. Меня зовут Биф. Приятно познакомиться!"
    # mt "Что он несет?!"
    # mt "!!!"
    # m "Биф!"
    # guest7 "Моника..." 
    # m "Адриано! Подожди!"
    # guest7 "Не знал, что ты снова вышла замуж... Я... Я рад за тебя."
    # m "Адриано!"
    # m "Биф!!!"
    # guest7 "Биф, у меня не получится отужинать с вами."
    # biff "Жаль!"
    # biff "До свидания, Адриано!"
    # guest7 "Всего хорошего!" 
    # m "Биф!!!"
    # m "Какого черта ты влез в наш разговор!"
    # m "Что еще за шуточки про мужа!!!"
    # m "Мне нужно поговорить с ним!"
    # m "Отпусти меня!"
    # biff "Ты никуда не пойдешь!"
    # biff "Успокойся и не веди себя как истеричная безмозглая кукла!"
    # biff "Ты забыла, что ты должна притворяться Моникой Бакфетт?"
    # m "Зачем ты ему сказал, что ты мой муж?!"
    # biff "Потому что он пускал слюни на тебя."
    # biff "Я понимаю, что такая глупая кукла как ты, пытается с кем-то познакомиться здесь."
    # biff "Но не забывай, что ты лишь только притворяешься Моникой Бакфетт!"
    # biff "Что бы было, если бы ты встретилась с ним?!"
    # biff "Он бы сразу понял, что ты дешевая шлюха, а не та, за кого себя выдаешь!"
    # biff "Папочка не хочет терять репутацию из-за тебя!"
    # m "Что?!"
    # biff "Что слышала!"
    # biff "Закрой рот и не беси меня!"
    # biff "Нам сейчас надо поговорить с Мистером Кэпбеллом."
    # biff "Он один из инвесторов, если ты вдруг забыла."
    # biff "Ты же помнишь своими мозгами, которых почти нет, что должна сделать все..."
    # biff "Чтобы инвестор дал свое согласие на сотрудничество с нами?"
    # mt "!!!"
    # mt "Сволочь!"
    # mt "Придурок!"
    # biff "Вон стоит этот денежный мешок."
    # biff "Подойдем к нему."
    # mt "!!!"
    m "Adriano, können wir zusammen essen?"
    biff "Willst du Adriano zu unserem Dinner einladen?"
    biff "Das ist eine gute Idee, Darling!"
    biff "Adriano, kommst du mit meiner Frau Monica und mir mit?"
    guest7 "..."
    biff "Wir werden einen wunderbaren Abend haben und unsere Familien kennen lernen."
    biff "Ja, Darling?"
    guest7 "Monica, ist... ist das dein Ehemann?"
    biff "Ja. Mein Name ist Biff. Schön Sie kennen zu lernen."
    mt "Was geht denn jetzt?!"
    mt "!!!"
    m "Biff!"
    guest7 "Monica..." 
    m "Adriano, warte!"
    guest7 "Ich wusste nicht, dass Sie wieder verheiratet sind... Es... es freut mich für Sie."
    m "Adriano!"
    m "Biff!!!"
    guest7 "Biff, ich kann mit dir nicht essen."
    biff "Das wäre eine Schande!"
    biff "Auf Wiedersehen, Adriano!"
    guest7 "Viel Glück!" 
    m "Biff!!!"
    m "Was zum Teufel sollte das?"
    m "Was machst du für Witze über meinen Mann?"
    m "Ich muss mit ihm reden!"
    m "Lass mich los!"
    biff "Du gehst nirgendwo hin!"
    biff "Beruhige Dich und benimm Dich nicht wie eine Irre!"
    biff "Hast du vergessen, dass du so tun musst, als wärst du Monica Buckfett?"
    m "Warum hast du ihm gesagt, dass du mein Mann bist?!"
    biff "Weil er in dich vernarrt ist."
    biff "Ich verstehe schon, dass ein Trottel wie du versucht, jemanden hier kennen zu lernen."
    biff "Aber vergiss nicht, dass du nur vorgeben sollst, dass du Monica Buckfett bist."
    biff "Was wäre passiert, wenn du ihn getroffen hättest?"
    biff "Er hätte sofort gemerkt, dass du eine billige Hure bist und nicht die, für die du dich ausgibst."
    biff "Daddy will wegen dir nicht seinen Ruf gefährden!"
    m "Was?!"
    biff "Was hast du gehört?"
    biff "Halt deinen Mund und geh mir nicht auf die Nerven!"
    biff "Wir müssen jetzt mit Herrn Campbell reden."
    biff "Er ist einer der Investoren, falls du das schon vergessen hast."
    biff "Du erinnerst dich hoffentlich, mit deinem Mikrogehirn, dass du alles tun musst..."
    biff "Was ein Investor will, damit er mit uns kooperiert?"
    mt "!!!"
    mt "Du Bastard!"
    mt "Idiot!"
    biff "Dieser Geldsack ist es wert."
    biff "Gehen wir zu ihm."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1109
translate german ep211_dialogues2_public_event_34_7ae94873:

    # mt "Мистер Кэмпбелл."
    # mt "Хозяин этого вечера."
    # mt "Богатый, но крайне жадный неудачник. Фи!"
    mt "Herr Campbell."
    mt "Der Gastgeber dieses Abends."
    mt "Ein reicher, aber extrem ekliger Loser! Pah!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1117
translate german ep211_dialogues2_public_event_35_02deca4b:

    # biff "Мистер Кэмпбэлл, мы с Миссис Бакфетт хотели бы поздравить Вас."
    # m "Добрый вечер, Мистер Кэмбелл."
    # mt "Идиот Биф готов в задницу целовать этого мерзкого Мистера Кэмпбелла."
    # campbell "Добрый вечер."
    # biff "Ваша компания уже много лет развивается очень успешно."
    # biff "Как и наш журнал."
    # campbell "Да, что касается вашего журнала..."
    # campbell "Я внимательно изучил документацию, которую вы мне прислали."
    # campbell "Но я еще не готов озвучить свое решение..."
    # campbell "Ведь речь идет о довольно крупной сумме денег."
    # campbell "Я не привык раскидываться деньгами понапрасну."
    # campbell "Я должен быть уверен в том, что не потеряю ни цента."
    # campbell "Эта сделка должна быть взаимовыгодной. Вы понимаете, о чем я?"
    # biff "Да, конечно, Мистер Кэмпбелл."
    # biff "Мы готовы предоставить вам всю необходимую информацию."
    # campbell "Миссис Бакфетт, вы являетесь лицом журнала..."
    # campbell "Вы сами как относитесь к столь радикальной смене курса журнала?"
    # mt "Я готова разорвать этого чертового Бифа с его идиотскими идеями!!!"
    # mt "Или придушить... Нет, лучше ударить бутылкой по его пустой голове!!!"
    biff "Herr Campbell, Frau Buckfett und ich möchten Ihnen gerne gratulieren."
    m "Guten Abend, Herr Campbell."
    mt "Biff der Idiot küsst den Arsch von Herrn Campbell."
    campbell "Guten Abend."
    biff "Ihr Unternehmen ist seit Jahren sehr erfolgreich."
    biff "So wie unser Magazin."
    campbell "Ja, wegen dem Magazin..."
    campbell "Ich habe die Mappe studiert, die Sie mir geschickt haben."
    campbell "Aber ich kann noch keine Entscheidung fällen..."
    campbell "Immerhin reden wir von viel Geld."
    campbell "Ich will kein Geld aus dem Fenster werfen."
    campbell "Ich muss sicher sein, dass ich kein Geld verliere."
    campbell "Dieser Deal muss wirklich lohnend sein. Wissen Sie, was ich meine?"
    biff "Ja, natürlich, Herr Campbell."
    biff "Wir können Ihnen all die nötige Information geben."
    campbell "Frau Buckfett, Sie sind das Gesicht des Magazines..."
    campbell "Wie fühlen Sie sich bei so einem drastischen Kurswechsel?"
    mt "Ich werde diesen verdammten Biff vernichten... und seine dummen Ideen gleich mit!!!"
    mt "Oder erwürgen?... Nein, besser, wenn ich seinen leeren Kopf mit einer ebensolchen Flasche zerschmerttere!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1143
translate german ep211_dialogues2_public_event_35_8d1d8508:

    # m "Мистер Кэмпбелл, я поддерживаю эту идею."
    # m "Я уверена, что Вы сделаете правильный выбор, сделав инвестицию в наш журнал."
    # campbell "До меня дошли слухи, что Вы настолько поддерживаете эту идею..."
    # campbell "Что сами позируете на фотосессиях, Миссис Бакфетт."
    # mt "!!!"
    # biff "Да, Мистер Кэмбелл. Миссис Бакфетт провела уже несколько фотосессий."
    # biff "Желаете посмотреть снимки с этих фотосессий, Мистер Кэмпбелл?"
    # mt "Что?!?!?!"
    # m "Биф!"
    # campbell "Да, я бы посмотрел. Но не только на снимки..."
    # mt "!!!"
    # campbell "Моя компания занимается пошивом дизайнерской одежды."
    # campbell "Я хотел бы прорекламировать свою последнюю коллекцию."
    # campbell "Я готов предоставить платье для проведения фотосессии..."
    # campbell "Также я хочу посмотреть на работу журнала, так сказать, изнутри."
    # campbell "Если у Миссис Бакфетт запланированы фотосессии на ближайшее время..."
    # campbell "То я хотел бы поприсутствовать на одной из них."
    # mt "!!!"
    # biff "Да, конечно, Мистер Кэмпбелл! Мы будем рады Вашему визиту!"
    # mt "Вот сволочь!!! Что он несет?!"
    # m "Биф, я..."
    # biff "Миссис Бакфетт хочет сказать, что на днях у нее будет фотосессия."
    # biff "Она Вас приглашает поприсутствовать на ней, Мистер Кэмпбелл."
    # biff "Мы с радостью проведем эту фотосессию в предоставленном Вами наряде!"
    # mt "Я убью этого придурка Бифа!"
    # campbell "Договорились. Сообщите мне и я приеду к вам."
    # campbell "Возможно, после фотосессии, я приму решение по инвестиции в ваш журнал."
    # biff "Отлично, Мистер Кэмпбелл! Будем рады Вас видеть!"
    # m "Биф, как ты себе это представляешь?!"
    # m "!!!"
    # biff "Цыпочка обещала быть хорошей."
    # biff "Она сделает так, чтобы инвесторы несли мне свои деньги."
    # biff "Скоро у цыпочки будет возможность продемонстрировать свою работу..."
    # biff "Так, чтобы у этого мешка с деньгами не осталось никаких сомнений."
    # biff "Ты поняла меня?"
    # m "..."
    m "Herr Campbell, mir gefällt diese Idee."
    m "Ich bin sicher, dass es die richtige Entscheidung ist, in unser Magazin zu investieren."
    campbell "Ich habe Gerüchte gehört, dass sie die neue Idee sehr unterstützen..."
    campbell "Dass Sie selbst für Fotos posieren, Frau Buckfett."
    mt "!!!"
    biff "Ja, Herr Campbell. Frau Buckfett hatte bereits einige Fotosessions."
    biff "Möchten Sie die Bilder sehen, Herr Campbell?"
    mt "Was?!?!?!"
    m "Biff!"
    campbell "Ja, gerne. Aber nicht nur die Bilder..."
    mt "!!!"
    campbell "Meine Firma stellt Designerkleider her."
    campbell "Ich würde gerne meine letzte Kollektion bewerben."
    campbell "Ich möchte dazu ein Kleid für ein Shooting auswählen..."
    campbell "Und gleichzeitig einen Blick aus dem Inneren des Magazines."
    campbell "Wenn Frau Buckfett in naher Zukunft ein Shooting plant..."
    campbell "Dann würde ich gerne daran teilnehmen."
    mt "!!!"
    biff "Ja, natürlich, Herr Campbell! Wir freuen uns auf Ihren Besuch!"
    mt "Was für ein Bastard!!! Was wird das?!"
    m "Biff, Ich..."
    biff "Frau Buckfett möchte gerne sagen, dass sie nächsten Tag ein Shooting hat."
    biff "Sie möchte Herrn Campbell dazu einladen."
    biff "Und gerne das Shooting in dem Outfit machen, das Herr Campbell aussuchen wird!"
    mt "Ich werde Biff töten!"
    campbell "Ich stimme zu. Melden Sie sich, und ich komme."
    campbell "Vielleicht mache ich nach dem Shooting eine Aussage zu dem Investment in das Magazin."
    biff "Toll Herr Campbell! Wir freuen uns schon!"
    m "Biff, wie stellst du dir das vor?!"
    m "!!!"
    biff "Das Mädchen hat doch versprochen, brav zu sein."
    biff "Sie wird dafür sorgen, dass die Investoren Geld einzahlen."
    biff "Bald wird das Mädchen die Gelegenheit dazu haben, ihre Arbeit zu würdigen..."
    biff "Dann wird dieser Geldsack keine Zweifel mehr haben."
    biff "Verstanden?!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1193
translate german ep211_dialogues2_public_event_35_7f599f0c:

    # m "Биф, я не буду проводить фотосессию в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # m "Почему я?! Почему не Мелани?"
    # biff "Потому что Мистер Кэмпбелл так хочет."
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "Biff, ich werde kein Fotoshooting in Anwesenheit dieses Investors machen!"
    m "Ich will nicht, dass er mich anstarrt!"
    m "Warum ich? Warum nicht Melanie?"
    biff "Weil es Herr Campbell so will."
    biff "Du wirst nie wieder einen Job bekommen..."
    biff "Also mach es auch so."
    mt "Verdammter Campbell. Verdammter Biff. Ich hasse sie alle!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1202
translate german ep211_dialogues2_public_event_35_f6028d59:

    # mt "Сволочь!"
    # mt "!!!"
    # mt "С другой стороны, это будет дорогое дизайнерское платье..."
    # mt "Скорее всего, оно будет восхитительно на мне смотреться."
    # mt "Вряд ли оно будет слишком откровенным или пошлым."
    # m "..."
    # m "Я проведу эту фотосессию, Биф."
    # biff "Ну вот. Другое дело, цыпочка. Папочка тобой доволен."
    mt "Du Bastard!"
    mt "!!!"
    mt "Andererseits, es geht um ein sehr teures Designerstück..."
    mt "Es wird wahrscheinlich großartig an mit aussehen."
    mt "Und wahrscheinlich ist es nicht unangemessen oder vulgär."
    m "..."
    m "Ich mache das Shooting, Biff."
    biff "Na also. Noch was, Mädchen. Daddy ist zufrieden mit dir."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1217
translate german ep211_dialogues2_public_event_36_c98a233a:

    # mt "Это место мне нравится..."
    # mt "Не то что тот дешевый ресторан в отеле. Фи!"
    mt "Ich mag diesen Ort..."
    mt "Nicht wie das billige Hotelrestaurant. Pah!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1223
translate german ep211_dialogues2_public_event_37_0357f681:

    # mt "Какое интересное дизайнерское решение в центре терассы."
    mt "Was für eine tolle Designlösung hier auf der Terrasse."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1228
translate german ep211_dialogues2_public_event_38_d1be412f:

    # mt "С этой терассы открывается чудесный вид на ночной город."
    mt "Diese Terrasse gewährt einen traumhaften Blick über die Stadt."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1233
translate german ep211_dialogues2_public_event_39_a97df8b2:

    # mt "Здесь очень уютные столики и приятная атмосфера."
    # mt "Видно, что над клубом Мистера Кэмпбелла работал хороший дизайнер."
    mt "Hier sind sehr bequeme Stühle und eine tolle Atmosphäre."
    mt "Es ist offensichtlich, dass ein guter Designer hier am Werk war."

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:69
    old "Я хорошо выполняю свою работу!"
    new "Ich mache meinen Job gut!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:86
    old "Как я это сделаю?"
    new "Wie soll ich das machen?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:151
    old "Переодеться в вечернее платье."
    new "Zieh Dir ein Abendkleid an."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:192
    old "Поехать на мероприятие вместе с Бифом."
    new "Gehe mit Biff zu dem Event."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:266
    old "Пообщаться с гостями."
    new "Rede mit den Gästen."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:293
    old "У меня были другие, более важные дела..."
    new "Ich habe andere, wichtigere Dinge zu tun..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:304
    old "Я так не считаю, Миссис Уайт."
    new "Nein, hat es nicht, Frau White."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:318
    old "Мой журнал был всегда успешнее Вашего бульварного чтива."
    new "Mein Magazin war schon immer erfolgreicher als dein Schundblatt."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:376
    old "Какие пробы, Грейс?"
    new "Welche Tests, Grace?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:386
    old "Мелани в отпуске."
    new "Melanie ist im Urlaub."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:400
    old "И что тебе на это пообещал мой менеджер Биф?"
    new "Und was hat dir mein Manager Biff zugesagt?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:454
    old "Спасибо, Исаак."
    new "Danke, Isaac."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:468
    old "Ты неверно понял моего менеджера."
    new "Du hast meinen Manager falsch verstanden."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:527
    old "У меня были другие, более важные дела."
    new "Ich habe andere, wichtigere Dinge zu tun."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:548
    old "Вы обсуждали эту работу с Алексом?"
    new "Hast du mit Alex darüber gesprochen?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:627
    old "Мистер Кэмпбелл пригласил сегодня всю элиту мира моды."
    new "Herr Campbell hat die Elite der ganzen Modewelt eingeladen."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:640
    old "У нас с Миссис Уайт несколько напряженные отношения."
    new "Frau White und ich haben eine enge Beziehung."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:738
    old "Моника ходила на фитнес с Бетти"
    new "Monica ging mit Betty zum Workout"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:742
    old "Я же вам говорила, что у меня приключения..."
    new "Ich habe doch gesagt, dass ich Abenteuer machen..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:787
    old "Ребекка, у тебя такой интересный наряд сегодня!"
    new "Rebecca, dein Outfit ist so toll heute!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:832
    old "Ребекка, не вижу никакой проблемы, чтобы познакомиться с ним."
    new "Rebecca, ich sehe kein Problem darin, euch bekannt zu machen."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:839
    old "Поговорить с Тернером."
    new "Rede mit Turner."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:871
    old "Мистер Тернер, я хотела бы Вас познакомить со своей подругой..."
    new "Herr Turner, ich würde Sie gerne meiner Freundin vorstellen..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:900
    old "Мистер Тернер, мне нужно подумать."
    new "Herr Turner, ich muss darüber nachdenken."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:908
    old "Вернуться к Ребекке и Стефани."
    new "Gehe zurück zu Rebecca und Stephanie."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:924
    old "Он согласился при одном условии..."
    new "Unter einer Bedingung..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:924
    old "Он отказался."
    new "Er hat abgelehnt."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:987
    old "Я подумаю, девочки."
    new "Ich denke drüber nach, Mädels."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1031
    old "Адриано, ты и правда на все готов ради меня?"
    new "Adriano, bist du wirklich bereit für mich?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1047
    old "Пригласить Адриано на ужин."
    new "Lade Adriano zum Abendessen ein."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1101
    old "Подойти к Мистеру Кэмбеллу."
    new "Gehe rauf zu Herrn Campbell."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1140
    old "Я поддерживаю эту идею."
    new "Ich unterstütze diese Idee."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1188
    old "Я не буду участвовать в этом!"
    new "Da mache ich nicht mit!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1210
    old "Провести фотосессию в платье от инвестора."
    new "Mache ein Fotoshooting in einem Kleid des Investors"

