# TODO: Translation updated at 2020-03-31 14:42

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:7
translate german ep211_dialogues3_photoshoot_1_58686973:

    # mt "Сегодня у меня фотосессия в каком-то наряде от инвестора."
    # mt "Надеюсь, это будет приличный наряд..."
    mt "Heute habe ich ein Fotoshooting in einem Investorenoutfit."
    mt "Ich hoffe, es ist anständig..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:15
translate german ep211_dialogues3_photoshoot_2_0659dabc:

    # mt "!!!"
    # biff "В скором времени, Я планирую опубликовать эти кадры в широкий доступ."
    # mt "ЧТО-О-О?!"
    # mt "!!!!!"
    # campbell "Опубликуйте их после фотосессии в моем платье 'Королева сердец'."
    # campbell "Если вы их опубликуете до этой фотосессии..."
    # campbell "То снимки в моем платье будут публике неинтересны."
    # biff "Конечно, Мистер Кэмпбелл!"
    # biff "Кстати, Миссис Бакфетт уже пришла на фотосессию."
    # biff "Можете проходить в фотостудию, Мистер Кэмпбелл."
    # campbell "Да, спасибо."
    # m "Биф!"
    # m "Зачем ты показал эти фотографии инвестору?!"
    # m "!!!"
    # biff "Я тебя забыл спросить, кукла безмозглая, что мне делать!"
    # biff "Ты не задаешь вопросы, когда сосешь на улице члены за $ 20!.."
    # biff "Но пытаешься спорить, когда я показываю твою задницу, даже без члена в ней, состоятельному инвестору!"
    # biff "Не забывай, какая деньги я плачу тебе, кукла!"
    # m "!!!"
    # biff "Хватит орать тут и быстро иди переодевайся!"
    # biff "Тебя ждет Мистер Кэмпбелл. И только попробуй сорвать эту фотосессию!!!"
    # biff "Я тебя в один миг вышвырну отсюда на улицу!!!"
    # mt "ААААААА!"
    # mt "НЕНАВИЖУ!!!"
    # mt "УБЬЮ!!!"
    mt "!!!"
    biff "Ich plane, diese Bilder bald großflächig zu verbreiten."
    mt "BITTE WAS?!"
    mt "!!!!!"
    campbell "Veröffentliche sie nach dem Fotoshooting in meinem Queen of Hearts Kleid."
    campbell "Wenn du sie vorher veröffentlichst..."
    campbell "Werden die Bilder mit meinem Outfit nicht mehr so interessant sein."
    biff "Natürlich, Herr Campbell!"
    biff "Anbei, Frau Buckfett ist bereit für das Fotoshooting."
    biff "Sie können in das Studio gehen, Herr Campbell."
    campbell "Ja, danke."
    m "Biff!"
    m "Warum hast du diese Fotos dem Investor gezeigt?!"
    m "!!!"
    biff "Ich habe vergessen, dich zu fragen, hirnlose Puppe. Was sollte ich tun?"
    biff "Du stellst auch keine Fragen, wenn du auf der Straße schwänze für 20 $ lutscht..."
    biff "Aber du willst diskutieren, wenn ich deinen Arsch her zeige, sogar wenn kein Schwanz drin ist!"
    biff "Не забывай, какая деньги я плачу тебе, кукла!"
    m "!!!"
    biff "Hör auf zu heulen und geh dich endlich umziehen!"
    biff "Herr Campbell wartet schon. Und versuch, dieses Shooting nicht zu verkacken!!!"
    biff "Sonst schmeiße ich dich sofort raus!!!"
    mt "ААААААА!"
    mt "ICH HASSE SIE!!!"
    mt "TÖTE!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:52
translate german ep211_dialogues3_photoshoot_3_6026cae9:

    # m "Алекс!!!"
    # m "Это разве платье?!?!?!"
    # m "Эта тряпка на мне совсем не закрывает мою грудь!!!"
    # m "Алекс, как я буду сниматься в этом?! Да еще и при этом инвесторе?!"
    # alex_photograph "Миссис Бакфетт, не переживайте."
    # alex_photograph "Это платье очень Вам идет! Вы в нем настоящая королева!"
    # alex_photograph "Я буду делать кадры, на которых ничего не будет видно."
    # mt "Этот фотограф-извращенец всегда так говорит, а в итоге..."
    # mt "Нужно сходить к Бифу и послать его к черту!"
    # mt "Или пусть предоставит другое платье!"
    # mt "Или фотосессия отменяется!"
    m "Alex!!!"
    m "Soll das ein Kleid sein?!?!?!"
    m "Dieser Fetzen verdeckt nicht meine Brüste!!!"
    m "Alex, wie soll ich das machen? Und was ist mit dem Investor?!"
    alex_photograph "Keine Sorge, Frau Buckfett."
    alex_photograph "Das Kleid steht dir total gut! Du bist eine wahre Königin darin!"
    alex_photograph "Ich mache Bilder aus einem Winkel, aus dem man nichts sieht."
    mt "Der perverse Fotograf sagt das immer, aber am Ende..."
    mt "Ich muss zu Biff und das verschieben!"
    mt "Oder ein anderes Kleid auswählen lassen!"
    mt "Oder das gleich alles absagen!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:71
translate german ep211_dialogues3_photoshoot_4_7ba4ad62:

    # m "Биф, я не буду фотографироваться в ЭТОМ!!!"
    # m "Это не платье!"
    # m "У меня вся грудь открыта в нем!!!"
    # m "!!!"
    # biff "У тебя, кукла, никто не спрашивал!"
    # m "Биф, я предупреждаю, что я не буду делать никаких откровенных кадров!"
    # m "Я соглашусь на кадры только с прикрытой грудью!"
    # biff "А я тебя предупреждаю, что если Кэмпбелл откажется инвестировать..."
    # biff "То виновата в этом будешь ты, кукла безмозглая!"
    # biff "У тебя не хватает мозгов понять, что от этой фотосессии многое зависит?"
    # biff "Проведи ее и чтобы никаких глупостей!"
    # biff "Это твоя работа! Ты получаешь за это немаленькие деньги!"
    # biff "Иди в фотостудию!"
    # mt "Мерзавец!"
    # mt "!!!"
    m "Biff, DARIN will ich nicht fotografiert werden!!!"
    m "Das ist kein Kleid!"
    m "Meine Brüste hängen raus!"
    m "!!!"
    biff "Niemand fragt dich, Puppe!"
    m "Biff, ich warne dich, lass keine schmuddeligen Fotos machen!"
    m "Ich stimme nur Fotos zu, bei denen meine Brüste bedeckt sind!"
    biff "Und ich warne dich: Wenn Campbell nicht investieren will..."
    biff "Dann bist du daran Schuld, hirnlose Puppe!"
    biff "Hast du genug Verstand und zu kapieren, dass von dem Shooting sehr viel abhängt?"
    biff "Hör also auf mit dem Unsinn!"
    biff "Das ist dein Job! Du bekommst einen Haufen Geld dafür!"
    biff "Geh ins Fotostudio!"
    mt "Bastard!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:92
translate german ep211_dialogues3_photoshoot_4_7d321a67:

    # m "Биф, я не буду фотографироваться в этом платье!"
    # m "Да еще в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # m "Почему я?! Почему не Мелани?"
    # biff "Потому что Мистер Кэмпбелл так хочет!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # biff "Если будешь и дальше спорить со мной..."
    # biff "Я заставлю тебя фотографироваться с членом во рту!"
    # mt "!!!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "Biff, ich lasse mich darin nicht fotografieren!"
    m "Ja, und erst recht nicht, wenn der Investor dabei ist!"
    m "Ich will nicht, dass er mich anstarrt!"
    m "Warum ich? Warum nicht Melanie?"
    biff "Herr Campbell will es so!"
    biff "Du wirst nie wieder einen Job bekommen..."
    biff "Also mach es auch so."
    biff "Wenn du weiter diskutierst..."
    biff "Dann zwinge ich dich dazu, die Bilder mit einem Schwanz in deinem Mund zu machen!"
    mt "!!!"
    mt "Verdammter Campbell. Verdammter Biff. Ich hasse sie alle!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:106
translate german ep211_dialogues3_photoshoot_4_3748637d:

    # mt "Дъявол!"
    # mt "Он вышвырнет меня с работы, если я откажусь."
    # mt "А мне нужны деньги."
    # mt "Где я смогу заработать 5 тысяч в месяц для сучки Виктории?"
    # m "Я проведу эту фотосессию..."
    # biff "Иди в фотостудию."
    # mt "Чертов Биф!"
    # mt "На публичном вечере я всем сказала, что публика никогда не увидит мою грудь!"
    # mt "Что я всем им скажу теперь?! О ужас!!!"
    # mt "!!!"
    mt "Böses Arschloch!"
    mt "Er schmeißt mich raus, wenn ich ablehne."
    mt "Und ich brauche das Geld."
    mt "Wo kann ich fünf Riesen für diese Bitch Victoria verdienen?"
    m "Ich mache das Fotoshooting..."
    biff "Geh ins Fotostudio!"
    mt "Verdammter Biff!"
    mt "Ich habe Jedem gesagt, dass man nie meine Brüste öffentlich sehen wird!"
    mt "Was sage ich denen jetzt allen? Oh Gott!!!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:122
translate german ep211_dialogues3_photoshoot_5_1173bb4f:

    # m "Биф..."
    # m "Мне нужна работа."
    # biff "Если цыпочка хочет работать, она сделает фотосессию."
    # biff "В платье от инвестора и в его присутствии."
    # m "..."
    # biff "Ты согласна?"
    # mt "!!!"
    m "Biff..."
    m "Ich brauche einen Job."
    biff "Wenn das Mädchen arbeiten will, dann macht sie einfach ein Shooting."
    biff "In einem Kleid des Investors und in seiner Anwesenheit."
    m "..."
    biff "Bist Du einverstanden?"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:134
translate german ep211_dialogues3_photoshoot_5_68ecbce7:

    # m "Нет! Я не буду фотографироваться в этом платье!"
    # m "Да еще в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # biff "Если будешь и дальше спорить со мной..."
    # biff "Я заставлю тебя фотографироваться с членом во рту!"
    # mt "!!!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "Nein! Ich werde nicht in diesem Kleid fotografiert werden!"
    m "Ja, und erst recht nicht, wenn der Investor dabei ist!"
    m "Ich will nicht, dass er mich anstarrt!"
    biff "Du wirst nie wieder einen Job bekommen..."
    biff "Also mach es auch so."
    biff "Wenn du weiter diskutierst..."
    biff "Dann zwinge ich dich dazu, die Bilder mit einem Schwanz in deinem Mund zu machen!"
    mt "!!!"
    mt "Verdammter Campbell. Verdammter Biff. Ich hasse sie alle!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:146
translate german ep211_dialogues3_photoshoot_5_5f6298e9:

    # mt "Дъявол!"
    # mt "Он вышвырнет меня с работы, если я откажусь."
    # mt "А мне нужны деньги."
    # mt "Где я смогу заработать 5 тысяч в месяц для сучки Виктории?"
    # mt "..."
    # mt "На публичном вечере я всем сказала, что публика никогда не увидит мою грудь!"
    # mt "Что я всем им скажу теперь?! О ужас!!!"
    # mt "..."
    # m "Я проведу эту фотосессию..."
    # biff "Иди переодевайся."
    # biff "Я пока позвоню Мистеру Кэмпбеллу, чтобы приехал на съемку."
    # mt "..."
    mt "Böses Arschloch!"
    mt "Er schmeißt mich raus, wenn ich ablehne."
    mt "Und ich brauche das Geld."
    mt "Wo kann ich fünf Riesen für diese Bitch Victoria verdienen?"
    mt "..."
    mt "Ich habe Jedem gesagt, dass man nie meine Brüste öffentlich sehen wird!"
    mt "Was sage ich denen jetzt allen? Oh Gott!!!"
    mt "..."
    m "Ich mache das Fotoshooting..."
    biff "Zieh dich um."
    biff "Ich hole Herrn Campbell für das Shooting."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:165
translate german ep211_dialogues3_photoshoot_6_930bd5eb:

    # m "Алекс!"
    # m "Только попробуй взять ракурс, где будет видна моя... моя..."
    # campbell "Миссис Бакфетт, Вам нравится платье, которое я Вам подбрал?"
    # mt "Биф сказал, что от этой фотосессии зависит решение этого неудачника..."
    # mt "Если я сделаю что-то не так, он откажется от инвестирования в журнал..."
    # mt "Тогда Биф выгонит меня с этой работы..."
    # mt "А мне нужны деньги для этой сучки Виктории."
    # mt "Черт!!!"
    m "Alex!"
    m "Versuch mal, einen Blickwinkel zu finden wo... wo..."
    campbell "Frau Buckfett, gefällt Ihnen das Kleid, das ich ausgesucht habe?"
    mt "Biff sagte, dass die Entscheidung des Losers von diesem Fotoshooting abhängt..."
    mt "Wenn ich was falsch mache, wird er nicht in das Magazin investieren..."
    mt "Dann wird mich Biff feuern..."
    mt "Aber ich brauche das Geld für Victoria."
    mt "Verdammt!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:179
translate german ep211_dialogues3_photoshoot_6_9a6a2d68:

    # m "Платье мне нравится, Мистер Кэмпбелл..."
    # m "Только мне кажется, что оно несколько откровенное..."
    # campbell "Вы сами мне сказали, что поддерживаете новый курс журнала."
    # campbell "Я подобрал платье в соответствии с курсом Вашего журнала."
    # campbell "И нахожу его весьма подходящим для Вас, Миссис Бакфетт."
    # campbell "Приступайте!"
    # mt "Мерзкий тип!"
    # mt "Скорее надо провести эту долбанную фотосессию..."
    # mt "И пусть он убирается отсюда!"
    # alex_photograph "Приступим, Миссис Бакфетт."
    m "Ich mag das Kleid, Herr Campbell..."
    m "Aber es wirkt auf mich ein klein wenig..."
    campbell "Sie selbst haben mir gesagt, dass Sie den neuen Kurs des Magazins unterstützen."
    campbell "Ich habe das Kleid gemäß diesem Kurs ausgesucht."
    campbell "Und ich denke, es steht Ihnen sehr gut, Frau Buckfett."
    campbell "Machen Sie weiter!"
    mt "Blödmann!"
    mt "Ich mache besser dieses blöde Shooting..."
    mt "Und bald ist alles vorbei!"
    alex_photograph "Los geht’s, Frau Buckfett."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:198
translate german ep211_dialogues3_photoshoot_7_2d9080fd:

    # mt "Мне нужно, чтобы он согласился вложить деньги в журнал..."
    # mt "Если я сорву эту фотосессию, то этот неудачник просто откажется."
    # mt "Биф сказал, что выгонит меня с работы, если хоть одни из инвесторов откажется..."
    # m "Алекс, ты помнишь, что ты мне обещал перед началом съемки?"
    # alex_photograph "Да, конечно, Миссис Бакфетт."
    # alex_photograph "Я все сделаю, как надо, не переживайте."
    # m "Алекс, эта поза не будет хорошо смотреться в кадре..."
    # alex_photograph "Что вы, Миссис Бакфетт, это будет просто великолепный кадр!"
    # m "Алекс! Снимай меня с другого ракурса!!"
    # alex_photograph "Да, конечно. Сейчас еще один снимок и я возьму другой ракурс."
    # m "Алекс, ты уверен, что в таком ракурсе не будет видно ничего лишнего?"
    # alex_photograph "Конечно, Миссис Бакфетт! Вы можете мне довериться."
    # m "Алекс, не снимай меня крупным планом! Ты забыл, что ты мне обещал?"
    # alex_photograph "Я помню, Миссис Бакфетт. Кадры получаются отличные!"
    # alex_photograph "Вам очень идет это платье! Настоящая королева!"
    # m "Алекс, я не буду вставать в такую позу!"
    # campbell "Кхм... Эта поза как нельзя лучше демонстрирует платье..."
    # campbell "И характеризует новый курс вашего журнала, Миссис Бакфетт..."
    # mt "!!!"
    # alex_photograph "Согласен. Миссис Бакфетт, это очень интересный ракурс."
    # alex_photograph "Ничего лишнего в кадре не будет видно, не переживайте."
    # m "Ты уверен в этом, Алекс?"
    # alex_photograph "Конечно. Я Вам обещаю, Миссис Бакфетт!"
    # campbell "Благодарю. Мне было любопытно поприсутствовать."
    # mt "Куда этот неудачник пошел?"
    # mt "А если он пошел к Бифу и сейчас скажет ему, что отказывается?!"
    # mt "Тогда я не смогу больше здесь работать!!!"
    # mt "Мне нужно переодеться и идти к Бифу."
    # mt "Нужно узнать, что решил этот мерзкий Мистер Кэмпбелл..."
    mt "Ich muss dafür sorgen, dass er in das Magazin investiert..."
    mt "Wenn ich das Shooting verkacke, wird der Loser einfach ablehnen zu investieren."
    mt "Biff sagte, er feuert mich, wenn auch nur ein Investor ablehnt..."
    m "Alex, erinnerst du dich, was du vor dem Shooting versprochen hast?"
    alex_photograph "Natürlich, Frau Buckfett."
    alex_photograph "Ich mache alles richtig, keine Sorge."
    m "Alex, das wird im Foto nicht gut aussehen..."
    alex_photograph "Danke, Frau Buckfett, das wird großartig."
    m "Alex! Nimm einen anderen Blickwinkel!!"
    alex_photograph "Na klar. Noch ein Foto und ich ändere den Winkel."
    m "Alex, bist du sicher, dass man aus der Perspektive nichts sieht?"
    alex_photograph "Natürlich, Frau Buckfett! Sie können mir vertrauen."
    m "Alex, du pisst mich an! Hast du vergessen, was du versprochen hast?"
    alex_photograph "Ich erinnere mich Frau Buckfett. Die Fotos sind exzellent!"
    alex_photograph "Dieses Kleid steht Ihnen wirklich. Eine wahre Königin!"
    m "So posiere ich nicht!"
    campbell "Ähm... Diese Pose unterstreicht optimal das Kleid..."
    campbell "Und characterisiert ideal den neuen Unternehmenskurs, Frau Buckfett..."
    mt "!!!"
    alex_photograph "Dem stimme ich zu, Frau Buckfett, eine sehr interessante Perspektive."
    alex_photograph "Man wird auf dem Foto sonst nichts sehen, keine Sorge."
    m "Bist du da sicher, Alex?"
    alex_photograph "Natürlich. Ich verspreche es, Frau Buckfett!"
    campbell "Danke. Ich war neugierig hier dabei zu sein."
    mt "Wo ist der Loser hin?"
    mt "Und wenn er zu Biff ist und gesagt hat, dass er nicht investiert?"
    mt "Dann kann ich hier nicht mehr arbeiten!!!"
    mt "Ich muss mich umziehen und zu Biff."
    mt "Ich muss rausfinden, was dieser dämliche Campbell entschieden hat..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:240
translate german ep211_dialogues3_photoshoot_8_04d2efc7:

    # biff "Мистер Кэмпбелл, я уверен, что вы сделали правильный выбор!"
    # campbell "Посмотрим."
    # campbell "Будем надеяться, что это будет выгодная сделка для нас обоих..."
    # biff "Конечно, Мистер Кэмпбелл!"
    # biff "С Вами приятно сотрудничать."
    # campbell "Я уже опаздываю на важную встречу."
    # biff "Как я Вам уже говорил, мы будем рады видеть Вас снова в нашем офисе!"
    # campbell "Миссис Бакфетт, надеюсь, это была не последняя фотосессия..."
    # campbell "На которую я был приглашен..."
    # mt "???"
    # mt "До свидания, Мистер Кэмпбелл."
    # biff "Папочка доволен, что цыпочка смогла убедить первого инвестора."
    # biff "Но папочка недоволен тем, что осталось еще пять колеблющихся инвесторов..."
    # biff "Цыпочка должна проявить свои таланты убеждения..."
    # biff "Полученные ею в прошлой жизни на грязной улице."
    # biff "Иначе цыпочка рискует вернуться к ней!"
    # mt "!!!"
    # mt "Вот сволочь!!!"
    biff "Herr Campbell, ich bin sicher, sie haben sich richtig entschieden!"
    campbell "Wir werden sehen."
    campbell "Hoffentlich wird das eine gute Entscheidung für uns alle..."
    biff "Natürlich, Herr Campbell!"
    biff "Ich freue mich auf die Zusammenarbeit."
    campbell "Ich bin schon spät dran für ein wichtiges Meeting."
    biff "Wie ich schon sagte, Sie sind hier jederzeit willkommen!"
    campbell "Frau Buckfett, ich hoffe, das war nicht unser letztes Shooting!"
    campbell "Zu dem ich eingeladen war..."
    mt "???"
    mt "Auf Wiedersehen, Herr Campbell."
    biff "Daddy freut sich, dass das Mädchen den ersten Investor überzeugen konnte."
    biff "Aber Daddy ist ncht so glücklich darüber, dass noch weitere fünf Investoren warten..."
    biff "Das Mädchen muss ihre Überredungskünste spielen lassen..."
    biff "Welche sie durch ihr früheres Leben auf der Straße erworben hat."
    biff "Sonst läuft das Mädchen Gefahr, ihr altes Leben zurück zu bekommen!"
    mt "!!!"
    mt "Was für ein Bastard!"

translate german strings:

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:43
    old "Идти в фотостудию и переодеться."
    new "Gehe zum Fotostudio und zieh dich um."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:65
    old "Пойти к Бифу."
    new "Gehe zu Biff."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:87
    old "Идти в фотостудию и провести фотосессию в платье 'Королева сердец'."
    new "Gehe in's Fotostudio und beginne das Shooting im Kleid 'Queen of Hearts'."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:87
    old "Я не буду участвовать в этом!!!"
    new "Das mache ich nicht mit!!"

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:116
    old "Идти в фотостудию и провести фотосессию."
    new "Gehe ins Fotostudio und mache das Shooting."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:176
    old "Платье мне нравится, Мистер Кэмпбелл..."
    new "Ich mag das Kleid, Herr Campbell..."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:233
    old "Пойти кв кабиент к Бифу и узнать, что решил инвестор."
    new "Gehe zu Biff und finde raus, was der Investor entschieden hat."

