# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:4
translate english e211_dialogues_revenge_quest1_826aeb2b:

    # m "Ну что, корнишон..."
    # m "Пришло время поговорить по душам."
    # fred "..."
    # m "Итак, что ты знаешь про то, что случилось со мной?"
    # m "Говори!"
    # fred "ММффхпп... Мэм... мфхппп"
    # fred "Я... Я ничего не знаю, Мэм... мфхппп..."
    # m "О, Фред, фред..."
    # m "Как жаль... Я знала, что ты не очень далекого ума и повторяла это в свое время..."
    # m "Но, все-таки я была уверена, что капля рассудка у тебя есть, потому я и держала тебя..."
    # m "Ведь ты знаешь, что я деловой человек..."
    # m "А деловые люди не задают лишних вопросов."
    # m "Я не собираюсь много раз повторять одно и то же."
    # m "И, очень жаль, что лимит отведенного тебе времени для ответов ты тратишь на всякие глупости."
    # fred "..."
    # m "Я назвала тебя корнишоном, помнишь за что?"
    # fred "..."
    # m "За твой маленький член, Фред."
    # fred "..."
    # m "Да, я вижу что твой отросток достаточно выделяется среди общей массы двуногих животных..."
    # m "Однако, я оценивала тебя как мужчину, Фред..."
    # m "Ты ведь понимаешь, что размер члена у мужчины измеряется не отсюда..." 
    # m "А отсюда..." 
    # fred "..."
    # m "Поэтому, несмотря ни на что, ты корнишон, Фред..."
    # m "И никогда не изменишься..."
    # m "Маленькая собачка до старости щенок..."
    # m "Но я не виню тебя..."
    # fred "..."
    # m "Однако, корнишоны бывают полезные... и никчемные..."
    # fred "..."
    # m "Ты оказался никчемным корнишоном, Фред..."
    # m "Я найду нужную информацию и без тебя."
    # m "Но, ты знаешь, несмотря на то что я сказала, твой член, все-таки, портит картину корнишона."
    # m "А ты знаешь, я люблю порядок."
    # m "Поэтому не обижайся... Ничего личного, просто порядок."
    # fred "НЕЕЕТ!!!"
    # fred "ММПППХХХФФФФ!!! Я ХПФМММ!"
    # fred "Я СКАЖУ! МХХХПФМММ!"
    # m "О, ты хочешь быть полезным корнишоном, Фред?"
    # m "Тогда я потерплю небольшой беспорядок и не стану отстреливать тебе член..."
    # fred "Миссис Бакфетт! Прошу!"
    # fred "Не делайте глупостей! Я все скажу!"
    # m "Хорошо, Фред! Но это зависит от того что ты скажешь мне!"
    # m "Итак! Откуда ты узнал про то что случилось со мной?!"
    # fred "От Стива, Вашего младшего партнера!"
    # fred "Я узнал про Вас от него!"
    # m "От Стива?"
    # fred "Да, Миссис Бакфетт! В тот день я заезжал к нему и он сообщил мне все."
    # m "Зачем ты заезжал к нему?!"
    # fred "..."
    # m "Говори, Фред!"
    # m "ИЛИ, КЛЯНУСЬ! Я ОТСТРЕЛЮ ТВОИ ЯЙЦА К ЧЕРТОВОЙ МАТЕРИ!!!"
    # fred "Я заезжал к нему, чтобы отчитаться..."
    # m "Отчитаться о чем?!"
    # fred "О Ваших делах, Мэм... О Ваших передвижениях и связях..."
    # m "ЧТО?! ТЫ ШПИОНИЛ ЗА МНОЙ?!"
    # m "ШПИОНИЛ ДЛЯ ЭТОГО СЛИЗНЯКА СТИВА?!"
    # fred "Да, Мэм... Но я не знал что с Вами случится такое..."
    # fred "Поверьте, я не имею никакого отношения к этому!"
    # m "Ладно, Фред. Я знала что ты мерзавец..."
    # m "И ничуть не удивлена тому что ты, ко всему прочему, еще и шпионил за мной..."
    # m "Итак, какая у Стива была цель?"
    # m "С какой целью он собирал информацию про меня?"
    # m "Он хотел лишить меня компании, чтобы завладеть ей?!"
    # fred "Мэм... Нет..."
    # m "А что тогда, Фред?!"
    # fred "Мэм... Он собирал информацию про Вас, чтобы..."
    # fred "Чтобы переспать с Вами, Мэм..."
    # m "Вот мерзкий слизняк!"
    # m "Этот мешок с дерьмом думает своим членом, вместо мозгов!"
    # m "Впрочем как и ты, Фред!"
    # m "Интересно, сколько еще подобных мерзавцев вынашивало такие планы в отношении меня..."
    # fred "Мэм... Если честно... То, по-моему, ВСЕ..."
    # fred "Все мужчины вокруг ищут способы переспать с Вами, Мэм..."
    # m "Заткнись, Фред!"
    # m "Итак, что Стив сказал тебе?!"
    # fred "Мистер Стив сказал мне что некие люди взяли управление компанией в свои руки..."
    # fred "Сказал что Вы лишились всего имущества что у Вас есть..."
    # fred "И своих счетов..."
    # m "Не удивлена, что ты использовал эти знания для таких же похотливых целей, как и тот мешок с дерьмом!"
    # m "Откуда он это узнал?! У каких людей?!"
    # m "С кем он связан?!"
    # fred "Мэм... Я не знаю про тех людей, с которыми связан Мистер Стив..."
    # m "Значит ты, Фред, все-таки, бесполезный корнишон..."
    # fred "НЕТ!! Миссис Бакфетт!!!"
    # fred "Я знаю про причину того, что случилось с Вами!"
    # fred "Мистер Стив сказал мне!"
    # m "Да?"
    # m "И, в чем-же причина?"
    # fred "Мистер Стив не сказал мне точно, но это что-то связанное со днем до того, как Вы приехали в полицию!"
    # m "И что же это было?!"
    # fred "Я не знаю, Миссис Бакфетт!"
    # fred "Это какое-то событие или Ваш поступок!"
    # fred "Миссис Бакфетт! Я Вам нужен!"
    # fred "Приведите сюда Мистера Стива и я помогу Вам узнать у него все что Вам нужно!"
    # fred "Устройте нам очную ставку и он не сможет отвертеться!"
    # m "Хм... А ты очень любишь свой член, Фред..."
    # m "Итак, откуда ты получал информацию обо мне, впоследствии?!"
    # m "Откуда ты знал, что Дик хотел меня видеть?"
    # m "КТО передавал тебя это?!"
    # fred "Виктория..."
    # m "КТО?!"
    # fred "Виктория, Миссис Бакфетт..."
    # m "Ты... ты знаешь эту сучку?!"
    # fred "Да, Миссис Бакфетт..."
    # m "Я еще расспрошу тебя про нее..."
    # m "Но сейчас у меня большое желание увидеть этот мешок с дерьмом, по имени Стив!"
    # m "Корнишончик, я скоро вернусь!"
    # m "Веди себя хорошо, обещаешь?!"
    # fred "Да, Миссис Бакфетт..."
    m "Well, cornichon..."
    m "It's time to have a serious talk."
    fred "..."
    m "So, what do you know about what happened to me?"
    m "Speak!"
    fred "Mhhhhmh... Ma'am... Mhpmh..."
    fred "I... I know nothing, ma'am... Mhpmh..."
    m "О, Фред, фред..."
    m "What a pity... I always knew you weren't too bright of a man and I even used to tell you that back in the day..."
    m "But I was pretty sure you had a drop of logic in you, that's why I didn't fire you..."
    m "You know I'm a real businesswoman..."
    m "And people like only ask necessary questions."
    m "I'm not going to ask the same question over and over."
    m "And it's a shame you're wasting your precious answer time on such silly things."
    fred "..."
    m "Do you remember why I started calling you a cornichon?"
    fred "..."
    m "For your small dick, Fred."
    fred "..."
    m "Yes, I know that part of your body is quite impressive compared to most two-legged animals..."
    m "But I was judging you as a man..."
    m "And for a man, his dick size doesn't start from here..." 
    m "But from here..." 
    fred "..."
    m "So that's why you're still a cornichon, Fred..."
    m "And you'll never change..."
    m "A tiny dog. A mongrel till you die..."
    m "But I don't blame you..."
    fred "..."
    m "Still, cornichons can be either useful... Or useless..."
    fred "..."
    m "You turned out to be a useless cornichon, Fred..."
    m "I'll find out what I need even without you."
    m "But you know, you dick still doesn't fall in line with your nickname."
    m "And you know how much I love order."
    m "So, nothing personal... Just setting things straight."
    fred "NOOO!!!"
    fred "MHHHMPHHPH!!! I'LL... MMMHPMM!"
    fred "I'LL TELL YOU! MMMHPMM!"
    m "Oh, you want to be a useful cornichon, Fred?"
    m "Then I'll endure this little bit of chaos and won't shoot off your dick..."
    fred "Ms. Buckfett! Please!"
    fred "Don't be rash! I'll tell you everyting!"
    m "Good, Fred! But everything depends on what you tell me!"
    m "So! Where did you find out abou twhat happened to me?!"
    fred "From Steve, your associate!"
    fred "I've heard about you from him!"
    m "From Steve?"
    fred "Yes, Ms. Buckfett! I visited him that day and he told me everything."
    m "Why did you visit him?!"
    fred "..."
    m "Talk, Fred!"
    m "OR I SWEAR! I'LL SHOOT YOUR FUCKING BALLS OFF!!!"
    fred "I visited him to make a report..."
    m "To make what report?!"
    fred "About your business, ma'am... Where you went and what connections you had..."
    m "WHAT?! YOU WERE SPYING ON ME?!"
    m "FOR THAT SLUG, STEVE?!"
    fred "Yes, ma'am... But I had no idea something like that would happen to you..."
    fred "Believe me, I have no hand in all that!"
    m "Alright, Fred. I always knew you were a bastard..."
    m "So I'm not a bit surprised you were spying on me..."
    m "So, what was Steve's goal?"
    m "Why was he gathering info on me?"
    m "Did he want to rob me of my company?!"
    fred "No... Ma'am..."
    m "Then what, Fred?!"
    fred "Ma'am... He was gathering info on you..."
    fred "To have sex with you, ma'am..."
    m "What a slimy slug!"
    m "This piece of shit thinks with hid dick instead of his head!"
    m "Just like you, Fred!"
    m "I wonder how many bastards had similar plans for me..."
    fred "Ma'am... If I may... Everybody, probably..."
    fred "Every man around you looks for ways to have sex with you..."
    m "Shut up, Fred!"
    m "So, what did Steve tell you?!"
    fred "Mr. Steve told me certain people took over your company..."
    fred "That everything you owned was taken from you..."
    fred "Your bank account included..."
    m "I'm not surprised you used that info for perverted purposes, just like that piece of shit!"
    m "Where did he find out?! From who?!"
    m "Who is he working with?!"
    fred "Ma'am... I don't know who Mr. Steve is connected to..."
    m "Well, then you're a uselss cornichon after all, Fred..."
    fred "NO!! Mrs. Buckfett!!!"
    fred "I know the reason behind everythin that had happened to you!"
    fred "Mr. Steve told me!"
    m "Yes?"
    m "And what's that reason?"
    fred "Mr. Steve wasn't clear, but it was something about the day before you came to visit the police!"
    m "And what was that?!"
    fred "I don't know, Mrs. Buckfett!"
    fred "Some event or your certain acions!"
    fred "Mrs. Buckfett! You still need me!"
    fred "Bring Mr. Steve here and I'll help you find out what you need from him!"
    fred "Cross-examine us so he won't be able to wiggle out of this!"
    m "I see you still like your dick, Fred..."
    m "So, where did you get info about me after that?!"
    m "Why did you know Dick wanted to see me?"
    m "WHO gave you that info?!"
    fred "Victoria..."
    m "WHO?!"
    fred "It was Victoria, Mrs. Buckfett..."
    m "You... You know that bitch?!"
    fred "Yes, Mrs. Buckfett ..."
    m "I'll ask you about her a bit later..."
    m "For now, I have a really big need of meeting that piece of shit, Steve!"
    m "I'll be back soon, my lovely cornichon!"
    m "Be a good boy, okay?!"
    fred "Yes, Mrs. Buckfett ..."

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:125
translate english e211_dialogues_revenge_quest1a_a1218199:

    # mt "Мне надо идти к этому мешку с дерьмом Стиву!"
    mt "I need to see that piece of shit, Steve!"

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:131
translate english e211_dialogues_revenge_quest2_c361969d:

    # jane "Здравствуйте, Миссис Бакфетт!"
    # m "Здравствуй, Джейн!"
    # m "Стив у себя?"
    # jane "Да, Миссис Бакфетт, Мистер Стив у себя в кабинете..."
    # jane "Я предупрежу его, что..."
    # m "Не стоит, Джейн..."
    # m "Я сама сообщу ему о своем визите."
    # m "Пожалуйста, не беспокой нас..."
    # jane "Хорошо, Миссис Бакфетт..."
    jane "Hello, Mrs. Buckfett!"
    m "Hello, Jane!"
    m "Is Steve present?"
    jane "Yes, Mrs. Buckfett, Mr. Steve is in his office"
    jane "Let me warn him..."
    m "No need to, Jane..."
    m "I'll announce my visit myself."
    m "Please don’t disturb us..."
    jane "All right, Mrs. Buckfett ..."

# game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:143
translate english e211_dialogues_revenge_quest3_87c0fb13:

    # steve "Моника!"
    # steve "Рад тебя видеть!"
    # steve "Ты пришла заключить новый контракт?"
    # m "Да, Стив... Я пришла заключить новый контракт..."
    # steve "Моника, извини..."
    # steve "Я уже потратил средства на кое-кого другую..."
    # steve "Приходи через неделю..."
    # steve "Мы заключим очень выгодный контракт!"
    # m "Стив... Я бы хотела заключить контракт сейчас, если ты не против..."
    # m "Более того, я не буду брать с тебя деньги..."
    # steve "Не будешь брать деньги?"
    # steve "Хмммм..."
    # steve "Знаешь, Моника..."
    # steve "Ко мне недавно заходила Джейн и..."
    # steve "И она высосала все что было в моем члене, Моника..."
    # steve "Он совсем сухой и я боюсь что..."
    # m "Не переживай, Стив..."
    # m "Если у тебя не получится, ты ведь не рискуешь деньгами..."
    # steve "Ты права, Моника! Это отличная сделка!"
    # steve "Залезай под стол... Ты знаешь что Джейн может зайти..."
    # steve "А у меня с ней скоро свадьба и, в общем, ты понимаешь..."
    # m "Я все понимаю, Стив..."
    # m "Никаких проблем, усаживайся поудобнее..."
    # steve "Моника, надо-же! Своим присутствием ты вливаешь в меня мужскую силу!"
    # steve "Можешь приступать!"
    # steve "Но помнишь, что по условиям контракте ты не берешь у меня денег за это?!"
    # m "Да, Стив..."
    # m "Я не стану брать у тебя деньги в этот раз..."
    # m "..."
    # m "Вместо этого, я возьму твои яйца..." 
    # steve "!!!"
    steve "Monica!"
    steve "Glad to see you!"
    steve "Did you come to sign a new contract?"
    m "Yes, Steve, I came here exactly to do that..."
    steve "Sorry, Monica"
    steve "But I've already spent those resources on someone else..."
    steve "Come back in a week..."
    steve "And we'll make a new wonderful contract for you!"
    m "Steve... I'd like to sign that conract right now..."
    m "I won't even take your money right away, if you don't mind..."
    steve "You won' ttake any money?"
    steve "Hmmmm..."
    steve "You know, Monica..."
    steve "Jane just visited me and..."
    steve "Sucked out everything that was inside my dick..."
    steve "It's so empty, so I'm afraid..."
    m "Don't worry, Steve..."
    m "You won't lose any money even you wouldn't be able to do it..."
    steve "That's right, Monica! What a fine bargain!"
    steve "Get under the table... Jane can come in any moment, you know..."
    steve "And we have a wedding soon, so, you know..."
    m "I get it, Steve, don't worry..."
    m "It's okay, make yourself at home..."
    steve "Wow, Monica! Your presence is filling me with maculine powers!"
    steve "You can start!"
    steve "Но помнишь, что по условиям контракте ты не берешь у меня денег за это?!"
    m "Yes, Steve..."
    m "I won't take your money this time..."
    m "..."
    m "I'll have your balls instead!" 
    steve "!!!"

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues8_revenge_quest.rpy:121
    old "Идти к Стиву"
    new "Go to Steve"

