# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:13
translate english ep211_dialogues5_shiny_hole_1_0c40f660:

    # ashley "[monica_pub_name], танцы на сегодня еще не закончились."
    # m "???"
    # ashley "Тебе еще нужно будет поработать..."
    # ashley "Для одного клиента."
    # m "В смысле? Что значит поработать для одного клиента?!"
    # ashley "У моего заведения возникли финансовые трудности, по оплате кредита..."
    # ashley "Знаешь-ли, не так-то просто содержать такое яркое место..."
    # ashley "Да еще и обеспечивать тебя работой!"
    # m "..."
    # ashley "Один из посетителей паба, Мистер Беркельбаух, работает в кредитном отделе банка."
    # ashley "Он готов помочь."
    # m "Я тут вообще причем?"
    # ashley "Этот банкир готов оказать помощь не просто так..."
    # ashley "Он требует приват танец для него."
    # m "Ваша рыжая королева трущоб легко с этим справится."
    # ashley "Перестань цепляться к Молли!"
    # ashley "Она тут самая лучшая из моих девочек!"
    # m "!!!"
    # ashley "Клиент требует приват с тобой."
    # m "Я не собираюсь в этом участвовать!"
    # m "Кому надо, тот пусть и танцует в привате для этого неудачника!"
    # ashley "В таком случае, [monica_pub_name], ты уволена!"
    # ashley "Мало того, что ты постоянно крадешь чаевые..."
    # ashley "Так еще и споришь со мной!"
    # ashley "Да, и передай Клэр, что она тоже уволена."
    # ashley "И виновата в этом будешь только ты!"
    # m "!!!"
    # m "Что?! Клэр здесь ни при чем!"
    # m "И вообще! Почему сразу увольнение?!"
    # m "Только из-за того, что я отказалась идти в приват с каким-то..."
    # m "Никчемным банкиром!"
    # ashley "Да!"
    # ashley "Я вынуждена буду уволить всех, если он откажется помогать!"
    # ashley "Поэтому или ты сейчас же сделаешь так, как я сказала..."
    # ashley "Или убирайся отсюда ко всем чертям!!!"
    # m "!!!"
    # ashley "[monica_pub_name], иных вариантов нет."
    # ashley "Я даже готова простить тебе то, что ты в очередной раз украла чаевые..."
    # ashley "И отменить штраф..."
    # ashley "Если ты сейчас пойдешь в приват с этим банкиром."
    # m "..."
    # ashley "Тебе нечего бояться."
    # ashley "Ты с ним будешь только вдвоем."
    # ashley "Я тоже буду присутствовать..."
    # ashley "Я должна убедиться, что все пройдет, как надо."
    # mt "Вот черт! И что мне теперь делать?"
    # mt "Она сказала, что уволит не только меня, но и Клэр..."
    # mt "..."
    # mt "С другой стороны..."
    # mt "Это же просто танец. Только не на сцене, а для одного клиента."
    # mt "Тем более, что Эшли готова меня не штрафовать, если я соглашусь..."
    # m "..."
    # m "Я станцую для него, но только в одежде!"
    # ashley "Нет, [monica_pub_name], так дело не пойдет."
    # ashley "Ты покажешь ему не только свою грудь..."
    # ashley "Но и свою голенькую попку." 
    # ashley "А я проконтролирую, чтобы твою попку было хорошо видно..."
    # m "Я не буду танцевать перед ним голая!!!"
    # m "За кого ты меня принимаешь?!"
    # ashley "Тогда выметайся отсюда, [monica_pub_name]!"
    # ashley "Мне надоело с тобой спорить!!!"
    # m "!!!"
    ashley "[monica_pub_name], the dances are still not over."
    m "???"
    ashley "You still need to work a bit more."
    ashley "One more client."
    m "What do you mean, one more client?!"
    ashley "My establishment is in a bit of a finincial pickle, credit..."
    ashley "You know, it's hard to run a place like this."
    ashley "And supply you with work!"
    m "..."
    ashley "One of the patrons, Mr. Berckelbauch, works in a credit department in a bank."
    ashley "He's willing to help."
    m "And what does it have to do with me?"
    ashley "His help won't come for free..."
    ashley "He demands a private dance."
    m "Your redhead slum queen will deal with it no sweat."
    ashley "Stop bullying Molly!"
    ashley "She's my best girl here!"
    m "!!!"
    ashley "A client demands a private dance from you."
    m "I'm not going to take part in this!"
    m "I don't need to dance for some loser just because of you!"
    ashley "In that case, you're fired, [monica_pub_name]!"
    ashley "Not only you always steal tips..."
    ashley "You're also arguing with me!"
    ashley "Yes, and tell Clairse she's also fired."
    ashley "And it's all your fault!"
    m "!!!"
    m "What?! What does Claire have to do with it?"
    m "And! Why would you just fire us!"
    m "Just because I refused to do a private dance for some..."
    m "Worthless banker!"
    ashley "Yes!"
    ashley "I'll be forced to fire everybody, if he refuses to help!"
    ashley "So you'll do what I asked, or..."
    ashley "Get the hell out of here!!!"
    m "!!!"
    ashley "[monica_pub_name], you have no other choice."
    ashley "I'll even be generous enough to forget the fact you've stolen tips again..."
    ashley "And retract your fine..."
    ashley "If you do a private dance for that banker."
    m "..."
    ashley "Don't be afraid."
    ashley "It's gonna be just the two of you."
    ashley "I'll be there as well, though."
    ashley "I need to make sure everything goes accroding to plan."
    mt "Damn! What am I gonna do!"
    mt "She told me she going to fire Claire as well..."
    mt "..."
    mt "From the other side..."
    mt "It's just a dance. Just for one client instead of a crowd."
    mt "Ashley also said she won't fine me if I agree..."
    m "..."
    m "I'll dance for him, but only clothed!"
    ashley "No, [monica_pub_name], that won't cut it."
    ashley "You'll not only show him you tits..."
    ashley "But also your naked butt." 
    ashley "And I'll make sure your ass will be clearly visible."
    m "I won't dance naked in front of him!!!"
    m "Who do you take me for?!"
    ashley "Then get out of here, [monica_pub_name]!"
    ashley "I'm tired of arguing with you!!!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:88
translate english ep211_dialogues5_shiny_hole_1_3bc438d3:

    # mt "Я не собираюсь раздеваться перед каким-то..."
    # mt "Никчемным неудачником!"
    # mt "Пусть Эшли сама вертит перед ним своим голым задом!"
    # m "!!!"
    # m "За кого ты меня принимаешь?!"
    # m "Я не пойду ни в какой приват!"
    # ashley "Тогда выметайся отсюда, [monica_pub_name]!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "I'm not going to undress in front of some..."
    mt "Worthless loser!"
    mt "Ashley can wiggle her naked ass for him herself!"
    m "!!!"
    m "Who do you take me for?!"
    m "I'm not going to any private dances!"
    ashley "Then get out of here, [monica_pub_name]!!!"
    m "With pleasure!"
    mt "Finally, I won't need to come back to this hole!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:100
translate english ep211_dialogues5_shiny_hole_1_cb2a5eb3:

    # m "А сколько клиент мне за это заплатит?"
    # ashley "Нисколько!"
    # ashley "Ты будешь подарком от заведения."
    # m "!!!"
    # ashley "Но я готова простить тебе штраф за это."
    # mt "Дьявол!"
    # m "Я пойду в приват. Где он?"
    # ashley "Приходи в подсобку после танца."
    # ashley "Я с клиентом буду ждать тебя там."
    # mt "!!!"
    # mt "Как я это сделаю?!"
    # mt "..."
    # mt "Так... Соберись!"
    # mt "Ты [monica_pub_name], а не Моника Бакфетт."
    # mt "А [monica_pub_name] не леди, а обычная стриптизерша."
    # mt "Она не боится танцевать голой перед всякими неудачниками."
    m "And how much will he pay me for that?"
    ashley "Nothing!"
    ashley "You'll be a gift from our establishment."
    m "!!!"
    ashley "But I'll let your fine slide this time for that."
    mt "Devil!"
    m "I'm going to do it. Where is he?"
    ashley "Come to the back room after the dance."
    ashley "Me and the client will be waiting for you."
    mt "!!!"
    mt "How am I gonan do this?!"
    mt "..."
    mt "Phew... Be calm!"
    mt "You're [monica_pub_name], not Monica Buckfett."
    mt "And [monica_pub_name] is not a lady, but a simple stripper.."
    mt "She not afraid to dance naked in front of some loser..."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:125
translate english ep211_dialogues5_shiny_hole_2_28bba5f9:

    # mt "Эта извращенка Эшли не упустит своего шанса..."
    # mt "Чтобы пялиться на меня!"
    # mt "Делая вид, что она контролирует меня."
    # banker "О, детка..."
    # banker "Наконец-то ты пришла, [monica_pub_name]."
    # mt "Очередной никчемный неудачник."
    # banker "Давай, крошка, лезь на стол."
    # banker "Не заставляй меня ждать... Время - деньги."
    # mt "Мерзкий тип!"
    # mt "Если он притронется ко мне - врежу ему по яйцам!"
    # ashley "Ну? Чего ты ждешь?!"
    # ashley "Ты слышала, что тебе нужно сделать?"
    # mt "!!!"
    mt "This pervert, Ashley, won't miss a chance..."
    mt "To oggle me!"
    mt "While making it look she's controlling me."
    banker "Oh, baby..."
    banker "Finally, you've come, [monica_pub_name]."
    mt "Another worthless loser."
    banker "Come on, honey, get on the table."
    banker "Don't make me wait. Time is money."
    mt "Stinker!"
    mt "If he touches me, I'll kick his balls!"
    ashley "So? What are you waiting for?!"
    ashley "You heard what you need to do."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:147
translate english ep211_dialogues5_shiny_hole_2_7392d7af:

    # banker "Детка, снимай с себя трусики."
    # banker "Хочу посмотреть, что ты там прячешь."
    # mt "Черт!"
    # ashley "Выполняй!"
    # mt "!!!"
    banker "Hey baby, take off your panties."
    banker "I want to see what you're hiding there."
    mt "Heck!"
    ashley "Come on, do it!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:158
translate english ep211_dialogues5_shiny_hole_2_670931df:

    # mt "Я не собираюсь танцевать голой перед..."
    # mt "Перед каким-то никчемным неудачником!"
    # mt "Пусть Эшли сама вертит перед ним своим голым задом!"
    # m "!!!"
    # m "Нет!"
    # m "Я не буду этого делать!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "I'm not going to dance naked in front of..."
    mt "Some worthless loser!"
    mt "Ashley can wiggle her naked ass for him herself!"
    m "!!!"
    m "No!"
    m "I won't do it!"
    ashley "Then get out of here!!!"
    m "With pleasure!"
    mt "Finally, I won't need to come back to this hole!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:169
translate english ep211_dialogues5_shiny_hole_2_ddd6a857:

    # mt "Это делает [monica_pub_name], а не я."
    # mt "[monica_pub_name] просто потанцует и уйдет отсюда."
    # banker "Эй, крошка."
    # banker "Смотри, что у меня для тебя есть!"
    # banker "Пойдем ко мне!" 
    # mt "?!?!?!"
    # m "Эшли?!"
    # m "Мы так не договаривались!!!"
    # ashley "Тебе просто нужно спуститься вниз и посидеть у клиента на коленях."
    # ashley "Чего здесь такого?!"
    # ashley "Делай, что тебе говорят!"
    # mt "Какого черта тут происходит?!"
    # mt "Она решила подложить меня под этого мерзкого типа?!"
    # mt "Знала бы она с кем вообще имеет дело!!!"
    # mt "!!!"
    mt "[monica_pub_name] is doing this, not me."
    mt "[monica_pub_name] will just dance and get out of here."
    banker "Hey baby."
    banker "Look what I've got for you!"
    banker "Come here!" 
    mt "?!?!?!"
    m "Ashley?!"
    m "It's not what we agreed on!!!"
    ashley "You just need to sit don on the client's lap."
    ashley "What's there to fear?!"
    ashley "Do what you're told!"
    mt "What the hell is going on here?!"
    mt "Did she decide to lay me under this nasty guy?!"
    mt "If only she knew who she's messing with!!!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:191
translate english ep211_dialogues5_shiny_hole_2_6b54e0c8:

    # mt "Я не собираюсь этого делать!"
    # mt "Пусть он лапает Эшли своими грязными руками!"
    # m "!!!"
    # m "Нет!"
    # m "Я не буду этого делать!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    mt "I'm not going to do it!"
    mt "He'd better not touch me with his dirty hands!"
    m "!!!"
    m "No!"
    m "I won't do it!"
    ashley "Then get out of here!!!"
    m "With pleasure!"
    mt "Finally, I won't need to come back to this hole!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:202
translate english ep211_dialogues5_shiny_hole_2_c186442e:

    # mt "Грязная извращенка!"
    # mt "Ненавижу ее!!!"
    # mt "!!!"
    # banker "Мммм, какая ты аппетитная, крошка..."
    # ashley "Ну что, Мистер Беркельбаух, Вы довольны?"
    # ashley "Вы помните номер кредитного договора, по которому надо дать отсрочку?"
    # banker "Эшли, знаешь что больше всего в мире мне не нравится?"
    # ashley "Что, Мистер Беркельбаух?"
    # banker "Больше всего в мире мне не нравится, когда меня обманывают."
    # ashley "Что это значит? На что Вы намекаете? В чем обман?"
    # banker "Эшли, помнишь какое было условие?"
    # ashley "Вы хотели увидеть самую красивую попку Shiny Hole..."
    # ashley "И за это..."
    # banker "Я не уверен что это самая красивая попка Shiny Hole."
    # banker "Возможно, ты обманываешь меня."
    # ashley "ЧТО?! Я???"
    # ashley "Я с самого начала говорила тебе... Вам..."
    # ashley "С самого начала говорила что у Молли задница лучше, чем у [monica_pub_name]!"
    # ashley "Но ты... то есть Вы..."
    # banker "Эшли, прекрати! Задница Молли мне уже надоела."
    # banker "Эта ваша королева Shiny Hole готова на все ради пары баксов на чай!"
    # ashley "В чем тогда дело?! Почему Вы обвиняете меня в нечестности?!"
    # banker "Я не уверен что у [monica_pub_name] лучшая задница, потому что я не могу сравнить их все."
    # banker "Я еще не все увидел."
    # banker "А, потому, я имею право сомневаться в том, что ты даешь мне то, что декларируешь."
    # ashley "Что я де... декл... Что это за слово?"
    # ashley "Послушайте, Мистер Беркельбаух, Вы наш постоянный клиент и Вы знаете, что Клэр не танцует приват."
    # ashley "Ее задницу не получится оценить. Она танцует не ради денег."
    # ashley "Я никак не могу надавить на нее. Если я буду настаивать, она просто уйдет отсюда!"
    # banker "Я вижу задницу Клэр через день! Пусть она в тоненьких трусиках, но я могу оценить ее из зала."
    # ashley "Но в чем тогда проблема? Это все что у нас есть!"
    # ashley "У нас больше нет никаких попок, чтобы сравнить между ними!"
    # ashley "Я честно выполнила то о чем мы договорились!"
    # banker "Нет, Эшли! Здесь, в Shiny Hole, есть еще одна попка, которую никто не видел!"
    # banker "И ее не оценить из зала, потому что она пока не танцует, а зря!"
    # ashley "Какая? Кто это? Почему я не знаю про нее?!"
    # ashley "Это Джо снова притащил какую-то шлюху?!"
    # ashley "Также как сделал это с [monica_pub_name]?"
    # mt "!!!"
    # banker "Нет, Эшли! Я говорю про твою попку!"
    # ashley "ЧТО?! Причем здесь моя задница, Мистер Беркельбаух?!"
    # banker "При том, Эшли, что я подозреваю что твоя попка самая лучшая в Shiny Hole!"
    # banker "И ты скрыла это от меня, тем самым обманув."
    # banker "А ты уже знаешь что я больше всего не люблю..."
    # ashley "Но... Но как можно сравнивать меня с..."
    # ashley "С [monica_pub_name]?"
    # banker "Почему нельзя? Я не видел всех попок Shiny Hole и я имею право сомневаться!"
    # ashley "И что же ты хочешь?!"
    # banker "Залезай на стол и покажи свою попку, а я сравню ее с этой!"
    # ashley "Вообще-то я замужем!"
    # ashley "Моя попка, она... Она только для Джо, моего мужа!"
    # banker "Я не собираюсь сейчас трахать тебя, Эшли!"
    # banker "Но учти, отказ от проверки значит что ты что-то скрываешь от меня!"
    # banker "Если ты не предоставишь доказательство того, что твоя попка хуже, чем у [monica_pub_name]..."
    # banker "Или, если вдруг эта твоя попка не окажется хуже, чем у нее, то..."
    # banker "То банк завтра же выставит требование о досрочном погашении всей вашей кредитной линии, Эшли!!!"
    # banker "Я не терплю, когда меня пытаются выставить дураком, подсунув второсортный материал!"
    # mt "ЧТО?!!"
    # ashley "!!!"
    # banker "Давай! Залезай сейчас же! Я жду!"
    # ashley "Ты мне что, не оставляешь выбора?! Ты знаешь что я вкладываю душу в этом место!"
    # ashley "Я не могу потерять его!"
    # banker "Это ты не оставляешь мне выбора, Эшли! Ты отказываешься предъявить доказательство!"
    # banker "Вертишься, юлишь..."
    # banker "Ведь, если твоя попка и правда хуже, то тебе нечего бояться, правда?"
    # ashley "!!!"
    # banker "Да, и смотри на меня! Личико влияет на оценку любой попки!"
    # banker "Исходя из специфики своей работы, я люблю все оценивать комплексно!"
    # ashley "!!!"
    # banker "Да, и скажи [monica_pub_name], чтобы она сняла свою маску."
    # banker "Я вижу ее личико каждый день, когда она обслуживает клиентов."
    # banker "Незачем скрывать его сейчас. Это помешает комплексной оценке!"
    # m "ЧТО?!"
    # ashley "Давай, снимай свою дурацкую маску, делай что он говорит!"
    # m "Но!.."
    # ashley "Давай, он и так знает кто ты на самом деле!"
    # m "Он знает кто Я???"
    # ashley "Да, он знает, что ты новенькая официантка! Давай снимай!"
    mt "And fondle Ashley instead, that pervert!"
    mt "I hate her!!!"
    mt "!!!"
    banker "Hmmm, you're so hot, baby..."
    ashley "So, Mr. Berckelbauch, are you satisfied?"
    ashley "Do you remember the credit contract number you need to prolong?"
    banker "Ashley, do you know what I hate the most?"
    ashley "What, Mr. Berckelbauch?"
    banker "I hate being fooled the most."
    ashley "What do you mean? Who's fooling you?"
    banker "Do you remember what we agreed on, Ashley?"
    ashley "You wanted to see the sexiest butt in the Shiny Hole."
    ashley "And for that..."
    banker "I'm not quite sure this is the sexies ass of the Shiny Hole."
    banker "You may be folling me."
    ashley "WHAT?! ME???"
    ashley "I told you from the start..."
    ashley "That Molly's ass is better than [monica_pub_name]'s!"
    ashley "But you..."
    banker "Stop it, Ashley! I'm tired of Molly's ass."
    banker "Your Queen of the Shiny Hole is ready to do anything for a couple of bucks!"
    ashley "What's the matter then?! Why are accusing me of fooling you?!"
    banker "I'm not sure [monica_pub_name] has the best ass, because I didn't compare them all."
    banker "I haven't seen all of your asses."
    banker "Which means I have the right to doubt the validity of your claims."
    ashley "Validity... What's that about?"
    ashley "Listen, Mr. Berckelbauch, you're our patron and you know Claire doesn't do privates."
    ashley "You won't be able to appraise her ass. She doesn't dance for money."
    ashley "I have no way to persuade her. She'll just leave if I push her too much!"
    banker "I see her ass every other day. She may wear tiny panties, but can see her clearly even from the stage."
    ashley "Then what's the problem? That's all we've got."
    ashley "We don't have any more butts for you to compare!"
    ashley "I've dilligently carried out my part of the deal!"
    banker "No, Ashley! Here, in Shiny Hole, there's one more ass nobody have seen."
    banker "And it can't be seen from the main hall"
    ashley "Where? Who? Why don't I know about her?!"
    ashley "Did Joe bring another whore here?!"
    ashley "The same way he brought [monica_pub_name]?"
    mt "!!!"
    banker "No, Ashley! I'm talking about your butt!"
    ashley "WHAT?! What does my butt have anything to do with it, Mr. Berckelbauch?!"
    banker "And I suspect your ass is the best here, Ashley!"
    banker "And you've concealed it from me, hence you've tried to fool me!"
    banker "And you know what I hate the most..."
    ashley "But... How can you compare me to..."
    ashley "To [monica_pub_name]?"
    banker "Why not? I haven't seen all of the Shiny Hole's butts so I have my doubts!"
    ashley "And what do you want?!"
    banker "Get on the table and show me you ass, and I'll compare you to hers!"
    ashley "Don't you know I'm married?!"
    ashley "My butt, it's... Only for my husband, Joe!"
    banker "I'm not going to fuck me, Ashley!"
    banker "But remember, declining would mean you're hiding something from me!"
    banker "If you don't provide me proof that you ass is better than [monica_pub_name]'s..."
    banker "And if your ass doesn't turn out to be worse than hers..."
    banker "The bank will immediately send you a notice about paying your debt as soon as possible."
    banker "I can't take it when someone is trying to fool me, by triyng to shove second-rate good in front of me."
    mt "WHAT??!"
    ashley "!!!"
    banker "Come on! Get on the table! I'm waiting!"
    ashley "You're leaving me no choice, huh?! You know I pour my heart into this place!"
    ashley "I can't lose it!"
    banker "You're the one who's not leaving me a choice, Ashley! You're refusing to provide me proof!"
    banker "Wiggling around..."
    banker "Because if your ass is really worse, you have nothing to fear, right?"
    ashley "!!!"
    banker "And llok at me! Your pretty face will be taken into consideration!"
    banker "Judging from the specifics of your trade, I prefer to make complex examinations!"
    ashley "!!!"
    banker "And tell [monica_pub_name] to take off her mask."
    banker "I see her face every day when she services other clients"
    banker "No need to hide it now. This will prevent me from judging properly!"
    m "WHAT?!"
    ashley "Take off your stupid mask, do what he asks!"
    m "But...!"
    ashley "Come on, he already nows who you really are!"
    m "Who knows who I am???"
    ashley "Yes, he knows you're our rookie waitress! Come on, take it off!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:323
translate english ep211_dialogues5_shiny_hole_2_68566620:

    # m "Я не собираюсь делать подобное! Это уже слишком!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    m "I'm not going to do it! It's too much!"
    ashley "Then get out of here!!!"
    m "With pleasure!"
    mt "Finally, I won't need to come back to this hole!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:330
translate english ep211_dialogues5_shiny_hole_2_7801caeb:

    # ashley "Только попробуй сделать что-то, чтобы твоя задница понравилась ему меньше моей!"
    # ashley "Тогда ты не просто вылетишь отсюда..."
    # ashley "Но я снова повешу на тебя все украденные чаевые, которые до этого простила тебе!"
    # m "!!!"
    # ashley "Встань в лучшую позу, какую только можешь! Соблазни его!"
    # mt "Что я делаю... О БОЖЕ..."
    # mt "Я стоя голая... АБСОЛЮТНО ГОЛАЯ!!!"
    # mt "Без маски..."
    # mt "Стою так, чтобы моя попа понравилась больше, чем задница хозяйки дыры в трущобах!"
    # mt "И понравилась кому?!?!"
    # mt "Какому-то никчемному клерку из кредитного отдела занюханного банка!"
    # mt "Ведь он даже не представляет, на какую леди он сейчас смотрит!"
    # mt "Ему недостижим мой уровень, даже в его снах!"
    # ashley "Ну, убедился?!"
    # banker "Я пока размышляю..."
    # banker "Какое твое мнение, Эшли?"
    # ashley "В смысле какое мое мнение?"
    # banker "Как ты думаешь, чья задница хуже? Твоя или [monica_pub_name]?"
    # ashley "Мне обязательно это говорить?"
    # banker "Да, Эшли. Я хочу услышать это от тебя."
    # banker "Я хочу услышать твою уверенность... в своей правоте..."
    # ashley "!!!"
    # ashley "Я... Я считаю..."
    # ashley "Я считаю что моя задница хуже, чем у [monica_pub_name]."
    # banker "Хорошо, Эшли! Твоя уверенность убедила меня."
    # banker "Да и, по правде говоря, твоя задница действительно ни к черту в сравнению с попкой [monica_pub_name]!"
    # ashley "!!!"
    # banker "Я подпишу бумаги."
    # banker "Но, впрочем, она не настолько уж плоха для сцены."
    # banker "Я бы, как зритель, одобрил, если бы ты вышла на сцену в одном лишь фартуке."
    # banker "Хе-хе!"
    # ashley "Мистер Беркельбаух!"
    # ashley "Я уже говорила Вам, что для танцев у нас есть такие шлюхи, как [monica_pub_name]."
    # ashley "Я занимаюсь здесь управлением и ведением бизнеса!"
    # banker "Да, Эшли. Конечно!"
    # banker "Хе-хе!"
    # banker "Сообщи мне, если у тебя снова возникнут финансовые трудности!"
    # m "Мы закончили? Я могу идти?!"
    # banker "Не так быстро! Я все еще не кончил."
    # banker "Эшли, ты ведь знаешь, приватный танец должен длиться, пока клиент не будет удовлетворен..."
    # ashley "Да, Мистер Беркельбаух..."
    # ashley "[monica_pub_name], ты должна удовлетворить клиента!"
    # m "Что?! Я не знала о подобном правиле!"
    # m "С какой стати Я..."
    # ashley "Знание правил не помогает тебе придерживаться их!"
    # ashley "Не забывай почему ты оказалась здесь!"
    # ashley "Быстро иди и удовлетвори клиента!"
    # m "Но как... Как я удовлетворю его?!"
    # banker "Я бы хотел чтобы эта прекрасная попка потерлась о мой банковский член."
    # ashley "Ты слышала?! Быстро иди к нему!"
    # m "!!!"
    ashley "Just you try and do something so that I like your ass less than mine!"
    ashley "Then not only you'll get booted from here..."
    ashley "But I'll also get you pay for all the tips I've forgiven you for before!"
    m "!!!"
    ashley "Take the best pose you can make! Seduce him!"
    mt "What am I doing... OH GOD...."
    mt "I'm standing here naked... ABSOLUTELY NAKED!!!"
    mt "Without my mask..."
    mt "Trying to make my ass look better than of this place's owner!"
    mt "And for whom?!?!"
    mt "For some worthless clerk from the credit department of a worthless bank!"
    mt "He has no idea what lady he's looking at right now!"
    mt "He's nowhere near my level!"
    ashley "Well, satisfied?!"
    banker "I'm still considering..."
    banker "What do you think, Ashley?"
    ashley "What do you mean?"
    banker "Whose ass is better? Your or [monica_pub_name]?"
    ashley "Do I have to say it?"
    banker "Yes, Ashley. I want to hear it from you."
    banker "I want to hear your conviction... In the fact you're right..."
    ashley "!!!"
    ashley "I.. I think..."
    ashley "I think my ass is worse than [monica_pub_name]'s."
    banker "Good, Ashley. You've persuaded me."
    banker "And, to tell you the truth, your ass is really much worse comapred to [monica_pub_name]."
    ashley "!!!"
    banker "I'll sign the papers."
    banker "But, actually, she's fit for stage."
    banker "I would've approved her dancing in a naked apron."
    banker "Hehe!"
    ashley "Mr. Berckelbauch!"
    ashley "I already told you that for dancing we have whores like [monica_pub_name]."
    ashley "I'm managing everything here."
    banker "Yes, Ashley. Of course!"
    banker "Hehe!"
    banker "Tell me if you have any more finiancial troubles."
    m "Are we done? Can I go?!"
    banker "Not so fast, I'm not finished yet!"
    banker "Ashley, you know a private dance must continue until the client is satisfied, right?"
    ashley "yes, Mr. Beckelbauch..."
    ashley "[monica_pub_name], you need to pleasaure the client!"
    m "What?! I never knew about that rule!"
    m "Why would I..."
    ashley "The knowledge of rules doesn't help you follow them!"
    ashley "Don't forget why you're here!"
    ashley "Go and pleasure your client!"
    m "But how... Would I do it?!"
    banker "I want this beautiful ass to run against my banker ass."
    ashley "Did you hear me?! Come to him, quick!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:398
translate english ep211_dialogues5_shiny_hole_2_68566620_1:

    # m "Я не собираюсь делать подобное! Это уже слишком!"
    # ashley "Тогда выметайся отсюда!!!"
    # m "С радостью!"
    # mt "Наконец-то, мне не нужно больше возвращаться в эту чертову дыру!"
    m "I'm not going to do it! It's too much!"
    ashley "Then get out of here!!!"
    m "With pleasure!"
    mt "Finally, I won't need to come back to this hole!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:404
translate english ep211_dialogues5_shiny_hole_2_efb8e9bd:

    # banker "Вот так... Да."
    # banker "Хорошая девочка."
    # mt "Фу!"
    # mt "Вот он извращенец!"
    # banker "Девочки, вы хорошо поработали."
    # banker "Эшли, жду тебя завтра у себя в банке."
    # banker "Обсудим детали кредитного договора."
    # banker "Пока, крошка." 
    # ashley "[monica_pub_name], только попробуй рассказать об этом кому-нибудь!"
    # ashley "Если хоть кто-то узнает!"
    # ashley "Я тебя придушу!!!"
    # mt "Жаль. Думаю, Джо было бы интересно услышать подробности."
    # ashley "Поняла меня, [monica_pub_name]?!"
    # m "Я не расскажу никому."
    # ashley "Все! Иди! Ты на сегодня свободна."
    banker "Yes... Like that."
    banker "Good girl."
    mt "Phew!"
    mt "He's such a pervert!"
    banker "You've done a good job, girls."
    banker "Ashley, I'll be waiting for you at the bank, tomorrow."
    banker "We''l discuss the details of your credit contract."
    banker "Bye, baby." 
    ashley "[monica_pub_name], just you try telling about this to anyone!"
    ashley "If even one person hears about this!"
    ashley "I'll strangle you!!!"
    mt "A pity. Joe would've loved to hear the details of this."
    ashley "Do you understand me, [monica_pub_name]?!"
    m "Я не расскажу никому."
    ashley "That's it! Go! You're free for today."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:521
translate english ep211_dialogues5_shiny_hole_3_d349bd92:

    # ashley "Кстати, [monica_pub_name]!"
    # ashley "Нашим клиентам очень понравился твой танец с Клэр."
    # ashley "Они теперь просят, чтобы ты станцевала с Молли!"
    # ashley "А как ты знаешь, желание наших клиентов - закон!"
    # m "!!!"
    # m "Танцевать с этой рыжей сучкой?!"
    # m "Да ни за что!!!"
    # ashley "Тебе придется."
    # ashley "И я уже говорила, чтобы вы прекратили эту свою битву сучек!"
    # ashley "Она здесь королева и ее попка для меня важнее, чем твоя!"
    # m "!!!"
    # ashley "Ты так и не помирилась с ней?!"
    # m "Еще чего!"
    # m "Я еще должна сама к ней подходить и мириться?!"
    # m "После того, как она меня подставила?"
    # ashley "Да!"
    # ashley "Тебе надо попросить у Молли прощения!"
    # ashley "Вам придется в следующий раз вместе танцевать на сцене!"
    # ashley "И мне не надо, чтобы вы поубивали друг друга там!"
    # ashley "Наши клиенты должны остаться довольны."
    # ashley "Они щедро платят за танцы..."
    # ashley "И выручка паба в эти дни значительно увеличивается."
    # ashley "Так что никаких отговорок я слышать не буду!!!"
    # mt "Черт!"
    # mt "Долбанная Молли!"
    # mt "!!!"
    ashley "By the way, [monica_pub_name]!"
    ashley "Our clients really liked your dance with Claire."
    ashley "Now they're asking to see you dance with Molly!"
    ashley "And you know that our clients word is a law."
    m "!!!"
    m "Dancing with this redhead bitch>!"
    m "No way!!!"
    ashley "You'll have to."
    ashley "And I've already told you to stop those catfights."
    ashley "She's a queen here and her butt is more improtant than yours!"
    m "!!!"
    ashley "You haven't made up with her?"
    m "Don't even think!"
    m "I need to go do it myself?!"
    m "After she set me up?"
    ashley "Yes!"
    ashley "You need to apologize to Molly!"
    ashley "You'll have to dance with her next time!"
    ashley "And I don't need you to fight each other!"
    ashley "Our clients must be satisfied."
    ashley "They pay handsomely for the dance..."
    ashley "And the pub's payout increases a lot."
    ashley "So I won't hear about it from you!"
    mt "Heck!"
    mt "Fucking Molly!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:553
translate english ep211_dialogues5_shiny_hole_4_f4c080a6:

    # mt "Ненавижу эту сучку!!!"
    # mt "Теперь я еще должна и просить у нее прощения!"
    # mt "!!!"
    # mt "Я не буду этого делать!"
    # mt "Возможно, я просто попробую заговорить с ней."
    # mt "..."
    mt "I hate this bitch!!!"
    mt "Now I need to apologize to her!"
    mt "!!!"
    mt "I won't do it!"
    mt "Maybe I'll just try to talk to her."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:565
translate english ep211_dialogues5_shiny_hole_4_56ccee50:

    # mt "Нет!!!"
    # mt "Я не буду разговаривать с этой сучкой!"
    # mt "Мне плевать, что там Эшли говорит!"
    # mt "Ей надо, пусть сама с ней и танцует!"
    mt "No!!!"
    mt "I won't talk to this bitch!"
    mt "I don't care what Ashley says!"
    mt "She can dance with her herself!"

# game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:571
translate english ep211_dialogues5_shiny_hole_4_9f0a0a5c:

    # molly "!!!"
    molly "!!!"

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:83
    old "Пойти в приват с клиентом."
    new "Do a private dance for the client."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:83
    old "Не делать этого! (увольнение с паба)"
    new "Don't do it! (you'll be fired from the pub)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:117
    old "Идти в подсобку барменов и станцевать приват."
    new "Go into the bartender room and do a private dance."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:140
    old "Залезть на стол и танцевать."
    new "Get on the table and dance."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:153
    old "Снять трусики."
    new "Take your panties off."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:186
    old "Сесть на колени к банкиру."
    new "Sit on bamker's lap."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:186
    old "Не делать этого! (увольнение из паба)"
    new "Don't do it! (you'll be fired from the pub)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:319
    old "Снять маску"
    new "Take your mask off"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:394
    old "Тереться о член Мистера Беркельбауха..."
    new "Rub against Mr. Berckelbauch's dick..."

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:560
    old "Заговорить с Молли (в следующем обновлении)"
    new "Talk to Molly (in the next update)"

    # game/Quests/EP2_11/ep211_dialogues5_shiny_hole.rpy:560
    old "Ни за что!"
    new "No way!"

