# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:7
translate english ep211_dialogues3_photoshoot_1_58686973:

    # mt "Сегодня у меня фотосессия в каком-то наряде от инвестора."
    # mt "Надеюсь, это будет приличный наряд..."
    mt "Today I have a photo shoot in some outfit from an investor."
    mt "I hope it will be a decent outfit ..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:15
translate english ep211_dialogues3_photoshoot_2_0659dabc:

    # mt "!!!"
    # biff "В скором времени, Я планирую опубликовать эти кадры в широкий доступ."
    # mt "ЧТО-О-О?!"
    # mt "!!!!!"
    # campbell "Опубликуйте их после фотосессии в моем платье 'Королева сердец'."
    # campbell "Если вы их опубликуете до этой фотосессии..."
    # campbell "То снимки в моем платье будут публике неинтересны."
    # biff "Конечно, Мистер Кэмпбелл!"
    # biff "Кстати, Миссис Бакфетт уже пришла на фотосессию."
    # biff "Можете проходить в фотостудию, Мистер Кэмпбелл."
    # campbell "Да, спасибо."
    # m "Биф!"
    # m "Зачем ты показал эти фотографии инвестору?!"
    # m "!!!"
    # biff "Я тебя забыл спросить, кукла безмозглая, что мне делать!"
    # biff "Ты не задаешь вопросы, когда сосешь на улице члены за $ 20!.."
    # biff "Но пытаешься спорить, когда я показываю твою задницу, даже без члена в ней, состоятельному инвестору!"
    # biff "Не забывай, какая деньги я плачу тебе, кукла!"
    # m "!!!"
    # biff "Хватит орать тут и быстро иди переодевайся!"
    # biff "Тебя ждет Мистер Кэмпбелл. И только попробуй сорвать эту фотосессию!!!"
    # biff "Я тебя в один миг вышвырну отсюда на улицу!!!"
    # mt "ААААААА!"
    # mt "НЕНАВИЖУ!!!"
    # mt "УБЬЮ!!!"
    mt "!!!"
    biff "Soon, I plan to publish these images widely."
    mt "WHAAAAT?!"
    mt "!!!!"
    campbell "Publish them after the photo session in my dress 'Queen of Hearts'."
    campbell "If you publish them before this photo shoot ..."
    campbell "The pictures in my dress will not be interesting to the public."
    biff "Of course, Mr. Campbell!"
    biff "By the way, Mrs. Buckfett is ready for the photo shoot."
    biff "You can go to the photo studio, Mr. Campbell."
    campbell "Yes, thank you."
    m "Biff!"
    m "Why did you show these photos to the investor ?!"
    m "!!!"
    biff "I forgot to ask you, brainless doll, what I should or should not do!"
    biff "You don’t get to ask questions when you suck dick on the street for $ 20! .."
    biff "But you're trying to argue when I show your ass, even without a dick in it, to a wealthy investor!"
    biff "Не забывай, какая деньги я плачу тебе, кукла!"
    m "!!!"
    biff "Stop yelling here and go change, quickly!"
    biff "Mr. Campbell is waiting for you. And try not to fuck up this photo shoot !!!"
    biff "I’ll throw you out of here in an instant !!!"
    mt "AAAAAAA!"
    mt "I HATE HER!!!"
    mt "I'LL KILL HIM!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:52
translate english ep211_dialogues3_photoshoot_3_6026cae9:

    # m "Алекс!!!"
    # m "Это разве платье?!?!?!"
    # m "Эта тряпка на мне совсем не закрывает мою грудь!!!"
    # m "Алекс, как я буду сниматься в этом?! Да еще и при этом инвесторе?!"
    # alex_photograph "Миссис Бакфетт, не переживайте."
    # alex_photograph "Это платье очень Вам идет! Вы в нем настоящая королева!"
    # alex_photograph "Я буду делать кадры, на которых ничего не будет видно."
    # mt "Этот фотограф-извращенец всегда так говорит, а в итоге..."
    # mt "Нужно сходить к Бифу и послать его к черту!"
    # mt "Или пусть предоставит другое платье!"
    # mt "Или фотосессия отменяется!"
    m "Alex !!!"
    m "Is this a dress?!?!?!"
    m "This rag does not cover my chest at all !!!"
    m "Alex, how am I going to do this?! And before the investor to boot?!"
    alex_photograph "Don't worry, Mrs. Buckfett."
    alex_photograph "This dress suits you very much! You are the real queen in it!"
    alex_photograph "I'm gonna take pictures in such a way you won't have to show anything."
    mt "This pervert photographer always says that, but in the end ..."
    mt "You need to go to Biff and see if you can reschedule!"
    mt "Or let him provide another dress!"
    mt "Or cancel the photo shoot!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:71
translate english ep211_dialogues3_photoshoot_4_7ba4ad62:

    # m "Биф, я не буду фотографироваться в ЭТОМ!!!"
    # m "Это не платье!"
    # m "У меня вся грудь открыта в нем!!!"
    # m "!!!"
    # biff "У тебя, кукла, никто не спрашивал!"
    # m "Биф, я предупреждаю, что я не буду делать никаких откровенных кадров!"
    # m "Я соглашусь на кадры только с прикрытой грудью!"
    # biff "А я тебя предупреждаю, что если Кэмпбелл откажется инвестировать..."
    # biff "То виновата в этом будешь ты, кукла безмозглая!"
    # biff "У тебя не хватает мозгов понять, что от этой фотосессии многое зависит?"
    # biff "Проведи ее и чтобы никаких глупостей!"
    # biff "Это твоя работа! Ты получаешь за это немаленькие деньги!"
    # biff "Иди в фотостудию!"
    # mt "Мерзавец!"
    # mt "!!!"
    m "Biff, I will not be photographed in THIS!!!"
    m "It's not a dress!"
    m "My tits are just hanging out!!!"
    m "!!!"
    biff "No one asked you, doll!"
    m "Biff, I warn you that I wouldn’t make any candid shots!"
    m "I agree to photos only with covered breasts!"
    biff "And I warn you that if Campbell refuses to invest ..."
    biff "You will have to answer for this, you brainless doll!"
    biff "Do you have enough brains to understand that a lot depends on this photo shoot?"
    biff "So go do it, and no nonsense, you hear?"
    biff "This is your job! You get a lot of money for it!"
    biff "Go to the photo studio!"
    mt "Bastard!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:92
translate english ep211_dialogues3_photoshoot_4_7d321a67:

    # m "Биф, я не буду фотографироваться в этом платье!"
    # m "Да еще в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # m "Почему я?! Почему не Мелани?"
    # biff "Потому что Мистер Кэмпбелл так хочет!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # biff "Если будешь и дальше спорить со мной..."
    # biff "Я заставлю тебя фотографироваться с членом во рту!"
    # mt "!!!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "Biff, I won’t be photographed in this dress!"
    m "Yes, even in the presence of this investor!"
    m "I don’t want him to stare at me!"
    m "Why me?! Why not Melanie?"
    biff "Because Mr. Campbell wants it that way!"
    biff "You won’t get any other job ..."
    biff "Until you have this photo shoot!"
    biff "If you continue to argue with me ..."
    biff "I'll make you take pictures with a dick in your mouth!"
    mt "!!!"
    mt "Fucking Mr. Campbell! Damn Biff! I hate them all!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:106
translate english ep211_dialogues3_photoshoot_4_3748637d:

    # mt "Дъявол!"
    # mt "Он вышвырнет меня с работы, если я откажусь."
    # mt "А мне нужны деньги."
    # mt "Где я смогу заработать 5 тысяч в месяц для сучки Виктории?"
    # m "Я проведу эту фотосессию..."
    # biff "Иди в фотостудию."
    # mt "Чертов Биф!"
    # mt "На публичном вечере я всем сказала, что публика никогда не увидит мою грудь!"
    # mt "Что я всем им скажу теперь?! О ужас!!!"
    # mt "!!!"
    mt "Evil asshole!"
    mt "He'll throw me out of work if I refuse."
    mt "And I need money."
    mt "Where can I earn 5 thousand a month for that bitch Victoria ?"
    m "I will take part in this photo shoot ..."
    biff "Go to the photo studio."
    mt "Damn Biff!"
    mt "At a public party, I told everyone that the public would never see my breasts!"
    mt "What will I tell them all now ?! Oh God!!!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:122
translate english ep211_dialogues3_photoshoot_5_1173bb4f:

    # m "Биф..."
    # m "Мне нужна работа."
    # biff "Если цыпочка хочет работать, она сделает фотосессию."
    # biff "В платье от инвестора и в его присутствии."
    # m "..."
    # biff "Ты согласна?"
    # mt "!!!"
    m "Biff..."
    m "I need a job."
    biff "If the chick wants to work, she will do a photo shoot."
    biff "In a dress from the investor and in his presence."
    m "..."
    biff "Do you agree?"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:134
translate english ep211_dialogues3_photoshoot_5_68ecbce7:

    # m "Нет! Я не буду фотографироваться в этом платье!"
    # m "Да еще в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # biff "Если будешь и дальше спорить со мной..."
    # biff "Я заставлю тебя фотографироваться с членом во рту!"
    # mt "!!!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "No! I won’t be photographed in this dress!"
    m "Yes, even in the presence of this investor!"
    m "I don’t want him to stare at me!"
    biff "You won’t get any other job ..."
    biff "Until you have this photo shoot!"
    biff "If you continue to argue with me ..."
    biff "I'll make you take pictures with a dick in your mouth!"
    mt "!!!"
    mt "Fucking Mr. Campbell! Damn Biff! I hate them all!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:146
translate english ep211_dialogues3_photoshoot_5_5f6298e9:

    # mt "Дъявол!"
    # mt "Он вышвырнет меня с работы, если я откажусь."
    # mt "А мне нужны деньги."
    # mt "Где я смогу заработать 5 тысяч в месяц для сучки Виктории?"
    # mt "..."
    # mt "На публичном вечере я всем сказала, что публика никогда не увидит мою грудь!"
    # mt "Что я всем им скажу теперь?! О ужас!!!"
    # mt "..."
    # m "Я проведу эту фотосессию..."
    # biff "Иди переодевайся."
    # biff "Я пока позвоню Мистеру Кэмпбеллу, чтобы приехал на съемку."
    # mt "..."
    mt "Evil asshole!"
    mt "He'll throw me out of work if I refuse."
    mt "And I need money."
    mt "Where can I earn 5 thousand a month for that bitch Victoria ?"
    mt "..."
    mt "At a public party, I told everyone that the public would never see my breasts!"
    mt "What will I tell them all now ?! Oh God!!!"
    mt "..."
    m "I will take part in this photo shoot ..."
    biff "Go change."
    biff "I'll call Mr. Campbell for the shoot."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:165
translate english ep211_dialogues3_photoshoot_6_930bd5eb:

    # m "Алекс!"
    # m "Только попробуй взять ракурс, где будет видна моя... моя..."
    # campbell "Миссис Бакфетт, Вам нравится платье, которое я Вам подбрал?"
    # mt "Биф сказал, что от этой фотосессии зависит решение этого неудачника..."
    # mt "Если я сделаю что-то не так, он откажется от инвестирования в журнал..."
    # mt "Тогда Биф выгонит меня с этой работы..."
    # mt "А мне нужны деньги для этой сучки Виктории."
    # mt "Черт!!!"
    m "Alex!"
    m "Just try to take a view where my... my..."
    campbell "Mrs. Buckfett, do you like the dress I picked for you?"
    mt "Biff said that the decision of this loser depends on this photo shoot ..."
    mt "If I do something wrong, he won't invest in the magazine..."
    mt "Then Biff will fire me from this job ..."
    mt "And I need money for that bitch Victoria."
    mt "Fuck!!!"

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:179
translate english ep211_dialogues3_photoshoot_6_9a6a2d68:

    # m "Платье мне нравится, Мистер Кэмпбелл..."
    # m "Только мне кажется, что оно несколько откровенное..."
    # campbell "Вы сами мне сказали, что поддерживаете новый курс журнала."
    # campbell "Я подобрал платье в соответствии с курсом Вашего журнала."
    # campbell "И нахожу его весьма подходящим для Вас, Миссис Бакфетт."
    # campbell "Приступайте!"
    # mt "Мерзкий тип!"
    # mt "Скорее надо провести эту долбанную фотосессию..."
    # mt "И пусть он убирается отсюда!"
    # alex_photograph "Приступим, Миссис Бакфетт."
    m "I like the dress, Mr. Campbell ..."
    m "Only it seems to me that it is somewhat lewd..."
    campbell "You yourself told me that you support the new course of the magazine."
    campbell "I picked up the dress according to the course of your magazine."
    campbell "And I find it very suitable for you, Mrs. Buckfett."
    campbell "Proceed!"
    mt "Stinker!"
    mt "I'd rather do that fucking photo shoot..."
    mt "So he would get out of here!"
    alex_photograph "Here we go, Mrs. Buckfett."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:198
translate english ep211_dialogues3_photoshoot_7_2d9080fd:

    # mt "Мне нужно, чтобы он согласился вложить деньги в журнал..."
    # mt "Если я сорву эту фотосессию, то этот неудачник просто откажется."
    # mt "Биф сказал, что выгонит меня с работы, если хоть одни из инвесторов откажется..."
    # m "Алекс, ты помнишь, что ты мне обещал перед началом съемки?"
    # alex_photograph "Да, конечно, Миссис Бакфетт."
    # alex_photograph "Я все сделаю, как надо, не переживайте."
    # m "Алекс, эта поза не будет хорошо смотреться в кадре..."
    # alex_photograph "Что вы, Миссис Бакфетт, это будет просто великолепный кадр!"
    # m "Алекс! Снимай меня с другого ракурса!!"
    # alex_photograph "Да, конечно. Сейчас еще один снимок и я возьму другой ракурс."
    # m "Алекс, ты уверен, что в таком ракурсе не будет видно ничего лишнего?"
    # alex_photograph "Конечно, Миссис Бакфетт! Вы можете мне довериться."
    # m "Алекс, не снимай меня крупным планом! Ты забыл, что ты мне обещал?"
    # alex_photograph "Я помню, Миссис Бакфетт. Кадры получаются отличные!"
    # alex_photograph "Вам очень идет это платье! Настоящая королева!"
    # m "Алекс, я не буду вставать в такую позу!"
    # campbell "Кхм... Эта поза как нельзя лучше демонстрирует платье..."
    # campbell "И характеризует новый курс вашего журнала, Миссис Бакфетт..."
    # mt "!!!"
    # alex_photograph "Согласен. Миссис Бакфетт, это очень интересный ракурс."
    # alex_photograph "Ничего лишнего в кадре не будет видно, не переживайте."
    # m "Ты уверен в этом, Алекс?"
    # alex_photograph "Конечно. Я Вам обещаю, Миссис Бакфетт!"
    # campbell "Благодарю. Мне было любопытно поприсутствовать."
    # mt "Куда этот неудачник пошел?"
    # mt "А если он пошел к Бифу и сейчас скажет ему, что отказывается?!"
    # mt "Тогда я не смогу больше здесь работать!!!"
    # mt "Мне нужно переодеться и идти к Бифу."
    # mt "Нужно узнать, что решил этот мерзкий Мистер Кэмпбелл..."
    mt "I need him to agree to invest in a magazine ..."
    mt "If I mess up this photo shoot, then this loser will simply refuse."
    mt "Biff said that he would fire me if at least one of the investors refused ..."
    m "Alex, do you remember what you promised me before shooting?"
    alex_photograph "Yes, of course, Mrs. Buckfett."
    alex_photograph "I’ll do everything right, don’t worry."
    m "Alex, this pose won't look good in the picture..."
    alex_photograph "Oh no, Mrs. Buckfett, it's gonna be a great shot!"
    m "Alex! Take pictures from a different angle !!"
    alex_photograph "Oh sure. Just one more shot and I will take a different angle."
    m "Alex, are you sure that nothing unnecessary will be seen from this angle?"
    alex_photograph "Of course, Mrs. Buckfett! You can trust me."
    m "Alex, don't zoom in on me! Did you forget what you promised me?"
    alex_photograph "I remember, Mrs. Buckfett. The photos are excellent!"
    alex_photograph "This dress really suits you! You're a real queen!"
    m "I'm not posing like that!"
    campbell "Ahem ... This pose perfectly demonstrates the dress ..."
    campbell "And characterizes the new course of your magazine, Mrs. Buckfett ..."
    mt "!!!"
    alex_photograph "I agree. Mrs. Buckfett, this is a very interesting perspective."
    alex_photograph "Nothing unnecessary will be visible in the photo, don’t worry."
    m "Are you sure about that, Alex?"
    alex_photograph "Of course. I promise you, Mrs. Buckfett!"
    campbell "Thank you. It was a rather pleasureable experience."
    mt "Where did that loser go?"
    mt "What if he went to Biff and to tell him that he refuses?!"
    mt "Then I can’t work here anymore !!!"
    mt "I need to change clothes and go to Biff."
    mt "I need to find out what this vile Mr. Campbell has decided ..."

# game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:240
translate english ep211_dialogues3_photoshoot_8_04d2efc7:

    # biff "Мистер Кэмпбелл, я уверен, что вы сделали правильный выбор!"
    # campbell "Посмотрим."
    # campbell "Будем надеяться, что это будет выгодная сделка для нас обоих..."
    # biff "Конечно, Мистер Кэмпбелл!"
    # biff "С Вами приятно сотрудничать."
    # campbell "Я уже опаздываю на важную встречу."
    # biff "Как я Вам уже говорил, мы будем рады видеть Вас снова в нашем офисе!"
    # campbell "Миссис Бакфетт, надеюсь, это была не последняя фотосессия..."
    # campbell "На которую я был приглашен..."
    # mt "???"
    # mt "До свидания, Мистер Кэмпбелл."
    # biff "Папочка доволен, что цыпочка смогла убедить первого инвестора."
    # biff "Но папочка недоволен тем, что осталось еще пять колеблющихся инвесторов..."
    # biff "Цыпочка должна проявить свои таланты убеждения..."
    # biff "Полученные ею в прошлой жизни на грязной улице."
    # biff "Иначе цыпочка рискует вернуться к ней!"
    # mt "!!!"
    # mt "Вот сволочь!!!"
    biff "Mr. Campbell, I'm sure you made the right choice!"
    campbell "We will see."
    campbell "Hopefully this will be a good step for both of us ..."
    biff "Of course, Mr. Campbell!"
    biff "It's gonna a pleasure working with you."
    campbell "I'm already late for an important meeting."
    biff "As I told you, we will be glad to see you again in our office!"
    campbell "Mrs. Buckfett, I hope this was not the last photo shoot ..."
    campbell "To which I was invited ..."
    mt "???"
    mt "Goodbye, Mr. Campbell."
    biff "Daddy is pleased that the chick was able to convince the first investor."
    biff "But daddy is unhappy that there are five more hesitating investors left ..."
    biff "The chick must show her persuasion talents ..."
    biff "She received in her previous life on a dirty street."
    biff "Otherwise, the chick runs the risk of returning to her shitty life!"
    mt "!!!"
    mt "What a bastard !!!"

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:43
    old "Идти в фотостудию и переодеться."
    new "Go to a photo studio and change clothes."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:65
    old "Пойти к Бифу."
    new "Go to Biff."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:87
    old "Идти в фотостудию и провести фотосессию в платье 'Королева сердец'."
    new "Go to the photo studio and conduct a photo session in the 'Queen of Hearts' dress."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:87
    old "Я не буду участвовать в этом!!!"
    new "I will not participate in this !!!"

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:116
    old "Идти в фотостудию и провести фотосессию."
    new "Go to a photo studio and conduct a photo shoot."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:176
    old "Платье мне нравится, Мистер Кэмпбелл..."
    new "I like the dress, Mr. Campbell ..."

    # game/Quests/EP2_11/ep211_dialogues3_fotoshoot.rpy:233
    old "Пойти кв кабиент к Бифу и узнать, что решил инвестор."
    new "Go to Biff's office and find out what the investor has decided."

