# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:27
translate english ep211_dialogues6_slum_apartment_1_0bd0bb16:

    # mt "Каждый раз, когда прихожу сюда..."
    # mt "Боюсь, что встречу ту кошмарную лесбиянку."
    # mt "Как вспомню этот ужас в хостеле..."
    # mt "Нет! Даже думать об этом не хочу!"
    # mt "Тоже мне, дешевый ночлег!"
    # mt "!!!"
    # mt "Хммм..."
    # mt "Кстати, о дешевом ночлеге..."
    # mt "И почему я раньше об этом не задумывалась?!"
    # mt "У меня сейчас есть работа. Заработок у меня стабильный."
    # mt "Возможно, мне удастся арендовать какую-нибудь небольшую квартиру?"
    # mt "По-моему, это хорошая идея!"
    # mt "Я, наконец-то, перестану работать на эту семейку идиотов!"
    # mt "И жить независимо ни от кого!!!"
    # mt "Только как мне подобрать подходящую по цене квартиру?"
    # mt "..."
    # mt "Юлия снимает квартиру в ужасном доме!"
    # mt "Но стоит признать, что квартира у нее довольно уютная."
    # mt "Конечно, там все старое и убогое..."
    # mt "Но все же я была бы не против жить в подобной квартире."
    # mt "Представь только, Моника!"
    # mt "Никто не будет тебе указывать, что делать и какую одежду носить..."
    # mt "Никто не будет ограничивать тебя в еде или в походах в душ..."
    # mt "..."
    # mt "Кто может знать, где найти дешевое жилье?"
    # mt "???"
    # mt "В прошлый раз продавец шавермы посоветовал мне хостел..."
    # mt "Возможно, стоит спросить у него?"
    mt "Every time I come here ..."
    mt "I'm afraid I'll meet that nightmarish lesbian."
    mt "As I recall this horror at the hostel ..."
    mt "No! I don’t even want to think about it!"
    mt "Cheap bed, they said!"
    mt "!!!"
    mt "Hmmm."
    mt "Speaking of cheap accommodation ..."
    mt "Why didn’t I think about this before ?!"
    mt "I have a job right now. My earnings are stable."
    mt "Maybe I can rent some small apartment?"
    mt "I think it’s a good idea!"
    mt "I will finally stop working for that family of idiots!"
    mt "And live independently!!!!!!"
    mt "Just how do I find the right apartment for the right price?"
    mt "..."
    mt "Julia rents an apartment in a terrible house!"
    mt "But it's worth admitting that she has a pretty cozy apartment."
    mt "Of course, it's all old and miserable..."
    mt "But I'd love to live in a flat like this."
    mt "Imagine it Monica!"
    mt "No one will tell you what to do and what clothes to wear ..."
    mt "No one will limit your food or when you can shower ..."
    mt "..."
    mt "Now then, who knows where to find cheap housing?"
    mt "???"
    mt "Last time, a shawarma seller sent me to a hostel ..."
    mt "Perhaps, I should ask him?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:67
translate english ep211_dialogues6_slum_apartment_2_75f2b7ff:

    # mt "Уверена, он знает какое-нибудь дешевое жилье."
    # mt "Мне эта идея настолько понравилась..."
    # mt "И почему я раньше об этом не подумала?"
    mt "I'm sure he knows about some cheap housing."
    mt "I like this idea so much ..."
    mt "And why haven't I thought about this before?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:76
translate english ep211_dialogues6_slum_apartment_3_02b8e298:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # m "Нет. Мне не нужен твой кебаб!"
    # m "..."
    shawarma "Oh Madame!"
    shawarma "Have you come for the most delicious kebab in the area?"
    m "No. I don't need your kebab!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:83
translate english ep211_dialogues6_slum_apartment_3_3e89a366:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # mt "Нет, я пока не готова тратить деньги на апартаменты."
    # mt "Мне это сейчас не по карману."
    # m "Сам ешь свой отвратительный кебаб!"
    shawarma "Oh Madame!"
    shawarma "Have you come for the most delicious kebab in the area?"
    mt "No, I'm not ready to spend money on apartments yet."
    mt "I can’t afford it now."
    m "Eat your own disgusting kebab!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:92
translate english ep211_dialogues6_slum_apartment_3_4ccfab15:

    # mt "Животное!"
    # m "!!!"
    mt "Animal!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:97
translate english ep211_dialogues6_slum_apartment_3_08c0c4af:

    # m "Я хотела кое-что у тебя спросить..."
    # shawarma "Все, что Мадаме захотеть, Джек все сделать!"
    # shawarma "Для прекрасной Мадаме Джеку ничего не жалко!"
    # m "Мне..."
    # m "..."
    # m "Одной моей знакомой нужны апартаменты."
    # m "Она хочет их арендовать..."
    # m "За небольшую плату."
    # m "Ты знаешь, где можно найти что-то подходящее?"
    # shawarma "О, Мадаме!"
    # shawarma "Вы правильно сделали, что пришли ко мне!"
    # shawarma "Джек все здесь знать!"
    # shawarma "Для восхитительной Мадаме у Джека есть апрартаменты!"
    # m "Это... Это не для меня квартира..."
    # shawarma "Мадаме может не волноваться."
    # shawarma "Джек никому не рассказывать!" 
    # m "!!!"
    # m "Так у тебя есть апартаменты под аренду?" 
    # shawarma "Конечно, Мадаме!!!"
    # shawarma "И как раз сейчас они свободны!"
    # shawarma "Это шикарный апрартамент! Мадаме будет очень доволен!"
    # shawarma "И всего за 50 долларов за один неделя!"
    # shawarma "Прекрасный Мадаме не найдет ничего дешевле!"
    # mt "Всего 50 долларов в неделю?!"
    # mt "Боже! Я не верю в эту удачу!"
    # mt "Наконец-то!"
    # mt "..."
    # mt "Хотя... Это не такие уж маленькие деньги для меня сейчас..."
    # mt "!!!"
    # mt "Интересно, что это за апартаменты?"
    # m "А где эти апартаменты находятся?"
    # shawarma "Недалеко отсюда, Мадаме!"
    # shawarma "Мадаме хочет посмотреть свой будущий шикарный апрартамент?"
    # m "..."
    m "I wanted to ask you something ..."
    shawarma "Anything Madame wants, Jack do!"
    shawarma "For the beautiful Madame, Jack doesn’t feel sorry for anything!"
    m "I am.."
    m "..."
    m "One of my friends needs an apartment."
    m "She wants to rent it ..."
    m "For a small fee."
    m "Do you know where you can find something suitable?"
    shawarma "Oh Madame!"
    shawarma "You did the right thing that you came to me!"
    shawarma "Jack know everything here!"
    shawarma "For the delightful Madame, Jack has apartments!"
    m "This ... This is not an apartment for me ..."
    shawarma "Madame, no need to worry."
    shawarma "Jack not tell anyone!" 
    m "!!!"
    m "So, do you have apartments for rent?" 
    shawarma "Of course, Madame !!!"
    shawarma "And right now they are cheap!"
    shawarma "This is a beautiful apartment! Madame will be very pleased!"
    shawarma "And for only $ 50 a one week!"
    shawarma "Lovely Madame will not find anything cheaper!"
    mt "Only 50 dollars a week ?!"
    mt "Oh god, I can't believe my luck!"
    mt "Finally!"
    mt "..."
    mt "Although ... It's a sizeable sum for me now ..."
    mt "!!!"
    mt "I wonder what kind of apartment it is?"
    m "Where are these apartments located?"
    shawarma "Not far from here, Madame!"
    shawarma "Madame wants to see her future luxury apartment?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:138
translate english ep211_dialogues6_slum_apartment_3_57df20b7:

    # mt "Я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Нет."
    # m "Мне нужно еще подумать."
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    mt "I'm not ready to spend money on housing yet."
    mt "I can’t afford it now."
    m "No."
    m "I need to think more."
    shawarma "If Madame decides, she can come to Jack!"
    shawarma "Jack will be happy to help beautiful Madame!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:146
translate english ep211_dialogues6_slum_apartment_3_35ce5548:

    # m "А там никто больше не будет жить, кроме меня?"
    # shawarma "Конечно, нет!"
    # shawarma "Мадаме будет хозяйкой в этот шикарный апрартамент!"
    # m "Отлично!"
    # m "Я хочу их посмотреть!"
    m "And no one will live there except me?"
    shawarma "Of course not!"
    shawarma "Madame will be the mistress of this beautiful apartment!"
    m "Excellent!"
    m "I want to see them!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:157
translate english ep211_dialogues6_slum_apartment_4_0b452b14:

    # mt "Этот дом просто кошмарный!!!"
    mt "This house is just awful !!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:163
translate english ep211_dialogues6_slum_apartment_5_731c9362:

    # mt "Жуть!!!"
    # mt "Он что-то говорил про шикарные апартаменты?"
    # mt "Шикарные апартаменты в ТАКОМ доме?!"
    # mt "???"
    # m "Ты уверен, что апартаменты хорошие?"
    # shawarma "Конечно, Мадаме!"
    # shawarma "Там есть очень большой комнат!"
    # shawarma "Отдельный кухня!"
    # shawarma "И даже отдельный душ!"
    # shawarma "Мадаме идти за мной и сам все посмотреть!"
    # m "..."
    mt "Horrible!!!"
    mt "Didn’t he say something about luxury apartments?"
    mt "Luxury apartments in such a house ?!"
    mt "???"
    m "Are you sure the apartments are good?"
    shawarma "Of course, madam!"
    shawarma "There have very large rooms!"
    shawarma "Separate kitchen!"
    shawarma "And even a separate shower!"
    shawarma "Madame please follow me and see everything!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:179
translate english ep211_dialogues6_slum_apartment_6_3df513d4:

    # m "Куда ты меня привел?!"
    # m "Это что?! Квартира?!"
    # m "?!?!?!"
    # shawarma "Да, Мадаме!"
    # shawarma "Теперь это Ваш шикарный апрартамент!"
    # m "Шикарный?!"
    # m "Да ты охренел?!"
    # shawarma "В этот прекрасный апрартамент раньше жить рабочие."
    # m "Рабочие?!"
    # shawarma "Да! Они делать ремонт в очень богатых местах!"
    # shawarma "Может быть, Мадаме слышать про отель Ле Фгранд или офис Модный Журнал?"
    # m "!!!"
    # shawarma "Рабочий, который делать такую хорошую работу, всегда любить комфорт и чистота."
    # shawarma "Они бы не жить здесь, если бы это место не быть таким хорошим!"
    # m "..."
    # m "А что это за убогие обои?! Это тоже от рабочих?"
    # shawarma "Нет, Мадаме."
    # shawarma "Еще раньше здесь жить прекрасный женщин, чистый ангел!"
    # shawarma "Он оказывать здесь небольшие услуги уважаемым жителям нашей улица!"
    # mt "Боже! Какой кошмар!"
    # shawarma "Ну что? Мадаме будет жить в этот шикарный квартир?"
    # m "..."
    m "Where did you bring me ?!"
    m "What's this?! An apartment?!"
    m "?!?!?!"
    shawarma "Yes Madame!"
    shawarma "Now this is your gorgeous apartment!"
    m "Gorgeous ?!"
    m "Are you fucking crazy?!"
    shawarma "Workers used to live in this beautiful apartment."
    m "Workers ?!"
    shawarma "Yes! They do repairs in very rich places!"
    shawarma "Maybe Madame hear about the Le Frand hotel or the Fashion Magazine office?"
    m "!!!"
    shawarma "A worker who does such a good job always love comfort and cleanliness."
    shawarma "They wouldn’t live here if this place weren’t so nice!"
    m "..."
    m "What kind of wretched wallpapers are these ?! Is this also from the workers?"
    shawarma "No, Madame."
    shawarma "Even earlier, beautiful women live here, a pure angel!"
    shawarma "She here to provide small services to the distinguished inhabitants of our street!"
    mt "Oh god! What a nightmare!"
    shawarma "Well? Madame will live in this beautiful apartment?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:206
translate english ep211_dialogues6_slum_apartment_6_4171ca65:

    # m "Я не буду жить в этой!"
    # m "В этой!"
    # m "В этом пристанище для бомжей!!!"
    # m "!!!"
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    m "I won't be living in this...!"
    m "In this...!"
    m "In this homeless shelter !!!"
    m "!!!"
    shawarma "If Madame decides, she can come to Jack!"
    shawarma "Jack will be happy to help beautiful Madame!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:216
translate english ep211_dialogues6_slum_apartment_6_4ccfab15:

    # mt "Животное!"
    # m "!!!"
    mt "Animal!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:221
translate english ep211_dialogues6_slum_apartment_6_f2a90234:

    # mt "Может быть, стоит арендовать эту грязную дыру?"
    # mt "Всего 50 долларов в неделю..."
    # mt "..."
    # mt "Это ведь на какое-то время."
    # mt "Потом я подберу себе жилье получше."
    # m "Я... Я согласна арендовать эти ужасные апра... апартаменты ненадолго."
    # shawarma "Отлично! Мадаме сделать правильный решение!"
    # shawarma "Джек очень счастлив, что такой восхитительный женщин будет жить в его апрартамент!"
    # m "Когда требуется оплата, прямо сейчас? Я сразу смогу здесь жить?"
    # shawarma "Конечно, Мадаме сразу может тут остаться и жить!"
    # shawarma "Только Джеку сначала нужен документ Мадаме..."
    # mt "Документы?!"
    # mt "Дъявол!!!"
    # mt "!!!"
    # mt "Что же делать?!"
    # m "Я... Я не хотела бы показывать свои документы..."
    # m "Тем более, у меня их нет с собой..."
    # m "Я их забыла дома..."
    # m "..."
    # m "Без документов никак нельзя?"
    # shawarma "Если Мадаме хочет снять этот квартир без документ..."
    # shawarma "То Джек легко помочь Мадаме с этим!"
    # shawarma "Этот прекрасный апартамент не входит в жилой фонд..."
    # shawarma "Поэтому здесь нет злой проверяющий миграционных бумаг!"
    # shawarma "И такой прекрасный леди мочь жить здесь без документ!"
    # m "В таком случае, мы договорились."
    # m "Я арендую эту ужасную квартиру!"
    # shawarma "Прекрасно! Джек счастлив помочь такой восхитительный женщин!"
    # shawarma "Этот шикарный квартир будет стоить всего 300 долларов в неделю для Мадаме!"
    # m "!!!"
    # m "ЧТО?!"
    # m "Ты же говорил, что она стоит $ 50 в неделю!"
    # m "Почему сейчас стало $ 300?!"
    # m "?!?!?!"
    # shawarma "Специально для Мадаме!"
    # shawarma "Документ есть - апартамент стоит $ 50 в неделю!"
    # shawarma "Документ нет - апартамент стоит $ 300 в неделю!"
    # shawarma "Джек все для Вас готов сделать, Мадаме!"
    # shawarma "Мадаме никакой квартир больше не найдет, если у нее нет документ!"
    # shawarma "Да еще и по специальный цена!"
    # m "Апартаменты в трущобах за 300 долларов в неделю?!"
    # m "?!?!?!"
    # mt "Вот сволочь!"
    # mt "!!!"
    # mt "300 долларов в неделю..."
    # mt "..."
    mt "Maybe it's worth renting this dirty hole?"
    mt "Just $ 50 a week ..."
    mt "..."
    mt "After all, it's just temporary."
    mt "Then I will find a better place for myself."
    m "I ... I agree to rent these terrible apartments ... for a short while."
    shawarma "Excellent! Madame make the right decision!"
    shawarma "Jack is very happy that such delightful woman live in his apartment!"
    m "When do you want me to pay, right now? Can I live here right away?"
    shawarma "Of course, Madame can immediately stay here and live!"
    shawarma "Only Jack needs Madame's document first ..."
    mt "Documents?!"
    mt "Shit!!!"
    mt "!!!"
    mt "What to do?!"
    m "I ... I don’t want to show my documents ..."
    m "Moreover, I don’t have them with me ..."
    m "I forgot them at home ..."
    m "..."
    m "Without documents, is it impossible?"
    shawarma "If Madame wants to rent this apartment without a document ..."
    shawarma "Then Jack is easy to help Madame with this!"
    shawarma "This beautiful apartment is not part of the housing stock ..."
    shawarma "Therefore, there is no angry migrant papers checker!"
    shawarma "And such a beautiful lady could be able to live here without a document!"
    m "In that case, we agreed."
    m "I rent this terrible apartment!"
    shawarma "Perfectly! Jack is happy to help such delightful women!"
    shawarma "This beautiful apartment will cost you only $ 300 a week for Madame!"
    m "!!!"
    m "WHAT?!"
    m "You said that it costs $ 50 a week!"
    m "Why is now $ 300 ?!"
    m "?!?!?!"
    shawarma "For Madame!"
    shawarma "There is a document - an apartment costs $ 50 per week!"
    shawarma "No document - an apartment costs $ 300 per week!"
    shawarma "Jack is ready to do everything for you, Madame!"
    shawarma "Madame will no longer find any apartments if she doesn’t have a document!"
    shawarma "Yes, and at a special price!"
    m "Slum apartments for $ 300 a week ?!"
    m "?!?!?!"
    mt "What a jerk!"
    mt "!!!"
    mt "300 dollars a week ..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:272
translate english ep211_dialogues6_slum_apartment_6_9cf469b3:

    # m "Я не буду жить в этом!"
    # m "В этом пристанище для бомжей!!!"
    # m "Да еще и за такие деньги!"
    # m "!!!"
    # shawarma "Если Мадаме надумает, может приходить к Джеку!"
    # shawarma "Джек будет рад помочь прекрасной Мадаме!"
    m "I won’t live here!"
    m "In this homeless shelter !!!"
    m "And for that kind of money!"
    m "!!!"
    shawarma "If Madame decides, she can come to Jack!"
    shawarma "Jack will be happy to help beautiful Madame!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:282
translate english ep211_dialogues6_slum_apartment_6_4ccfab15_1:

    # mt "Животное!"
    # m "!!!"
    mt "Animal!"
    m "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:287
translate english ep211_dialogues6_slum_apartment_6_ee1676d6:

    # mt "Вот дъявол!"
    # mt "Мне не удастся снять жилье без документов..."
    # mt "Получается, что это единственный вариант, который я могу найти..."
    # mt "..."
    # shawarma "Мадаме жить один и Джек ее не беспокоить совсем."
    # shawarma "Только один раз в неделю Джек приходить за деньгами."
    # mt "И что мне делать?"
    # mt "???"
    # mt "С другой стороны... Это будет МОЕ жилье... МОЕ!!!"
    # mt "О том, где я живу, никто не будет знать..."
    # mt "Я буду сама себе хозяйка..."
    # mt "И больше никакие никчемные деревенщины мною не будут командовать!"
    # shawarma "Мадаме согласен?"
    # m "Деньги платить сейчас?"
    # shawarma "Да. Сейчас."
    # shawarma "И Мадаме может сразу оставаться жить здесь."
    # m "Следующая оплата ровно через неделю?"
    # shawarma "Джек будет приходить {c}каждая суббота вечер{/c} за деньгами."
    # shawarma "Мадаме платить и оставаться здесь жить!"
    # m "..."
    mt "The devil!"
    mt "I won’t be able to rent a house without documents ..."
    mt "It turns out that this is the only option I can find ..."
    mt "..."
    shawarma "Madame live alone and Jack does not bother her at all."
    shawarma "Only once a week does Jack come for money."
    mt "What am I supposed to do?"
    mt "???"
    mt "On the other hand ... It will be MY place... MY !!!"
    mt "Nobody will know about where I live ..."
    mt "I will be my own mistress ..."
    mt "And no more worthless hillbillys will command me!"
    shawarma "Madame agree?"
    m "Pay money now?"
    shawarma "Yes. Now."
    shawarma "And Madame can immediately start living here."
    m "Next payment will be exactly one week later?"
    shawarma "Jack will be coming {c} every Saturday night {/c} for money."
    shawarma "Madame pay and stay here live!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:313
translate english ep211_dialogues6_slum_apartment_6_decc33f8:

    # shawarma "Джек счастлив помочь прекрасной Мадаме!"
    # shawarma "Джек придти за деньгами в следующий суббота."
    # shawarma "Вот ключи от Ваш шикарный апартамент!"
    # shawarma "До суббота, прекрасный леди!"
    # m "..." 
    shawarma "Jack is happy to help beautiful Madame!"
    shawarma "Jack come for money next Saturday."
    shawarma "Here are the keys to your luxury apartment!"
    shawarma "Until Saturday, beautiful lady!"
    m "..." 

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:327
translate english ep211_dialogues6_slum_apartment_7_617c7d7a:

    # mt "Это самое жуткое место, которое я видела в своей жизни!"
    # mt "Ни в коем случае нельзя, чтобы кто-нибудь узнал, что Моника Бакфетт живет здесь!"
    # mt "!!!"
    # mt "С другой стороны..."
    # mt "Теперь у меня есть МОЕ жилье!"
    # mt "Я могу послать к черту сопляка Барди и эту дуру Бетти!"
    # mt "Хотя... Наверное пока не стоит этого делать..."
    # mt "Вдруг у меня не окажется денег на продление аренды..."
    # mt "Но, все равно, Я теперь независима от них!"
    # mt "Это маленький шаг навстречу к моей цели."
    # mt "Тот день, когда Моника Бакфетт вернет себе все, что у нее отняли, становится все ближе!"
    mt "This is the creepiest place I've seen in my life!"
    mt "In no case should anyone know that Monica Buckfett lives here!"
    mt "!!!"
    mt "From the other side..."
    mt "Now I have MY place!"
    mt "I can stay the hell away from that Bardi jerk and that fool Betty!"
    mt "Although ... Probably it's not worth it yet ..."
    mt "What if I don't have the money to extend the lease."
    mt "But, anyway, I’m now independent from them!"
    mt "This is a small step towards my goal."
    mt "The day when Monica Buckfett regains everything that was taken from her, is getting closer!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:346
translate english ep211_dialogues6_slum_apartment_8a_1ba992ec:

    # mt "Какое же кошмарное это место!"
    # mt "Может, стоит сделать тут небольшой ремонт?"
    mt "What a nightmare this place is!"
    mt "Maybe I should do a bit of repairs here?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:351
translate english ep211_dialogues6_slum_apartment_8b_9dc00cc2:

    # mt "Фи! Какая грязь!"
    # mt "Кто сюда притащил весь этот хлам?"
    mt "Wow! What a mess!"
    mt "Who brought all this stuff here?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:356
translate english ep211_dialogues6_slum_apartment_8c_702a51ac:

    # mt "Это, конечно, не сравнится с моей шикарной кроватью..."
    # mt "На которой спит теперь эта сучка Бетти."
    # mt "Но все же, на этом можно спать..."
    mt "This, of course, couldn’t compare with my gorgeous bed ..."
    mt "On which that Betty bitch is sleeping now."
    mt "But still, you can sleep on it ..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:362
translate english ep211_dialogues6_slum_apartment_8d_f554aef4:

    # mt "Что за кошмарная мебель здесь?!"
    # mt "Я не хочу даже прикасаться к ней!"
    mt "What terrible furniture is this?!"
    mt "Я не хочу даже прикасаться к ней!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:367
translate english ep211_dialogues6_slum_apartment_8e_e893cc3d:

    # mt "Нужно будет принести сюда свои наряды..."
    mt "You will need to bring my outfits here ..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:372
translate english ep211_dialogues6_slum_apartment_8f_a9d90429:

    # mt "Ужасная кухня!"
    # mt "Надеюсь, здесь нет тараканов?"
    # mt "Все равно я не смогу готовить здесь еду!"
    mt "Awful kitchen!"
    mt "Надеюсь, здесь нет тараканов?"
    mt "Все равно я не смогу готовить здесь еду!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:378
translate english ep211_dialogues6_slum_apartment_8g_247dc2c6:

    # mt "Эта посуда осталась от прежних жильцов?"
    # mt "Фи! Я не буду ее трогать!"
    mt "Were these dishes left from the previous residents?"
    mt "Ew! I won’t touch them!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:384
translate english ep211_dialogues6_slum_apartment_8h_6a5868f1:

    # mt "Эта ванная комната отвратительна!"
    # mt "Я не хочу сюда даже заходить!"
    mt "This bathroom is disgusting!"
    mt "I don’t even want to go in there!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:389
translate english ep211_dialogues6_slum_apartment_8i_0871f6f2:

    # mt "Фууу!"
    # mt "Как мне на этом писать?!"
    mt "Phew!"
    mt "How will I pee on this ?!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:394
translate english ep211_dialogues6_slum_apartment_8j_926d56b0:

    # mt "Это что за непонятная куча старого хлама?"
    # mt "В этом можно как-то умываться и мыть руки?"
    mt "What's that strange pile of old junk?"
    mt "Is it possible to wash your hands and face here somehow?"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:399
translate english ep211_dialogues6_slum_apartment_8k_6128cdb6:

    # mt "Мне придется мыть свое великолепное тело водой из куска ржавой трубы..."
    # mt "..."
    mt "I have to wash my magnificent body with water from a piece of rusty pipe ..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:412
translate english ep211_dialogues6_slum_apartment_9_ae61b4c8:

    # mt "А это еще что?"
    # mt "Хммм..."
    # mt "Это подделка на мою любимую модель этого бренда..."
    # mt "..."
    # mt "Почему бы мне не носить это дома?"
    # mt "Нужно померить этот наряд."
    # mt "..."
    # mt "Я, конечно, догадываюсь, кто носил это раньше..."
    # mt "Но это неважно... Это теперь МОЕ!!!"
    mt "А это еще что?"
    mt "Hmmm."
    mt "Это подделка на мою любимую модель этого бренда..."
    mt "..."
    mt "Why don't I wear this at home?"
    mt "Нужно померить этот наряд."
    mt "..."
    mt "Я, конечно, догадываюсь, кто носил это раньше..."
    mt "Но это неважно... Это теперь МОЕ!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:427
translate english ep211_dialogues6_slum_apartment_9a_8ee288fc:

    # mt "Хорошо, что никто не увидит меня в подделке этого бренда..."
    # mt "О том, что их до меня носил кто-то я предпочитаю не думать."
    # mt "Джек говорил, что раньше здесь жила какая-то проститутка..."
    # mt "..."
    # mt "Мне не важно! Эта одежда теперь моя!"
    mt "Хорошо, что никто не увидит меня в подделке этого бренда..."
    mt "О том, что их до меня носил кто-то я предпочитаю не думать."
    mt "Jack said that some kind of prostitute used to live here ..."
    mt "..."
    mt "I don’t care! These clothes are now mine!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:437
translate english ep211_dialogues6_slum_apartment_10_5cc3ee7e:

    # shawarma "Прекрасный Мадаме!"
    # shawarma "Джек пришел взять с нее деньги за шикарный апартамент!"
    # mt "За эту квартиру и $ 50 жалко платить..."
    # m "..."
    # shawarma "Мадаме стал еще прекрасней в этот домашней костюм!"
    # shawarma "Джек не может отвести глаз от прелестной Мадаме!"
    # shawarma "Вы такой яркий сияющий женщин!"
    # shawarma "Я подходить к дом и видеть, как он светится, благодаря Ваша красота!"
    # mt "Когда он уже заткнется и уйдет отсюда!"
    # m "..."
    # shawarma "Я подумал, что Мадаме слишком прекрасен, чтобы давать Джеку целых $ 300!"
    # shawarma "Джек сделать благородный поступок и предложить скидку для Мадаме!"
    # m "Скидку?"
    # shawarma "Да!"
    # shawarma "Джек сделать скидка в 10 процент, если..."
    # shawarma "Мадаме позволит прикоснуться ему к ее красота и целовать Джека!"
    # mt "!!!"
    # shawarma "Но это еще не все!"
    # shawarma "Джек сделать очень-очень щедрый скидка для Мадаме. 20 процент!"
    # shawarma "Если нефритовый стержень Джека проникать внутрь прекрасный Мадаме!!!"
    # m "Что ты несешь?!"
    # m "Что это все значит?!"
    # shawarma "Это значит, Джек предлагать Вам выгодный сделка."
    # shawarma "Скидка в 10 или 20 процент."
    # m "..."
    shawarma "Lovely Madame!"
    shawarma "Jack came to get money from her for a luxury apartment!"
    mt "I wouldn't pay even $ 50 for this appartment ..."
    m "..."
    shawarma "Madame became even more beautiful in this homemade costume!"
    shawarma "Jack can't take his eyes off the pretty Madame!"
    shawarma "You are such a bright shining woman!"
    shawarma "I approach the house and see how it glows, thanks to your beauty!"
    mt "Когда он уже заткнется и уйдет отсюда!"
    m "..."
    shawarma "I thought Madame was too beautiful to give Jack as much as $ 300!"
    shawarma "Jack do a noble deed and offer a discount for Madame!"
    m "Discount?"
    shawarma "Yes!"
    shawarma "Jack make a 10 percent discount if ..."
    shawarma "Madame will allow him to touch her beauty and kiss Jack!"
    mt "!!!"
    shawarma "But that is not all!"
    shawarma "Jack make a very very generous discount for Madame. 20 percent!"
    shawarma "If the jade rod of Jack penetrate the beautiful Madame !!!"
    m "What are you talking about ?!"
    m "What does all this mean ?!"
    shawarma "This means Jack is offering you a bargain."
    shawarma "Discount of 10 or 20 percent."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:467
translate english ep211_dialogues6_slum_apartment_10_5a8eea34:

    # mt "Почему бы мне не воспользоваться его предложением?"
    # mt "Скидка мне не помешает."
    # m "И что мне сделать, чтобы получить эту скидку?"
    # shawarma "У прекрасной Мадаме рот как лепесток роз!"
    # shawarma "Такой же восхитительный и нежный!"
    # shawarma "Джек будет счастлив дать в этот рот свой нефритовый стержень!"
    # m "ЧТО?!"
    # m "Да как ты смеешь мне подобное предлагать?!"
    # m "!!!"
    # shawarma "Джек делать очень щедрый и благородный предложение Мадаме..."
    # shawarma "Но если Мадаме откажется, Джек на нее не обижаться."
    # shawarma "Тогда она может просто заплатить Джеку $ 300 за шикарный квартир."
    # mt "Черт!"
    # mt "И что же мне делать?"
    # mt "10 процентов от $ 300 - это немало."
    # mt "А у меня сейчас каждый цент на счету."
    # m "..."
    mt "Why not take advantage of his offer?"
    mt "The discount will come handy."
    m "And what should I do to get this discount?"
    shawarma "Beautiful Madame has a mouth like a rose petal!"
    shawarma "So delightful and tender!"
    shawarma "Jack will be happy to give his jade rod to this mouth!"
    m "WHAT?!"
    m "How dare you offer me such a thing ?!"
    m "!!!"
    shawarma "Jack make a very generous and noble offer to Madame ..."
    shawarma "But if Madame refuses, Jack does not take offense at her."
    shawarma "Then she can just pay Jack $ 300 for beautiful apartments."
    mt "Heck!"
    mt "So what should I do?"
    mt "10 percent of $ 300 is a lot."
    mt "And I have to count every cent now."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:490
translate english ep211_dialogues6_slum_apartment_10_5fa75320:

    # m "Ты что, ненормальный?!"
    # m "Конечно, я не буду этого делать!"
    # m "Как ты мог вообще до такого додуматься!!!"
    m "Are you crazy?!"
    m "Of course I won’t do it!"
    m "How could you even think of such a thing !!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:497
translate english ep211_dialogues6_slum_apartment_10_aa0f5f5b:

    # mt "Животное!"
    # m "!!!"
    # shawarma "Тогда Мадаме платить Джеку $ 300."
    mt "Animal!"
    m "!!!"
    shawarma "Then Madame would pay Jack $ 300."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:506
translate english ep211_dialogues6_slum_apartment_10_885e44c4:

    # mt "Почему бы мне не воспользоваться его предложением?"
    # mt "Скидка мне не помешает."
    # m "И что мне сделать, чтобы получить эту скидку?"
    # shawarma "Красота Мадаме ослеплять Джека!"
    # shawarma "Мадаме прекрасна как древнегреческий богинь!"
    # shawarma "Джек будет счастлив, если она позволит..."
    # shawarma "Проникнуть нефритовый стержень Джека в ее сладкий дырочка!"
    # m "ЧТО-О-О-О?!"
    # m "?!?!?!"
    # m "Да как ты смеешь мне подобное предлагать?!"
    # m "!!!"
    # shawarma "Джек делать очень щедрый и благородный предложение Мадаме..."
    # shawarma "Но если Мадаме откажется, Джек на нее не обижаться."
    # shawarma "Тогда она может просто заплатить Джеку $ 300 за шикарный квартир."
    # mt "Черт!"
    # mt "И что же мне делать?"
    # mt "20 процентов от $ 300 - это немало."
    # mt "А у меня сейчас каждый цент на счету."
    # m "..."
    mt "Why not take advantage of his offer?"
    mt "The discount will come handy."
    m "And what should I do to get this discount?"
    shawarma "Madame's Beauty blind Jack!"
    shawarma "Madame is beautiful as the ancient Greek goddesses!"
    shawarma "Jack will be happy if she allows ..."
    shawarma "Penetrate Jack's jade rod into her sweet hole!"
    m "WHAT?!"
    m "?!?!?!"
    m "How dare you offer me such a thing ?!"
    m "!!!"
    shawarma "Jack make a very generous and noble offer to Madame ..."
    shawarma "But if Madame refuses, Jack does not take offense at her."
    shawarma "Then she can just pay Jack $ 300 for beautiful apartments."
    mt "Heck!"
    mt "So what should I do?"
    mt "20 percent of $ 300 is a lot."
    mt "And I have to count every cent now."
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:531
translate english ep211_dialogues6_slum_apartment_10_5fa75320_1:

    # m "Ты что, ненормальный?!"
    # m "Конечно, я не буду этого делать!"
    # m "Как ты мог вообще до такого додуматься!!!"
    m "Are you crazy?!"
    m "Of course I won’t do it!"
    m "How could you even think of such a thing !!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:538
translate english ep211_dialogues6_slum_apartment_10_aa0f5f5b_1:

    # mt "Животное!"
    # m "!!!"
    # shawarma "Тогда Мадаме платить Джеку $ 300."
    mt "Animal!"
    m "!!!"
    shawarma "Then Madame would pay Jack $ 300."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:548
translate english ep211_dialogues6_slum_apartment_10_9cb21b79:

    # m "Мне не нужны никакие скидки!"
    # m "Я готова заплатить сумму полностью."
    # m "Забирай деньги и иди!"
    # shawarma "Отлично, Мадаме! Джек очень рад!"
    # shawarma "Джек придет в {c}следующий суббота вечер{/c}!"
    # shawarma "И Мадаме может не сомневаться!"
    # shawarma "Джек очень благородный и щедрый!"
    # shawarma "Он снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    m "I do not need any discounts!"
    m "I am ready to pay the full amount."
    m "Take the money and go!"
    shawarma "Great, Madame! Jack is very happy!"
    shawarma "Jack will come on {c} next Saturday night {/c}!"
    shawarma "And Madame can be sure!"
    shawarma "Jack is very noble and generous!"
    shawarma "He will again offer Madame a discount next Saturday!"
    m "Alright! Go already! I'm busy!"
    mt "Animal!"
    mt "It’s so good that I won’t see him for a whole week!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:564
translate english ep211_dialogues6_slum_apartment_10_996db04f:

    # mt "Что же мне делать?"
    # mt "У меня не хватает денег на оплату..."
    # mt "Может, он согласится подождать несколько дней?"
    # m "..."
    # m "Я тебе смогу заплатить за апартаменты через несколько дней."
    # m "Ты же не выселишь такую прекрасную леди, как я, на улицу?"
    # m "Всего лишь несколько дней и я все оплачу."
    # shawarma "Нет-нет, Мадаме!"
    # shawarma "Джек восхищается Вашей красотой."
    # shawarma "Но Джек с Мадаме договорился, что деньги будут каждый суббота."
    # shawarma "Нет денег в суббота - нет шикарный апрартамент у Мадаме!"
    # shawarma "Джеку, конечно, очень жаль..."
    # shawarma "Но он вынужден выселять прекрасный леди прямо сейчас!"
    mt "What should I do?"
    mt "I don’t have enough money to pay ..."
    mt "Maybe he agrees to wait a few days?"
    m "..."
    m "I can pay you for the apartment in a few days."
    m "You're not gonna put a beautiful lady like me out on the street, are you?"
    m "Only a few days and I will pay for everything."
    shawarma "No no, Madame!"
    shawarma "Jack admires your beauty."
    shawarma "But Jack and Madame agreed that the money would be every Saturday."
    shawarma "No money on Saturday - no luxury apartment for Madame!"
    shawarma "Jack, of course, is very sorry ..."
    shawarma "But he is forced to evict a beautiful lady right now!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:590
translate english ep211_dialogues6_slum_apartment_11_b942ba20:

    # m "10 процентов - это сколько?"
    # shawarma "Целых $ 30, Мадаме!"
    # shawarma "Джек делать очень щедрый предложение для Вас!"
    # mt "Черт!"
    # mt "Если я соглашусь, я сэкономлю целых $ 30!"
    # mt "..."
    # m "Если об этом узнает хоть одна живая душа!!!"
    # m "!!!"
    # shawarma "Что Вы, Мадаме?!"
    # shawarma "Джек честный и благородный!"
    # shawarma "Джек никому не рассказать о Мадаме!"
    # m "Если кто-то узнает, я тебя убью!"
    # shawarma "Прекрасный Мадаме может не переживать!"
    # shawarma "Джек дает слово мужчины!"
    # mt "Моника, до чего ты докатилась?"
    # mt "Ты собралась делать минет какому-то неудачнику за скидку..."
    # mt "..."
    # mt "Но об этом ведь никто не узнает..."
    # mt "Тем более он даже не догадывается кто я такая..."
    # mt "..."
    # mt "А я сэкономлю деньги."
    # mt "Фу! Не могу поверить, что я делаю это..."
    # mt "И, главное, кому?!"
    # mt "Фу!!!"
    # mt "!!!"
    # shawarma "О, прекрасный Мадаме!"
    # shawarma "Словно лепестки роз ласкают мой нефритовый стержень!"
    # shawarma "Такие нежный и сладкий губы и ротик у Мадаме."
    # shawarma "Джек готов наслаждаться этим вечно!"
    # shawarma "О, Мадаме! Поласкайте мой стержень своим нежным языком!"
    # shawarma "Да, восхитительно!"
    # shawarma "Мммммм!!!"
    # shawarma "Ещееее!"
    # shawarma "ОООООООО!!!" 
    # shawarma "Мадаме, мне никто не доставлял большего наслаждения, чем Вы!!!"
    # shawarma "Джек сдержать свое слово и сделать для Мадаме скидку в 10 процент!"
    # m "..."
    # shawarma "Джек снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    # mt "Не могу поверить, что я сделала это!!!"
    # mt "Какая мерзость!!!"
    # mt "В следующий раз никаких скидок, Моника!"
    # mt "Такой леди, как ты, не пристало заниматься подобными непотребствами!"
    # mt "!!!"
    m "How much is 10 percent?"
    shawarma "As much as $ 30, Madame!"
    shawarma "Jack make a very generous offer for you!"
    mt "Heck!"
    mt "If I agree, I will save as much as $ 30!"
    mt "..."
    m "If at least one living soul finds out about it !!!"
    m "!!!"
    shawarma "What do you mean, Madame ?!"
    shawarma "Jack is honest and noble!"
    shawarma "Jack doesn't tell anyone about Madame!"
    m "If someone finds out, I will kill you!"
    shawarma "The beautiful Madame may not worry!"
    shawarma "Jack gives you his word!"
    mt "Monica, what have you come to?"
    mt "You are going to give a blowjob to some loser for a discount ..."
    mt "..."
    mt "But no one will know about this ..."
    mt "Moreover, he does not even know who I am ..."
    mt "..."
    mt "And I will save money."
    mt "Well! I can’t believe that I am doing this ..."
    mt "And, most importantly, to whom ?!"
    mt "Fuck !!!"
    mt "!!!"
    shawarma "Oh beautiful Madame!"
    shawarma "Like rose petals caressing my jade rod!"
    shawarma "Madame has such delicate and sweet lips and mouth."
    shawarma "Jack is ready to enjoy it forever!"
    shawarma "Oh Madame! Caress my rod with your gentle tongue!"
    shawarma "Yes, amazing!"
    shawarma "Mmmmmm !!!"
    shawarma "More!"
    shawarma "OOOOOOOO !!!" 
    shawarma "Madame, no one gave me more pleasure than you !!!"
    shawarma "Jack keep his word and make Madame a 10 percent discount!"
    m "..."
    shawarma "Jack will again offer Madame a discount next Saturday!"
    m "Alright! Go already! I'm busy!"
    mt "Animal!"
    mt "It’s so good that I won’t see him for a whole week!"
    mt "I can’t believe that I did that !!!"
    mt "What a nasty thing!!!"
    mt "Next time no discounts, Monica!"
    mt "Such a lady like you should not engage in such obscenities!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:651
translate english ep211_dialogues6_slum_apartment_12_df4357b8:

    # m "20 процентов - это сколько?"
    # shawarma "Целых $ 60, Мадаме!"
    # shawarma "Джек делать очень щедрый предложение для прекрасный леди!!!"
    # mt "Черт!"
    # mt "Если я соглашусь, я сэкономлю целых $ 60!"
    # mt "..."
    # mt "Моника, ты сейчас серьезно?!"
    # mt "Как ты можешь даже предполагать подобное?!"
    # mt "Ты действительно займешься с этим животным сексом за скидку в $ 60?!"
    # mt "?!?!?!"
    # mt "..."
    # mt "Но об этом ведь никто не узнает..."
    # mt "..."
    # mt "А я сэкономлю деньги."
    # m "Я тебя сразу предупрежаю!!!"
    # m "Если об этом узнает хоть одна живая душа!!!"
    # m "Если ты хотя бы намекнешь кому-то о том, что здесь сейчас будет!!!"
    # m "Я тебя убью!!!"
    # m "!!!"
    # m "Ты меня понял?!"
    # shawarma "Что Вы, Мадаме?!"
    # shawarma "Джек честный и благородный!"
    # shawarma "Джек никому не рассказать о Мадаме!"
    # shawarma "Прекрасный Мадаме может не переживать!"
    # shawarma "Джек дает слово мужичины!"
    # shawarma "У Мадаме великолепный попочка!!!"
    # shawarma "Сладкий и прекрасный попочка!!!"
    # shawarma "Джек очень любить такие!"
    # m "Не смей делать какие-нибудь извращенства!"
    # shawarma "Нет-нет, что Вы, Мадаме."
    # shawarma "Джек просто трогать сладкий попочка."
    # shawarma "Ммммм, гладкий и упругий... как персик!"
    # mt "Боже... Когда же он заткнется?!"
    # mt "Фу! Не могу поверить, что я делаю это..."
    # mt "!!!"
    # shawarma "О, какой сладкий дырочка у Мадаме!!!"
    # shawarma "Как тепло и хорошо мой нефритовый стержень!!!"
    # shawarma "Ооооо, как сладко!!!"
    # shawarma "Джек готов наслаждаться этим вечно!"
    # shawarma "Мммммм!!!"
    # shawarma "Джек делать прекрасный Мадаме скидка каждый суббот!!!"
    # shawarma "Оооо, Джек просто на седьмом небе!!!"
    # shawarma "Ааааа!!!"
    # shawarma "Мммммм!!!"
    # shawarma "ОООООООО!!!" 
    # shawarma "Мадаме, мне никто не доставлял больший наслаждений, чем Вы!!!"
    # shawarma "Джек сдержать свое слово и сделать для Мадаме скидку в 20 процент!"
    # m "..."
    # shawarma "Джек снова предлагать Мадаме скидку в следующий суббота!"
    # m "Все! Иди! Мне некогда!"
    # mt "Животное!"
    # mt "Как хорошо, что я его целую неделю теперь не увижу!"
    # mt "Не могу поверить, что я сделала это!!!"
    # mt "Какая мерзость!!!"
    # mt "В следующий раз никаких скидок, Моника!"
    # mt "Такой леди, как ты, не пристало заниматься подобными непотребствами!"
    # mt "!!!"
    m "20 percent is how much?"
    shawarma "As much as $ 60, Madame!"
    shawarma "Jack make a very generous offer for the beautiful lady !!!"
    mt "Heck!"
    mt "If I agree, I will save as much as $ 60!"
    mt "..."
    mt "Monica, are you serious now ?!"
    mt "How can you even suggest such a thing ?!"
    mt "Are you really going to have sex with this animal for a $ 60 discount ?!"
    mt "?!?!?!"
    mt "..."
    mt "But no one will know about this ..."
    mt "..."
    mt "And I will save money."
    m "I warn you right away !!!"
    m "If at least one living soul finds out about it !!!"
    m "If you say anything to anyone about what is going to happen here !!!"
    m "I will kill you !!!"
    m "!!!"
    m "Got it?!"
    shawarma "What do you mean, Madame ?!"
    shawarma "Jack is honest and noble!"
    shawarma "Jack doesn't tell anyone about Madame!"
    shawarma "The beautiful Madame may not worry!"
    shawarma "Jack gives you his word!"
    shawarma "Madame has a magnificent ass !!!"
    shawarma "Sweet and lovely ass !!!"
    shawarma "Jack is very fond of such ass!"
    m "Don't you dare do anything perverted!"
    shawarma "No, no, of course not, Madame."
    shawarma "Jack just touch the sweet ass."
    shawarma "Mmmmm, smooth and firm ... like a peach!"
    mt "God ... When will he shut up ?!"
    mt "Well! I can’t believe that I am doing this ..."
    mt "!!!"
    shawarma "Oh, what a sweet hole Madame has !!!"
    shawarma "How warm and good my jade rod is !!!"
    shawarma "Ohhhhhh, how sweet !!!"
    shawarma "Jack is ready to enjoy it forever!"
    shawarma "Mmmmmm !!!"
    shawarma "Jack do a wonderful Madame discount every Saturday !!!"
    shawarma "Ohhh, Jack is just in seventh heaven !!!"
    shawarma "Ahhhh !!!"
    shawarma "Mmmmmm !!!"
    shawarma "OOOOOOOO !!!" 
    shawarma "Madame, no one gave me more pleasure than you !!!"
    shawarma "Jack keep his word and make Madame a 20 percent discount!"
    m "..."
    shawarma "Jack will again offer Madame a discount next Saturday!"
    m "Alright! Go already! I'm busy!"
    mt "Animal!"
    mt "It’s so good that I won’t see him for a whole week!"
    mt "I can’t believe that I did that !!!"
    mt "What a nasty thing!!!"
    mt "Next time no discounts, Monica!"
    mt "Such a lady like you should not engage in such obscenities!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:720
translate english ep211_dialogues6_slum_apartment_13_d850b685:

    # mt "Вот скотина!"
    # mt "Грязное инстинктивное животное!!!"
    # mt "Как он посмел меня выставить на улицу?!"
    # mt "?!?!?!"
    # mt "Я все равно зайду обратно в квартиру!"
    # mt "Ключи же остались у меня!"
    # mt "!!!"
    # mt "Только нужно дождаться, когда он уйдет из квартиры."
    mt "You bastard!"
    mt "Dirty primal animal !!!"
    mt "How dare he put me out on the street?!"
    mt "?!?!?!"
    mt "I'm going back to the apartment anyway!"
    mt "I still have the keys!"
    mt "!!!"
    mt "I just have to wait until he leaves the apartment."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:734
translate english ep211_dialogues6_slum_apartment_14_8e4fef89:

    # mt "Мне нужно немного позже прийти сюда."
    # mt "Это животное еще в квартире..."
    mt "I need to come here a little later."
    mt "This animal is still in the apartment ..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:742
translate english ep211_dialogues6_slum_apartment_15_efc3ce3b:

    # mt "Вот скотина!!!"
    # mt "Он поменял замки в моей квартире!!!"
    # mt "Сволочь!!!"
    # mt "!!!"
    # mt "И что мне теперь делать?!"
    # mt "Неужели мне придется идти к нему и уговаривать впустить меня обратно?!"
    # mt "?!?!?!"
    mt "You bastard!!!"
    mt "He changed the locks in my apartment !!!"
    mt "Swine!!!"
    mt "!!!"
    mt "And what should I do now?!"
    mt "Do I really have to go to him and persuade him to let me in?!"
    mt "?!?!?!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:750
translate english ep211_dialogues6_slum_apartment_15_8fc1f114:

    # mt "Он все равно меня не впустит. У меня нет денег заплатить за неделю..."
    # mt "Мне нужно заработать $ 300."
    # mt "Потом я пойду и поговорю с ним."
    # mt "Он не сможет отказать мне."
    mt "He won’t let me in anyway. I have no money to pay for a week ..."
    mt "I need to earn $ 300."
    mt "Then I will go and talk to him."
    mt "He can’t refuse me."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:761
translate english ep211_dialogues6_slum_apartment_16_c0b38246:

    # mt "Я не могу зайти в свою квартиру..."
    # mt "Эта сволочь поменяла замки!"
    # mt "Мне нужно пойти к нему."
    mt "I can’t go into my apartment ..."
    mt "This bastard changed the locks!"
    mt "I need to go to him."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:772
translate english ep211_dialogues6_slum_apartment_17_500edb17:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # shawarma "Или Мадаме хочет снова жить в шикарный апрартамент?"
    # m "Я хочу вернуться в свою квартиру!"
    # shawarma "Джек не может отказать такой прекрасный леди!"
    # shawarma "А у Мадаме есть деньги?"
    # m "Да!"
    # shawarma "Мадаме может заплатить деньги Джеку прямо сейчас."
    # shawarma "Джек даст Мадаме новый ключ."
    # shawarma "И она может снова жить в шикарный апрартамент Джека!"
    shawarma "Oh Madame!"
    shawarma "Have you come for the most delicious kebab in the area?"
    shawarma "Or does Madame want to live in a beautiful apartment again?"
    m "I want to go back to my apartment!"
    shawarma "Jack can’t refuse such a beautiful lady!"
    shawarma "Does Madame have money?"
    m "Yes!"
    shawarma "Madame can pay money to Jack right now."
    shawarma "Jack will give Madame a new key."
    shawarma "And she can live again in Jack's beautiful apartment!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:784
translate english ep211_dialogues6_slum_apartment_17_cf64e261:

    # shawarma "Отлично, Мадаме!"
    # shawarma "Джек счастлив, что прекрасный Мадаме снова будет жить в его апрартамент!"
    # shawarma "Вот Ваш ключ. С возвращенем, прекрасный леди!"
    # mt "Наконец-то я могу вернуться в свою квартиру!"
    # mt "!!!"
    shawarma "Great, Madame!"
    shawarma "Jack is happy that the beautiful Madame will live in his apartment again!"
    shawarma "Here is your key. Welcome back, beautiful lady!"
    mt "Finally, I can return to my apartment!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:792
translate english ep211_dialogues6_slum_apartment_17_58f6c4c1:

    # mt "Нет, я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Я пока не готова заплатить деньги..."
    # shawarma "Если Мадаме передумает, она знать, где найти Джека!"
    # m "..."
    mt "No, I'm not ready to spend money on a place yet."
    mt "I can’t afford it now."
    m "I'm not ready to pay the money yet ..."
    shawarma "If Madame changes her mind, she knows where to find Jack!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:800
translate english ep211_dialogues6_slum_apartment_17_8b2a483c:

    # shawarma "О, Мадаме!"
    # shawarma "Вы пришли за самый вкусный кебаб в округе?"
    # shawarma "Или Мадаме хочет снова жить в шикарный апрартамент?"
    # mt "Нет, я пока не готова тратить деньги на жилье."
    # mt "Мне это сейчас не по карману."
    # m "Я пока не готова заплатить деньги..."
    # shawarma "Если Мадаме передумает, она знать, где найти Джека!"
    # m "..."
    shawarma "Oh Madame!"
    shawarma "Have you come for the most delicious kebab in the area?"
    shawarma "Or does Madame want to live in a beautiful apartment again?"
    mt "No, I'm not ready to spend money on a place yet."
    mt "I can’t afford it now."
    m "I'm not ready to pay the money yet ..."
    shawarma "If Madame changes her mind, she knows where to find Jack!"
    m "..."

# game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:814
translate english ep211_dialogues6_slum_apartment_18_ec2a48e9:

    # mt "Наконец-то я дома!"
    # mt "Никогда бы не подумала, что буду рада вернуться сюда!"
    # mt "!!!"
    mt "Finally I'm home!"
    mt "I would never have thought that I would be happy to be back here!"
    mt "!!!"

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:62
    old "Спросить у продавца шавермы про аренду квартиры."
    new "Ask the shawarma seller about renting an apartment."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:74
    old "Спросить про апартаменты..."
    new "Ask about apartments ..."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:74
    old "Уйти отсюда."
    new "Get out of here."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:90
    old "Моника называла продавца шавермы животным"
    new "Monica called the shawarma seller an animal"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:133
    old "Нет. $ 50 в неделю - это слишком дорого."
    new "No. $ 50 a week is too expensive."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:308
    old "Заплатить $ 300 за апартаменты."
    new "Pay $ 300 for the apartment."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:320
    old "Заработать $ 300 за аренду апартаментов до субботы."
    new "Earn $ 300 for renting an apartment till Saturday."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:321
    old "У меня теперь есть место, где я могу жить. Апартаменты в трущобах... Но это лучше, чем подвал в доме, где живет семейка идиотов."
    new "I have a place where I can live now. It’s an apartment in the slums ... But this is still better than the basement of the house where that idiotic family lives."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "Заплатить со скидкой."
    new "Pay with a discount."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "Заплатить $ 300"
    new "Pay $ 300"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:462
    old "У меня нет денег."
    new "I have no money."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:464
    old "Скидка 10 процентов."
    new "10 percent discount."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:464
    old "Скидка 20 процентов."
    new "20 percent discount."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:484
    old "Ни за что!!!"
    new "Never!!!"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:728
    old "Вернуться в квартиру позже."
    new "Return to the apartment later."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:764
    old "Поговорить с Джеком и снова заселиться в квартиру."
    new "Talk with Jack and check into the apartment again."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:770
    old "Спросить про квартиру..."
    new "Ask about the apartment ..."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:782
    old "Заплатить $ 300."
    new "Pay $ 300."

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:782
    old "Нет! Я не готова платить такую сумму!"
    new "No! I'm not ready to pay such an amount!"

    # game/Quests/EP2_11/ep211_dialogues6_slum_apartment.rpy:819
    old "Оплата за апартаменты в трущобах."
    new "Payment for the slums apartment."

