# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_escort_scene1.rpy:13
translate english ep211_escort_scene1_1a_5139b4d8:

    # mt "Что мне делать дальше?"
    # mt "..."
    mt "What should I do next?"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:31
translate english ep211_escort_scene1_1a_98200677:

    # mt "Что ж... Надеюсь, [monica_hotel_name] повезет сегодня с клиентом..."
    mt "Well ... I hope [monica_hotel_name] will get lucky with a client today..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:35
translate english ep211_escort_scene1_1a_25ff8835:

    # mt "Нет! Я не буду заниматься этим!!!"
    # mt "Я Моника Бакфетт! Я никогда не опущусь до подобной грязи!"
    # mt "!!!"
    mt "No! I won’t do this !!!"
    mt "I'm Monica Buckfett! I will never stoop that low!"
    mt "!!!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:46
translate english ep211_escort_scene1_1_9213bb70:

    # mt "Так, Моника. Соберись!"
    # mt "Не надо так нервничать."
    # mt "Ты в любой момент можешь послать всех к черту и уйти."
    # client "Добрый вечер, Мисс."
    # client "Я Вас раньше здесь не видел. Как вас зовут?"
    # m "Добрый вечер, Мистер."
    # m "Меня зовут [monica_hotel_name]."
    # client "[monica_hotel_name]. Какое прекрасное имя. Как и его обладательница."
    # client "Я очень рад, что сегодня проведу вечер с Вами, [monica_hotel_name]."
    # mt "Хмм... Разговаривает вежливо, выглядит вполне прилично."
    # mt "Думаю, от него не стоит ожидать никаких извращений..."
    # client "Позволите мне сразу пригласить Вас в номер, [monica_hotel_name]?"
    # mt "..."
    mt "So, Monica. Get together!"
    mt "Don't be so nervous."
    mt "You can send everyone to hell at any moment and leave."
    client "Good evening, Miss."
    client "I have not seen you here before. What is your name?"
    m "Good evening, Mister."
    m "My name is [monica_hotel_name]."
    client "[monica_hotel_name]. What a beautiful name. Just like its owner."
    client "I am very happy to spend the evening with you, [monica_hotel_name]."
    mt "Hmm... He talks politely, looks pretty decent."
    mt "I think I shouldn't expect any perversions from him..."
    client "Let me invite you to your room right now, [monica_hotel_name]?"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:64
translate english ep211_escort_scene1_1_3d014ec3:

    # mt "Нет! Я не могу это сделать!"
    # m "Я..."
    # m "Я не смогу с Вами пойти..."
    # m "Я... Я не работаю здесь!"
    # m "Я просто зашла поесть в ресторан..."
    # client "О, извините, Мисс."
    # client "Наверное, я перепутал столик."
    mt "No! I cannot do it!"
    m "I..."
    m "I can’t go with you..."
    m "I... I don't work here!"
    m "I just went to eat at a restaurant..."
    client "Oh sorry, Miss."
    client "I guess I got the wrong the table."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:76
translate english ep211_escort_scene1_1_5c853789:

    # mt "Это же совсем нестрашно."
    # mt "Это просто обычный неудачник."
    # mt "Наверное, приходит сюда раз в месяц в день зарплаты. Фи!"
    # mt "Что-то пойдет не так - я просто уйду отсюда."
    # mt "Хммм..."
    # mt "Они мне тогда сказали, что будут давать мне заказы..."
    # mt "Только с проблемными клиентами."
    # mt "..."
    # mt "Мне нужно сказать этой никчемной администраторше, что у меня клиент."
    # mt "Может, она скажет, что с ним не так."
    # m "Да, мы можем пойти в номер."
    # m "Только мне нужно отойти на пару минут."
    # client "Конечно, [monica_hotel_name]."
    # client "Я буду ждать тебя у лифта."
    mt "This is totally not scary."
    mt "This is just an ordinary loser."
    mt "Probably comes here once a month on a payday. Ew!"
    mt "If something goes wrong - I’ll just leave here."
    mt "Hmmm."
    mt "They told me then they'd give me orders..."
    mt "From problem customers."
    mt "..."
    mt "I need to tell this worthless administrator that I have a client."
    mt "Maybe she will say what is wrong with him."
    m "Yes, we can go to the room."
    m "It's just I need to leave for a few minutes."
    client "Of course, [monica_hotel_name]."
    client "Я буду ждать тебя у лифта."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:96
translate english ep211_escort_scene1_2_72e84a43:

    # m "У меня клиент. Он зовет пойти с ним в номер..."
    # reception "Я уже в курсе..."
    # reception "Это один из наших постоянных клиентов."
    # reception "Девочки не любят работать с ним."
    # m "Почему?"
    # mt "Вроде он не похож на извращенца."
    # reception "У него не встает, но он никак не хочет смириться с этим..."
    # reception "Он всегда заказывает девочек и мурыжит их до утра."
    # reception "Очень хочет кончить..."
    # reception "Но, как правило, безрезультатно."
    # reception "Потом скандалит и обвиняет девочек в том, что они плохо работают."
    # mt "!!!"
    # m "То есть... Если он скажет, что я плохо работаю, то..."
    # reception "Штраф."
    # mt "Вот сучка!"
    # m "Ты же сама говоришь, что дело в клиенте, а не в девочках!"
    # m "Какой еще штраф?!"
    # reception "Это правило нашего ВИП Эскорта."
    # mt "Что за бред!!!"
    # reception "И я переоделась бы на твоем месте..."
    # reception "Иди в служебный коридор."
    # reception "Там можно найти что-нибудь, что возбудит этого клиента."
    # m "Но..."
    # reception "Все! Иди. Не заставляй клиента ждать тебя!"
    # m "..."
    # reception "Быстро!"
    m "I have a client. He asked me to go to a room woth him..."
    reception "I already know ..."
    reception "This is one of our regular customers."
    reception "Girls don’t like to work with him."
    m "Why?"
    mt "He doesn’t look like a pervert."
    reception "He can’t get his wee-wee up, but he does not want to come to terms with it..."
    reception "He always orders girls and messes with them until morning."
    reception "He wants to cum ..."
    reception "But it usually doesn't come to that."
    reception "Then he accuses the girls of not doing their job properly."
    mt "!!!"
    m "Then... If he says that I did a bad job ..."
    reception "You get fined."
    mt "What a bitch!"
    m "You're saying it's the client, not the girls!"
    m "Why would I get fined?!"
    reception "This is the rule of our VIP Escort."
    mt "Nonsense !!!"
    reception "And I would change if I were you ..."
    reception "Иди в служебный коридор."
    reception "Там можно найти что-нибудь, что возбудит этого клиента."
    m "But..."
    reception "Все! Иди. Не заставляй клиента ждать тебя!"
    m "..."
    reception "Hurry up!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:130
translate english ep211_escort_scene1_3_a8f99376:

    # client "[monica_hotel_name], я Вас уже заждался."
    # client "Пройдемте в номер!"
    # client "Мне уже не терпится посмотреть, что у Вас под платьем..."
    # mt "..."
    # mt "Так, Моника, соберись!"
    # mt "Тебе надо представить, что ты [monica_hotel_name]."
    # mt "А не Моника Бакфетт."
    # mt "А это просто обычный неудачник."
    # mt "Наверное, приходит сюда раз в месяц в день зарплаты. Фи!"
    # mt "Что-то пойдет не так - я просто уйду отсюда."
    client "[monica_hotel_name], я Вас уже заждался."
    client "Пройдемте в номер!"
    client "Мне уже не терпится посмотреть, что у Вас под платьем..."
    mt "..."
    mt "So, Monica, think!"
    mt "You have to imagine that you are [monica_hotel_name]."
    mt "Not Monica Buckfett."
    mt "And this is just an ordinary loser."
    mt "Probably comes here once a month on a payday. Ew!"
    mt "If something goes wrong - I’ll just leave here."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:145
translate english ep211_escort_scene1_4_1399e723:

    # m "Что мне нужно сделать?"
    # mt "Дал бы денег просто так и отпустил бы..."
    # mt "У меня нет никакого желания делать для него что-то."
    # client "Для начала [monica_hotel_name] должна снять платье..."
    # mt "Моника, не переживай."
    # mt "Тебе нечего стесняться. У тебя великолепное тело."
    # mt "..."
    # mt "Он, наверняка, никогда не видел такой красивой женщины, как я."
    # mt "Сейчас он разденется и начнет лапать мое прекрасное тело. Фу!"
    # client "[monica_hotel_name], присаживайтесь рядом со мной."
    # client "Если [monica_hotel_name] позволит мне целовать ее ножку..."
    # client "Я буду щедр с Мисс."
    # mt "Он хочет целовать мне ноги?"
    # mt "Да еще и платить за это?!"
    # mt "?!?!?!"
    # mt "Он это серьезно?!"
    # mt "???"
    # mt "Может, я ослышалась?"
    # m "Мистер, Вы хотите целовать мою ногу?"
    # client "Да, Мисс. Позвольте Вашу ножку."
    # m "..."
    # m "Ммммм..."
    # mt "Это приятно..."
    # mt "Черт!"
    # mt "Он за это еще и денег заплатит?"
    # mt "Я готова работать так каждый вечер."
    # mt "О, как же приятно..."
    # client "А теперь [monica_hotel_name] возьмет мой палец в свой ротик..."
    # client "И пососет его..."
    # mt "???"
    m "What do I need to do?"
    mt "I wish he would just give me money and let me go..."
    mt "I have no desire to do anything for him."
    client "To start, [monica_hotel_name] must take off her dress..."
    mt "Monica, don’t worry."
    mt "You have nothing to be shy about. You have a great body."
    mt "..."
    mt "He probably never saw such a beautiful woman like me."
    mt "Now he will undress and begin to paw my beautiful body. Ew!"
    client "[monica_hotel_name], have a seat next to me."
    client "If [monica_hotel_name] allows me to kiss her leg..."
    client "I will be generous with Miss."
    mt "Does he want to kiss my legs?"
    mt "And pay for it as well?!"
    mt "?!?!?!"
    mt "Is he serious?!"
    mt "???"
    mt "Maybe I misheard?"
    m "Mister, you want to kiss my leg?"
    client "Yes, miss. Let me kiss your leg."
    m "..."
    m "Mmmm..."
    mt "So nice..."
    mt "Heck!"
    mt "Will he also pay money for this?"
    mt "I am ready to work like this every night."
    mt "Oh, how nice ..."
    client "And now [monica_hotel_name] will take my finger in her mouth..."
    client "And suck it ..."
    mt "???"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:187
translate english ep211_escort_scene1_4_0d5ba6cc:

    # mt "Фу! Нет! Я не могу это сделать!"
    # mt "Я не хочу облизывать грязные руки этого неудачника!"
    # m "Я..."
    # m "Я не смогу..."
    # m "Я... Я не предоставляю такую услугу!"
    # client "Но, Мисс... Мне сказали, что..."
    # m "Нет. Я не буду этого делать!"
    mt "Ew! No! I can't do it!"
    mt "I don't want to lick that loser's dirty hands!"
    m "I..."
    m "I can't..."
    m "I... I do not provide such a service!"
    client "But, Miss... I was told that..."
    m "No. I will not do it!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:200
translate english ep211_escort_scene1_4_d6c1ab97:

    # mt "Это унизительно и..."
    # mt "Противно!"
    # mt "Но брать в рот его грязный палец!!!"
    # mt "!!!"
    # mt "Но он сказал, что будет щедр..."
    # mt "Все же это не какое-то там гадкое извращенство..."
    # mt "..."
    # mt "Это просто работа, Моника."
    # mt "..."
    # mt "Главное, чтобы меня не стошнило прямо на него."
    # client "Соси его!"
    # client "Оооооо!!!"
    # client "Как же приятно! Ещееее!!!"
    # client "А теперь, [monica_hotel_name], раздвинь ноги!"
    # client "Я хочу посмотреть на твою киску!"
    # client "!!!"
    # mt "Черт!"
    # mt "Какой-то мерзкий неудачник сейчас будет пялиться на мою..."
    # mt "..."
    # mt "Но если я откажу ему, он не заплатит денег."
    # mt "И будут проблемы с этой никчемной администраторшей..."
    # mt "Она говорила, что будет штраф."
    # mt "А мне нужны деньги."
    # mt "..."
    mt "It is humiliating and..."
    mt "It's disgusting!"
    mt "Or take his dirty finger in his mouth !!!"
    mt "!!!"
    mt "But he said he would be generous..."
    mt "Yet this is not some nasty perversion there..."
    mt "..."
    mt "It's just a job, Monica."
    mt "..."
    mt "The main thing is not to puke on him."
    client "Suck it!"
    client "Oooooh!!!"
    client "How nice! More!!!"
    client "And now, [monica_hotel_name], spread your legs!"
    client "I want to look at your pussy!"
    client "!!!"
    mt "Heck!"
    mt "Some vile loser will now be staring at my ..."
    mt "..."
    mt "But if I refuse him, he won’t pay me."
    mt "And there will be problems with that worthless administrator ..."
    mt "She said she would fine me."
    mt "And I need money."
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:230
translate english ep211_escort_scene1_4_24fd42b5:

    # client "О, дааааа!"
    # client "Дрочи!"
    # m "???"
    # client "Я хочу смотреть, как ты дрочешь себе!"
    # client "Ну! Давай же! Дрочи!"
    client "Oh yeah!"
    client "Masturbate!"
    m "???"
    client "Я хочу смотреть, как ты дрочешь себе!"
    client "Ну! Давай же! Дрочи!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:239
translate english ep211_escort_scene1_4_49d82231:

    # mt "Фу! Нет! Я не хочу!"
    # mt "Мне надоело возиться с этим неудачником!"
    # mt "!!!"
    # m "Нет. Я не буду этого делать!"
    mt "Ew! No! I don’t want to!"
    mt "I'm tired of messing with this loser!"
    mt "!!!"
    m "No. I will not do it!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:248
translate english ep211_escort_scene1_4_f57aafd8:

    # mt "Надеюсь, ему достаточно будет того, что он посмотрит как я себя трогаю..."
    # mt "Лучше так, чем он будет лезть к моей..."
    # mt "Ко мне своими грязными пальцами!"
    # client "Оооо!!! Я сейчас!!!"
    # client "Еще чуть-чуть!!!"
    # client "Ааааа!!!"
    # client "Засунь себе свой палец в дырочку!!!"
    # client "Давай же!!!"
    # client "ААААААА!!!"
    # mt "?!"
    # mt "Кончил?"
    # mt "Этот никчемный неудачник в жизни не видел такой красивой женщины как Я."
    # mt "Неудивительно, что с теми сучками из эскорта у него не получалось!"
    # mt "!!!"
    # mt "Боже. Моника, ты серьезно сейчас?!"
    # mt "Ты гордишься тем, что какой-то мерзкий тип обкончался, глядя на тебя?!"
    # mt "Ты что, совсем с ума сошла?!"
    # mt "Фу!"
    # mt "..."
    # client "Ты самая лучшая девочка здесь, [monica_hotel_name]."
    # client "Мне очень понравилось."
    # m "..."
    # client "Здесь 700 долларов. Я обязательно приду к тебе еще раз, [monica_hotel_name]." 
    # mt "700 долларов?!"
    # mt "Я заработала 700 долларов, облизывая палец незнакомому мужчине!"
    # mt "..."
    # mt "Меньше всего хочется отдавать половину этой сучке на ресепшене..."
    # mt "Может, уйти и больше просто не приходить сюда?"
    # mt "Что она мне сделает?"
    # mt "С другой стороны, здесь я за вечер могу заработать такие большие деньги."
    # mt "А она меня больше не пустит в ресторан."
    # mt "Нет, мне не стоит пока терять эту возможность заработка."
    mt "I hope it’s enough for him to see me touching myself ..."
    mt "Better me then him ..."
    mt "with his dirty fingers!"
    client "Oh!!! I'm coming!!!"
    client "A little bit more!!!"
    client "Ahhhh !!!"
    client "Засунь себе свой палец в дырочку!!!"
    client "Come on!!!"
    client "AAAAAAA!!!"
    mt "?!"
    mt "Your done?"
    mt "This worthless loser has never seen a woman as beautiful as me in his Iife."
    mt "Not surprisingly, he didn't succeed with those escort bitches!"
    mt "!!!"
    mt "Oh god Monica, are you serious now ?!"
    mt "Are you proud that some vile guy came while looking at you?!"
    mt "Are you really out of your mind?!"
    mt "Phew!"
    mt "..."
    client "You are the best girl here, [monica_hotel_name]."
    client "I really liked it."
    m "..."
    client "Here is 700 dollars. I will definitely come to you again, [monica_hotel_name]." 
    mt "700 dollars?!"
    mt "I earned $ 700 by licking some stranger's finger!"
    mt "..."
    mt "Least of all I want to give half to this bitch at the reception..."
    mt "Maybe I should just leave and never return here?"
    mt "What will she do to me?"
    mt "On the other hand, here I can earn so much money over one evening."
    mt "And she will not let me into the restaurant anymore."
    mt "No, I should not lose this money opportunity yet."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:294
translate english ep211_escort_scene1_5_4026cc9e:

    # m "Клиент заплатил 700 долларов."
    # reception "И остался доволен."
    # reception "Ты хорошо поработала ртом."
    # mt "!!!"
    # m "Откуда ты?.."
    # reception "Я все знаю..."
    # reception "Это моя работа!"
    # reception "Вот твои деньги."
    # reception "Завтра можешь приходить снова."
    # reception "На сегодня все."
    # reception "Клиенты не любят использованный товар."
    # mt "Вот сучка!"
    # mt "Откуда она знает, что я... Работала ртом?!"
    # mt "Она подглядывала?!"
    # mt "!!!"
    m "The client paid 700 dollars."
    reception "And he was pleased."
    reception "You did a good job with your mouth."
    mt "!!!"
    m "Why do you...?"
    reception "I know..."
    reception "Absolutely, your wish is my command!"
    reception "Here's your money."
    reception "You can come again tomorrow."
    reception "That's all for today."
    reception "Customers don’t like used goods."
    mt "What a bitch!"
    mt "How does she know that I... worked with mouth?!"
    mt "Did she peep on me?!"
    mt "!!!"

# game/Quests/EP2_11/ep211_escort_scene1.rpy:315
translate english ep211_escort_scene1_6_424a662d:

    # mt "Я пока не могу так рисковать!"
    # mt "Эта сучка меня не пустит больше в ресторан, если я не отдам ей 50 процентов."
    # mt "А мне не выгодно терять такой заработок."
    # mt "Но я обязательно потом что-нибудь придумаю: чтобы не делиться с ней!"
    # mt "..."
    mt "I can’t take such a risk!"
    mt "This bitch won't let me go to the restaurant anymore unless I give her 50 percent."
    mt "And it’s not profitable for me to lose that kind of income."
    mt "But I’ll definitely come up with something later, so I won't need to share with her!"
    mt "..."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:328
translate english ep211_escort_scene1_7_1c313cdf:

    # mt "Я сегодня за вечер заработала 350 долларов."
    # mt "Неплохой заработок, учитывая мою временную ситуацию."
    # mt "Возможно, мне стоит пересилить себя и поработать здесь еще какое-то время."
    # mt "Быть может, у меня получится зарабатывать еще больше."
    # mt "Мне нужно будет прийти сюда завтра."
    # mt "..."
    # mt "Я ведь в любой момент смогу отказаться и уйти."
    mt "I made $ 350 this evening."
    mt "Good money, given my temporary situation."
    mt "Perhaps I should accept my fate and work here for some time."
    mt "Perhaps I will manage to earn even more."
    mt "I will need to come here tomorrow."
    mt "..."
    mt "I can refuse and quit at any time anyway."

# game/Quests/EP2_11/ep211_escort_scene1.rpy:340
translate english ep211_escort_scene1_8_4ad016fe:

    # mt "Я никогда не смогу решиться на такое!"
    # mt "Я Моника Бакфетт, а не какая-то проститутка!"
    mt "I'll never be able to accept this!"
    mt "I'm Monica Buckfett, not some prostitute!"

translate english strings:

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:15
    old "Встреча с клиентом (сцена)."
    new "Meeting with the client (scene)."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:15
    old "Ждать клиента за столиком."
    new "Waiting for a customer at the table."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:17
    old "Клиент в номере отеля."
    new "Customer in a hotel room."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:17
    old "Выезд к клиенту."
    new "Departure to the client."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:91
    old "Пойти на ресепшн к администратору."
    new "Go to the reception desk."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:124
    old "Пойти к клиенту. Он ждет у лифта."
    new "Go to the customer. He is waiting by the elevator."

    # game/Quests/EP2_11/ep211_escort_scene1.rpy:236
    old "Нет, я не хочу этого делать!"
    new "No, I don't want to do this!"

