# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:7
translate english ep211_dialogues4_julia_1_2f3feef2:

    # mt "Пора уже заканчивать эту комедию с нежностями."
    # mt "Мне надоело строить из себя какую-то влюбленную дурочку."
    # mt "..."
    # mt "Мне нужно попасть к Юлии домой."
    # mt "Тогда я точно смогу залезть к ней под платье..."
    # mt "Или хотя бы посмотреть, какого цвета белье лежит у нее в шкафчиках."
    # mt "А вдруг она меня тогда обманула и она вообще не носит трусики?"
    # mt "Это бы объяснило то, что она так упорно отказывается дать заглянуть себе под юбку..."
    # mt "Нужно будет это выяснить."
    # mt "..."
    # mt "И как мне попасть к ней домой?"
    # mt "???"
    # mt "Хм... Придется пригласить ее на свидание еще раз..."
    # mt "И напроситься к ней в гости."
    # mt "Да, точно."
    # mt "Она уже доверяет мне намного больше, чем раньше."
    # mt "Думаю, в этот раз она мне не откажет."
    # m "Милая, я хотела бы провести с тобой вечер..."
    # m "Сменить обстановку..."
    # m "Мы с тобой видимся только на работе."
    # m "Что скажешь?"
    # julia "Миссис Бакфетт..."
    # julia "Вы... Вы приглашаете меня на свидание?!"
    # m "Да, милая. Я хочу пригласить тебя на ужин."
    # julia "О, Миссис Бакфетт, это замечательная идея!"
    # julia "Я с радостью проведу с Вами вечер!"
    # julia "А когда?"
    # m "Сегодня вечером, после работы."
    # m "В том же кафе рядом с твоим домом."
    # julia "Хорошо, Миссис Бакфетт. С нетерпением буду ждать вечера!"
    mt "It's time to end this farce with all the tenderness."
    mt "I'm tired of faking this lovey-dovey persona."
    mt "..."
    mt "I need to get to Julia's home."
    mt "Then I can definitely get under her dress ..."
    mt "Or at least see what color the panties are in her dresser."
    mt "What if she deceived me back then and she doesn’t wear panties at all?"
    mt "This would explain the fact that she so stubbornly refuses to let me look under her skirt ..."
    mt "I need to find that out."
    mt "..."
    mt "And how do I get in her house?"
    mt "???"
    mt "Hmm ... I have to ask her out again ..."
    mt "And ask to visit her."
    mt "Yes, exactly."
    mt "She already trusts me a lot more than before."
    mt "I think this time she won’t refuse me."
    m "Honey, I would like to spend the evening with you ..."
    m "Change the scenery ..."
    m "You and I see each other only at work."
    m "What do you say?"
    julia "Mrs. Buckfett..."
    julia "You ... are you inviting me for a date ?!"
    m "Yes, darling. I want to invite you to dinner."
    julia "Oh Mrs. Buckfett, that's a great idea!"
    julia "I will be happy to spend the evening with you!"
    julia "But when?"
    m "Tonight, after work."
    m "In the same cafe next to your house."
    julia "Okay, Mrs. Buckfett. I will look forward to the evening!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:50
translate english ep211_dialogues4_julia_2_34703247:

    # julia "Миссис Бакфетт! Я так рада нашей встрече!"
    # m "Привет, милая..."
    julia "Mrs. Buckfett! I am so glad to see you!"
    m "Hello, honey ..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:57
translate english ep211_dialogues4_julia_2_0077a8a0:

    # mt "Нет, я не хочу этого делать!" 
    # mt "Не хочу и не буду!"
    # mt "Мне надоели эти глупости!"
    # mt "!!!"
    mt "No, I don't want to do this!" 
    mt "I don't and I won't!"
    mt "I'm tired of this nonsense!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:63
translate english ep211_dialogues4_julia_2_35713388:

    # cafe_barista "Добрый вечер. Пожалуйста наше меню."
    # julia "О, я так давно не ела чизкейк!"
    # m "Милая..."
    # m "Думаю, что тебе не нужно заказывать чизкейк."
    # julia "???"
    # m "..."
    # m "Это вредно для фигуры..."
    # julia "Тогда, может быть..."
    # julia "..."
    # mt "Долбанная официанта!"
    # mt "Зачем она притащила меню?!"
    # cafe_barista "Мэм, а Вы что желаете?"
    # m "Я ничего не буду!"
    # m "Я как раз недавно плотно поела и, боюсь, еще один прием пищи может сказаться на моей фигуре."
    # mt "Не хватало еще тратить здесь свои деньги!"
    # mt "Откуда вообще взялись такие цены в этой дыре?!"
    # julia "Я выбрала!"
    # julia "Мне, пожалуйста, этот салат. Греческий."
    # mt "Никчемная Юлия!"
    # mt "Можно было выбрать что-то и подешевле!"
    # julia "И еще латте, пожалуйста."
    # mt "!!!"
    # julia "Миссис Бакфетт, Вы точно ничего не хотите?"
    # m "Нет, милая. Я не голодна..."
    # cafe_barista "Может, воды?"
    # m "НЕТ!" 
    # cafe_barista "Хорошо. Скоро принесу Ваш заказ."
    # mt "Мне снова придется платить за ужин!"
    # mt "А самой сидеть и смотреть, как ест эта никчемная Юлия!"
    # mt "!!!"
    # julia "Миссис Бакфетт, Вы сегодня так хорошо выглядите..."
    # m "Спасибо... Милая..."
    # m "Ты тоже."
    # m "..."
    # mt "Мне даже не о чем с ней поговорить..."
    # mt "И неудивительно! О чем может разговаривать с какой-то служанкой такая леди как Я?!"
    # m "..."
    cafe_barista "Good evening. Please look over our menu."
    julia "Oh, I haven’t eaten cheesecake for so long!"
    m "Darling..."
    m "I think you don’t need to order a cheesecake."
    julia "???"
    m "..."
    m "That is bad for the figure ..."
    julia "Then maybe ..."
    julia "..."
    mt "Fucking waitress!"
    mt "Why did she bring the menu ?!"
    cafe_barista "Ma'am, what do you want?"
    m "I don’t want anything!"
    m "I ate just recently and, I'm afraid, another meal may affect my figure."
    mt "I don't want to spend any money here!"
    mt "Where did such prices came from in this hole ?!"
    julia "I've made my choice!"
    julia "I'd like a greek salad, please.."
    mt "Worthless Julia!"
    mt "You could’ve chosen something cheaper!"
    julia "И еще латте, пожалуйста."
    mt "!!!"
    julia "Mrs. Buckfett, you really don’t want anything?"
    m "No, honey. I'm not hungry..."
    cafe_barista "Maybe water?"
    m "NO!" 
    cafe_barista "Alright. I’ll bring your order soon."
    mt "I will have to pay for dinner again!"
    mt "And to sit and watch this worthless Julia eat!"
    mt "!!!"
    julia "Mrs. Buckfett, you look so good today ..."
    m "Thank you ... Honey ..."
    m "You too."
    m "..."
    mt "I don’t even have anything to talk about with her ..."
    mt "And no wonder! What can a lady like me talk about with some maid?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:115
translate english ep211_dialogues4_julia_2_4ec02e1e:

    # m "Юлия, милая, расскажи о себе..."
    # m "Я тут поняла, что совсем ничего о тебе не знаю..."
    # cafe_barista "Ваш заказ, пожалуйста."
    # julia "Спасибо."
    # julia "Мне приятно, что Вас это интересует, Миссис Бакфетт..."
    # m "..."
    # julia "Я родилась и выросла в другой стране."
    # julia "..."
    # julia "У моей семьи нет большого достатка."
    # julia "Родители живут от зарплаты до зарплаты."
    # julia "..."
    # julia "Я очень скучаю по своей родине, но..."
    # julia "Я не хочу возвращаться туда."
    # m "Почему?"
    # julia "У меня есть богатый и влиятельный родственник. Мой дядя."
    # julia "Он пытается влиять на нашу семью и мне это совсем не нравится."
    # julia "У меня с ним очень плохие отношения."
    # julia "В моей семье меня никто не понимал и не поддерживал."
    # julia "Поэтому я уехала и живу независимо от них."
    # julia "Должно произойти нечто экстраординарное, чтобы я вернулась к ним..."
    # julia "..."
    # mt "Странно... Дома у нее богатый родственник."
    # mt "Могла бы наладить с ним отношения и не знать никакой нужды."
    # mt "А она здесь работает за копейки."
    # mt "Никогда не понимала логику неудачников..."
    # m "..."
    # m "Сейчас ты живешь здесь, в трущобах?"
    # julia "Да, Миссис Бакфетт."
    # julia "Я арендую тут квартиру."
    # mt "Хммм.."
    # mt "Арендовать квартиру в трущобах - это, наверное, недорого?"
    # mt "..."
    # mt "Но жить в трущобах!!! Фи!"
    # mt "..."
    # mt "С другой стороны..."
    # mt "Не будет деревенщины Бетти и озабоченного сопляка Барди..."
    # mt "Сколько уже можно работать на эту семейку идиотов?!"
    # mt "Да еще и без оплаты!"
    # mt "Я смогу забыть эту семейку, как страшный сон."
    # mt "Начать жить независимо ни от кого."
    # mt "Почему бы мне не попробовать?"
    # mt "..."
    # mt "Только у кого мне узнать про аренду квартиры?"
    # mt "Мне нужно будет подумать об этом..."
    # cafe_barista "Мэм, с вас $ 20."
    # julia "Миссис Бакфетт, спасибо за ужин."
    # julia "Я... Я хотела бы... в знак благодарности за вечер..."
    # julia "Пригласить Вас к себе домой."
    # mt "!!!"
    # mt "Отлично!"
    # julia "Только я стесняюсь, что такая леди как Вы..."
    # julia "Придет в такую конуру, в которой я живу..."
    # m "Да. Это, конечно, будет шокирующе для меня и непривычно..."
    # m "Но ради моих чувств к тебе, милая, я готова потерпеть этот дискомфорт."
    # mt "Я почти у цели!"
    # mt "Какой замечательный сегодня вечер!"
    # julia "Спасибо, Миссис Бакфетт. Вы так добры."
    # m "Ну что? Пойдем?"
    # julia "Да, Миссис Бакфетт."
    m "Julia, honey, tell me about yourself ..."
    m "I realized that I don’t know anything about you ..."
    cafe_barista "Here's your order. Please enjoy."
    julia "Thank you."
    julia "I'm glad you're interested, Mrs. Buckfett ..."
    m "..."
    julia "I was born and raised in another country."
    julia "..."
    julia "My family is not very wealthy."
    julia "My parents live from paycheck to paycheck."
    julia "..."
    julia "I really miss my homeland, but ..."
    julia "I don’t want to go back there."
    m "Why?"
    julia "I have a rich and influential relative. My uncle."
    julia "He is trying to influence our family and I don’t like it at all."
    julia "I have a very bad relationship with him."
    julia "In my family, no one understood or supported me."
    julia "So I left and now live independently of them."
    julia "Something extraordinary must happen for me to return to them ..."
    julia "..."
    mt "Strange ... She has a rich relative at home."
    mt "She could have fixed your relationship with him and not know any need."
    mt "And she works here for change."
    mt "I never understood the logic of losers ..."
    m "..."
    m "Do you live here in slums now?"
    julia "Mrs. Buckfett."
    julia "I rent an apartment here."
    mt "Hmmm .."
    mt "To rent an apartment in a slum is probably inexpensive?"
    mt "..."
    mt "But to live in slums !!!! Ew!"
    mt "..."
    mt "From the other side..."
    mt "There will be no bumpkin Betty and that perverted kid Bardi..."
    mt "I've had enough of working for this family of idiots!"
    mt "And for free to boot!"
    mt "I can forget this little family like a nightmare."
    mt "Start living independently from anyone."
    mt "Why don't I give it a try?"
    mt "..."
    mt "Only who should I ask about renting an apartment?"
    mt "I will need to think about it ..."
    cafe_barista "It'll be $ 20, ma'am."
    julia "Mrs. Buckfett, thanks for the dinner."
    julia "I... I'd like to... as a token of gratitude for the evening..."
    julia "Invite you to my home."
    mt "!!!"
    mt "Excellent!"
    julia "Only I'm embarrassed that a lady like you..."
    julia "Will come to such a kennel I live in..."
    m "Yes. This, of course, will be shocking to me and unusual ..."
    m "But for the sake of my feelings for you, dear, I am ready to suffer this discomfort."
    mt "I'm almost there!"
    mt "What a wonderful evening tonight!"
    julia "Thank you, Mrs. Buckfett. You are so kind."
    m "Well? Shall we go?"
    julia "Mrs. Buckfett."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:189
translate english ep211_dialogues4_julia_3_28da916e:

    # mt "О Боже! Какой кошмарный дом!"
    # mt "Как здесь можно жить?!"
    # mt "Уверена, тут живут одни неудачники и... извращенцы!"
    # mt "И тут небезопасно вечером..."
    # mt "Нет. Вряд ли я смогу жить в таких условиях."
    # mt "Такая леди, как я, никогда не сможет привыкнуть к подобному."
    # mt "..."
    # mt "Хотя... Для меня и это место сейчас бы подошло..."
    mt "Oh my God! What a nightmarish house!"
    mt "How can one live here ?!"
    mt "I’m sure that only losers live here and ... perverts!"
    mt "And it’s not safe in the evening here..."
    mt "No. It is unlikely that I can live in such conditions."
    mt "A lady like me can never get used to it."
    mt "..."
    mt "Although ... For me, this place would be suitable now ..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:202
translate english ep211_dialogues4_julia_4_58570ed2:

    # mt "Хммм... Я думала, будет намного хуже."
    # mt "Нет, здесь все, конечно, ужасно, но..."
    # mt "В моей ситуации это могло бы стать неплохим вариантом на время."
    # mt "Пожалуй, стоит обдумать вопрос аренды квартиры."
    # mt "Наверняка жилье здесь почти ничего не стоит..."
    # mt "И я смогу договориться с кем-нибудь о том, чтобы снимать его без лишних документов..."
    # mt "И потом... Все равно никто не узнает, что я живу в трущобах."
    # mt "Это ведь ненадолго."
    # julia "..."
    # m "Юлия, милая, ты напрасно переживала."
    # m "У тебя очень уютно."
    # julia "Правда?"
    # m "Да, милая..."
    # m "..."
    mt "Hmmm ... I thought it would be much worse."
    mt "No, everything here is, of course, terrible, but ..."
    mt "In my situation, this could be a good option for a while."
    mt "Perhaps it is worth considering renting an apartment here."
    mt "Surely housing here costs almost nothing ..."
    mt "And I can find someone to rent it from without most documents ..."
    mt "And then ... Anyway, no one will know that I live in the slums."
    mt "This is not for long."
    julia "..."
    m "Julia, dear, you worried in vain."
    m "It's very comfy in here."
    julia "Really?"
    m "Yes darling..."
    m "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:222
translate english ep211_dialogues4_julia_4_283b99cb:

    # mt "Нет, я не буду этого делать!" 
    # mt "Мне надоело заниматься этими глупостями!"
    # mt "!!!"
    # m "Знаешь, Юлия, у меня сегодня еще много дел."
    # m "Так что, я пойду."
    # julia "Но... Миссис Бакфетт!"
    # julia "Это из-за того, что я..."
    # julia "Постоянно Вам отказываю?"
    # m "Это уже не имеет значения!"
    # m "Забудь все, что было!"
    # m "Увидимся на работе."
    # julia "..."
    mt "No, I won't do that!" 
    mt "I'm tired of doing these stupid things!"
    mt "!!!"
    m "You know, Julia, I still have a lot to do today."
    m "So, I will go."
    julia "But... Mrs. Buckfett!"
    julia "This is because I ..."
    julia "Constantly refuse youe advances?"
    m "It doesn’t matter anymore!"
    m "Forget there was anything between us!"
    m "See you at work."
    julia "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:236
translate english ep211_dialogues4_julia_4_409e9ae0:

    # mt "Вот он момент!"
    # julia "!!!"
    # julia "Миссис Бакфетт, я... Я еще не готова..."
    mt "Here is the moment!"
    julia "!!!"
    julia "Mrs. Buckfett, I ... I'm not ready yet ..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:245
translate english ep211_dialogues4_julia_4_e66e4b42:

    # m "Милая, я тебя просто потрогаю и не более того."
    # m "У тебя ведь есть там трусики, правда?"
    # julia "Да, Миссис Бакфетт... Они есть..."
    # m "Можно я проверю это? Я только проведу там рукой, я не буду подглядывать..."
    # julia "Ну... Если только потрогать... Только совсем немного..."
    # mt "Ага! Она все-таки носит трусики!"
    # mt "Я почти у цели!"
    # mt "Осталось уговорить ее приподнять платье..."
    # julia "Миссис Бакфетт... На сегодня этого будет достаточно..."
    # mt "Твою мать!!!"
    # mt "!!!"
    # mt "!!!!!!"
    m "Honey, I’m just touching you and nothing more."
    m "You have panties there, right?"
    julia "Yes, Mrs. Buckfett ... They are ..."
    m "Can I check it? I will only pass my hand there, I will not peep ..."
    julia "Well ... If you only ... just a little bit ..."
    mt "Yeah! She still wears panties!"
    mt "I'm almost there!"
    mt "All that's lef is to persuade her to raise her dress ..."
    julia "Mrs. Buckfett ... That will be enough for today ..."
    mt "Fuck!!!"
    mt "!!!"
    mt "!!!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:266
translate english ep211_dialogues4_julia_4_075ce702:

    # mt "Мне надоело заниматься этими глупостями!" 
    # mt "!!!"
    # m "Знаешь, Юлия, у меня сегодня еще много дел."
    # m "Так что, я пойду."
    # julia "Но... Миссис Бакфетт!"
    # julia "Это из-за того, что я Вам отказала?"
    # m "Это уже не имеет значения!"
    # m "Забудь все, что было!"
    # m "Увидимся на работе."
    # julia "..."
    mt "I'm tired of doing these stupid things!" 
    mt "!!!"
    m "You know, Julia, I still have a lot to do today."
    m "So, I will go."
    julia "But... Mrs. Buckfett!"
    julia "Is it because I refused you?"
    m "It doesn’t matter anymore!"
    m "Forget there was anything between us!"
    m "See you at work."
    julia "..."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:278
translate english ep211_dialogues4_julia_4_f66090be:

    # mt "Так, Моника, спокойно."
    # mt "У тебя есть еще один вариант..."
    # m "Юлия, милая. Мне нужно в туалет. Подскажи, где он?"
    # julia "Конечно, Миссис Бакфетт. Вон та дверь, справа."
    mt "Okay, Monica, calm down."
    mt "You have another option ..."
    m "Julia, honey. I need to go to the toilet. Where is it?"
    julia "Of course, Mrs. Buckfett. That door on the right."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:287
translate english ep211_dialogues4_julia_5_1f927c50:

    # julia "Дверь в туалет справа от входной двери, Миссис Бакфетт."
    julia "The toilet door to the right of the front door, Mrs. Buckfett."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:293
translate english ep211_dialogues4_julia_6_91374fb0:

    # mt "Стиральная машинка... Корзина для белья... Шкафчики..."
    # mt "Наверняка, здесь что-то есть из ее белья!"
    # mt "Дьявол!"
    # mt "Почему здесь ничего нет?!"
    # mt "Где все белье?!"
    # mt "У нее что, только одни трусики, которые сейчас на ней?!"
    # mt "Какого только хлама нет, но только не трусиков!!!"
    # mt "Какого черта?!"
    # mt "!!!"
    # mt "Никчемная Юлия!!!"
    # mt "Бесит!!!"
    mt "Washing machine ... Laundry basket ... Lockers ..."
    mt "Surely, there is some underwear in here!"
    mt "Devil!"
    mt "Why is there nothing here ?!"
    mt "Where is all the laundry ?!"
    mt "Does she only have a single pair of panties that she's wearing right now?!"
    mt "What bullshit is this, not on pair of panties !!!"
    mt "What the hell?!"
    mt "!!!"
    mt "Worthless Julia !!!"
    mt "Infuriating !!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:311
translate english ep211_dialogues4_julia_7_7871bfb2:

    # m "Милая, мне очень нравится твоя квартира."
    # m "Она небольшая, но уютная."
    # m "Я с удовольствием приду к тебе в гости еще раз..."
    # julia "Я буду очень рада, Миссис Бакфетт!"
    m "Honey, I really like your apartment."
    m "It is small but comfortable."
    m "I will be happy to come to visit you again ..."
    julia "That would make me happy, Mrs. Buckfett!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:320
translate english ep211_dialogues4_julia_7_0077a8a0:

    # mt "Нет, я не хочу этого делать!" 
    # mt "Не хочу и не буду!"
    # mt "Мне надоели эти глупости!"
    # mt "!!!"
    mt "No, I don't want to do this!" 
    mt "I don't and I won't!"
    mt "I'm tired of this nonsense!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:325
translate english ep211_dialogues4_julia_7_eeec6f75:

    # m "Мне так не хочется уходить от тебя..."
    # m "Но у меня сегодня еще дела."
    # m "Скоро увидимя, милая."
    # julia "До свидания, Миссис Бакфетт."
    # julia "Буду очень скучать и ждать встречи с Вами."
    m "I so don’t want to leave you ..."
    m "But I still have things to do today."
    m "See you soon, honey."
    julia "Goodbye, Mrs. Buckfett."
    julia "I look forward to seeing you."

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:334
translate english ep211_dialogues4_julia_8_dbd1814a:

    # mt "Снова ничего не получилось!!!"
    # mt "!!!"
    # mt "Сколько можно?!"
    # mt "?!?!?!"
    mt "It didn't work again!!!"
    mt "!!!"
    mt "What the hell?!"
    mt "?!?!?!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:342
translate english ep211_dialogues4_julia_9_023bd8b5:

    # mt "Все!"
    # mt "С меня хватит!"
    # mt "Пошло оно все к черту!"
    # mt "!!!"
    mt "That's' all!"
    mt "That's enough!"
    mt "Fuck it!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues4_julia.rpy:350
translate english ep211_dialogues4_julia_10_54d68fff:

    # mt "Тут небезопасно вечером..."
    # mt "Наверняка, здесь полно извращенцев!"
    # mt "Нужно скорее уходить отсюда!"
    # mt "!!!"
    mt "It's not safe here in the evening ..."
    mt "Surely, it is full of perverts!"
    mt "We need to leave here soon!"
    mt "!!!"

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:40
    old "После работы пойти на свидание с Юлией в кафе."
    new "After work, go on a date with Julia to a cafe."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:112
    old "Попросить Юлию рассказать о себе."
    new "Ask Julia to talk about herself."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:217
    old "Попытаться задрать платье Юлии."
    new "Try to pull up Julia's dress."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:242
    old "Я просто потрогаю..."
    new "I'm just touching ..."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:262
    old "Поискать трусики в ванной комнате."
    new "Look for panties in the bathroom."

    # game/Quests/EP2_11/ep211_dialogues4_julia.rpy:262
    old "Уйти отсюда! (завершение сюжета с Юлией)"
    new "Get out of here! (completion of the plot with Julia)"

