# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:17
translate english ep211_dialogues2_public_event_1_2b67fa28:

    # m "Биф..."
    # m "Я хотела узнать у тебя..."
    # m "Есть-ли еще работа?"
    # m "Мне нужны деньги..."
    # biff "Папочка доволен тем, как цыпочка провела презентацию."
    # biff "У тебя неплохо получается притворятся Моникой Бакфетт."
    # biff "Совсем скоро тебе придется сделать это еще раз..."
    # m "Я больше не собираюсь проводить никакие глупые презентации!"
    # biff "Во-первых, кукла, здесь я решаю, чем ты будешь заниматься!"
    # biff "Я здесь Босс!"
    # mt "Ненавижу эту сволочь!!!"
    # biff "Во-вторых, если не будешь меня слушаться..."
    # biff "Будешь ходить в той юбке с презентации и собирать отчеты у сотрудников!"
    # biff "Я и так собираюсь скоро заставить тебя делать это."
    # mt "!!!"
    # mt "Ни за что!"
    # biff "Но ты склоняешь меня к тому, чтобы сделать это прямо сейчас!"
    # biff "Понятно тебе, кукла?!"
    # m "..." 
    # biff "А теперь к делу..."
    # biff "Да, работа есть. Завтра ты поедешь со мной..."
    # m "???"
    # m "Куда?"
    # biff "У одного из наших будущих инвесторов завтра торжественный фуршет..."
    # biff "В честь дня рождения его компании."
    # biff "Мы приглашены на это торжественное мероприятие."
    # biff "На вечере будет много влиятельных людей из индустрии моды."
    # biff "А также будет присутствовать пресса."
    # m "..."
    # biff "Все, что от тебя требуется..."
    # biff "Пообщаться с репортерами от лица Моники Бакфетт."
    # biff "Тебе же не в первый раз придется притворяться ею."
    # biff "Так что думаю, ты справишься..."
    # biff "И не наговоришь никаких глупостей."
    # biff "Иначе я тебя вышвырну с работы обратно на улицу."
    # biff "Будешь обслуживать прохожих за 20 баксов."
    # biff "Ты же понимаешь, что мне ничего не стоит сделать это?"
    # biff "Ты мне итак слишком дорого обходишься, кукла двадцатидолларовая..."
    # m "!!!" 
    # biff "Чего ты так смотришь? Не согласна со мной?"
    # biff "Ты, смотрю, уже забыла, что я тебя с улицы сюда взял?"
    # biff "Сколько ты там зарабатывала за день, отсасывая у местных бомжей?"
    # biff "50 баксов? Или 100?"
    # biff "Пять бомжей в день и сотка баксов в кармане?"
    # biff "Аха-ха-ха!!!"
    # m "!!!"
    # biff "Я тебе плачу 5000 баксов за одну фотосессию!!!"
    # biff "Это немыслимые деньги для такой как ты!"
    # biff "А ты, шлюха неблагодарная, при этом еще пытаешься со мной спорить!"
    # biff "И не выполняешь свою работу!"
    m "Biff..."
    m "I wanted to know..."
    m "Is there any more work?"
    m "I need money!"
    biff "Daddy is happy with the way the chick gave her presentation."
    biff "You're good at pretending to be Monica Buckfett."
    biff "You'll have to do it again soon..."
    m "I'm not going to give any more stupid presentations!"
    biff "First of all, doll, I decide what you're going to do here!"
    biff "I'm the boss!"
    mt "I hate this bastard !!!"
    biff "Secondly, if you don’t obey me ..."
    biff "You'll have wear that skirt while collecting reports from staff!"
    biff "I'm going to make you do it soon enough."
    mt "!!!"
    mt "No way!"
    biff "But you're forcing me to do it right now!"
    biff "Is that clear, doll?!"
    m "..." 
    biff "Now, to the point..."
    biff "Yeah, there's work. Tomorrow, you'll come with me..."
    m "???"
    m "Where?"
    biff "One of our future investors will have a formal reception tomorrow ..."
    biff "In honor of his company's birthday."
    biff "We are invited to this gala event."
    biff "There will be many influential people from the fashion industry that evening."
    biff "And also the press will be present."
    m "..."
    biff "All that is required of you ..."
    biff "Is talking to reporters on behalf of Monica Bucket."
    biff "It's not the first time you have to pretend to be her."
    biff "So I think you can do it ..."
    biff "And do not say any nonsense."
    biff "Otherwise, I'll throw you out back into the street."
    biff "You will serve passers-by for 20 bucks."
    biff "Do you understand how easy it is for me?"
    biff "You are too expensive for me, a twenty-dollar doll ..."
    m "!!!" 
    biff "Why are you looking at me like that? Do you have something to say?"
    biff "I see you've forgotten I took you from the street."
    biff "How much did you earn there per day, sucking off local homeless people?"
    biff "50 bucks? Or 100?"
    biff "Five homeless people a day and a hundred bucks in your pocket?"
    biff "Ah-ha-ha!!!"
    m "!!!"
    biff "I pay you 5000 bucks for one photo shoot !!!"
    biff "This is unthinkable money for someone like you!"
    biff "And you, you ungrateful whore, are still trying to argue with me!"
    biff "And don't do your job!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:73
translate english ep211_dialogues2_public_event_1_0138fb27:

    # m "Неправда, Биф!"
    # m "Я хорошо выполняю свою работу!"
    # biff "Да ты что?!"
    # biff "Почему же тогда еще ни один из инвесторов не дал свой ответ?!"
    # m "!!!"
    # biff "Ты думала, я пошутил тогда?!"
    # biff "Я жду результатов! Ты вообще что-нибудь для этого сделала?"
    # m "..."
    # biff "Это твоя забота, цыпочка. Иначе..."
    # biff "..."
    # biff "Ты сама должна понимать, что это в твоих интересах."
    # m "..."
    m "That's not true, Biff!"
    m "I do my job well!"
    biff "Really now?!"
    biff "Why, then, has not a single investor answered?!"
    m "!!!"
    biff "Did you think I was joking then?!"
    biff "I'm expecting results! Did you do anything for that?"
    m "..."
    biff "This is your concern, girl. Otherwise ..."
    biff "..."
    biff "You must understand that this is in your best interests."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:89
translate english ep211_dialogues2_public_event_1_caaaed87:

    # m "Биф, но..."
    # m "Как я это сделаю?"
    # biff "Мне все равно, как цыпочка будет с ними договариваться."
    # biff "Это проблемы цыпочки. Папочке нужен результат!"
    # mt "Вот мразь!"
    # mt "!!!"
    # biff "И нечего так смотреть на меня!"
    # biff "Ты здесь никто! Какая-то грязная шлюха с улицы..."
    # biff "Еще пытаешься свои условия мне диктовать!"
    # m "..."
    # biff "В общем, кукла, ты испортила мне настроение."
    # biff "Теперь ты должна это исправить. Что ты можешь мне предложить?"
    # m "После всего, что ты мне тут наговорил!.."
    # m "Я еще должна поднимать тебе настроение?!"
    # biff "Да. Хорошие цыпочки именно так и поступают..."
    # m "!!!"
    # biff "Скажи мне, ты хорошая цыпочка?"
    # m "..."
    m "But Biff ..."
    m "How will I do that?"
    biff "I don’t care how the chick negotiates with them."
    biff "These are your problems.  Daddy needs results!"
    mt "What a jerk!"
    mt "!!!"
    biff "And don't look at me like that!"
    biff "You are a nobody here! Some dirty whore from the street ..."
    biff "Still trying to dictate your conditions to me!"
    m "..."
    biff "Anyway, doll, you've ruined my mood."
    biff "Now you have to fix it. What can you offer me?"
    m "After all that you have told me! .."
    m "Do I have to make you feel better?!"
    biff "Yes. Good girls do exactly that..."
    m "!!!"
    biff "Tell me, are you a good girl?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:114
translate english ep211_dialogues2_public_event_1_e8e86b30:

    # m "Я не тебе не кукла и не шлюха!"
    # m "И не цыпочка!!!"
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не сделаешь то, что Я тебе говорю!"
    # mt "Да пошел ты!"
    # mt "Я найду другой способ зарабатывать деньги!"
    m "I'm not your doll and I'm not whore!"
    m "And not a chick!!!"
    biff "You won’t get any other job ..."
    biff "Until you do what I tell you!"
    mt "Fuck you!"
    mt "I will find another way to make money!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:123
translate english ep211_dialogues2_public_event_1_15601f85:

    # mt "Безмоглый кретин!"
    # mt "!!!"
    # m "Я хорошая цыпочка."
    # biff "Чем хорошая цыпочка будет поднимать настроение папочке?"
    # mt "Ненавижу его!"
    # biff "Я жду тебя завтра, цыпочка."
    # m "..."
    mt "Stupid idiot!"
    mt "!!!"
    m "I am a good chick."
    biff "What will my good chick do to cheer up daddy?"
    mt "I hate him!"
    biff "I'll be waiting for you tomorrow, girl."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:136
translate english ep211_dialogues2_public_event_2_5cea6789:

    # m "Биф..."
    # m "А что насчет работы?"
    # biff "Я же сказал, что завтра будешь работать."
    # m "..."
    # biff "Приходи завтра вечером, кукла."
    # mt "Я тебе не кукла, придурок!"
    m "Biff..."
    m "What about work?"
    biff "I said that you will work tomorrow."
    m "..."
    biff "Come tomorrow night, doll."
    mt "I’m not your doll, moron!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:147
translate english ep211_dialogues2_public_event_3_531eeb4a:

    # m "Биф..."
    # biff "А, цыпочка пришла!"
    # biff "Иди переодевайся."
    # biff "И поторопись! Нам уже пора выезжать."
    m "Biff..."
    biff "Ah, the chick came!"
    biff "Go change."
    biff "And hurry up! It’s time for us to leave."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:157
translate english ep211_dialogues2_public_event_4_0b3944e8:

    # mt "Мне нужно пойти в фотостудию."
    # mt "Биф сказал, что мне надо поторопиться."
    mt "I need to go to the photo studio."
    mt "Biff said I need to hurry."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:163
translate english ep211_dialogues2_public_event_5_9f059684:

    # mt "Этот фотограф-извращенец наверняка знает, какое платье мне подготовили."
    # alex_photograph "Миссис Бакфетт! Великолепно выглядите!"
    # m "Как и всегда."
    # m "Алекс, мне нужно платье для мероприятия..."
    # alex_photograph "Да, Миссис Бакфетт. Оно в гримерной комнате."
    mt "This pervert photographer probably knows what dress I’ll be wearing."
    alex_photograph "Mrs. Buckfett! You look great!"
    m "As always."
    m "Alex, I need a dress for the event..."
    alex_photograph "Yes, Mrs. Buckfett. It's in the dressing room."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:172
translate english ep211_dialogues2_public_event_5_b7852eba:

    # alex_photograph "О! Миссис Бакфетт!"
    # alex_photograph "!!!"
    # m "Алекс, как я выгляжу?"
    # alex_photograph "Вы восхитительны!!!"
    # alex_photograph "У меня просто нет слов!"
    # alex_photograph "!!!"
    # m "Тебе это платье не кажется слишком откровенным?"
    # m "Особенно в зоне декольте?"
    # alex_photograph "Нет, конечно! Оно идеально подчеркивает всю Вашу красоту."
    # mt "Хм..."
    # mt "Действительно."
    # mt "У меня великолепная фигура. Пусть все смотрят и завидуют."
    # mt "Далеко не каждая женщина сможет надеть такое платье."
    # mt "А я могу. Ведь я самая красивая женщина в этом городе."
    # mt "Вернее, в стране!"
    # mt "Наконец-то, у меня новое платье."
    # mt "Оно, конечно, не такое дорогое, как мне хотелось бы..."
    # mt "И достаточно откровенное."
    # mt "Но оно мне нравится..."
    # mt "Оставлю его себе."
    alex_photograph "Oh! Mrs. Buckfett!"
    alex_photograph "!!!"
    m "Alex, how do I look?"
    alex_photograph "You are gorgeous!!!"
    alex_photograph "I have no words!"
    alex_photograph "!!!"
    m "Don't you think this dress is too revealing?"
    m "Especially around my bust?"
    alex_photograph "No, of course not! It perfectly emphasizes all your beauty."
    mt "Hmm..."
    mt "Really."
    mt "I have a great figure. Let everyone look and envy."
    mt "Not every woman can wear such a dress."
    mt "I can. I'm the most beautiful woman in this town."
    mt "Or rather, in the whole country!"
    mt "Finally, I have a new dress."
    mt "It's not as expensive as I would like..."
    mt "And quite vulgar."
    mt "But I like it..."
    mt "I'll keep it."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:198
translate english ep211_dialogues2_public_event_6_cf5f4df7:

    # biff "Цыпочка, выглядишь, как настоящая Моника Бакфетт!"
    # biff "Хорошо, что у тебя совсем нет мозгов..."
    # biff "И ты не можешь этим воспользоваться. Аха-ха!"
    # m "..." 
    # biff "Так. Я не понял, а почему ты надела трусики?"
    # biff "Папочка тебе запретил носить трусики!"
    # m "..."
    # m "Биф, это платье слишком откровенное."
    # m "Миссис Бакфетт никогда не пошла бы в таком платье на публичное мероприятие..."
    # biff "Можно подумать, ты знаешь о том, что сделала бы сучка Бакфетт. Аха-ха!"
    # mt "Идиот!!!"
    # mt "!!!"
    # m "Биф, там будет много людей и пресса."
    # m "..."
    # biff "Ну и что?"
    # m "В этом платье видно, если я буду без трусиков..."
    # m "Всем будет видно мою... Мою... Ну ты понял."
    # biff "И что ты предлагаешь?"
    # m "Можно я не буду снимать эти трусики?"
    # biff "Папочка разрешит оставить трусики только хорошей цыпочке."
    # m "..."
    biff "Chick, you look like a real Monica Buckfett!"
    biff "Good thing you don't have any brains at all..."
    biff "And you can't use that fact. Aha-ha!"
    m "..." 
    biff "Hey. Who told you to put on panties?"
    biff "Daddy forbade you from wearing panties!"
    m "..."
    m "Biff, this dress is too revealing."
    m "Mrs. Buckfett would never wear a dress like that for a public event..."
    biff "It's not like you would know what that Buckfett's bitch would wear. Ahaha!"
    mt "Idiot!!!"
    mt "!!!"
    m "Biff, there's gonna be a lot of people and the press."
    m "..."
    biff "So what?"
    m "They will see I'm not wearing panties in this dress..."
    m "Everyone will see my... my... well, you know."
    biff "And what do you suggest?"
    m "May I keep my panties on?"
    biff "Daddy will only let a good chick keep her panties on."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:223
translate english ep211_dialogues2_public_event_6_45e8f8c6:

    # mt "Ненавижу этого придурка!"
    # mt "!!!"
    # m "Я хорошая цыпочка."
    # biff "Ну ладно. Можешь не снимать трусики..."
    # biff "Но если ты будешь плохой цыпочкой..."
    # biff "Например, не будешь слушаться папочку."
    # biff "Или недостаточно будешь стараться быть Моникой Бакфетт."
    # biff "Или... Или поставишь пятно на этом безумно дорогом платье."
    # biff "Тогда я сразу же заставлю тебя снять эти трусики!"
    # mt "!!!"
    # biff "Будешь хорошей цыпочкой - папочка будет доволен."
    # m "..."
    mt "I hate that jerk!"
    mt "!!!"
    m "I am a good chick."
    biff "All right. You don't have to take your panties off..."
    biff "But if you're a bad chick..."
    biff "For example, you will not obey daddy."
    biff "Or you don’t try hard enough to be Monica Buckfett."
    biff "Or ... Or put a stain on this insanely expensive dress."
    biff "Then I will immediately make you take them off!"
    mt "!!!"
    biff "If your a good chick - daddy will be pleased."
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:242
translate english ep211_dialogues2_public_event_7_1706963f:

    # mt "В этот вечер я буду наслаждаться своей настоящей жизнью."
    # mt "Наконец-то вкусно поем приличной еды и выпью дорогого вина..."
    # mt "А вокруг меня будут крутиться журналисты и мои поклонники..."
    # mt "Черт! Я заслужила возможность побыть собой настоящей!"
    # biff "Цыпочка, ты помнишь о том, что ты должна быть хорошей..."
    # biff "И не расстраивать папочку?"
    # biff "Сейчас цыпочка пойдет и пообщается с гостями."
    # biff "Тебе нужно открывать свой рот и говорить только правильные вещи."
    # biff "Для этого цыпочке не обязательно уметь разговаривать."
    # m "???"
    # biff "Что ты на меня так смотришь?"
    # biff "Я знаю, что у тебя нет мозгов."
    # biff "Поэтому когда не знаешь, что сказать - молчи."
    # biff "Когда ты молчишь, ты больше похожа на Монику Бакфетт."
    # m "..."
    # biff "Все, иди. Папочка будет за тобой присматривать."
    # biff "Представь, что ты не двадцатидолларовая шлюха..."
    # biff "Какой и являешься на самом деле. Ты - Моника Бакфетт."
    # mt "Пусть этот болван говорит, что хочет."
    # mt "Я буду наслаждаться и ничего не сможет испортить мне настроение."
    mt "This evening I will enjoy myself."
    mt "Finally, I can eat good food and drink expensive wine..."
    mt "And I'll be surrounded by journalists and my fans..."
    mt "Shit! I deserve to be myself!"
    biff "Hey chick, do you remember that you have to be good ..."
    biff "And not upset daddy?"
    biff "Now go and chat with the guests."
    biff "When you speak say only the right things."
    biff "You don’t need to be a smooth talker for that."
    m "???"
    biff "Why are you looking at me like that?"
    biff "I know you have no brains."
    biff "Therefore, when you don’t know what to say, be silent."
    biff "When you don't talk, you look more like Monica Buckfett."
    m "..."
    biff "All right, go. Daddy's gonna be watching you."
    biff "Imagine you're not a 20 dollar whore ..."
    biff "Which you really are. Tonight you're Monica Buckfett."
    mt "Let this fool say what he wants."
    mt "I will enjoy this and nothing can ruin my mood."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:275
translate english ep211_dialogues2_public_event_8_110646cd:

    # mt "Миссис Уайт."
    # mt "Ее журнал всегда был прямым конкурентом моего журнала."
    # mt "Терпеть ее не могу!"
    # mt "Та еще старая грымза!"
    mt "Mrs. White."
    mt "Her magazine has always been a direct competitor to my magazine."
    mt "I can not stand her!"
    mt "That old hag!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:283
translate english ep211_dialogues2_public_event_9_d1149033:

    # mt "Миссис Уайт?"
    # mt "Кого я меньше всего ожидала увидеть на этом приеме, так это ее..."
    # guest1 "Миссис Бакфетт... Добрый вечер."
    # m "Миссис Уайт, рада встрече." 
    # guest1 "Не ожидала увидеть Вас здесь..."
    # guest1 "Вас совсем не видно в последнее время, Миссис Бакфетт."
    # guest1 "Вы пропустили несколько модных показов..."
    # guest1 "Я уже не говорю о неделе моды, где Вас тоже не было."
    # mt "Черт!"
    mt "Mrs. White?"
    mt "I didn’t expected to see her at this reception..."
    guest1 "Mrs. Buckfett ... Good evening."
    m "Mrs. White, nice to meet you." 
    guest1 "I did not expect to see you here ..."
    guest1 "You haven’t around at all lately, Mrs. Buckfett."
    guest1 "You missed some fashion shows ..."
    guest1 "I'm not even talking about fashion week, though you weren’t there either."
    mt "Heck!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:296
translate english ep211_dialogues2_public_event_9_886ed0ce:

    # m "..."
    # m "У меня были другие, более важные дела, Миссис Уайт."
    # guest1 "Важнее, чем показы знаменитых модельеров в мировой столице моды?"
    # guest1 "Что может быть важнее в нашем бизнесе, Миссис Бакфетт?"
    # guest1 "Хотя..."
    # guest1 "Я совсем забыла, что Ваш журнал теперь не совсем про моду..."
    # guest1 "Ваш журнал, Миссис Бакфетт, и раньше не дотягивал до уровня моего журнала."
    # mt "!!!"
    m "..."
    m "I had other, more important things, Mrs. White."
    guest1 "More important than the shows of famous fashion designers in the world fashion capital?"
    guest1 "What could be more important in our business, Mrs. Buckfett?"
    guest1 "Wait..."
    guest1 "I completely forgot that your magazine is now not entirely about fashion ..."
    guest1 "Your magazine, Mrs. Buckfett, was never quite at the level of my magazine."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:307
translate english ep211_dialogues2_public_event_9_d166f866:

    # mt "Сучка!"
    # m "Я так не считаю, Миссис Уайт."
    # guest1 "Да, Миссис Бакфетт. Ваш журнал был намного хуже!"
    # guest1 "А сейчас Вы не знаете уже, что придумать..."
    # guest1 "Идете на какие-то откровенные шаги, называя это сменой курса журнала..."
    # guest1 "Выглядит это все очень сомнительно."
    # guest1 "Не удивлюсь, если скоро Вы лично будете раздеваться перед камерой."
    # mt "Почему эта грымза говорит об этом?"
    # mt "Она что-то знает о моих откровенных фотосессиях?!"
    # mt "!!!"
    # guest1 "Думаете, это сделает Ваш журнал успешным, Миссис Бакфетт?"
    mt "Bitch!!!"
    m "I don't think so, Mrs. White."
    guest1 "Yes, Mrs. Buckfett. that’s because your magazine was much worse!"
    guest1 "And now you don’t know what to come up with ..."
    guest1 "You take drastic steps, calling it a change in the course of the magazine ..."
    guest1 "It all looks very doubtful."
    guest1 "I won’t be surprised if soon you’ll be undressing in front of the camera yourself."
    mt "Why is this hag talking about this?"
    mt "Does she know something about my candid photo shoots ?!"
    mt "!!!"
    guest1 "Do you think this will make your magazine a success, Mrs. Buckfett?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:321
translate english ep211_dialogues2_public_event_9_5301aed9:

    # m "..."
    # m "Мой журнал был всегда успешнее Вашего бульварного чтива."
    # m "И сейчас, благодаря смене курса, он стал еще популярнее."
    # m "Чего не скажешь о Вас и Вашем журнале."
    # m "Кстати, что касается фотосессий..."
    # m "Я могу позволить себе участвовать в фотосессиях для моего журнала."
    # m "Моей красоте завидуют многие топ-модели страны."
    # m "А Вам, Миссис Уайт, остается только завидовать этому факту."
    # guest1 "Ни в коем случае, Миссис Бакфетт."
    # guest1 "Я никогда не стала бы сниматься в сомнительных фотосессиях."
    # guest1 "Надеюсь, и Вы до этого не опуститесь." 
    # mt "!!!"
    # guest1 "Вынуждена прервать нашу милую беседу, Миссис Бакфетт."
    # guest1 "Приятно было с Вами встретиться."
    # mt "Ненавижу эту грымзу!"
    # mt "Злобная стерва!"
    # mt "!!!"
    # biff "Цыпочка должна притворяться лучше."
    # biff "Будешь и дальше себя так вести и спорить с уважаемыми людьми..."
    # biff "Не зная всех ньюансов предмета разговора..."
    # biff "Все поймут, что ты не Моника Бакфетт, а ее дешевая подделка."
    # mt "!!!"
    m "..."
    m "My magazine has always been more successful than your pulp fiction."
    m "And now, thanks to the change of course, it has become even more popular."
    m "Which cannot be said about you and your magazine."
    m "By the way, as for photo shoots ..."
    m "I can afford to participate in photo shoots for my magazine."
    m "Many of the country's top models envy my beauty."
    m "And you, Mrs. White, can only envy this fact."
    guest1 "No way, Mrs. Buckfett."
    guest1 "I'd never do a questionable photo shoot."
    guest1 "I hope you won't stoop that low either." 
    mt "!!!"
    guest1 "I’m forced to end our sweet conversation, Mrs. Buckfett."
    guest1 "It was nice meeting you."
    mt "I hate this hag!"
    mt "Evil bitch!"
    mt "!!!"
    biff "You should pretend better."
    biff "If you continue to behave this way and argue with respected people ..."
    biff "Not knowing all the info of the subject of the conversation ..."
    biff "Everyone will understand that you are not Monica Buckfett, but her cheap fake."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:352
translate english ep211_dialogues2_public_event_10_c4f90472:

    # mt "Мне не о чем больше разговаривать с этой грымзой!"
    # mt "Терпеть ее не могу!"
    mt "I have nothing more to talk about with this hag!"
    mt "I can not stand her!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:360
translate english ep211_dialogues2_public_event_11_72f9ddbd:

    # mt "Я знаю ее."
    # mt "Грейс..."
    # mt "Была моделью в нескольких журналах о моде."
    # mt "Мечтает стать топ-моделью."
    # mt "Красивая, но очень глупая..."
    mt "I know her."
    mt "Grace..."
    mt "She was a model in several fashion magazines."
    mt "She dreams of becoming a top model."
    mt "Beautiful, but very stupid ..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:370
translate english ep211_dialogues2_public_event_12_acfd0cb3:

    # guest2 "Миссис Бакфетт, здравствуйте."
    # guest2 "Вы превосходно выглядите!"
    # m "Спасибо, Грейс."
    # guest2 "Ваше платье просто великолепно!"
    # m "Чего не скажешь о твоем вульгарном наряде..."
    # guest2 "Миссис Бакфетт, я хотела поблагодарить Вас за приглашение на пробы."
    guest2 "Mrs. Buckfett, hello."
    guest2 "You look great!"
    m "Thanks, Grace."
    guest2 "Your dress is just gorgeous!"
    m "The same can't be said about your vulgar outfit ..."
    guest2 "Mrs. Buckfett, I wanted to thank you for inviting me to the audition."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:379
translate english ep211_dialogues2_public_event_12_60ae35ba:

    # mt "???"
    # m "Грейс, что ты имеешь ввиду? Какие пробы?"
    # guest2 "Мне на днях позвонил Ваш менеджер Биф."
    # guest2 "Он сказал, что Вам требуется топ-модель."
    # guest2 "И пригласил меня на пробы."
    # mt "Мой менеджер Биф? Как интересно..."
    # guest2 "Я хотела спросить, Мелани у Вас больше не работает?"
    mt "???"
    m "Grace, what do you mean? What audition?"
    guest2 "Your manager Biff called me the other day."
    guest2 "He said that you need a top model."
    guest2 "And he invited me to an audition."
    mt "My manager Biff? How interesting..."
    guest2 "I wanted to ask, does Melanie no longer work for you?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:389
translate english ep211_dialogues2_public_event_12_bbff8ebf:

    # m "Мелани сейчас в небольшом отпуске."
    # mt "Мелани..."
    # mt "Ее давно уже не видно на работе."
    # mt "Она должна была раздобыть компромат на Викторию и пропала куда-то."
    # mt "..."
    # mt "Нужно спросить у этого придурка Бифа."
    # mt "Может, он знает, когда вернется Мелани..."
    # guest2 "Меня немного смущает новый курс Вашего журнала."
    # guest2 "Но на пробы в топ-модель Вашего журнала я приду."
    # guest2 "Я сказала Вашему менеджеру, что приму участие в пробах."
    # guest2 "При условии, что не будет никаких откровенных кадров."
    m "Melanie is on a short leave now."
    mt "Melanie..."
    mt "She has not been seen at work for a long time."
    mt "She needed to get some dirt on Victoria, but ended up disappearing."
    mt "..."
    mt "You need to ask this moron Biff."
    mt "Maybe he knows when Melanie will be back ..."
    guest2 "I'm a little confused by the new course of your magazine."
    guest2 "But I’ll come to the top model audition of your magazine."
    guest2 "I told your manager that I would take part in the audition."
    guest2 "Provided that there will be no lewd photos."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:403
translate english ep211_dialogues2_public_event_12_15069d19:

    # m "И что тебе на это пообещал мой менеджер Биф?"
    # guest2 "Он заверил меня, что мне не нужно беспокоится об этом."
    # guest2 "И что он все сделает, как я хочу."
    # mt "Ха-ха!!!"
    # m "Удачи тебе на пробах, Грейс."
    # guest2 "Спасибо, Миссис Бакфетт."
    # mt "Интересно, как Биф собирается заставить ее раздеваться перед камерой?"
    # biff "Цыпочка не должна забывать, что она Моника Бакфетт."
    # biff "А не шлюха, которая совсем недавно отсасывала у бомжей..."
    # biff "Дешевая шлюха не в курсе, что происходит в журнале."
    # biff "А Моника Бакфетт в курсе всех дел."
    # biff "И не задает глупых вопросов будущим моделям журнала."
    # mt "!!!"
    m "And what did my manager Biff promise you?"
    guest2 "He assured me that I didn’t need to worry about it."
    guest2 "And that he will do everything as I want."
    mt "Haha!!!"
    m "Good luck with your audition, Grace."
    guest2 "Thank you, Mrs. Buckfett."
    mt "I wonder how Biff is going to make her undress in front of the camera?"
    biff "The chick must not forget that she is Monica Buckfett."
    biff "And not the whore who recently sucked off hobos..."
    biff "The cheap whore doesn't know what is going in the magazine."
    biff "And Monica Buckfett is up to date."
    biff "And she doesn’t ask stupid questions to future models of the magazine."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:425
translate english ep211_dialogues2_public_event_13_78d6e5a8:

    # mt "Мне не о чем больше разговаривать с ней..."
    # mt "Поверила обещаниям Бифа, что станет топ-моделью журнала."
    # mt "Глупая девочка!"
    mt "I have nothing more to talk about with her ..."
    mt "She believed Biff’s promises that she would become the top model of the magazine."
    mt "Stupid girl!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:434
translate english ep211_dialogues2_public_event_14_7f74311d:

    # mt "Топ-модель. Весьма востребован в мире моды."
    # mt "..."
    # mt "Сразу видно, что он самовлюбленный никчемный придурок."
    mt "Top model. Very popular in the fashion world."
    mt "..."
    mt "It is immediately clear that he is a narcissistic, worthless moron."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:442
translate english ep211_dialogues2_public_event_15_0693abea:

    # guest3 "Миссис Бакфетт, Вы прекрасно выглядите."
    # m "Спасибо."
    # m "Я тебя где-то видела... Мы знакомы?"
    # guest3 "Меня зовут Исаак. Я модель."
    # guest3 "Работаю на модных показах."
    # guest3 "Иногда участвую в фотосессиях."
    # m "..."
    # mt "Надеюсь, что Бифу не придет в его пустую голову идея..."
    # mt "Пригласить какого-нибудь придурка на съемку."
    # guest3 "Я Ваш давний поклонник, Миссис Бакфетт."
    # guest3 "И хочу сказать, что в последнее время Ваш журнал стал намного лучше."
    # guest3 "Я буду рад принять участие в фотосессии ню с Вами..."
    guest3 "Mrs. Buckfett, you look beautiful."
    m "Thank you."
    m "I saw you somewhere ... Do we know each other?"
    guest3 "My name is Isaac. I'm a model."
    guest3 "I work at fashion shows."
    guest3 "Sometimes I participate in photo shoots."
    m "..."
    mt "I hope that Biff doesn’t come up with any ideas with that empty head of his..."
    mt "And invites some moron to a shoot."
    guest3 "I am a longtime fan, Mrs. Buckfett."
    guest3 "And I want to say that recently your magazine has become much better."
    guest3 "I will be happy to participate in a nude photo shoot with you ..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:457
translate english ep211_dialogues2_public_event_15_97774775:

    # m "Спасибо, Исаак..."
    # mt "Стоп!"
    # mt "Что?!"
    # m "Фотосессия ню?!"
    # m "?!?!?!"
    # guest3 "Ваш менеджер Биф сказал, что в скором будущем планируется эротическая фотосессия, в паре."
    # guest3 "И пригласил меня поучаствовать в ней."
    # guest3 "Конечно же, я не отказался." 
    # mt "!!!"
    # mt "Я этому Бифу яйца оторву!"
    # mt "Что он задумал?!"
    m "Thank you, Isaac ..."
    mt "Stop!"
    mt "What?!"
    m "A nude photo shoot?!"
    m "?!?!?!"
    guest3 "Your manager Biff said that in the near future an erotic photo shoot is planned, and that you'll need a pair."
    guest3 "So he invited me to participate in it."
    guest3 "Of course, I didn’t refuse." 
    mt "!!!"
    mt "I’ll tear Biff’s balls off!"
    mt "What is he up to ?!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:471
translate english ep211_dialogues2_public_event_15_05fdf059:

    # m "..."
    # m "Возможно, Исаак, ты неверно понял моего менеджера."
    # m "Мы... Мы планируем серию фотосессий с участием мужчин моделей."
    # m "Но о моем присутствии в кадре и речи быть не может."
    # m "Мой менеджер имел ввиду не меня, а другую модель..."
    # guest3 "Нет, Миссис Бакфетт. Он говорил именно о Вас."
    # guest3 "В любом случае, я с удовольствием поработаю в Вашем журнале."
    # guest3 "Приятного вечера, Миссис Бакфетт."
    # mt "Биф сволочь!!!"
    # biff "Кукла!"
    # biff "Ты на грани провала!"
    # biff "Еще немного и все поймут, что ты дешевая подделка Моники Бакфетт!"
    # m "Биф, что за эротические фотосессии с участием этого парня?!"
    # m "?!?!?!"
    # biff "Это тебя не касается, кукла безмозглая!"
    # biff "Такое решение принял папочка!"
    # biff "Как папочка скажет, так и будешь делать!"
    # biff "Это твоя работа. Ты за это получаешь большие деньги!"
    # m "!!!"
    # biff "Быстро взяла себя в руки!"
    # biff "Еще раз услышу, что задаешь глупые вопросы гостям..."
    # biff "Немедленно вылетишь с этой модной вечеринки прямо на улицу, дальше сосать члены за $ 20!"
    # biff "Поняла!?"
    # mt "НЕНАВИЖУ!"
    # mt "!!!"
    m "..."
    m "Perhaps, you misunderstood my manager, Isaac."
    m "We ... We are planning a series of photo shoots featuring male models."
    m "But I won't be in the picture."
    m "My manager didn’t mean me, but a different model ..."
    guest3 "No, Mrs. Buckfett. He was talking specifically about you."
    guest3 "Anyway, I'd love to work in your magazine."
    guest3 "Have a nice evening, Mrs. Buckfett."
    mt "That bastard, Biff !!!"
    biff "Doll!"
    biff "You're on the verge of failure!"
    biff "A little more and everyone will understand that you are a cheap fake Monica Buckfett!"
    m "Biff, what do you mean, erotic photo sessions with this guy?!"
    m "?!?!?!"
    biff "It doesn't concern you, brainless doll!"
    biff "This decision was made by daddy!"
    biff "And you will do what daddy says!"
    biff "It's your job. You get a lot of money for that!"
    m "!!!"
    biff "Quickly, pull yourself together!"
    biff "If I hear you ask another stupid question..."
    biff "You'll fly from this fashionable party right out to the street, then suck the members for $ 20!"
    biff "Got it !?"
    mt "I HATE HIM!"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:505
translate english ep211_dialogues2_public_event_16_a9dce1bf:

    # mt "Я не хочу больше с ним разговаривать!"
    # mt "Я ни за что не соглашусь на эротическую фотосессию!"
    # mt "Ни с ним, ни с кем-либо еще!!!"
    mt "I don’t want to talk to him anymore!"
    mt "I would never agree to an erotic photo shoot!"
    mt "Not with him, nor with anyone else !!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:514
translate english ep211_dialogues2_public_event_17_98edc287:

    # mt "Райен. Один из самых востребованных и знаменитых фотографов города, вроде Алекса."
    # mt "Как по мне, ничего особенного я в его работах не видела."
    mt "Ryan. One of the most sought after and famous photographers of the city, like Alex."
    mt "As for me, there's nothing really special about his work."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:521
translate english ep211_dialogues2_public_event_18_2b1c78c8:

    # guest4 "Миссис Бакфетт, добрый вечер."
    # m "Здравствуй, Райен."
    # guest4 "Мы с Вами давно не встречались..."
    # guest4 "В последнее время, Вы почти не посещаете публичные мероприятия."
    # guest4 "Даже пропустили несколько модных показов."
    # mt "И? Я что, должна оправдываться?!"
    guest4 "Mrs. Buckfett, good evening."
    m "Hello, Ryan."
    guest4 "I have been waiting to meet you for a long time ..."
    guest4 "Recently, you almost do not attend public events."
    guest4 "Even missed a few fashion shows."
    mt "And? Do I have to make excuses?!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:530
translate english ep211_dialogues2_public_event_18_a2905a2b:

    # m "У меня были другие, более важные дела, Райен."
    # guest4 "Понимаю, Миссис Бакфетт."
    # guest4 "Кстати о Ваших, так сказать, важных делах..."
    # guest4 "..."
    # mt "???"
    # guest4 "Я видел Ваши фотографии с закрытой фотосессии..."
    # mt "ЧТОООО?!"
    # mt "?!?!?!"
    # guest4 "Работа хорошая, но чувствуется Ваша скованность..."
    # guest4 "Я знаю, как сделать подобные кадры более чувственными."
    # mt "..."
    # mt "Как?"
    # mt "Откуда?"
    # mt "Кто?"
    # mt "?!?!?!"
    # mt "Алекс?!"
    # mt "!!!"
    # mt "Алекс сволочь!!!"
    m "I had other, more important things, Ryan."
    guest4 "I understand, Mrs. Buckfett."
    guest4 "Speaking of your important matters, so to speak ..."
    guest4 "..."
    mt "???"
    guest4 "I saw your photos from a closed photo shoot ..."
    mt "WHAAT?!"
    mt "?!?!?!"
    guest4 "The work is good, but you're still a bit stiff..."
    guest4 "I know how to make such pictures more sensual."
    mt "..."
    mt "How?"
    mt "Where?"
    mt "Who!"
    mt "?!?!?!"
    mt "Alex ?!"
    mt "!!!"
    mt "That bastard !!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:551
translate english ep211_dialogues2_public_event_18_17add987:

    # m "Вы обсуждали эту работу с Вашим коллегой Алексом?"
    # guest4 "Нет, Миссис Бакфетт."
    # guest4 "Алекс считает, что он лучший в своем деле."
    # guest4 "И не любит, когда ему дают профессиональные советы относительно его работ."
    # mt "..."
    # mt "Кто тогда?"
    # mt "Биф?!"
    # mt "!!!"
    # guest4 "Миссис Бакфетт, с большим сожалением вынужден оставить Вас."
    # guest4 "И помните, что всегда можете обратиться ко мне."
    # guest4 "Вы убедитесь, что мои снимки шедевральны."
    # guest4 "Приятно провести вечер."
    # mt "Я уверена, это сделал Биф!!!"
    # mt "АААААА!!!!"
    # mt "НЕНАВИЖУ!!!!!!"
    # biff "Нужно быть вежливее с такими уважаемыми людьми!"
    # biff "Ничего не понимаешь в том, что они говорят - улыбайся и молчи!"
    # biff "У тебя и правда совсем нет мозгов."
    # biff "Ты даже просто пообщаться с гостями не можешь!"
    # biff "Мне приходится все контролировать!"
    # m "Биф, ты показывал мои фотографии этому фотографу?!"
    # m "?!?!?!"
    # biff "..."
    # biff "Конечно, цыпочка!"
    # biff "И я планирую показать их также нашим инвесторам, как наглядное подтверждение нашего нового курса!"
    # biff "Я планирую это сделать до того, как эти снимки станут достоянием всей публики."
    # biff "Я считаю, что наши инвесторы заслуживают того, чтобы увидеть это первыми!"
    # biff "Цыпочка, ты согласна со мной?"
    # m "!!!"
    # m "Биф... Может быть, та фотосессия останется закрытой?"
    # biff "Нет, цыпочка! Это исключено!"
    # biff "И хватит со мной спорить!"
    # biff "Иди и дальше притворяйся Моникой Бакфетт, пока я не потерял терпение!"
    # mt "!!!"
    # mt "Я не могу допустить, чтобы кто-то увидел те кадры!"
    m "Did you discuss this work with your colleague Alex?"
    guest4 "No, Mrs. Buckfett..."
    guest4 "Alex believes that he is the best in his field."
    guest4 "And he does not like it when he is given professional advice regarding his work."
    mt "..."
    mt "Who then?"
    mt "Biff ?!"
    mt "!!!"
    guest4 "Mrs. Buckfett, regretfully I’m forced to leave you."
    guest4 "But remember that you can always contact me."
    guest4 "You will see that my pictures are masterpieces."
    guest4 "Have a nice evening."
    mt "I'm sure Biff did it !!!"
    mt "AAAAAA !!!!"
    mt "I HATE HIM!!!!!!"
    biff "You have to be more polite with such esteemed people!"
    biff "You don't understand what they're saying - smile and shut up!"
    biff "You really have no brains at all."
    biff "You can’t even simply chat with the guests!"
    biff "I have to control everything!"
    m "Biff, did you show my photos to this photographer ?!"
    m "?!?!?!"
    biff "..."
    biff "Of course, girl!"
    biff "Yes and I plan to show them to our investors as well, as a visual confirmation of our new course!"
    biff "I plan to do this before these pictures become public."
    biff "I believe that our investors deserve to be the first to see this!"
    biff "Don't you agree with me, chick?"
    m "!!!"
    m "Biff ... Maybe that photo shoot will remain closed?"
    biff "No, no! That is out of the question!"
    biff "And stop arguing with me!"
    biff "Go ahead and pretend to be Monica Buckfett, until I lose my patience!"
    mt "!!!"
    mt "I can’t let anyone see those pictures!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:595
translate english ep211_dialogues2_public_event_19_b9e7b732:

    # mt "Мне не о чем больше разговаривать с ним..."
    # mt "Ведет себя, как-будто он какая-то звезда."
    # mt "На деле, обычный фотограф-извращенец."
    mt "I have nothing more to talk to him about ..."
    mt "Acting like he's some kind of star."
    mt "In reality, he's an ordinary pervert photographer."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:604
translate english ep211_dialogues2_public_event_20_b60f0ce2:

    # mt "Мия и Шарлотт. Светские львицы."
    # mt "Не пропускают ни одного мероприятия."
    # mt "Их мужья возглавляют совет директоров одной крупной корпорации."
    # mt "А эти две особы только и успевают, что тратить их деньги."
    mt "Mia and Charlotte. Socialites."
    mt "They never miss a single event."
    mt "Their husbands are heads of the board of directors of a large corporation."
    mt "And these women only manage to spend their money."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:613
translate english ep211_dialogues2_public_event_21_5e6651b7:

    # guest5 "Добрый вечер."
    # guest6 "Здравствуйте."
    # guest5 "Мия, я весьма удивлена тому факту, что Мистер Кэмпбелл..."
    # guest5 "Пригласил на этот праздничный фуршет владелицу журнала..."
    # guest5 "С сомнительной репутацией."
    # guest6 "Я тоже удивлена." 
    # guest6 "Странно, что Вы посещаете подобные мероприятия..."
    # guest6 "Я думала на праздничном фуршете Мистера Кэмпбелла..."
    # guest6 "Будут присутствовать исключительно представители высшего света."
    # mt "Я и есть леди из высшего общества!"
    # mt "Две змеи!"
    # mt "Никчемные дуры!"
    guest5 "Good evening."
    guest6 "Hello."
    guest5 "Miya, I’m quite surprised that Mr. Campbell ..."
    guest5 "I invited the owner of the magazine to this festive buffet ..."
    guest5 "With such dubious reputation."
    guest6 "I am also surprised." 
    guest6 "It’s strange that you attend such events ..."
    guest6 "I was thinking at Mr. Campbell's banquet ..."
    guest6 "Only representatives of high society will be present."
    mt "I am a lady from high society!"
    mt "Two snakes!"
    mt "Worthless bitches!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:630
translate english ep211_dialogues2_public_event_21_ec1cfbd9:

    # m "Мистер Кэмпбелл пригласил сегодня всю элиту мира моды."
    # m "И мне весьма странно видеть на этом вечере вас."
    # m "Вы имеете какое-то отношение к индустрии моды?"
    # m "Уверена, что нет."
    # m "Человек, разбирающийся в моде и искусстве..."
    # m "Никогда не назвал бы мой журнал сомнительным."
    # guest6 "Как странно... Миссис Уайт, владелица другого модного журнала..."
    # guest6 "Она одной из первых употребила слово 'сомнительный' касательно Вашего журнала."
    # guest6 "Получается, она ничего не понимает в моде и искусстве?"
    # mt "!!!"
    m "Mr. Campbell invited the entire fashion world elite today."
    m "And it’s very strange for me to see you tonight."
    m "Do you have anything to do with the fashion industry?"
    m "I’m sure not."
    m "A person versed in fashion and art ..."
    m "would never call my magazine questionable."
    guest6 "How strange ... Mrs. White, the owner of another fashion magazine ..."
    guest6 "She was one of the first to use the word 'questionable' about your magazine."
    guest6 "It turns out she does not understand anything in fashion and art?"
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:643
translate english ep211_dialogues2_public_event_21_a66427c9:

    # m "У нас с Миссис Уайт несколько напряженные отношения."
    # m "Мы конкуренты."
    # m "А Миссис Уайт никогда не отличалась тактичностью."
    # m "Впрочем, как и некоторые здесь присутствующие..."
    # guest5 "..."
    # guest6 "..."
    # m "Я считаю, что вообще вести диалог о подобных вещах, не соответствует моему высокому уровню."
    # m "До свидания. Возможно, увидимся на одном из будущих модных показов."
    # biff "Ты пятно на платье не поставила, глупая кукла?"
    # m "Нет!"
    # biff "Смотри, аккуратнее. Хоть одно маленькое пятно..."
    # biff "И я высчитаю стоимость платья из твоей зарплаты!"
    # biff "Тебе придется целый месяц сниматься с членом во рту за бесплатно!"
    # mt "Да пошел ты!"
    # mt "Козел!"
    m "Mrs. White and I have a somewhat tense relationship."
    m "We're competitors."
    m "And Mrs. White has never been tactful."
    m "However, like some of those present here ..."
    guest5 "..."
    guest6 "..."
    m "I believe that generally conducting a dialogue about such things doesn’t correspond to my high level."
    m "Bye. Maybe I'll see you at one of the future fashion shows."
    biff "You didn't put a stain on the dress, stupid doll?"
    m "No!"
    biff "Watch it. One little spot..."
    biff "And I will deduct the cost of the dress from your salary!"
    biff "You will have to take dicks in your mouth for free for a month!"
    mt "Fuck you!"
    mt "Asshole!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:667
translate english ep211_dialogues2_public_event_22_55274d88:

    # mt "Фи! Не хочу больше разговаривать с этими дурами!"
    mt "Ew! I don't want to talk to those stupid people anymore!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:672
translate english ep211_dialogues2_public_event_23_f334f1d9:

    # reporter1 "Миссис Бакфетт, можно взять у Вас интервью."
    # m "Можно..."
    # reporter1 "Скажите, это правда, что Ваш журнал теперь больше про эротику?"
    # reporter1 "Чем про моду..."
    # m "Мой журнал, в первую очередь, про женскую красоту."
    # reporter2 "Миссис Бакфетт, ходят слухи, что проводятся достаточно..."
    # reporter2 "Откровенные фотосессии для Вашего журнала..."
    # m "Мы проводим фотосессии, на которых в полной мере раскрываем..."
    # m "Всю женственность и красоту наших моделей."
    # reporter3 "Когда мы сможем увидеть эти долгожданные снимки?"
    # m "Совсем скоро вы сможете насладиться эстетикой этих снимков."
    # reporter2 "Миссис Бакфетт, говорят Вы лично позируете перед камерой."
    # reporter2 "Это правда?"
    # m "Я самая лучшая модель. Со мной никто не сравниться."
    # m "Поэтому иногда я лично учавствую в фотосессиях..."
    # reporter1 "Миссис Бакфетт, а еще говорят, что у Вас была фотосессия..."
    # reporter1 "Где Ваша грудь практически полностью видна из-под платья."
    # reporter1 "Собираетесь ли Вы сделать фотосессия топлесс?"
    # m "Интересно, кто мог такое рассказать вам?"
    # m "Это не так. Я никогда не позволила бы себе обнажить грудь перед камерой."
    # m "Мир не достоин того, чтобы созерцать совершенную красоту моего тела."
    # reporter2 "Миссис Бакфетт, а кто этот мужчина, с которым Вы пришли?"
    # m "Это мой менеджер."
    # m "У меня нет времени заниматься некоторыми рутинными делами..."
    # m "Я управляю большой компанией, а всей остальной рутиной занимается он."
    # reporter3 "В одном из своих интервью Вы достаточно неприязенно отзывались..."
    # reporter3 "О Мистере Кэмпбелле. А сегодня вы присутствуете на его мероприятии..."
    # reporter3 "С чем связано..."
    # m "Интервью окончено. Вы можете сделать еще несколько снимков."
    # mt "Никчемные журналисты!"
    # mt "Про какие слухи они говорили? Откуда они их узнают?"
    # mt "Кто может рассказывать такие подробности? Алекс? Бифф?"
    # mt "Узнаю - уволю всех к черту!"
    # mt "Когда снова стану Боссом..."
    # mt "Мне во что бы то ни стало нужно скорее возвращать мой журнал МНЕ!"
    # mt "И прекращать эти глупости со сменой курса журнала!"
    reporter1 "Mrs. Buckfett, can we interview you?"
    m "Sure..."
    reporter1 "Tell me, is it true that your magazine is more on the erotic side now?"
    reporter1 "Than about fashion ..."
    m "My magazine is primarily about women's beauty."
    reporter2 "Mrs. Buckfett, there are rumors that some quite..."
    reporter2 "Candid photo shoots are being taken for your magazine ..."
    m "We conduct photo shoots in which we fully disclose ..."
    m "All the femininity and beauty of our models."
    reporter3 "When can we see these long-awaited pictures?"
    m "Soon you will be able to enjoy the aesthetics of these pictures."
    reporter2 "Mrs. Buckfett, they say you are personally posing in front of the camera."
    reporter2 "Is that true?"
    m "I am the best model we have. Nobody can compare to me."
    m "Therefore, sometimes I personally participate in photo shoots ..."
    reporter1 "Mrs. Buckfett, and they also say that you had a photo shoot ..."
    reporter1 "Where your chest is almost completely visible from under the dress."
    reporter1 "Are you going to make a topless photo shoot?"
    m "I wonder who could have told you this."
    m "This is not true. I would never allow myself to bare my chest in front of the camera."
    m "The world is not worthy to contemplate the perfect beauty of my body."
    reporter2 "Mrs. Buckfett, and who is this man you came with?"
    m "This is my manager."
    m "I don’t have time to do some chores ..."
    m "I run a big company, and he does the rest of the routine."
    reporter3 "In one of your interviews, you spoke with hostility..."
    reporter3 "About Mr. Campbell. And today you are attending his event ..."
    reporter3 "What is the reason ..."
    m "The interview is over. You can take some more pictures."
    mt "Worthless journalists!"
    mt "What rumors were they talking about? How do they know them?"
    mt "Who can tell such details? Alex? Biff"
    mt "I'll find out - and fire them!"
    mt "When I become the Boss again ..."
    mt "I need to quickly return my magazine to ME whatever the cost!"
    mt "And stop this nonsense with a change in the course of the magazine!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:721
translate english ep211_dialogues2_public_event_24_8271d075:

    # mt "Стефани и Ребекка?!"
    # mt "А они то что здесь делают?!"
    # mt "Дьявол!"
    # mt "..."
    # mt "С другой стороны, это шанс восстановить мою репутацию перед ними..."
    mt "Stephanie and Rebecca ?!"
    mt "And what are they doing here ?!"
    mt "Devil!"
    mt "..."
    mt "On the other hand, this is a chance to restore my reputation in front of them ..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:731
translate english ep211_dialogues2_public_event_25_2da32c61:

    # stephanie "Моника!"
    # rebecca "Какая неожиданная встреча!"
    # m "Привет, подружки!"
    # rebecca "У тебя такое шикарное платье!"
    # stephanie "Да, оно прекрасно подчеркивает твою фигуру!"
    # m "Спасибо, девочки."
    stephanie "Monica!"
    rebecca "What an unexpected meeting!"
    m "Hello, my friends!"
    rebecca "You have such a gorgeous dress!"
    stephanie "Yes, it perfectly emphasizes your figure!"
    m "Thanks, girls."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:739
translate english ep211_dialogues2_public_event_25_abbd17de:

    # rebecca "Немного непривычно видеть тебя вновь в таком раскошном образе."
    # rebecca "Мы уже привыкли, что ты носишь вещи какой-то провинциальной дуры, которая покрикивает на тебя."
    rebecca "It’s a little unusual to see you again in such a luxurious attire."
    rebecca "We're used to you wearing things that are a provincial fool shouting at you."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:745
translate english ep211_dialogues2_public_event_25_2c33916e:

    # m "Я же вам говорила, что у меня приключения..."
    # m "Но сегодня я решила принять прглашение Мистера Кэмпбелла."
    # rebecca "Все равно странно, что ты позволяешь этой провинциалке командовать тобой..."
    # rebecca "Это выглядит очень смешно."
    # rebecca "То, что ты носишь за ней ее вещи - это тоже приключения, да?"
    # rebecca "А сюда ты ее не стала брать? Хи-хи..."
    # mt "Черт! Вот пристали со своими глупыми вопросами!"
    # mt "Как хорошо, что здесь нет Бетти..."
    # m "Ничего странного. Просто такая игра."
    # stephanie "И как долго она еще будет продолжаться?"
    # stephanie "Ведь ты пропускаешь все наши девичники."
    # m "Я же сказала, что недолго! Скоро я закончу это дело и займусь своими обычными заботами."
    # stephanie "Да? Ты говорила что тебе больше неинтересны обычные развлечения."
    # stephanie "Что ты тогда делаешь здесь?"
    # rebecca "Да, Моника. Я помню, что ты говорила, что это скучно."
    # rebecca "И что твои развлечения сейчас гораздо интереснее!"
    # mt "!!!"
    # m "Подружки... Да, мне сейчас это не очень интересно."
    # m "Но не забывайте кто Я!"
    # m "Я - владелица крупнейшего журнала моды!"
    # m "И мне необходимо бывать на подобных вечерах, чтобы решать серьезные дела и вести переговоры!"
    # rebecca "Хорошо, Моника."
    # rebecca "Мы рады видеть тебя здесь!"
    # stephanie "Да, Моника. Мы рады."
    # stephanie "А то, если честно, мы начали сомневаться, говоришь ли ты нам правду."
    # stephanie "Вдруг ты действительно работаешь гувернанткой у той провинциальной дуры."
    # m "Что вы, подружки!"
    # m "Как вы могли такое подумать?!"
    # m "Это ведь было бы так нелепо! Фи!"
    # m "Моника Бакфетт и какая-то гувернантка..."
    # stephanie "Да, Моника. Это было бы совершенно нелепо."
    # stephanie "И я очень рада, что это не так."
    # m "А как у вас дела, подружки?"
    # m "Я не ожидала вас увидеть на этом вечере."
    # stephanie "Все отлично."
    # stephanie "Ты ведь знаешь, мы не можем пропустить подобной вечеринки."
    # stephanie "Здесь можно найти много интересных людей, с которыми можно познакомиться."
    # mt "И, судя по наряду Ребекки, найти, с кем бы переспать..."
    # mt "Стефани пришла сюда развлекаться."
    # mt "А Ребекка явно хочет найти очередной мешок с деньгами."
    # mt "..."
    m "I told you that I have adventures ..."
    m "But today I decided to accept Mr. Campbell's invitation."
    rebecca "It's still strange that you let this provincial command you ..."
    rebecca "It looks very funny."
    rebecca "The fact that you carry her things behind her is also an adventure, right?"
    rebecca "And you didn’t get it here? Hee hee ..."
    mt "Heck! They tire me out with their stupid questions!"
    mt "It’s good that Betty is not here ..."
    m "Nothing strange. It's just a game."
    stephanie "And how long will it last?"
    stephanie "After all, you miss all our girl parties."
    m "I told you it wasn't long! Soon I'll finish this case and take care of my usual concerns."
    stephanie "Yes? You said you weren't interested in ordinary entertainment anymore."
    stephanie "What are you doing here then?"
    rebecca "Yes, Monica. I remember that you said it was boring."
    rebecca "And that your entertainment is now much more interesting!"
    mt "!!!"
    m "Girls ... Yes, I'm not very interested right now."
    m "But don’t forget who I am!"
    m "I am the owner of the largest fashion magazine!"
    m "And I need to go to such evenings to solve serious matters and negotiate!"
    rebecca "Alright, Monica."
    rebecca "We are glad to see you here!"
    stephanie "Yes, Monica. We are glad."
    stephanie "Honestly, we began to doubt whether you were telling us the truth."
    stephanie "Suddenly you really work as a maid for that provincial fool."
    m "Come on, girls!"
    m "How could you think that ?!"
    m "It would be so ridiculous! Ew!"
    m "Monica Buckfett working as some maid ..."
    stephanie "Yes, Monica. That would be completely ridiculous."
    stephanie "And I’m very glad that this is not true."
    m "How are you doing, girls?"
    m "I didn’t expect to see you this evening."
    stephanie "Everything is fine."
    stephanie "You know, we couldn't miss such a party."
    stephanie "There are many interesting people to meet here."
    mt "And, judging by Rebecca’s outfit, find someone to sleep with ..."
    mt "Stephanie came here to have fun."
    mt "And Rebecca clearly wants to find another moneybag."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:790
translate english ep211_dialogues2_public_event_25_bf0138c8:

    # m "Ребекка, у тебя такой интересный наряд сегодня!"
    # m "Тебе очень идет!"
    # mt "Похожа на новогоднюю елку..."
    # rebecca "Спасибо, подружка!"
    # m "С кем-нибудь познакомилась здесь?"
    # rebecca "Нет, но я очень хочу познакомиться вон с тем парнем."
    # rebecca "Ты же знаешь, кто он?"
    # m "Джеймс Тернер? Ну да, знаю..."
    # m "Обычный исполнитель... Ничего особенного."
    # rebecca "Моника, о нем сейчас пишут все СМИ!"
    # rebecca "Он мега популярен!"
    # rebecca "Я просто в восторге от него!"
    # m "И что тебе мешает познакомиться с ним?"
    # rebecca "Да он ни на кого внимания не обращает!"
    # rebecca "Я уже пыталась подойти к нему..."
    # stephanie "Да. Она пыталась. Это бесполезно."
    # stephanie "Моника, ты же здесь всех знаешь..."
    # stephanie "Может, познакомишь Ребекку с Тернером?"
    # stephanie "Я могла бы это сделать, но мой отец сенатор будет против."
    # stephanie "Я не могу это делать на публике, ты знаешь."
    # mt "???"
    # rebecca "Точно! Стефани, отличная идея!"
    # rebecca "Моника, пожалуйста!"
    # rebecca "Он очень знаменит и богат."
    # rebecca "Если я с ним начну встречаться, обо мне тоже будут писать все газеты!"
    # rebecca "Потом меня заметит какой-нибудь продюсер..."
    # rebecca "И я, наконец, тоже стану богатой и знаменитой!"
    # rebecca "Моника, ну что тебе стоит подойти к нему?"
    # rebecca "Ну пожалуйста!"
    # mt "Хммм..."
    # mt "А почему бы и мне не попробовать найти себе мужчину..."
    # mt "Который решит все мои небольшие временные недоразумения..."
    # mt "Которые у меня возникли?"
    # mt "Стоит попробовать."
    # mt "Я самая красивая женщина на этом вечере."
    # mt "Мне не составит никакого труда найти себе богатого мужчину."
    # mt "Но только не этого никчемного певца с фиолетовыми волосами! Фи!"
    # mt "Этот самовлюбленный кретин не потратит ни на какую девушку и цента!"
    # mt "Я найду себе мужчину лучше!"
    # mt "А этого, так уж и быть, оставлю Ребекке..."
    # mt "..."
    m "Rebecca, you have such an interesting outfit today!"
    m "It suits you very much!"
    mt "Looks like a Christmas tree ..."
    rebecca "Thank you, girl!"
    m "Did you meet anyone new here?"
    rebecca "No, but I really want to talk to that guy over there."
    rebecca "Do you know who he is?"
    m "James Turner? Well yes, I know ..."
    m "Just an ordinary performer ... Nothing special."
    rebecca "Monica, he's all the rage in the media nowadays!"
    rebecca "He is mega popular!"
    rebecca "He's so awesome!"
    m "And what prevents you from getting to know him?"
    rebecca "He doesn’t pay attention to anyone!"
    rebecca "I already tried to approach him ..."
    stephanie "Yes. She tried. It's useless."
    stephanie "Monica, you know everyone here ..."
    stephanie "Can you introduce Rebecca to Turner?"
    stephanie "I could have done it, but my father, the senator, would be against it."
    stephanie "I can’t do it in public, you know."
    mt "???"
    rebecca "Right! Stephanie, great idea!"
    rebecca "Monica, please!"
    rebecca "He is very famous and rich."
    rebecca "If I start dating him, all the newspapers will write about me too!"
    rebecca "Then some producer will notice me ..."
    rebecca "And I, finally, will also become rich and famous!"
    rebecca "Monica, it would be easy for you to talk to him, right?"
    rebecca "Please!"
    mt "Hmmm."
    mt "And why don't I try to find a man ..."
    mt "Which will solve all my small temporary troubles..."
    mt "I'm currently having?"
    mt "It's worth a try."
    mt "I’m the most beautiful woman here this evening."
    mt "It won’t be difficult for me to find a rich man."
    mt "But not this worthless singer with purple hair! Ew!"
    mt "This narcissistic cretin won't spend a cent on any girl!"
    mt "I will find a better man!"
    mt "And this one I will leave to Rebecca, since I'm so generous ..."
    mt "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:835
translate english ep211_dialogues2_public_event_25_8ec961d7:

    # m "Ребекка, не вижу никакой проблемы, чтобы познакомиться с ним."
    # m "Ждите меня здесь, девочки."
    # m "Я сейчас вернусь."
    m "Rebecca, I don’t see why I wouldn't be able to talk to him."
    m "Wait for me here, girls."
    m "I'll be right back."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:846
translate english ep211_dialogues2_public_event_26_655a17af:

    # mt "Сначала мне нужно подойти к этому никчемному Тернеру."
    mt "First I need to approach this worthless Turner."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:853
translate english ep211_dialogues2_public_event_27_6487a28e:

    # mt "Джеймс Тернер."
    # mt "Никчемный исполнитель никчемных песен."
    # mt "И что Ребекка в нем нашла?"
    mt "James Turner"
    mt "Worthless performer of worthless songs."
    mt "God knows what Rebecca found in him."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:861
translate english ep211_dialogues2_public_event_28_1588810d:

    # guest8 "Добрый вечер..."
    # guest8 "Моника Бакфетт, если не ошибаюсь?"
    # m "Все верно, Мистер Тернер. Добрый вечер."
    # guest8 "Рад знакомству."
    # guest8 "Вы уже пробовали вино, которое здесь подают?"
    # guest8 "Вполне неплохое..."
    # m "Да, пробовала. Очень вкусное."
    # mt "Какое вино?!"
    # mt "Не хватало еще испачкать платье!"
    # mt "Биф сказал что мне придется его отрабатывать... Даже боюсь вспоминать как..."
    guest8 "Good evening..."
    guest8 "Monica Buckfett, if I'm not mistaken?"
    m "That's right, Mr. Turner. Good evening."
    guest8 "Pleased to meet you."
    guest8 "Have you tried the wine served here?"
    guest8 "Not bad at all ..."
    m "Yes, I did. It's delicious."
    mt "What wine?!"
    mt "I don't want to stain the dress!"
    mt "Biff said that I would have to pay for it... I'm afraid to remember how..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:874
translate english ep211_dialogues2_public_event_28_5c765e14:

    # m "Мистер Тернер, я хотела бы Вас познакомить со своей подругой..."
    # guest8 "С подругой?"
    # m "Да. Вон та девушка в ярком платье."
    # guest8 "Ага. Видел ее."
    # guest8 "Она весь вечер пытается подкатить ко мне..."
    # guest8 "Так она Ваша подруга?"
    # m "Моя подруга и очень хорошая девушка."
    # mt "Я стала слишком много врать в последнее время..."
    # mt "Главное, чтобы это не вошло в привычку."
    # guest8 "..." 
    # guest8 "Вообще-то, я не против..." 
    # guest8 "И я прекрасно понимаю цель знакомства..."
    # m "..."
    # guest8 "Я познакомлюсь с ней при одном условии."
    # m "Каком условии, Мистер Тернер?"
    # guest8 "У меня планируется съемка нового клипа."
    # guest8 "Но я никак не могу подобрать подходящую локацию."
    # guest8 "Я слышал, что над интерьером Вашего дома работал какой-то известный дизайнер..."
    # guest8 "Я ранее видел его работы. И хочу сказать, что мне очень понравилось."
    # guest8 "Думаю, что Ваш дом вполне подойдет для съемки моего клипа."
    # m "???"
    # m "Это и есть Ваше условие, Мистер Тернер?"
    # guest8 "Да."
    # guest8 "Вы разрешаете мне снять клип в Вашем доме."
    # guest8 "А я соглашаюсь познакомиться с Вашей подругой."
    # mt "Вот дъявол!"
    m "Mr. Turner, I would like to introduce you to my friend..."
    guest8 "A friend?"
    m "Yes. There’s that girl in a bright dress."
    guest8 "Yeah. I saw her."
    guest8 "She's been trying to talk to me all evening ..."
    guest8 "So is she your friend?"
    m "My friend and a very nice girl."
    mt "I've started to lie too much lately ..."
    mt "The main thing is that this doesn’t become a habit."
    guest8 "..." 
    guest8 "Actually, I don't mind ..." 
    guest8 "And I understand why she wants to get to know me..."
    m "..."
    guest8 "I will talk her on one condition."
    m "What condition, Mr. Turner?"
    guest8 "I'm planning to shoot a new music video."
    guest8 "But I just can’t find the right location."
    guest8 "I heard that some famous designer worked on the interior of your house ..."
    guest8 "I've seen his work before. And I mean, I really liked it."
    guest8 "I think your house is quite suitable for shooting my video."
    m "???"
    m "Is this your condition, Mr. Turner?"
    guest8 "Yes."
    guest8 "You allow me to make a music video in your house."
    guest8 "And I agree to meet your friend."
    mt "The devil!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:903
translate english ep211_dialogues2_public_event_28_6a2909fc:

    # m "Мне приятно, что Вы хотите снять клип в стенах моего дома."
    # m "Я подумаю и дам Вам ответ немного позже..."
    # guest8 "Без проблем."
    # guest8 "Буду ждать."
    m "I am pleased that you want to make a music video in my house."
    m "I'll think about it and I'll give you the answer a little later..."
    guest8 "No problem."
    guest8 "I will wait."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:915
translate english ep211_dialogues2_public_event_29_fe330b46:

    # mt "Я не хочу подходить к нему!"
    # mt "Сейчас будет опять просить снять свой никчемный клип в моем доме..."
    mt "I don't want to approach him!"
    mt "He's gonna ask me to let him make his worthless music video in my house again..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:922
translate english ep211_dialogues2_public_event_30_7926b18d:

    # stephanie "Ну что?!"
    # rebecca "Он согласился?"
    stephanie "Well?!"
    rebecca "Did he agree?"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:926
translate english ep211_dialogues2_public_event_30_f5455032:

    # m "Он согласился при одном условии..."
    # rebecca "Каком условии?"
    # m "Он сказал, что хочет снять клип в моем доме."
    # m "Если я соглашусь, то он с тобой познакомиться, Ребекка."
    # rebecca "У тебя такой роскошный дом! Неудивительно что он попросил тебя об этом."
    # rebecca "И? Ты же согласилась, Моника?!"
    # m "Я сказала, что мне нужно подумать..."
    # rebecca "Что?!"
    # rebecca "Моника!!!"
    # rebecca "Ну пожалуйста скажи ему, что ты согласна!"
    # mt "Надо же, как она меня уговаривает..."
    # mt "Ее звездная карьера, практически в моих руках."
    # mt "Ха-ха!"
    # m "Я не хочу, чтобы кто-то топтался по моему дому своими грязными ногами..."
    # m "Ты ведь знаешь, что я не терплю чужаков на своей территории."
    # stephanie "Моника, зато в твоем доме снимут клип!"
    # stephanie "Это же круто!"
    # stephanie "Подумаешь, потопчутся немного."
    # stephanie "У тебя же есть гувернантка. Ей это все убирать, а не тебе."
    # mt "!!!"
    # m "Я подумаю, девочки..."
    m "He agreed on one condition ..."
    rebecca "What condition?"
    m "He said he wanted to shoot a music video in my house."
    m "If I agree, he will meet you, Rebecca."
    rebecca "You have such a luxurious home! No wonder he asked you to do that."
    rebecca "AND? You agreed, right, Monica ?!"
    m "I said I need to think ..."
    rebecca "What?!"
    rebecca "Monica!!!"
    rebecca "Please, tell him that you agree!"
    mt "She's trying so hard to convince me..."
    mt "Her career as a star is practically in my hands."
    mt "Ahaha!"
    m "I don’t want anyone to stomp around my house with their dirty feet ..."
    m "You know I don't tolerate outsiders on my territory."
    stephanie "Monica, but they’ll shoot a music video in your house!"
    stephanie "It's gonna be so cool!"
    stephanie "So what if they stomp around a bit?"
    stephanie "You have a maid. She's gonna clean it up, not you."
    mt "!!!"
    m "I'll think about it, girls ..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:949
translate english ep211_dialogues2_public_event_30_c64d3953:

    # m "Он отказался."
    # rebecca "Отказался?"
    # m "Да. Сказал, что у него уже есть девушка."
    # m "И он ни с кем знакомиться не хочет."
    # rebecca "Жаль..."
    # rebecca "Это был отличный план."
    m "He refused."
    rebecca "He did?"
    m "Yes. He said that he already has a girlfriend."
    m "And he doesn't want to meet anyone."
    rebecca "Sorry..."
    rebecca "It was a great plan."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:957
translate english ep211_dialogues2_public_event_30_ad4ffb94:

    # stephanie "Ребекка, не расстраивайся."
    # stephanie "У меня появилась отличная идея!"
    # stephanie "Почему бы тебе не сняться в журнале Моники?"
    # stephanie "Она легко сделает тебя известной."
    # mt "Твою мать!"
    # m "..."
    # rebecca "Да, но..."
    # rebecca "У Моники немного сменился курс журнала..."
    # m "..."
    # stephanie "Кстати, Моника, а почему ты приняла такое решение?"
    # stephanie "Ты ведь всегда так гордилась, что у тебя журнал о моде..."
    # stephanie "А теперь неожиданно изменила свое мнение..."
    # m "..."
    # m "Мне просто стало скучно, девочки."
    # m "Поэтому я приняла такое решение."
    # rebecca "Это правда, что ты участвуешь в откровенных фотосессиях?"
    # rebecca "Все об этом говорят."
    # m "Я не назвала бы их откровенными."
    # m "Я не раздеваюсь перед объективом камеры."
    # m "Просто провожу обычные фотосессии в красивых нарядах."
    # m "Я никогда не позволила бы себе показать на камеру..."
    # m "Какую-нибудь интимную часть своего прекрасного тела!"
    # stephanie "Ребекка, тогда тебе ничего не мешает сняться для журнала Моники!"
    # rebecca "Да, я тоже так думаю."
    # rebecca "Моника, ты же не будешь против?"
    # mt "Все! Они мне надоели!"
    # mt "Ведут себя, как две попрошайки."
    # mt "Моника дай то, Моника дай это..."
    # mt "!!!"
    stephanie "Rebecca, don't be upset."
    stephanie "I got a great idea!"
    stephanie "Why don't you model in Monica’s magazine?"
    stephanie "She will easily make you famous."
    mt "Fuck!"
    m "..."
    rebecca "Yes, but ..."
    rebecca "Monica has changed the course of the magazine a little ..."
    m "..."
    stephanie "By the way, Monica, why did you make that decision?"
    stephanie "You were always so proud that you had a fashion magazine ..."
    stephanie "And now you had suddenly changed her mind ..."
    m "..."
    m "I just got bored, girls."
    m "So I made that decision."
    rebecca "Is it true that you participate in candid photo shoots?"
    rebecca "Everyone is talking about it."
    m "I would not call them lewd."
    m "I do not undress in front of the camera."
    m "I just do regular photo shoots in beautiful outfits."
    m "I would never allow myself to show any ..."
    m "intimate parts of my beautiful body on camera!"
    stephanie "Well, then nothing prevents you from modeling for Monica’s magazine, Rebecca!"
    rebecca "I think the same."
    rebecca "Monica, you don’t mind?"
    mt "Ahhhh! I'm tired of them!"
    mt "They behave like two beggars."
    mt "I want this, Monica... I want that, Monica..."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:990
translate english ep211_dialogues2_public_event_30_e13076e6:

    # m "Я подумаю, девочки..."
    # m "А теперь, извините, мне нужно идти."
    # m "Мне нужно поговорить по работе еще с несколькими знаменитыми гостями."
    # m "Пока, пожружки!"
    # stephanie "До встречи, дорогая!"
    # rebecca "Я буду ждать ответа, Моника!"
    # m "Конечно, Ребекка!"
    m "I'll think about it, girls ..."
    m "Now, excuse me, I have to go."
    m "I need to talk with a few other famous guests."
    m "Bye bye!"
    stephanie "See you, dear!"
    rebecca "I‘ll wait for an answer, Monica!"
    m "Of course, Rebecca!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1003
translate english ep211_dialogues2_public_event_31_6d403a60:

    # mt "Не хочу больше к ним подходить!"
    # mt "Сейчас снова начнут у меня что-нибудь выпрашивать!"
    mt "I don’t want to approach them anymore!"
    mt "Now they’ll start asking me for something again!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1011
translate english ep211_dialogues2_public_event_32_2e3a0d8b:

    # mt "Адриано!"
    # mt "Он без ума от меня."
    # mt "Он сделал великолепный дизайн интерьера моего дома."
    # mt "Он делает все, что я захочу, стоит мне только об этом сказать."
    mt "Adriano!"
    mt "He is crazy in love me."
    mt "He made a splendid interior design of my house."
    mt "He's doing everything I want, I just need to say a word."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1020
translate english ep211_dialogues2_public_event_33_b8185386:

    # guest7 "Моника!"
    # guest7 "Как я рад снова встретиться с тобой, дорогая!"
    # guest7 "Я так скучал по тебе!"
    # guest7 "Ты ослепительно прекрасна в этом платье!"
    # m "Здравствуй, Адриано..."
    # m "Признаться, я тоже соскучилась по тебе."
    # guest7 "Как я рад это слышать, дорогая!"
    # guest7 "Расскажи, как твои дела?"
    # guest7 "Все ли у тебя хорошо на работе?"
    # guest7 "Может быть, я могу чем-то быть полезным?"
    # guest7 "Ты же знаешь, я для тебя все готов сделать!"
    guest7 "Monica!"
    guest7 "How glad I am to meet you again, dear!"
    guest7 "I missed you so much!"
    guest7 "You're glamorously beautiful in this dress!"
    m "Hello Adriano ..."
    m "I admit I missed you, too."
    guest7 "How glad I am to hear that, dear!"
    guest7 "Tell me how you're doing."
    guest7 "Are you doing well at work?"
    guest7 "Maybe I can be of some use?"
    guest7 " I'm ready to do anything for you!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1034
translate english ep211_dialogues2_public_event_33_a977d0cc:

    # m "Адриано, ты и правда на все готов ради меня?"
    # guest7 "Да, Моника!"
    # guest7 "Мое сердце всегда будет принадлежать только тебе!"
    # guest7 "В тот день, когда ты мне ответишь взаимностью..."
    # guest7 "Я стану самым счастливым мужчиной на свете!"
    # mt "Хм, мило..."
    # mt "Мне он, конечно, совсем не нравится..."
    # mt "Но..."
    # mt "Адриано тот человек, который сможет мне помочь с деньгами."
    # mt "На него я смогу положиться."
    # mt "И, наконец, решить свои временные трудности."
    # mt "Только... Что ему сказать?"
    # mt "Не рассказывать же ему всю правду..."
    m "Adriano, are you really ready to do anything for me?"
    guest7 "Yeah..."
    guest7 "My heart will always belong only to you!"
    guest7 "The day you reciprocate..."
    guest7 "I'll be the happiest man in the world!"
    mt "Uh, nice..."
    mt "I don't like him at all..."
    mt "But..."
    mt "Adriano is the man who can help me with the money."
    mt "I can rely on him."
    mt "And, finally, solve my temporary difficulties."
    mt "Just... What should I tell him?"
    mt "Don't tell him the whole truth..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1050
translate english ep211_dialogues2_public_event_33_ba7a0965:

    # m "Адриано, может мы поужинаем?.."
    # biff "Ты хочешь пригласить к нам на ужин Адриано?"
    # biff "Отличная идея, дорогая!"
    # biff "Адриано, вы придете к нам с Моникой вместе со своей женой?"
    # guest7 "..."
    # biff "Мы устроим замечательный вечер и познакомимся семьями."
    # biff "Да, дорогая?"
    # guest7 "Моника, это... Это твой муж?"
    # biff "Да. Меня зовут Биф. Приятно познакомиться!"
    # mt "Что он несет?!"
    # mt "!!!"
    # m "Биф!"
    # guest7 "Моника..." 
    # m "Адриано! Подожди!"
    # guest7 "Не знал, что ты снова вышла замуж... Я... Я рад за тебя."
    # m "Адриано!"
    # m "Биф!!!"
    # guest7 "Биф, у меня не получится отужинать с вами."
    # biff "Жаль!"
    # biff "До свидания, Адриано!"
    # guest7 "Всего хорошего!" 
    # m "Биф!!!"
    # m "Какого черта ты влез в наш разговор!"
    # m "Что еще за шуточки про мужа!!!"
    # m "Мне нужно поговорить с ним!"
    # m "Отпусти меня!"
    # biff "Ты никуда не пойдешь!"
    # biff "Успокойся и не веди себя как истеричная безмозглая кукла!"
    # biff "Ты забыла, что ты должна притворяться Моникой Бакфетт?"
    # m "Зачем ты ему сказал, что ты мой муж?!"
    # biff "Потому что он пускал слюни на тебя."
    # biff "Я понимаю, что такая глупая кукла как ты, пытается с кем-то познакомиться здесь."
    # biff "Но не забывай, что ты лишь только притворяешься Моникой Бакфетт!"
    # biff "Что бы было, если бы ты встретилась с ним?!"
    # biff "Он бы сразу понял, что ты дешевая шлюха, а не та, за кого себя выдаешь!"
    # biff "Папочка не хочет терять репутацию из-за тебя!"
    # m "Что?!"
    # biff "Что слышала!"
    # biff "Закрой рот и не беси меня!"
    # biff "Нам сейчас надо поговорить с Мистером Кэпбеллом."
    # biff "Он один из инвесторов, если ты вдруг забыла."
    # biff "Ты же помнишь своими мозгами, которых почти нет, что должна сделать все..."
    # biff "Чтобы инвестор дал свое согласие на сотрудничество с нами?"
    # mt "!!!"
    # mt "Сволочь!"
    # mt "Придурок!"
    # biff "Вон стоит этот денежный мешок."
    # biff "Подойдем к нему."
    # mt "!!!"
    m "Adriano, can we have dinner?.."
    biff "Do you want to invite Adriano to our dinner?"
    biff "That's a good idea, darling!"
    biff "Adriano, will you visit us with your wife?"
    guest7 "..."
    biff "We will have a wonderful evening over a warm, family-like dinner."
    biff "Yes darling?"
    guest7 "Monica, is ... Is this your husband?"
    biff "Yes. My name is Biff. Nice to meet you!"
    mt "What the hell is he saying?!"
    mt "!!!"
    m "Biff!"
    guest7 "Monica..." 
    m "Adriano! Wait!"
    guest7 "I didn’t know that you were married again ... I ... I am happy for you."
    m "Adriano!"
    m "Biff !!!"
    guest7 "Biff, I won’t be able to have dinner with you."
    biff "That’s a pity!"
    biff "Goodbye Adriano!"
    guest7 "Good luck!" 
    m "Biff !!!"
    m "What the hell are you doing in our conversation?"
    m "What do you mean, you're my husband ?!!"
    m "I need to talk to him!"
    m "Let me go!"
    biff "You're not going anywhere!"
    biff "Calm down and don't act like a hysterical, brainless doll!"
    biff "Did you forget that you have to pretend to be Monica Buckfett?"
    m "Why did you tell him that you are my husband ?!"
    biff "Because he was drooling over you."
    biff "I understand that a stupid doll like you is trying to meet someone here."
    biff "But don’t forget that you are only pretending to be Monica Buckfett!"
    biff "What would happen if you met him ?!"
    biff "He would immediately understand that you are a cheap whore, and not the one you impersonate!"
    biff "Daddy doesn’t want to lose his reputation because of you!"
    m "What?!"
    biff "What I said!"
    biff "Shut your mouth and don't piss me off!"
    biff "We need to talk to Mr. Capbell now."
    biff "He's one of the investors, in case you forgot."
    biff "You remember with your brains, which are almost absent, that you must do everything ..."
    biff "So an investor would agree to cooperate with us, right?"
    mt "!!!"
    mt "That bastard!"
    mt "Idiot!"
    biff "This money bag over there."
    biff "Let's go to him."
    mt "!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1109
translate english ep211_dialogues2_public_event_34_7ae94873:

    # mt "Мистер Кэмпбелл."
    # mt "Хозяин этого вечера."
    # mt "Богатый, но крайне жадный неудачник. Фи!"
    mt "Mr. Campbell."
    mt "The owner of this evening."
    mt "A rich but extremely greedy loser. Ew!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1117
translate english ep211_dialogues2_public_event_35_02deca4b:

    # biff "Мистер Кэмпбэлл, мы с Миссис Бакфетт хотели бы поздравить Вас."
    # m "Добрый вечер, Мистер Кэмбелл."
    # mt "Идиот Биф готов в задницу целовать этого мерзкого Мистера Кэмпбелла."
    # campbell "Добрый вечер."
    # biff "Ваша компания уже много лет развивается очень успешно."
    # biff "Как и наш журнал."
    # campbell "Да, что касается вашего журнала..."
    # campbell "Я внимательно изучил документацию, которую вы мне прислали."
    # campbell "Но я еще не готов озвучить свое решение..."
    # campbell "Ведь речь идет о довольно крупной сумме денег."
    # campbell "Я не привык раскидываться деньгами понапрасну."
    # campbell "Я должен быть уверен в том, что не потеряю ни цента."
    # campbell "Эта сделка должна быть взаимовыгодной. Вы понимаете, о чем я?"
    # biff "Да, конечно, Мистер Кэмпбелл."
    # biff "Мы готовы предоставить вам всю необходимую информацию."
    # campbell "Миссис Бакфетт, вы являетесь лицом журнала..."
    # campbell "Вы сами как относитесь к столь радикальной смене курса журнала?"
    # mt "Я готова разорвать этого чертового Бифа с его идиотскими идеями!!!"
    # mt "Или придушить... Нет, лучше ударить бутылкой по его пустой голове!!!"
    biff "Mr. Campbell, Mrs. Buckfett and I would like to congratulate you."
    m "Good evening, Mr. Campbell."
    mt "Idiot Biff is ready to kiss Mr. Campbell's disgusting ass."
    campbell "Good evening."
    biff "Your company has become very successfully over many years."
    biff "Just like our magazine."
    campbell "Yes, as for your magazine ..."
    campbell "I carefully studied the documentation that you sent me."
    campbell "But I'm not ready to voice my decision ..."
    campbell "After all, we are talking about a fairly large amount of money."
    campbell "I'm not used to throwing money in vain."
    campbell "I must be sure that I will not lose a cent."
    campbell "This deal must be mutually beneficial. Do you understand what I'm talking about?"
    biff "Yes, of course, Mr. Campbell."
    biff "We are ready to provide you with all the necessary information."
    campbell "Mrs. Buckfett, you are the face of the magazine ..."
    campbell "How do you feel about such a radical change in the course of the magazine?"
    mt "I am ready to break this damn Bifff with his idiotic ideas !!!"
    mt "Or choke... No, it's better to hit his empty head with a bottle!!!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1143
translate english ep211_dialogues2_public_event_35_8d1d8508:

    # m "Мистер Кэмпбелл, я поддерживаю эту идею."
    # m "Я уверена, что Вы сделаете правильный выбор, сделав инвестицию в наш журнал."
    # campbell "До меня дошли слухи, что Вы настолько поддерживаете эту идею..."
    # campbell "Что сами позируете на фотосессиях, Миссис Бакфетт."
    # mt "!!!"
    # biff "Да, Мистер Кэмбелл. Миссис Бакфетт провела уже несколько фотосессий."
    # biff "Желаете посмотреть снимки с этих фотосессий, Мистер Кэмпбелл?"
    # mt "Что?!?!?!"
    # m "Биф!"
    # campbell "Да, я бы посмотрел. Но не только на снимки..."
    # mt "!!!"
    # campbell "Моя компания занимается пошивом дизайнерской одежды."
    # campbell "Я хотел бы прорекламировать свою последнюю коллекцию."
    # campbell "Я готов предоставить платье для проведения фотосессии..."
    # campbell "Также я хочу посмотреть на работу журнала, так сказать, изнутри."
    # campbell "Если у Миссис Бакфетт запланированы фотосессии на ближайшее время..."
    # campbell "То я хотел бы поприсутствовать на одной из них."
    # mt "!!!"
    # biff "Да, конечно, Мистер Кэмпбелл! Мы будем рады Вашему визиту!"
    # mt "Вот сволочь!!! Что он несет?!"
    # m "Биф, я..."
    # biff "Миссис Бакфетт хочет сказать, что на днях у нее будет фотосессия."
    # biff "Она Вас приглашает поприсутствовать на ней, Мистер Кэмпбелл."
    # biff "Мы с радостью проведем эту фотосессию в предоставленном Вами наряде!"
    # mt "Я убью этого придурка Бифа!"
    # campbell "Договорились. Сообщите мне и я приеду к вам."
    # campbell "Возможно, после фотосессии, я приму решение по инвестиции в ваш журнал."
    # biff "Отлично, Мистер Кэмпбелл! Будем рады Вас видеть!"
    # m "Биф, как ты себе это представляешь?!"
    # m "!!!"
    # biff "Цыпочка обещала быть хорошей."
    # biff "Она сделает так, чтобы инвесторы несли мне свои деньги."
    # biff "Скоро у цыпочки будет возможность продемонстрировать свою работу..."
    # biff "Так, чтобы у этого мешка с деньгами не осталось никаких сомнений."
    # biff "Ты поняла меня?"
    # m "..."
    m "Mr. Campbell, I support this idea."
    m "I am sure that you will make the right choice by investing in our magazine."
    campbell "I heard rumors that you are so supportive of this idea ..."
    campbell "That you yourself are posing for photo shoots, Mrs. Buckfett."
    mt "!!!"
    biff "Yes, Mr. Campbell. Mrs. Buckfett has already had several photo shoots."
    biff "Would you like to see the pictures from these photo shoots, Mr. Campbell?"
    mt "What?!?!?!"
    m "Biff!"
    campbell "Yeah, I would. But not just the pictures..."
    mt "!!!"
    campbell "My company is engaged in tailoring designer clothes."
    campbell "I would like to advertise my latest collection."
    campbell "I am ready to provide a dress for a photo shoot ..."
    campbell "I also want to look at the work of the magazine, so to speak, from the inside."
    campbell "If Mrs. Buckfett has a photo shoot planned for the near future ..."
    campbell "Then I would like to attend one of them."
    mt "!!!"
    biff "Yes, of course, Mr. Campbell! We look forward to your visit!"
    mt "What a bastard !!! What is he saying ?!"
    m "Biff, I ..."
    biff "Mrs. Buckfett wants to say that she will have a photo shoot quite soon."
    biff "She invites you to attend, Mr. Campbell."
    biff "We will gladly hold this photo session in the outfit provided by you!"
    mt "I will kill that moron Biff!"
    campbell "Agreed. Let me know and I will come to you."
    campbell "Perhaps after the photo session, I will make a decision whether I should invest in your magazine."
    biff "Great, Mr. Campbell! We’ll be glad to see you!"
    m "Biff, how do you imagine this ?!"
    m "!!!"
    biff "The chick promised to be good."
    biff "She'll make sure the investors pay me their money."
    biff "Soon, the chick will have the opportunity to showcase their work ..."
    biff "So that this money bag has no doubts left."
    biff "Do you understand me?"
    m "..."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1193
translate english ep211_dialogues2_public_event_35_7f599f0c:

    # m "Биф, я не буду проводить фотосессию в присутствии этого инвестора!"
    # m "Я не хочу, чтобы он на меня пялился!"
    # m "Почему я?! Почему не Мелани?"
    # biff "Потому что Мистер Кэмпбелл так хочет."
    # biff "Ты не получишь никакую другую работу..."
    # biff "Пока не проведешь эту фотосессию!"
    # mt "Чертов Мистер Кэмпбелл! Чертов Биф! Ненавижу их всех!"
    m "Biff, I will not conduct a photo session in the presence of this investor!"
    m "I don’t want him to stare at me!"
    m "Why me?! Why not Melanie?"
    biff "Because Mr. Campbell wants it that way."
    biff "You won’t get any other job ..."
    biff "Until you have this photo shoot!"
    mt "Fucking Mr. Campbell! Damn Biff! I hate them all!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1202
translate english ep211_dialogues2_public_event_35_f6028d59:

    # mt "Сволочь!"
    # mt "!!!"
    # mt "С другой стороны, это будет дорогое дизайнерское платье..."
    # mt "Скорее всего, оно будет восхитительно на мне смотреться."
    # mt "Вряд ли оно будет слишком откровенным или пошлым."
    # m "..."
    # m "Я проведу эту фотосессию, Биф."
    # biff "Ну вот. Другое дело, цыпочка. Папочка тобой доволен."
    mt "That bastard!"
    mt "!!!"
    mt "On the other hand, it will be an expensive designer dress ..."
    mt "Most likely, it will look amazing on me."
    mt "It is unlikely to be too revealing or vulgar."
    m "..."
    m "I'll do this photo shoot, Biff."
    biff "Here you go. That's the spirit, chick. Daddy is happy with you."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1217
translate english ep211_dialogues2_public_event_36_c98a233a:

    # mt "Это место мне нравится..."
    # mt "Не то что тот дешевый ресторан в отеле. Фи!"
    mt "I like this place ..."
    mt "Not like that cheap hotel restaurant. Ew!"

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1223
translate english ep211_dialogues2_public_event_37_0357f681:

    # mt "Какое интересное дизайнерское решение в центре терассы."
    mt "What an interesting design decision in the center of the terrace."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1228
translate english ep211_dialogues2_public_event_38_d1be412f:

    # mt "С этой терассы открывается чудесный вид на ночной город."
    mt "This terrace offers a wonderful view of the night city."

# game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1233
translate english ep211_dialogues2_public_event_39_a97df8b2:

    # mt "Здесь очень уютные столики и приятная атмосфера."
    # mt "Видно, что над клубом Мистера Кэмпбелла работал хороший дизайнер."
    mt "It has very cozy tables and a pleasant atmosphere."
    mt "It can be seen that a good designer worked on Mr. Campbell's club."

translate english strings:

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:69
    old "Я хорошо выполняю свою работу!"
    new "I do my job well!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:86
    old "Как я это сделаю?"
    new "How will I do that?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:151
    old "Переодеться в вечернее платье."
    new "Change into an evening dress."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:192
    old "Поехать на мероприятие вместе с Бифом."
    new "Go to the event with Biff."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:266
    old "Пообщаться с гостями."
    new "Chat with guests."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:293
    old "У меня были другие, более важные дела..."
    new "I had other, more important matters ..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:304
    old "Я так не считаю, Миссис Уайт."
    new "I don't think so, Mrs. White."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:318
    old "Мой журнал был всегда успешнее Вашего бульварного чтива."
    new "My magazine has always been more successful than your pulp fiction."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:376
    old "Какие пробы, Грейс?"
    new "What tests, Grace?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:386
    old "Мелани в отпуске."
    new "Melanie is on vacation."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:400
    old "И что тебе на это пообещал мой менеджер Биф?"
    new "And what did my manager Biff promise you?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:454
    old "Спасибо, Исаак."
    new "Thanks, Isaac."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:468
    old "Ты неверно понял моего менеджера."
    new "You misunderstood my manager."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:527
    old "У меня были другие, более важные дела."
    new "I had other, more important matters."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:548
    old "Вы обсуждали эту работу с Алексом?"
    new "Did you discuss this job with Alex?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:627
    old "Мистер Кэмпбелл пригласил сегодня всю элиту мира моды."
    new "Mr. Campbell invited the entire fashion world elite today."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:640
    old "У нас с Миссис Уайт несколько напряженные отношения."
    new "Mrs. White and I have a somewhat tense relationship."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:738
    old "Моника ходила на фитнес с Бетти"
    new "Monica went to workout with Betty"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:742
    old "Я же вам говорила, что у меня приключения..."
    new "I told you that I have adventures ..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:787
    old "Ребекка, у тебя такой интересный наряд сегодня!"
    new "Rebecca, you have such an interesting outfit today!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:832
    old "Ребекка, не вижу никакой проблемы, чтобы познакомиться с ним."
    new "Rebecca, I don’t see why I wouldn't be able to talk to him."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:839
    old "Поговорить с Тернером."
    new "Talk to Turner."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:871
    old "Мистер Тернер, я хотела бы Вас познакомить со своей подругой..."
    new "Mr. Turner, I would like to introduce you to my friend..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:900
    old "Мистер Тернер, мне нужно подумать."
    new "I need time to think, Mr. Turner."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:908
    old "Вернуться к Ребекке и Стефани."
    new "Return to Rebecca and Stephanie."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:924
    old "Он согласился при одном условии..."
    new "He agreed on one condition ..."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:924
    old "Он отказался."
    new "He refused."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:987
    old "Я подумаю, девочки."
    new "I'll think about it, girls."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1031
    old "Адриано, ты и правда на все готов ради меня?"
    new "Adriano, are you really ready to do anything for me?"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1047
    old "Пригласить Адриано на ужин."
    new "Invite Adriano to dinner."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1101
    old "Подойти к Мистеру Кэмбеллу."
    new "Go up to Mr. Campbell."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1140
    old "Я поддерживаю эту идею."
    new "I support this idea."

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1188
    old "Я не буду участвовать в этом!"
    new "I will not participate in this!"

    # game/Quests/EP2_11/ep211_dialogues2_public_event.rpy:1210
    old "Провести фотосессию в платье от инвестора."
    new "Conduct the photo shoot in a dress from the investor."

