# TODO: Translation updated at 2020-03-31 14:43

# game/Quests/EP2_11/ep211_escort_scene2.rpy:10
translate english ep211_escort_scene2_1_61f7f42d:

    # waitress "Здравствуйте, Мэм! Администратор Вас ждет на ресепшене."
    waitress "Hello ma'am! The boss is waiting for you at the reception."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:15
translate english ep211_escort_scene2_1_bc3b4878:

    # waitress "Вы? Вы здесь работаете?!" 
    # waitress "Я, даже не думала, что..."
    # m "Я..."
    # m "Я здесь не работаю... Я жду, когда мне принесут еду."
    # waitress "Мэм, но Вы же ничего не заказывали..."
    # mt "Вот черт!"
    # m "Да?"
    # m "..."
    # m "А, ну конечно. Не заказывала..." 
    # m "Я... Жду здесь человека."
    # m "..."
    # m "Кто там меня звал? Администратор?"
    # waitress "Да, Мэм."
    # m "Я сейчас подойду к ней."
    waitress "You? Do you work here ?!" 
    waitress "I would've never thought..."
    m "I..."
    m "I don’t work here ... I am waiting for food to be brought to me."
    waitress "Ma'am, but you didn’t order anything ..."
    mt "Damn it!"
    m "Yes?"
    m "..."
    m "Ah, of course. I didn’t order ..." 
    m "I ... I'm waiting for a man here."
    m "..."
    m "Who called me there? The administrator?"
    waitress "Yes, Ma'am."
    m "I'll go talk to her."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:35
translate english ep211_escort_scene2_1_d93ce6c5:

    # waitress "Вы?!" 
    # m "Да, это Я!"
    # m "Удивительно, что ты все еще работаешь здесь!"
    # waitress "Мэм..."
    # waitress "А для меня удивительно, что Вы работаете здесь..."
    # m "!!!"
    # m "С чего ты взяла, что я здесь работаю?!" 
    # m "По-твоему, я похожа на работника ресторана?!"
    # waitress "Мэм... Вас администратор попросила позвать к себе..." 
    # waitress "Она сказала, что Вы одна из..."
    # m "Это неважно, что она сказала!"
    # m "Я не собираюсь выслушивать от тебя всякие глупости!"
    # m "Никчемная официантка!"
    waitress "You?!" 
    m "Yes, it's ME!"
    m "Surprisingly you still work here."
    waitress "Ma'am..."
    waitress "It's so surprising for me that you work here ..."
    m "!!!"
    m "What makes you think that I work here ?!" 
    m "Do you think I look like a restaurant employee ?!"
    waitress "Ma'am ... the administrator asked me to call you ..." 
    waitress "She said that you are one of ..."
    m "It doesn’t matter what she said!"
    m "I'm not going to listen to all sorts of nonsense from you!"
    m "Worthless waitress!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:56
translate english ep211_escort_scene2_2_b8283038:

    # mt "Странно, что ее здесь нет."
    # mt "Возможно, она в служебном коридоре?"
    mt "It’s strange that she’s not here."
    mt "Perhaps she is in the service hallway?"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:64
translate english ep211_escort_scene2_3_58eeafef:

    # client "Да, вот эта девушка. Я хочу ее."
    # reception "Это [monica_hotel_name]. Вы уверены?"
    # reception "У нас есть другие девушки для такого заказа."
    # client "Меня интересует именно эта."
    # client "Она больше подойдет для меня, чем остальные девушки."
    # reception "У тебя сегодня выезд к клиенту."
    # reception "Ты должна будешь сопровождать этого джентельмена на встрече."
    # reception "И вести себя, как его девушка."
    # reception "..."
    # reception "Правда, мне не понятно, почему клиент выбрал именно тебя..."
    # client "Не просто вести себя как моя девушка!"
    # client "Нужно сделать так, чтобы никто не догадался, что я плачу за это."
    # client "Это очень важно!"
    # reception "Будьте спокойны. Наши девушки - профессионалы."
    # reception "Если что-то будет не так..."
    # reception "То Вам будет компенсирована сумма вдвое больше той..."
    # reception "Которую Вы заплатите за заказ."
    # client "Очень надеюсь на это."
    # client "Для меня это принципиально важный момент."
    # m "Что мне нужно будет делать?"
    # client "Вам надо будет быть моей девушкой. Луизой."
    # m "Почему Луизой?"
    # reception "Помолчи!"
    # reception "Это желание клиента и у тебя нет права обсуждать его!"
    # mt "Никчемная администраторша!"
    # reception "Вы уверены, что Вам нужен только эскорт?"
    # reception "Не хотите ли воспользоваться опцией секса с этой девушкой?"
    # reception "Согласно нашего прейскуранта?"
    # client "Нет. Для меня важно, чтобы она вела себя как моя девушка."
    # client "Больше меня никакие услуги не интересуют."
    # client "Очень важно, чтобы она была похожа на мою девушку!"
    # reception "Вы можете воспользоваться любой услугой из прейскуранта..."
    # reception "Если передумаете."
    # reception "В наших интересах оказать как можно больше услуг для того..."
    # reception "Чтобы наш клиент остался максимально доволен."
    # mt "Она прямо навязывает ему услуги из прейскуранта."
    # mt "Ее, видимо, не устраивает, что мне попался нормальный клиент."
    # mt "А не какой-нибудь извращенец."
    # mt "Эти сучки теперь будут мне завидывать."
    # reception "Ну что, ты все поняла?"
    # reception "Будешь осуществлять эскорт, играя роль его девушки."
    # reception "Если будешь делать это плохо, то будешь оштрафована!"
    # reception "Тебе понятно, [monica_hotel_name]?!"
    # m "Да, мне все понятно."
    # reception "Иди переодевайся."
    # reception "Для этого заказа тебе надо кое-что поприличнее."
    client "Yes, this girl. I want her."
    reception "This is [monica_hotel_name]. Are you sure?"
    reception "We have other girls for such an order."
    client "This one interests me."
    client "She will fit me better than other girls."
    reception "Today you'll have to visit a client."
    reception "You will have to accompany this gentleman in a meeting."
    reception "And act like his girlfriend."
    reception "..."
    reception "To be honest, I don’t understand why the client chose you ..."
    client "Don't just act like my girlfriend!"
    client "It is necessary to make sure that no one realizes that I am paying for it."
    client "It is very important!"
    reception "Keep calm. Our girls are professionals."
    reception "If something goes wrong ..."
    reception "Then you will be compensated twice ..."
    reception "what you've paid for the order."
    client "I really hope so."
    client "For me, this is a fundamentally important point."
    m "What will I need to do?"
    client "You will need to be my girlfriend. Louise"
    m "Why Louise?"
    reception "Shut up!"
    reception "This is the client’s desire and you have no right to discuss it!"
    mt "Worthless administrator!"
    reception "Are you sure you only need an escort?"
    reception "Would you like to use the sex option with this girl?"
    reception "According to our price list?"
    client "No. It is important for me that she behaves like my girlfriend."
    client "No more services interest me."
    client "It is very important that she looks like my girlfriend!"
    reception "You can use any service from the price list ..."
    reception "If you change your mind."
    reception "It is in our interests to provide as many services as possible in order for our client to ..."
    reception "remains as satisfied as possible."
    mt "She directly imposes services from the price list on him."
    mt "She apparently doesn’t like that I came across a normal client."
    mt "Not some pervert."
    mt "These bitches will now envy me."
    reception "Well, do you understand everything?"
    reception "You will carry out an escort order, playing the role of his girlfriend."
    reception "If you do it badly, you will be fined!"
    reception "Do you understand, [monica_hotel_name] ?!"
    m "Yes, everything is clear to me."
    reception "Go change."
    reception "You need something more decent for this order."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:124
translate english ep211_escort_scene2_3a_ab9c57ca:

    # mt "Это его друг? Больше похож на его босса..."
    # client "Эй, Дэниел! Привет!"
    # daniel "Привет, Нэд! Как всегда, опаздываешь!"
    # ned "Да, мы с моей девушкой немного задержались..."
    # ned "Кстати, занокомься. Это Луиза."
    # ned "Луиза, это мой друг и коллега Дэниел."
    # ned "Сегодня он устраивает небольшую вечеринку для друзей."
    # daniel "Ну наконец-то Нэд познакомил меня со своей девушкой!"
    # daniel "Проходите в дом. Там вас двано уже все ждут."
    mt "Is this his friend? More like his boss ..."
    client "Hey Daniel! Hello!"
    daniel "Hi Ned! You are late, as always!"
    ned "Yes, my girlfriend and I were a little late ..."
    ned "Кстати, занокомься. Это Луиза."
    ned "Louise, this is my friend and colleague Daniel."
    ned "Today he is having a small party for friends."
    daniel "Ну наконец-то Нэд познакомил меня со своей девушкой!"
    daniel "Проходите в дом. Там вас двано уже все ждут."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:140
translate english ep211_escort_scene2_4_d0fa3872:

    # ned "Эй, ребята, привет!"
    # ned "Хочу представить вам мою девушку. Ее зовут Луиза."
    # ned "Луиза, это мои коллеги и друзья."
    # ned "Дэниел и его жена Эмма."
    # ned "Марти и его жена Натали."
    # daniel "Привет, Луиза!"
    # emma "Приятно познакомиться!"
    # marty "Привет!"
    # natalie "Присаживайтесь к нам."
    # natalie "Наконец-то, Нэд познакомил нас со своей девушкой."
    # natalie "Я очень рада познакомиться, Луиза."
    # m "Мне тоже приятно познакомиться."
    # mt "Моника, тебе сегодня повезло с клиентом..."
    # mt "Вкусный ужин, светские разговоры в компании приличных людей..."
    # mt "И никаких извращенцев."
    # mt "Все, к чему ты так привыкла... И чего так не хватает теперь."
    # ned "Луиза, дорогая, хочешь вина?"
    # m "Пожалуй, я не откажусь."
    # daniel "Нэд, так вот почему ты стал опаздывать на работу!" 
    # daniel "Очевидно, что с такой прекрасной девушкой ты не спишь целыми ночами!"
    # daniel "Аха-ха!"
    # emma "Дэниел, оставь свои пошлые шуточки."
    # emma "Ты смущаешь ими Луизу!"
    # daniel "Да ладно тебе, детка."
    # emma "И перестань называть меня деткой. Ты же знаешь, мне это не нравится!"
    # daniel "Хорошо, любимая, как скажешь."
    # daniel "Эй, Марти! Ты когда-нибудь расстаешься с телефоном?"
    # daniel "Натали, он в постель его тоже берет? Аха-ха!"
    # natalie "Марти очень много работает."
    # natalie "Даже сейчас он просматривает документы по работе."
    # natalie "Совсем не отдыхает. Да, дорогой?"
    # marty "Угу..."
    # emma "Луиза, расскажи нам, чем ты занимаешься?"
    # emma "Нэд ничего нам не рассказывал про тебя..."
    # m "Я являюсь руководителем в одной крупной компании."
    # natalie "Ого!"
    # m "Да. Помимо основной деятельности, связанной с индустрией моды..."
    # m "У меня еще бизнес в сфере недвижимости."
    # emma "О, серьезно?!" 
    # m "Да, у меня в подчинении много сотрудников."
    # daniel "Твоя деятельность связана с модной индустрией?"
    # emma "Расскажи нам. Это очень интересно!" 
    # m "По работе мне часто приходится посещать публичные мероприятия..."
    # m "Выступать перед публикой, давать интервью."
    # m "И, конечно же, я всегда в курсе всех событий в мире моды."
    # ned "Да, Луиза очень занятая девушка." 
    # ned "Редко такое бывает, что мы можем провести вечер вместе..."
    # ned "Я вас давно хотел с ней познакомить, но у нее не бывает свободного времени."
    # ned "По вечерам она обычно ведет какие-нибудь переговоры..."
    # ned "И важные бизнес-встречи."
    # ned "Ведь такие встречи очень важны для развития ее бизнеса."
    # ned "Да, дорогая?"
    # m "Все верно."
    # m "У меня широкий круг знакомых, которые имеют немалый вес в этом городе..."
    # m "И даже в стране."
    # daniel "И как у тебя хватает времени на что-то, кроме работы?" 
    # mt "Никчемные людишки..."
    # mt "Млеют при виде меня и от мысли том, кто я такая!!!"
    # m "Да, это довольно непросто..."
    # m "Грамотное планирование своего рабочего времени..."
    # m "А также помощь моих личных ассистентов..."
    # m "Позволяют мне иногда провести вечер не на работе, а в свое удовольствие."
    # m "Нэд, налей мне еще вина!" 
    # m "..."
    # m "Пожалуйста, дорогой." 
    # ned "Конечно, любимая."
    # emma "Луиза, как тебе наш с Дэниелем дом?"
    # emma "Мы его так долго выбирали..."
    # emma "Это наш гостевой дом. Мы любим устраивать здесь вечеринки с друзьями."
    # emma "У нас есть даже рояль!"
    # natalie "Но, к сожалению, никто из нас не умеет играть на нем..."
    # emma "Да..."
    # m "Эмма, у вас чудесный дом. Он очень изысканный."
    # mt "Конечно, не такой изысканный как мой дом..."
    # m "А что касается игры на пианино..."
    # m "Я из высшего общества, как вы уже поняли..."
    # m "Соответственно, у меня очень хорошее образование и воспитание."
    # m "В высшем обществе считается дурным тоном для девушки..."
    # m "Неумение владеть каким-либо музыкальным инструментом."
    # m "И я когда-то посещала занятия в музыкальной школе."
    # emma "Правда?! Это замечательно, Луиза!"
    # natalie "Сыграй нам что-нибудь, пожалуйста!!!"
    # m "Легко! Для меня это не составит никакого труда!"
    # emma "Мальчики, Луиза сейчас будет играть на пианино!"
    # natalie "Нэд, почему ты раньше не познакомил нас с такой замечательной девушкой?!"
    # ned "..."
    # mt "Похоже, что эта работа не так уж и плоха..."
    # mt "Нет, конечно это отвратительно, но..."
    # mt "Учитывая другие варианты заработать деньги, эскорт не так уж плох..."
    # mt "Я думала, что работа в эскорте будет моим кошмаром."
    # mt "Однако, в большинстве своем, это вполне безобидное общение."
    # mt "Я, пожалуй, поработаю здесь, пока не решу все свои проблемы."
    # mt "В любом случае, никто меня здесь не знает..."
    # mt "Даже если будут вопросы, я скажу, что это мой двойник."
    # mt "Если будет нужно, я найду где-нибудь в стране девушку, похожую на меня..."
    # mt "И предъявлю тем, кто будет что-то подозревать."
    # mt "Конечно, она будет всего-лишь похожа на меня..."
    # mt "У нее, конечно, не может быть такой красоты, которой обладаю Я!"
    # mt "Но, все-же..."
    # ned "Если у нас получится заключить с ними контракт..."
    # ned "Наши продажи взлетят в несколько раз."
    # daniel "Нэд, я не стал бы делать такие оптимистичные прогнозы."
    # daniel "С ними не так просто договориться, уж поверь мне..."
    # daniel "Но если у тебя это получится сделать..."
    # daniel "Я поговорю с директором о твоем повышении."
    # m "Нэд, подай мне салфетку."
    # ned "..."
    # ned "Конечно, дорогая."
    # m "И налей мне еще вина."
    # ned "..."
    # natalie "Луиза, наши мужья всегда так себя ведут..."
    # natalie "Постоянно только и разговоров, что о работе."
    # emma "Это точно."
    # emma "Но мы с Натали уже привыкли."
    # emma "Так что и ты привыкнешь."
    # natalie "Луиза, а какие у вас с Нэдом планы?"
    # natalie "Вы уже живете вместе или просто встречаетесь?"
    # emma "А может, вы собираетесь пожениться?"
    # natalie "Это было бы чудесно! Вы такая красивая пара!"
    # emma "Нэд не делал тебе предложение?"
    # m "Нэд только и думает, что о работе."
    # m "Уверена, ему мысль о женитьбе даже в голову не приходила."
    # m "Но когда Нэд все-таки решится..."
    # m "Ему придется постараться, чтобы я рассмотрела его предложение..."
    # emma "Хи-хи-хи..."
    # natalie "Девочки, мне нужно выйти на улицу, во двор."
    # natalie "Дэниел не разрешает курить в доме."
    # natalie "Никто не хочет составить мне компанию?"
    # emma "Я с тобой, Натали."
    # emma "Луиза, пойдем с нами?"
    # m "Да, пойдем."
    # ned "Луиза, дорогая, останься со мной, пожалуйста."
    # ned "Мы с тобой немного позже прогуляемся."
    ned "Hey guys!"
    ned "I want to introduce my girlfriend to you. Her name is Louise."
    ned "Louise, these are my colleagues and friends."
    ned "Daniel and his wife Emma."
    ned "Marty and his wife Natalie."
    daniel "Привет, Луиза!"
    emma "Nice to meet you!"
    marty "Hello!"
    natalie "Please, have a seat."
    natalie "Finally, Ned introduced us to his girlfriend."
    natalie "I am very happy to meet you, Louise."
    m "Nice to meet you too."
    mt "You got lucky with the client today, Monica..."
    mt "A delicious dinner, small talk in the company of decent people..."
    mt "And no perverts."
    mt "Everything that you're so used to... And everything you miss so dearly right now."
    ned "Louise, honey, do you want some wine?"
    m "Yes that would be nice."
    daniel "Ned, so that’s why you started to be late for work!" 
    daniel "Obviously, with such a beautiful girl you don’t sleep at night!"
    daniel "Aha-ha!"
    emma "Daniel, leave your vulgar jokes."
    emma "You're embarrassing Louise!"
    daniel "Come on, baby."
    emma "And stop calling me baby. You know I don’t like it!"
    daniel "Well, love, as you say."
    daniel "Hey Marty! Do you ever part with your phone?"
    daniel "Natalie, does he take it to bed too? Ahaha!"
    natalie "Marty works a lot."
    natalie "Even now, he is looking through work documents."
    natalie "He's not getting enough rest. Is that right, Dear?"
    marty "Yeah ..."
    emma "Louise, tell us what you do."
    emma "Ned didn't tell us anything about you ..."
    m "I am a CEO of a large company."
    natalie "Wow!"
    m "Yes. In addition to the main activities related to the fashion industry ..."
    m "I also have a real estate business."
    emma "Oh seriously?!" 
    m "Yes, I have a lot of employees."
    daniel "Is your activity related to the fashion industry?"
    emma "Tell us. It is very interesting!" 
    m "At work, I often have to attend public events..."
    m "Speak to the public, give out interviews."
    m "And, of course, I am always up to date with all the events in the fashion world."
    ned "Yes, Louise is a very busy girl." 
    ned "It rarely happens that we can spend an evening together..."
    ned "I have long wanted to introduce you to her, but she doesn’t have a lot of free time."
    ned "In the evenings, she usually leads some kind of negotiations ..."
    ned "And important business meetings."
    ned "After all, such meetings are very important for the development of her business."
    ned "Yes darling?"
    m "That's right."
    m "I have a wide circle of friends who have considerable weight in this city..."
    m "And even in the country."
    daniel "And how do you have enough time for something other than work?" 
    mt "Worthless little people..."
    mt "They are fawning over me at the mere sight of me and from the thought of who I am!!!"
    m "Yes, it’s rather difficult ..."
    m "Proper planning of your working time..."
    m "And also the help of my personal assistants..."
    m "They sometimes allow me to spend the evening not at work, but for my pleasure."
    m "Ned, pour me some more wine!" 
    m "..."
    m "Please dear." 
    ned "Of course, my love."
    emma "Louise, how do you like our house ?"
    emma "We've spent a long time choosing it ..."
    emma "This is our guest house. We love having parties here with friends."
    emma "We even have a piano!"
    natalie "But, unfortunately, none of us can play it ..."
    emma "Yes..."
    m "Emma, ​​you have a wonderful house. It is very exquisite."
    mt "Of course, not as exquisite as my house ..."
    m "As for playing the piano ..."
    m "I am from the high society, as you already understood ..."
    m "Hence I have a very good education and upbringing."
    m "In high society it is considered bad form for a girl ..."
    m "Not being able to play any musical instruments."
    m "So I once attended classes at a music school."
    emma "Is that true?! This is great, Louise!"
    natalie "Play us something please !!!"
    m "Easy! That won't be difficult for me!"
    emma "Guys, Louise is going to play the piano now!"
    natalie "Ned, why didn't you introduce us to such a wonderful girl before ?!"
    ned "..."
    mt "It seems that this work is not so bad..."
    mt "No, of course it's disgusting, but..."
    mt "Given other options for making money, an escort job is not so bad..."
    mt "I thought escort work would be my nightmare."
    mt "However, for the most part, this has been nothing but harmless small talk."
    mt "I’ll probably work here until I solve all my problems."
    mt "In any case, no one here knows me ..."
    mt "Even if there are questions, I will say that this is my double."
    mt "If necessary, I will find a girl who looks like me somewhere in the country..."
    mt "And present her to those who will suspect something."
    mt "Of course, she will just look similar to me ..."
    mt "She, of course, can’t have the beauty that I possess!"
    mt "But still..."
    ned "If we manage to strike a deal with them ..."
    ned "Our sales will skyrocket several times."
    daniel "Ned, I would not make such optimistic forecasts."
    daniel "It's not so easy to deal with them, believe me ..."
    daniel "But if you can do it ..."
    daniel "I will talk with the boss about your promotion."
    m "Ned, give me a napkin."
    ned "..."
    ned "Of course, dear."
    m "And pour me some more wine."
    ned "..."
    natalie "Louise, our husbands always behave like that ..."
    natalie "Constantly just talking about work."
    emma "That'sright."
    emma "But Natalie and I are already used to it."
    emma "So you will get used to it too."
    natalie "Louise, what are your plans with Ned?"
    natalie "Do you already live together or are you just dating?"
    emma "Or are you going to get married?"
    natalie "It would be fantastic! You are such a beautiful couple!"
    emma "Ned didn't make you an offer?"
    m "Ned just thinks about work."
    m "I’m sure the thought of getting married didn’t even occur to him."
    m "But when Ned does decide ..."
    m "He will have to try hard for me to consider his proposal ..."
    emma "Hee hee hee..."
    natalie "Girls, I need to go out into the courtyard."
    natalie "Daniel does not allow smoking in the house."
    natalie "Anyone want to keep me company?"
    emma "I'm with you, Natalie."
    emma "Louise, come with us?"
    m "Let's go."
    ned "Louise, dear, stay with me, please."
    ned "You and I will take a walk a little later."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:307
translate english ep211_escort_scene2_5_6beae6f8:

    # ned "Ну что, Дэниел! Я выиграл наше пари! Аха-ха!!!"
    # ned "Гони мне мои деньги! Я сделал это!"
    # ned "У меня получилось! Наконец-то!"
    # daniel "Что?!"
    # marty "???"
    # daniel "Ты про что?" 
    # daniel "Ты про... про... Она что, проститутка?!" 
    # ned "Да!" 
    # m "Ч-что?" 
    # m "???"
    # mt "Мне это послышалось?"
    # daniel "Не могу поверить! Нет!"
    # daniel "Сколько раз ты пытался нас провести..."
    # daniel "Я всегда чую проституток за версту!"
    # daniel "Но как?! Нет! Я не верю!"
    # m "..."
    # marty "Пусть она сама нам скажет!"
    # ned "Ну? Скажи им, кто ты?"
    # mt "!!!"
    # mt "Я не могу поверить!!!"
    # mt "Он это все... Подстроил из-за спора?!"
    # mt "?!?!?!"
    # m "Я... Я его девушка..."
    # daniel "Аха-ха!"
    # daniel "Ну что я говорил тебе! Я не могу ошибиться!"
    # daniel "Ты не смог провести меня в те разы, не сможешь и теперь!"
    # ned "Нет! Она проститутка! Ее зовут [monica_hotel_name]."
    # ned "Мы заключили пари..."
    # ned "Если я приведу проститутку и ты не сможешь ее определить, то пари мое!"
    # daniel "Скажи, кто ты?"
    # daniel "Ты ведь Луиза, правда?"
    # m "Да. Я Луиза."
    # m "Я девушка Нэда..."
    # ned "Ну хватит уже!"
    # ned "Говори им, кто ты! Твоя игра закончена, [monica_hotel_name]!"
    # m "..."
    # ned "Если ты не скажешь, то я сообщу администратору сервиса эскорта..."
    # ned "Что ты не выполняешь условия заказа!!!"
    # mt "!!!"
    # mt "Сволочь! Мерзавец!"
    ned "Well Daniel! I won our bet! Aha ha !!!"
    ned "Give me my money! I did it!"
    ned "I managed! At last!"
    daniel "What?!"
    marty "???"
    daniel "What are you talking about?" 
    daniel "Are you talking about ... about ... Is she a prostitute ?!" 
    ned "Yes!" 
    m "W-what?" 
    m "???"
    mt "Did I hear that?"
    daniel "No! I can’t believe it!!"
    daniel "How many times have you tried to fool us ..."
    daniel "I always smell prostitutes from a mile away!"
    daniel "But how?! No! I don’t believe you!"
    m "..."
    marty "Let her tell us herself!"
    ned "Well? Tell them who are you?"
    mt "!!!"
    mt "Unbelievable!!!"
    mt "He set it all... Because of a bet?!"
    mt "?!?!?!"
    m "I ... I am his girlfriend ..."
    daniel "Aha-ha!"
    daniel "What did I tell you? I can't make a mistake!"
    daniel "You couldn't get me back in those times, you can't!"
    ned "No! She is a prostitute! Her name is [monica_hotel_name]."
    ned "We made a bet..."
    ned "If I bring a escort and you can't identify her, I win!"
    daniel "Tell me, who are you?"
    daniel "You're Louise, aren't you?"
    m "Yes. I am Louise."
    m "I'm Ned's girlfriend ..."
    ned "Enough is enough!"
    ned "Tell them who you are! Your game is over, [monica_hotel_name]!"
    m "..."
    ned "If you don’t tell them, then I will inform your boss..."
    ned "That you don’t fulfill the conditions of the order !!!"
    mt "!!!"
    mt "You bastard! Bastard!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:360
translate english ep211_escort_scene2_5_05939e32:

    # m "Я БЫЛА твоей девушкой!"
    # m "Но, после того как ты посмел устроить такое при своих друзьях!"
    # m "Я больше не хочу тебя видеть!"
    # ned "!!!"
    # daniel "Ну что, Нэд? Ты снова облажался!" 
    # marty "Аха-ха!!!"
    # ned "..." 
    # daniel "Я тебе говорил, что за версту вижу шлюх!"
    m "I WAS your girlfriend!"
    m "But after you dared to do it with your friends!"
    m "I don't want to see you anymore!"
    ned "!!!"
    daniel "Well, Ned? You screwed up again!" 
    marty "Aha-ha!!!"
    ned "..." 
    daniel "I told you I can see whores a mile away!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:374
translate english ep211_escort_scene2_5_78f69e7f:

    # m "В условиях заказа было то, что я говорю, что я твоя девушка!"
    # m "А не доказываю обратное!!!"
    # m "Я соблюдаю условия!"
    # ned "Ага!"
    # ned "Она заговорила про условия!"
    # ned "Она призналась! Видишь, Дэниел?!"
    # daniel "Что?!"
    # daniel "Так ты действительно работаешь в эскорте?!"
    # m "Я... Я действительно здесь не совсем из чувственных побуждений..."
    # marty "А из каких?"
    # ned "Говори!"
    # m "..."
    # m "Из... Из несколько... Меркантильных..."
    # ned "Да она обычная проститутка из ВИП Эскорта!"
    # ned "Из отеля Ле Гранд! Я там нашел ее!"
    # mt "!!!"
    # marty "Я знаю всех, кто там работает..."
    # marty "Я не видел ее там!"
    # ned "Она там работает совсем недавно, потому я ее и заприметил."
    # ned "Я знал, что вы не могли ее там видеть."
    # ned "И она держится так статно, что сложно поверить в то..."
    # ned "Что она обычная проститутка."
    # mt "!!!"
    # mt "Мерзавец! Никчемный неудачник!"
    # mt "НЕНАВИЖУ!!!"
    # daniel "То есть... Погоди... Если она все же проститутка..."
    # daniel "То зачем ты притащил ее на эту встречу?!"
    # daniel "Ведь здесь же наши жены, Нэд!!!" 
    # daniel "Ты что, совсем сдурел?! Ты за кого нас держишь, а?!"
    # ned "Я знал, что ты не сможешь раскусить ее здесь, при Эмме. Аха-ха!"
    # ned "Если бы я привел ее в нашу сауну, как обычно приводил других..."
    # ned "То не смог бы выиграть наше пари!"
    # daniel "Ладно, твоя взяла."
    # daniel "Хотя..." 
    # daniel "Ты утверждаешь, что она проститутка..."
    # daniel "И, если она проститутка, то, получается, я могу ее трахнуть?"
    # ned "Конечно, можешь!"
    # m "ЧТО?!"
    # m "Нет!"
    # m "Мы так не договаривались!"
    # m "Ты меня нанял только сопровождать тебя!!!"
    # ned "Твоя администраторша навязывала мне ваш прейскурант."
    # ned "Она сказала, что я могу передумать в любой момент!"
    # m "Нет!"
    # m "!!!"
    # ned "Твое агентство гарантировало мне, что с тобой не будет проблем!"
    # ned "Мне позвонить твоему начальству?!"
    # mt "Сволочь!!!"
    # mt "Компания придурков!"
    # mt "Жалкие неудачники!"
    # mt "!!!"
    # daniel "Нэд, скажи, ты уже далал это?"
    # daniel "Пробовал ее? Ну и как она?"
    # ned "Если честно, то нет."
    # ned "Я договорился только сопровождать меня."
    # ned "Доплачивать за секс $ 500 - для меня дороговато."
    # ned "А вдруг бы ты раскусил ее? Тогда наше пари не покрыло бы мои расходы."
    # ned "Так что с нашим пари? Ты признаешь, что я выиграл?"
    # daniel "Да, черт возьми!"
    # daniel "И если ты ее еще не пробовал, то я буду первым!"
    # daniel "Я хочу трахнуть ее прямо сейчас!"
    # marty "А как же Эмма?"
    # marty "Она и Натали придут с минуты на минуту!"
    # daniel "К черту! Ребята, соврите что-нибудь!"
    # daniel "Скажите, что у меня важный звонок, а у Луизы..."
    # daniel "У Луизы закружилась голова и она ушла в уборную!"
    # daniel "И попросила ее не беспокоить!"
    # daniel "Как там тебя зовут?"
    # m "..."
    # ned "[monica_hotel_name]."
    # daniel "[monica_hotel_name], пойдем за мной!"
    # m "Но..."
    # m "Нет... Я не пойду... Я..."
    # ned "Все! Я звоню в ВИП Эскорт!"
    # ned "Скажу, что девушка отказывается работать по прейскуранту!"
    # mt "Черт! Что же мне делать?!"
    # mt "Я просто хотела заработать немного денег..."
    # mt "Я не предполагала, что это зайдет так далеко!"
    # mt "!!!"
    # ned "Добрый вечер. Да, я передумал..."
    # ned "Я хочу взять некоторые пункты из вашего прейскуранта."
    # reception "Да, сэр. Мы рады оказать Вам любые перечисленные в прейскуранте услуги!"
    # ned "Видите ли... Эта девушка... Она..." 
    # reception "Она что, отказывается что-то делать?!"
    # reception "Передайте ей, что она будет оштрафована или уволена!"
    # ned "Она..."
    # ned "Так ты согласна?"
    # m "!!!"
    m "On the terms of the order, it was that I say that I am your girlfriend!"
    m "However I won’t prove the opposite!!!"
    m "I comply with the conditions!"
    ned "Yes!"
    ned "She spoke about the conditions!"
    ned "She admitted it! See, Daniel ?!"
    daniel "What?!"
    daniel "So do you really work as an escort ?!"
    m "I... I'm really not here for a very sensible reason..."
    marty "And what kind of reason is that then?"
    ned "Speak!"
    m "..."
    m "For ... From a mercantile... reason ..."
    ned "Yes, she is an ordinary prostitute from VIP Escort!"
    ned "From Le Grand Hotel! I found her there!"
    mt "!!!"
    marty "I know everyone who works there ..."
    marty "I didn’t see her there!"
    ned "She just stared working there recently, that's why I noticed her."
    ned "I knew you couldn’t see her there."
    ned "And she keeps herself so cool that it’s hard to believe that ..."
    ned "That she is an ordinary prostitute."
    mt "!!!"
    mt "Bastard! Worthless loser!"
    mt "I HATE HER!!!"
    daniel "I mean... Wait... If she's a prostitute..."
    daniel "Then why did you drag her to this meeting ?!"
    daniel "After all, our wives are here, Ned !!!" 
    daniel "Are you completely crazy?! Who are you holding us for, huh?!"
    ned "I knew you wouldn't be able to find her here under Emma. Aha-ha!"
    ned "If I brought her to our sauna, as I used to bring others..."
    ned "I couldn’t have won our bet!"
    daniel "Okay, you got it."
    daniel "Wait..." 
    daniel "You claim she is a prostitute ..."
    daniel "And, if she is a prostitute, then I can fuck her, right?"
    ned "Of course you can!"
    m "WHAT?!"
    m "No!"
    m "That wasn't a deal!"
    m "You hired me only to accompany you !!!"
    ned "Your boss imposed your price list on me."
    ned "She said that I can change my mind at any moment!"
    m "No!"
    m "!!!"
    ned "Your agency guaranteed me that there would be no problems with you!"
    ned "Should I call your superiors ?!"
    mt "Swine!!!"
    mt "The company of morons!"
    mt "Pitiful losers!"
    mt "!!!"
    daniel "Ned, tell me, have you already gotten it?"
    daniel "Have you tried it? So how is she?"
    ned "To tell you the truth, no."
    ned "I only ordered her to accompany me."
    ned "Paying $ 500 for sex is expensive for me."
    ned "What if you'd have found it out? Then our bet wouldn't cover my expenses."
    ned "So what about our bet? Do you admit that I won?"
    daniel "Hell yes!"
    daniel "And if you have not tried it, then I will be the first!"
    daniel "I want to fuck her right now!"
    marty "But what about Emma?"
    marty "She and Natalie will come any minute!"
    daniel "To hell with it! You guys, lie or something!"
    daniel "Say that I have an important call, and Louise ..."
    daniel "Louise was dizzy and she went to the restroom!"
    daniel "I asked her not to worry!"
    daniel "What is your name, again?"
    m "..."
    ned "[monica_hotel_name]."
    daniel "[monica_hotel_name], follow me!"
    m "But..."
    m "No ... I will not go ... I ..."
    ned "All right! I'm calling VIP Escort!"
    ned "I will say that the girl refuses to work according to the price list!"
    mt "Fuck! What should I do?!"
    mt "I just wanted to make some money ..."
    mt "I did not expect it to go that far!"
    mt "!!!"
    ned "Good evening. Yes, I changed my mind ..."
    ned "I want to take some items from your price list."
    reception "Yes, sir. We are pleased to provide you with any of the services listed in the price list!"
    ned "You see ... This girl ... She ..." 
    reception "Does she refuse to do something ?!"
    reception "Tell her that she will be fined or fired!"
    ned "She’s..."
    ned "So do you agree?"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:487
translate english ep211_escort_scene2_5_2ddeab0a:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # ned "Эй... Полегче!"
    # ned "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fuck you!"
    m "Together with your friends!"
    m "A bunch of pathetic losers!!!"
    ned "Hey ... Easy!"
    ned "Or you won't get any money!"
    m "You can shove them in your ass!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:499
translate english ep211_escort_scene2_5_e746d83c:

    # mt "!!!"
    # mt "Мерзавец!!!"
    # mt "Если я сейчас откажусь, меня выгонят из эскорта!"
    # mt "Что же делать?!"
    # mt "Я не могу потерять эту работу..."
    # mt "Я Моника Бакфетт и никогда не соглашусь на что-то подобное!"
    # mt "..."
    # mt "Мне нужно представить, что я не Моника Бакфетт, а [monica_hotel_name]."
    # mt "Для [monica_hotel_name] обслужить клиента - несложное дело."
    # mt "Для [monica_hotel_name] важна только сумма заработка за вечер."
    # mt "Поэтому [monica_hotel_name] сейчас согласится пойти с Дэниелем..."
    # m "Я все слышала и нет необходимости никого увольнять."
    # m "Я согласна."
    # ned "Ну вот. Другое дело."
    # daniel "[monica_hotel_name], пошли за мной."
    # daniel "Давай, быстрее. У меня не так много времени."
    mt "!!!"
    mt "Bastard !!!"
    mt "If I refuse now, they will expel me from the escort!"
    mt "What to do?!"
    mt "I can’t lose this job ..."
    mt "I'm Monica Buckfett and I’ll never agree to something like that!"
    mt "..."
    mt "I need to imagine that I’m not Monica Buckfett, but [monica_hotel_name]."
    mt "Serving a customer is not a big deal for [monica_hotel_name]."
    mt "For [monica_hotel_name], only the amount of earnings per evening is important."
    mt "So [monica_hotel_name] will now agree to go with Daniel ..."
    m "I heard everything and there is no need to fire anyone."
    m "I agree."
    ned "There you go. That's better."
    daniel "[monica_hotel_name], follow me."
    daniel "Lets move. I don’t have much time."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:524
translate english ep211_escort_scene2_6_fa529d44:

    # daniel "Я с самого начала вечера захотел трахнуть тебя, [monica_hotel_name]."
    # mt "Эмма, видимо, и не подозревает, какой он козел на самом деле."
    # mt "Может, рассказать ей?"
    # daniel "Даже если ты была бы женой Нэда..."
    # daniel "Я непременно сделал бы это в один из дней!"
    # daniel "Я весь вечер раздумывал над тем, как осуществить это..."
    # daniel "И вовсе не ожидал, что трахнуть такую как Луиза будет так просто!"
    # mt "!!!"
    # mt "Мерзавец!"
    # daniel "Скорее раздевайся!"
    # m "Дэниел, я... Могу я тебя попросить?"
    # daniel "Что такое, [monica_hotel_name]?"
    # m "Я не хочу, чтобы о том, что здесь произойдет, кто-то узнал..."
    # daniel "Конечно, [monica_hotel_name]!"
    # daniel "Я не собираюсь никому рассказывать про такую сладкую детку."
    # daniel "Я не хочу делиться тобой с кем-то!"
    # daniel "Я буду заказывать тебя и трахать тебя сам!"
    # daniel "Снимай с себя это скорее! Мне не терпится!"
    # mt "[monica_hotel_name] сейчас снимет с себя платье."
    # mt "И будет зарабатывать деньги."
    # mt "Это просто работа."
    # daniel "Ложись на диван и раздвинь ноги."
    # daniel "Ммммм, какая же ты охренительная, детка..."
    # daniel "Я никому тебя не отдам."
    # daniel "Я буду твоим постоянным клиентом."
    # daniel "Ты будешь трахаться только со мной."
    # mt "У тебя, неудачник, денег на меня не хватит..."
    # daniel "О, ты просто супер, [monica_hotel_name]!"
    # daniel "Такая горячая! Такая охренительная!"
    # daniel "Дааа! Хочу трахать тебя каждый день!"
    # daniel "Мммммм..."
    # daniel "О, просто чертовски охренительно!!!"
    # daniel "Даааа!"
    # daniel "Ааааа!!!"
    daniel "From the very beginning of the evening, I wanted to fuck you, [monica_hotel_name]."
    mt "Emma, ​​apparently, doesn’t suspect what an asshole he really is."
    mt "Maybe I should tell her?"
    daniel "Even if you were Ned’s wife ..."
    daniel "I would've certainly done it one day!"
    daniel "I spent the whole evening thinking about how to do this ..."
    daniel "And I did not expect that it would be so easy to fuck someone like Louise!"
    mt "!!!"
    mt "Bastard!"
    daniel "Take off your clothes!"
    m "Daniel, I ... May I ask you?"
    daniel "What is it [monica_hotel_name]?"
    m "I don’t want anyone to find out what is going on here ..."
    daniel "Of course [monica_hotel_name]!"
    daniel "I'm not going to tell anyone about such a sweet baby."
    daniel "I don’t want to share you with anyone!"
    daniel "I will order you and fuck you myself!"
    daniel "Take it off! I can’t wait!"
    mt "[monica_hotel_name] is about to take off her dress."
    mt "And she's going to make money."
    mt "It is just a job."
    daniel "Lie down on the sofa and spread your legs."
    daniel "Mmmmm, how fuckable you are, baby ..."
    daniel "I won’t give you to anyone."
    daniel "I will be your regular customer."
    daniel "You will only fuck with me."
    mt "You, loser, don’t have enough money for me ..."
    daniel "Oh you are just super, [monica_hotel_name]!"
    daniel "So hot! So fucking hot!"
    daniel "Yeah! I want to fuck you every day!"
    daniel "Mmmmmm..."
    daniel "Oh, it's so fucking awesome!!!"
    daniel "Yeah!"
    daniel "Ahhhh !!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:571
translate english ep211_escort_scene2_7_8d30eb74:

    # emma "Нэд, Марти, а где Дэниел?"
    # marty "Ему позвонили с работы. Какой-то срочный звонок."
    # marty "Он пошел в свой кабинет на второй этаж, чтобы поговорить без посторонних."
    # marty "Он не хочет, чтобы ему мешали разговаривать по телефону."
    # natalie "А где Луиза?"
    # ned "У нее началось небольшое недомогание и она ушла в туалет."
    # ned "Попросила нас пока веселиться и не беспокоить ее."
    # ned "Она скоро придет."
    # ​natalie "Странно..."
    # marty "Что странного?"
    # natalie "Что парень и девушка одновременно отсутствуют..."
    # emma "Натали, уж не думаешь ли ты, что такая как Луиза..."
    # emma "Станет общаться с моим оболтусом и хамом?"
    # marty "..."
    # ned "..."
    # emma "Да и я его знаю..."
    # emma "Дэниел никогда бы не стал поступать так по отношению к Нэду."
    # emma "Так что, не говори ерунды. Они скоро придут."
    # emma "А пока давайте веселиться!"
    # natalie "Да, ты права. Я слишком подозрительна..."
    # natalie "Марти, дорогой, налей мне еще вина."
    emma "Ned, Marty, where's Daniel?"
    marty "He got a call from work. Some kind of urgent call."
    marty "He went to his office on the second floor to talk without strangers."
    marty "He doesn’t want to be bothered while talking on the phone."
    natalie "Where is Louise?"
    ned "She was a little dizzy and went to the bathroom."
    ned "She asked us to have fun and not to bother her."
    ned "She will come back soon."
    ​natalie "Strange ..."
    marty "What is strange?"
    natalie "That a guy and a girl are simultaneously absent ..."
    emma "Natalie, do you really think that someone like Louise ..."
    emma "Will chat with my fool and boor?"
    marty "..."
    ned "..."
    emma "Yes, and I know him ..."
    emma "Daniel would never do that to Ned."
    emma "So don't be silly. They'll come soon."
    emma "In the meantime, let's have fun!"
    natalie "Yes you are right. I'm too suspicious ..."
    natalie "Marty, honey, pour me some more wine."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:599
translate english ep211_escort_scene2_8_29925f14:

    # daniel "Мммммм..."
    # daniel "Какие же у тебя сиськи!"
    # daniel "Даааа!"
    # daniel "В следующий раз я куплю тебя на всю ночь!"
    # daniel "И буду трахать тебя до утра!"
    # daniel "Ааааа!!!"
    # daniel "Эй! Что ты делаешь здесь?!"
    # daniel "Что-то случилось?!"
    # daniel "Эмма что-то заподозрила?!"
    # marty "Нет, все в порядке!"
    # daniel "Тогда зачем ты приперся сюда?"
    # marty "Я сказал, что пойду проверю, все ли у тебя хорошо."
    # daniel "Ааааа..."
    # daniel "Твою мать! ДА!!!"
    # daniel "АААААА!!!"
    # daniel "У меня все хорошо, как видишь."
    # marty "Вижу..."
    # marty "Вообще-то, я спросил у Нэда..."
    # marty "И он разрешил мне тоже воспользоваться Луизой или как там ее зовут."
    # m "!!!"
    # daniel "Аха-ха!"
    # daniel "Я уже закончил, так что можешь делать с ней все, что хочешь!"
    # m "Нет!!!"
    # m "Я занималась этим с одним человеком!"
    # m "Не было условия, чтобы делать это с кем-то еще!!!"
    # marty "Нэд сказал, что дополнительный клиент стоит сверху $ 400."
    # marty "Это входит в твой прейскурант."
    # m "А почему $ 400?! Разве не должно быть дороже, если клиентов больше?!"
    # marty "Администратор сказала Нэду, что у тебя индивидуальный прейскурант."
    # marty "Чем больше мужчин, тем дешевле!"
    # marty "Аха-ха!"
    # daniel "Аха-ха!"
    # mt "Сволочь!"
    # mt "Сучка!!!"
    # mt "Ненавижу эту тварь!!!"
    # mt "Она специально сделала это!"
    # mt "Она мстит мне за то, что я обозвала ее никчемной и обещала уволить!"
    # mt "Между прочим, вполне заслуженно!"
    # mt "Это несправедливо!!!"
    # mt "Дьявол!!!"
    # marty "Ну так что? Я могу сделать это?"
    # m "!!!"
    daniel "Mmmmmm..."
    daniel "You have amazing tits!"
    daniel "Yeah!"
    daniel "Next time I'll pay for the whole night!"
    daniel "And I will fuck you until the morning!"
    daniel "Ahhhh !!!"
    daniel "Hey! What are you doing here?!"
    daniel "Did something happen?!"
    daniel "Did Emma suspect something?!"
    marty "No, everything is okay!"
    daniel "Then why did you come here?"
    marty "I said I'd go check if you were okay."
    daniel "Ahhhh ..."
    daniel "Fuck! YES!!!"
    daniel "AAAAAAH!!!"
    daniel "I'm fine, as you can see."
    marty "I see ..."
    marty "Actually, I asked Ned ..."
    marty "And he also allowed me to use Louise or whatever her name is."
    m "!!!"
    daniel "Aha-ha!"
    daniel "I'm done, so you can do whatever you want with her!"
    m "No!!!"
    m "I've done this with one person!"
    m "There was no condition to do it with someone else!!!"
    marty "Ned said an additional client costs another 0."
    marty "It's in your price list."
    m "Why $ 400 ?! Shouldn't it be more expensive if there are more customers ?!"
    marty "Your boss told Ned you had a personal price list."
    marty "The more men, the cheaper!"
    marty "Aha-ha!"
    daniel "Aha-ha!"
    mt "That bastard!"
    mt "Bitch!"
    mt "I hate this bitch!!!"
    mt "She did it on purpose!"
    mt "She takes revenge on me for calling her worthless and promising to fire her!"
    mt "For a reason, by the way!"
    mt "This is unfair !!!"
    mt "Damn it!!!"
    marty "So what? I can do it?"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:654
translate english ep211_escort_scene2_8_a254eba4:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # marty "Эй... Полегче!"
    # marty "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fuck you!"
    m "Together with your friends!"
    m "A bunch of pathetic losers!!!"
    marty "Hey ... Easy!"
    marty "Or you won't get any money!"
    m "You can shove them in your ass!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:666
translate english ep211_escort_scene2_8_dee3b8bf:

    # mt "!!!"
    # mt "Ненавижу их всех!"
    # mt "Поотрывала бы им яйца!!!"
    # mt "Мерзкие неудачники!"
    # marty "Ну? Чего молчишь? Ты согласна?"
    # mt "С другой стороны..."
    # mt "[monica_hotel_name] за этот вечер неплохо заработает."
    # mt "И, так получается, что деньги у меня с ней общие..."
    # m "Да... Согласна..."
    # marty "Вставай раком!"
    mt "!!!"
    mt "I hate them all!"
    mt "I will tear off their balls !!!"
    mt "Vile losers!"
    marty "Well? What do you saying? Do you agree?"
    mt "From the other side..."
    mt "[monica_hotel_name] will earn a lot this evening."
    mt "And so it turns out that I share money with her..."
    m "Yes, I agree..."
    marty "Time for doggie style!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:684
translate english ep211_escort_scene2_9_c3979c5f:

    # natalie "Дэниел, куда Марти ушел?"
    # daniel "Марти нашел меня и спросил, все ли у меня в порядке."
    # daniel "Я как раз закончил разговор и собирался возвращаться."
    # daniel "Тогда Марти решил зайти в туалет и я проводил его."
    # daniel "Нам пришлось идти в другой туалет, потому что основной был занят."
    # daniel "Там, видимо, сейчас Луиза."
    # daniel "Мы даже слышали какие-то звуки. Похоже, что ее тошнит."
    # natalie "Бедняжка!"
    # natalie "Она, должно быть, выбрала какое-то не то сочетание продуктов."
    # natalie "Эмма, может быть, нам стоит сходить к ней?" 
    # natalie "Проверим, все ли с ней хорошо?"
    natalie "Daniel, where did Marty go?"
    daniel "Marty found me and asked if I was okay."
    daniel "I was just finished talking and I was going back."
    daniel "That's when Marty decided to go to the bathroom, and I'd walked him there."
    daniel "We had to go to another toilet because the main one was busy."
    daniel "Apparently Louise is there now."
    daniel "We even heard some sounds. It looks like she's sick."
    natalie "Poor thing!"
    natalie "She must have chosen some kind of wrong combination of drink."
    natalie "Emma, ​​maybe we should go see her?" 
    natalie "Let's see if she's okay."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:703
translate english ep211_escort_scene2_10_43c2afda:

    # marty "Мммм, какая у тебя клевая попка!"
    # marty "Такая упругая..."
    # mt "Когда же он уже кончит и отстанет от меня?"
    # marty "О, дааа!"
    # marty "Мммммм..."
    # marty "ААААААХ!!!"
    # mt "Ну наконец-то!!!"
    # mt "Надо одеваться и скорее уходить из этого чертового дома!!!"
    marty "Mmmm, what nice ass you have!"
    marty "So firm ..."
    mt "When will he finish and leave me?"
    marty "Oh yeah!"
    marty "Mmmmmm..."
    marty "AAAAAAH !!!"
    mt "Finally!!!"
    mt "I need to get dressed and get out of this damn house!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:720
translate english ep211_escort_scene2_11_9eec7ddd:

    # ned "Не стоит. Я сейчас сам пойду к Луизе и проверю, как она себя чувствует."
    # emma "Да, конечно. Пусть Нэд идет." 
    # emma "Нэд, тебе стоит заботиться о такой хорошей девушке, как Луиза."
    # emma "Иначе ты рискуешь ее потерять."
    # emma "Должно быть, у нее действительно к тебе чувства..."
    # emma "Раз такая как она согласилась встречаться с тобой."
    # ned "Да, Эмма. Луиза моя девушка и я очень горжусь этим!"
    ned "No, no. I'm going to go to Louise and check on her."
    emma "Yes, of course. Let Ned go." 
    emma "Ned, you should take care of a wonderful girl like Louise."
    emma "Otherwise, you risk losing her."
    emma "She must really have feelings for you ..."
    emma "Since she agreed to date you."
    ned "Yes, Emma. Louise is my girlfriend and I am very proud of it!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:735
translate english ep211_escort_scene2_12_7739303b:

    # ned "Черт! Пустите меня!"
    # ned "Теперь моя очередь! Дайте сюда!"
    # ned "Я должен ее трахнуть тоже! Все-таки, это моя девушка!!!"
    # m "!!!"
    # m "Ты..."
    # ned "$ 200! Следующий клиент стоит $ 200!!!"
    # ned "Я специально подождал, чтобы получить скидку!!!"
    # ned "Жаль, мы не взяли с собой Джима!"
    # ned "Тогда мне бы это обошлось всего в $ 100!"
    # mt "Жалкий жадный неудачник!!!"
    # mt "Подонок!!!"
    # m "!!!"
    ned "Shit! Let me have a go!"
    ned "It's my turn! Give her here!"
    ned "I have to fuck her too! After all, it's my girlfriend!!!"
    m "!!!"
    m "You..."
    ned "$ 200! The next client costs $ 200 !!!"
    ned "I deliberately waited to get a discount !!!"
    ned "If only Jim was also here!"
    ned "Then it would’ve cost me only $ 100!"
    mt "Miserable greedy loser !!!"
    mt "Bastard !!!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:752
translate english ep211_escort_scene2_12_2ddeab0a:

    # m "Да пошел ты к черту!"
    # m "Вместе со своими друзьями!"
    # m "Сборище жалких неудачников!!!"
    # ned "Эй... Полегче!"
    # ned "А то останешься без денег!"
    # m "Засунь их себе в задницу!"
    # m "!!!"
    m "Fuck you!"
    m "Together with your friends!"
    m "A bunch of pathetic losers!!!"
    ned "Hey ... Easy!"
    ned "Or you won't get any money!"
    m "You can shove them in your ass!"
    m "!!!"

# game/Quests/EP2_11/ep211_escort_scene2.rpy:764
translate english ep211_escort_scene2_12_c01ef09b:

    # mt "!!!"
    # mt "Это просто работа..."
    # ned "Даааа!!!"
    # marty "Эй, Нэд! Натали ничего не спрашивала про меня?"
    # ned "Нет, но беги скорее, а то тебя начнут искать!"
    # ned "Аааа..."
    # ned "Аааааа..."
    # ned "Аааааааа..."
    # ned "АААААА!!!" 
    mt "!!!"
    mt "It's just a job..."
    ned "Yes !!!"
    marty "Hey Ned! Did Natalie ask anything about me?"
    ned "No, but you better get back or they'll start looking for you!"
    ned "Ahhh ..."
    ned "Ahhhh ..."
    ned "Aaaaaaaa ..."
    ned "AAAAAAH!!!" 

# game/Quests/EP2_11/ep211_escort_scene2.rpy:783
translate english ep211_escort_scene2_13_527969cf:

    # mt "Я не могу смотреть на этих похотливых козлов!"
    # mt "Они только что изменили своим женам!"
    # mt "Изменили, сделав... сделав... Даже не хочу об этом думать!"
    # mt "А теперь сидят и лгут им! Как ни в чем не бывало!"
    # mt "Как же это мерзко!"
    # mt "А более мерзко то, что мне после всего..."
    # mt "После всей этй грязи..."
    # mt "Мне нужно тоже притворяться перед Эммой и Натали!"
    # mt "Это какой-то кошмар!"
    # ned "Луиза, любимая, ты себя уже лучше чувствуешь?"
    # m "Да..."
    # m "Спасибо за твою заботу, дорогой..."
    # mt "Подонок!!!"
    # natalie "Луиза, мы с Эммой так переживали за тебя."
    # emma "Тебе точно стало лучше? Может, тебе дать какие-нибудь лекарства?"
    # mt "Дайте мне яду. Я налью его в бокалы ваших козлов!"
    # m "Мне уже лучше, спасибо."
    # natalie "Ну и хорошо. Луиза, у меня на завтра запланирован шоппинг."
    # natalie "Эмма тоже ко мне присоединиться. Не хочешь составить нам компанию?"
    # emma "Да, это отличная идея!"
    # emma "Луиза, ты же хорошо разбираешься в моде..."
    # emma "Пойдем завтра с нами!"
    # emma "Погуляем по магазинам, зайдем в ресторан."
    # natalie "Потом можно будет сходить в СПА. Мы отлично проведем время!"
    # m "Спасибо за предложение, девочки, но..."
    # m "У меня завтра много работы."
    # m "У меня каждый день расписан буквально поминутно."
    # m "К сожалению, у меня не будет времени."
    # mt "Не хватало еще тратить на всякую ерунду деньги, которые я заработала с таким трудом..."
    # mt "Тем более, их даже не хватит на новую сумочку..."
    # emma "Жаль..."
    # natalie "Луиза, у тебя такой плотный рабочий график."
    # natalie "Когда вы успеваете встречаться с Нэдом?"
    # m "..."
    # m "По вечерам... Мы уделяем друг другу время."
    # ned "Да, любимая. Мы стараемся встречаться каждый вечер."
    # emma "Наверное, это так волнительно - ждать вечера, чтобы встретиться с любимым..."
    # m "..."
    # natalie "Луиза, а Нэд часто дарит тебе подарки?"
    # natalie "Мне вот Марти дарит цветы только по праздникам..."
    # marty "Дорогая, ну ты же итак знаешь, что я тебя люблю..."
    # natalie "Знаю. Но мне все равно хочется внимания."
    # natalie "А ты только и знаешь, что сидишь целыми вечерами в телефоне и работаешь!"
    # marty "Ну не обижайся. Я стараюсь ради нас с тобой." 
    # emma "А мой Дэниел часто балует меня цветами и всякими приятными сюрпризами."
    # daniel "Конечно, любимая. Мне нравится делать тебя счастливой." 
    # mt "Боже... Меня сейчас стошнит от этого всего..."
    # ned "Луиза, дорогая. Мне кажется, тебе снова нехорошо."
    # ned "Может быть, я отвезу тебя домой?"
    # m "Да, дорогой. Я буду тебе очень благодарна."
    # m "Спасибо за приятный вечер." 
    # m "Я была рада с вами познакомиться."
    # emma "Я надеюсь, вы с Нэдом к нам еще приедете."
    # emma "Я буду очень рада тебя видеть, Луиза!"
    # natalie "И мы обязательно еще сходим с тобой на шоппинг!"
    # m "Хорошо. Обязательно."
    # marty "Пока, Луиза. Приятно было познакомиться."
    # daniel "И мне тоже было приятно. Пока."
    mt "I can’t look at these lustful assholes!"
    mt "They just cheated on their wives!"
    mt "I don’t even want to think about it!"
    mt "And now they sit and lie to them! As if nothing had happened!"
    mt "How disgusting!"
    mt "It's more disgusting that after all this..."
    mt "After all this billshit ..."
    mt "I need to pretend nothing happened in front of Emma and Natalie too!"
    mt "Just a nightmare!"
    ned "Louise, love, are you feeling better yet?"
    m "Yes..."
    m "Thank you for your concern, dear ..."
    mt "Bastard !!!"
    natalie "Louise, Emma and I were so worried about you."
    emma "Are you sure you feel better? Can I give you some medicine?"
    mt "Give me poison. I'll pour it into your asshole's glasses!"
    m "I'm feeling better, thanks."
    natalie "That's good. Louise, I have some shopping planned for tomorrow."
    natalie "Emma will join me too. Would you like to keep us company?"
    emma "Yes, that’s a great idea!"
    emma "Louise, you know a lot about fashion ..."
    emma "Come with us tomorrow!"
    emma "Let's go shopping, and go to the restaurant."
    natalie "Then we can go to SPA. We'll have a great time!"
    m "Thanks for the offer, girls, but ..."
    m "I have a lot of work tomorrow."
    m "I have every day planned literally down to the minute."
    m "Unfortunately, I will not have time."
    mt "I don't want to spend all the money that I earn..."
    mt "Moreover, I don’t even have enough for a new purse ..."
    emma "Sorry..."
    natalie "Louise, you have such a busy schedule."
    natalie "When do you manage to date Ned?"
    m "..."
    m "In the evenings ... We set aside time for each other."
    ned "Yes, love. We try to meet every night."
    emma "It's probably so exciting to wait for the evening to see each other..."
    m "..."
    natalie "Louise, does Ned give you presents often?"
    natalie "Marty gives me flowers only on holidays ..."
    marty "Darling, well, you know that I love you ..."
    natalie "I know. But I still want attention."
    natalie "All you know is you're sitting all night on your phone and working!"
    marty "No offense. I'm trying for you and me." 
    emma "And my Daniel often pampers me with flowers and all sorts of pleasant surprises."
    daniel "Of course, my love. I like to make you happy." 
    mt "Oh god... I think I'm goint to puke because of all of this..."
    ned "Louise, dear. I think you feel bad again."
    ned "Maybe I should take you home?"
    m "Yes, darling. I'll be very grateful to you."
    m "Thank you for a nice evening." 
    m "I was nice to meet you."
    emma "I hope you and Ned are coming to see us again."
    emma "I'll be very happy to see you, Louise!"
    natalie "And we will definitely go shopping with you!"
    m "Okay. Sure."
    marty "Bye, Louise. It was nice to meet you."
    daniel "Me too. Bye."

# game/Quests/EP2_11/ep211_escort_scene2.rpy:850
translate english ep211_escort_scene2_14_7046459d:

    # mt "Ненавижу эту никчемную администраторшу!"
    # mt "!!!"
    # reception "[monica_hotel_name]!!!"
    # reception "Мне звонил клент!"
    # reception "Он крайне недоволен твоим поведением!"
    # reception "Какого черта ты решила, что можешь диктовать свои условия клиенту?!"
    # m "Он изменил первоначальные условия..."
    # reception "Да!!! И он имел на это право!!!"
    # reception "Я тебя прощаю на первый раз и ограничусь только штрафом!"
    # reception "В следующий раз ты за подобное поведение вылетишь отсюда!!!"
    # reception "У нас ВИП Эскорт! Такое отношение к клиентам недопустимо!"
    # reception "Ты поняла меня?!?!"
    # m "Да..."
    # mt "Сучка!"
    # mt "Ненавижу!"
    # reception "Клиент за сопровождение заплатил $500."
    # reception "Ты оштрафована за невыполнение услуг согласно прейскуранту."
    # reception "И с этих денег ты не получаешь ни цента!"
    # mt "!!!"
    # m "Как?"
    # reception "Да, ни цента! И это ты еще легко отделалась!"
    # reception "Еще хоть одно малейшее нарушение и тебя ждет увольнение!!!"
    # reception "Тебе все понятно, [monica_hotel_name]?!"
    # m "Да..."
    # mt "Гори в аду, мразь!"
    # reception "Ты хорошо справилась с сегодняшним заказом..."
    # reception "Но клиент сказал, что ты вела себя нерешительно."
    # reception "[monica_hotel_name] должна сама предлагать услуги из прейскуранта!"
    # reception "И не заставлять клиентов уговаривать себя!"
    # reception "Если подобное поведение будет встречено еще раз..."
    # reception "То ты будешь оштрафована, понятно?!"
    # m "Да..."
    # mt "!!!"
    # reception "Клиент заплатил $500 за сопровождение на вечере..."
    # reception "И $1100 за три дополнительные услуги из прейскуранта."
    # reception "Твой заработок составляет 50 процентов от суммы."
    # reception "То есть $800."
    # reception "Вот твои деньги."
    # reception "Завтра можешь приходить снова."
    # reception "На сегодня все. Клиенты не любят использованный товар."
    # mt "Вот сучка!"
    # mt "!!!"
    mt "I hate this worthless administrator!"
    mt "!!!"
    reception "[monica_hotel_name] !!!"
    reception "The customer called me!"
    reception "He's very dissatisfied with your behavior!"
    reception "Why the hell did you think you could dictate your terms to the client?!"
    m "He changed the original conditions..."
    reception "Yes!!! And he was entitled to it!!!"
    reception "I forgive you for the first time and limit your punishment to a fine!"
    reception "Next time you'll be thrown out of here for this behavior!!!"
    reception "You are a VIP Escort! Such an attitude towards customers is unacceptable!"
    reception "You understand me?!?!"
    m "Yes..."
    mt "Bitch!!!"
    mt "I HATE HIM!"
    reception "The client paid $ 500 for escort."
    reception "You are fined for not fulfilling the services according to the price list."
    reception "So you don’t get a cent from that money!"
    mt "!!!"
    m "How?"
    reception "Yes, not a cent! And you still got off easy!"
    reception "One more slightest violation and you would've been fired !!!"
    reception "Do you understand me, [monica_hotel_name] ?!"
    m "Yes..."
    mt "Burn in hell, scum!"
    reception "You did well with today's order ..."
    reception "But the client said that you were hesitant."
    reception "[monica_hotel_name] should offer services from the price list!"
    reception "And don’t persuade customers to change their minds!"
    reception "If this behavior is mentioned again ..."
    reception "Then you will be fined, okay ?!"
    m "Yes..."
    mt "!!!"
    reception "The client paid $ 500 for the evening escort..."
    reception "And $ 1,100 for three additional services from the price list."
    reception "Your earnings are 50 percent of the amount."
    reception "That is $ 800."
    reception "Here's your money."
    reception "You can come again tomorrow."
    reception "That's all for today. Customers do not like used goods."
    mt "What a bitch!"
    mt "!!!"

translate english strings:

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:357
    old "Сказать, что я его девушка и уйти!"
    new "Say that I am his girlfriend and leave!"

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:357
    old "Сказать, что я работаю в эскорте."
    new "Say that I work as an escort."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:484
    old "Согласиться пойти с Дэниелем."
    new "Agree to go with Daniel."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:651
    old "Смириться с прейскурантом."
    new "Accept the price list."

    # game/Quests/EP2_11/ep211_escort_scene2.rpy:749
    old "Смириться, иначе меня ждет штраф или увольнение."
    new "Agree, or I'll be fined or fired."

